### PR TITLE
Implements emergency shower in medbay

### PR DESCRIPTION
**Pull request by Tenryumi**
Chemists, virologists and doctors alike! This is for you!
<strike>Have you ever run out of beakers/syringes, or had your surgery tools stolen by chucklefucks? Have you gone to Cargo to get new tools only to find there are no cargo techs and the QM died in Lavaland and didn't take a GPS?</strike> Have you ever accidentally covered yourself with your own acidic, flammable deathmix you powergaming little rascal you?
This update is for you!
# WHAT WAS ADDED:

<strike> - A new variant of autolathe that can _only_ produce medical equipment. Name and description of this particular autolathe have been changed to reflect this.

_Purpose:_ It's frustrating to run out of medical tools and have no means to get more. Beforehand if you lost surgery tools, particularly if in a very time-sensitive situation (someone stole the surgery tools and somebody has an alien embryo 30 seconds away from bursting,) the patient is screwed. It's frustrating having no more syringes or beakers as a virologist or chemist (if you don't want to dump all your trash reagents onto the floor.) </strike>
**A unanimous chorus of "NO!" has changed this PR; the autolathe is removed, but the shower stays.**
- An emergency shower

_Purpose:_ If a patient is covered in something flammable and is actively on fire, it's pretty awkward when the treating doctor realized he has to drag the patient to another room far down the hall, and then drag them all the way back to the medbay to actually be treated. This is a matter of both convenience and practicality.
### Locations of added object<strike>s</strike>:

dreammaker_2016-10-18_11-15-01
screenshot updated as of a83706195b5f54d7c23915df1bea25b7a636fccf

<strike>
# "I see you're indirectly buffing Virology and Chemistry by giving them a near infinite supply of materials to work with."

<strike>Please take into account that Science can do what's listed above but on speed. all they need that's found outside of Science are a 5-stack of plasma, silver, diamond and uranium, and they can create a fully functioning autolathe that produces _every_ autolathe item, producing items even faster than the default autolathe. This PR exists to make Medbay jobs more convenient to play and generally less frustrating.
# "But there's already an autolathe in Cargo, what's the point of this?"

Yes, yes there is an autolathe already on the station. It's also locked behind a cargo-only door. A chemist/virologist needing more medical tools has likely been working in the shift for about 20 minutes. In this time, based on my experience, cargo techs run off and become assistants with cargo access, either nobody plays QM or those whom did pick QM have run off to Lavaland and died trying to mine on their own (we all know how ridiculously treacherous lavaland is, dead miners are more than commonplace,) and the only way in under these circumstances is to either to wait for someone else to open the door, or to break in and leave Cargo open for anybody to run in and do whatever they want with it. Not only that but this also makes the Medbay lose personnel because somebody has to play tool delivery for a while (probably a chemist or virologist who would be better spending their time doing their respective jobs.)
</strike>
**The autolathe has been removed, so there's no point to this now.**

:cl:
rscadd: A shower has been added to the medbay, located inbetween the cyro tubes and sleepers.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
chem can already make infinite beakers, and giving medical the ability to make infinity materials will decrease some interdepartmental communication.

Shower is pretty good though

**Comment by Ephemeralis** [comment]
Fuck the autolathe, good idea on the shower.

Departmental specific autolathes are never a good thing. Either add a public limited-access one to somewhere, or nothing.

**Comment by Alek2ander** [comment]
:-1: >making cargo useless
also science usually has their own autolathe by that point, and they're closer.

**Comment by X-TheDark** [comment]
Strongly against the autolathe. If you need "backup" tools, give them to the CMO locker or something. But really, Cargo does have a Surgery Supply Crate for this exact reason, might want to start asking QM for that. It only costs 1000 points (considering Cargo starts with 5000).

The whole point of having limited-access tools is that they it's an escalation for security and medical personnel to get them back from the person. They are to be protected by CMO/Roboticist/Whomever-department-guy.

If you need an autolathe, ask Engineering/Science to build/get you one, I'm not sure medical doctors/random people running around with roundstart circular saws.

**Comment by Tenryumi** [comment]
The autolathe has been removed due to extremely popular request.

**Comment by utahclock** [comment]
can you put showr on wall between sleeper and cryo?

**Comment by Tenryumi** [comment]
If I put it between the cyro and sleeper, it leaves a risk of the slippery surface showers create slipping doctors running by, seriously interrupting their work. If a doctor is rushing a near-death patient in and he gets slipped by that shower, the few seconds it takes for them to get back up may cost the patient their life.
yaya

I put it in the corner there because there's almost no way you could go there unless you have a purpose.

**Comment by utahclock** [comment]
you can make tile no slip..

**Comment by X-TheDark** [comment]
To elaborate, there's a [noslip tile](https://github.com/yogstation13/yogstation/blob/master/code/game/turfs/simulated/floor/misc_floor.dm#L99) available, in case you think that placing a shower between sleeper/cryo would be good if not for the slipping.

**Comment by Tenryumi** [comment]
Oh my goodness, you're right. I'd forgotten all about that tile. implementing at once.

**Comment by ghost** [comment]
no noslip tile

just put the shower there

inefficiency is good

**Comment by ShadowDeath6** [comment]
New pic of map so we can see memetile

**Comment by Tenryumi** [comment]
I've already updated the picture in the original post.

**Comment by Tenryumi** [comment]
@AdamElTablawy I see far, _far_ too many terrible things coming from that tile not being a noslip.
Enough so that if it wasn't noslip, it would actually cause more problems than this PR intends to fix.

**Comment by ghost** [comment]
that's the intent yewmi

things going horribly wrong is a core part of ss13 and some asshole leaving the shower on leading to mass death and chaos is exactly the type of thing that makes it great

**Comment by X-TheDark** [comment]
To me, that sounds like an awful and frustrating experience, both for the doctors and the patients. Not the "holy shit, this is going so wrong, it's awesome" kind, but the "holy shit, this is actually shit".

**Comment by ghost** [comment]
good

**Comment by Ephemeralis** [comment]
So long as that noslip tile can be wrenched up by an intrepid traitor engineer and replaced with a non-noslip tile then yeah sure, why not.

**Comment by X-TheDark** [comment]
That's a good point, actually, I think the noslip tile can just be picked up by any old crowbar.

**Pull request merged**
