### PR TITLE
i heard korialstraza whining about how i was nerfing everything including carp and blob so here you go, have some goddamn lethal carp

### PR DESCRIPTION
**Pull request by ghost**
megacarp spawn much more often on the carp random event
##### Changelog

:cl:
rscadd: Schools of megacarp have been seen near the station.
/:cl:

### CODE REVIEW

**Comment by AsV9** [comment]
no stop

**Comment by ghost** [comment]
no stop

**Comment by ghost** [comment]
no really why

**Comment by ShadowDeath6** [comment]
try buffing blob instead :triumph:

**Comment by AndySok** [comment]
buff the blob

**Pull request closed without merging**
