### PR TITLE
[s] Makes it even more harder than the last to cheat as AI

### PR DESCRIPTION
**Pull request by monster860**
I removed the "dim" icon state from the file so that you can't use that as a reference point. It's never used anyways.

### CODE REVIEW

**Comment by monster860** [comment]
FML, I fucked up the secret tag.

**Comment by supernoodles13** [comment]
good job. totally a secret now

**Comment by monster860** [comment]
Eh, the discription is pretty vague.

**Comment by Earthykiller127** [comment]
brb finding a workaround

**Comment by monster860** [comment]
So have you found that workaround yet?

**Pull request merged**
