### PR TITLE
Ports Polaris / Baystation rocks.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
add: ports some rocks over, because the old ones look like mega ass.
/:cl:

Heya, I ported these to FTL13 and because Yog uses the same icon smoothing anyway I ported them here too so I can enjoy my time as miner a bit more. I'm not too great with changing sprites so if anyone would want to change how they look (re-coloring or something) feel free.

I can also possibly port the way their ore looks, but I'm not sure if they have sprites for the ores Yog has.

floyd out.

old:
https://i.gyazo.com/63cbb32414596bf30ae0350be3b01837.png

new: 

https://cdn.discordapp.com/attachments/134720091576205312/335906761087385601/unknown.png

https://i.gyazo.com/9032c23e57b26c0dec6007eacb692442.png

### CODE REVIEW

**Comment by Time-Green** [comment]
I'm glad you're contributing. Do you have any pictures?

**Comment by ghost** [comment]
right, sorry. I'll edit the main post

**Comment by Super3222** [comment]
To be honest, they don't fit lavaland. Maybe the asteroid, but not lavaland.

**Comment by ghost** [comment]
thats fair enough. I think they look 5 times as good as the current rocks but it's up to you guys :P

**Comment by ghost** [comment]
get tg rocks

**Comment by ghost** [comment]
you're already using tg rocks you tard

**Comment by LarissaMayrink** [comment]
He meant the new rocks, thot. Also you won't find something that fits lavaland at bay/ftl

**Comment by ghost** [comment]
they dont have anything newer. Also I technically got this from polaris and yawn. Not from Bay or FTL

**Comment by Super3222** [comment]
After seeing it in game I still don't like it. It clashes with the ash turfs, and doesn't fit the theme of lavaland.

**Comment by fonedsky** [comment]
Maybe if we give them a darker color scheme with some veins of lava running through, perhaps they'd fit with lavaland better?

**Comment by Super3222** [comment]
Yeah, I could go for that.

**Pull request merged**
