### PR TITLE
Castrates lizards

### LINKED ISSUE #2872: Removes one singular pixel on lizards. (Remove Beepis)
Removes one pixel that sticks out of jumpsuits on Male(male) lizards. 
The one sticking Pixel.
pixel
Nekid
one pixel lewd close

TG's Beepis removal technique
beepis gone

### PR DESCRIPTION
**Pull request by ThatLing**
Closes #2872.

This fixes lizards having a pixel stick out of their clothes.

:cl:  
bugfix: Lizards no longer have a pixel sticking out of their clothes.
/:cl:

### CODE REVIEW

**Comment by Smudged** [comment]
Thank you Ling, the dixel will be removed, finally.

**Comment by Time-Green** [comment]
rip beepsis

**Comment by Colburn3000** [comment]
I am going to miss my beepis

**Comment by Alexandria404** [comment]
Male lizards have paired hemipenes that are sac-like and lack erectile tissue.
https://en.wikivet.net/Lizard_Reproductive_System
Making SS13 anatomically correct :ok_hand:

**Pull request merged**
