### PR TITLE
Fixes Shuttle.

### PR DESCRIPTION
**Pull request by Zostroll**
Changes the airlocks on the right side of the shuttle into windows.
:cl: Zostroll
tweak: The stations escape shuttle has had it's airlock's stolen on it's right side due to budget constraints the have been replaced with windows.
/:cl:

### CODE REVIEW

**Comment by oisin100** [comment]
Changelog please!

You can setup a changelog by editing the OP
Example Changelog

```
Changes the airlocks on the right side of the shuttle into windows.
:cl: (YourCKEY)
tweak: Right shuttle airlocks have been replaced due to budget cuts.
:cl:
```

**Comment by Zostroll** [comment]
That ok?

**Comment by oisin100** [comment]
Perfect!

**Comment by Zostroll** [comment]
Yay my first merge!! :)

**Comment by Zostroll** [comment]
Why didn't it work... :(

**Comment by Zostroll** [comment]
@oisin100 Why did this not work? Was it like https://github.com/yogstation13/yogstation/issues/697 and were the folders not updated or did I do something wrong?

**Comment by Alek2ander** [comment]
You changed the shuttle template, but not the actual default shuttle which is already on the main map.

**Pull request merged**
