### PR TITLE
Reverts some input-strips

### PR DESCRIPTION
**Pull request by Amelia0010**
Reverts @Cruix's stripped input, as it broke several things. I'll be listing and updating as I come across them:

Instruments
Centcomm announcements
Request consoles

#### Changelog

:cl:
fix: Several inputs have been de-stripped.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
did this cause them to close when you pressed buttons? because that explains a bug on clown cars.

**Comment by Amelia0010** [comment]
no, you would click import, which would then open the box, as per usual. It would only allow you one line, and then say that said line was too long, though

**Comment by Cruix** [comment]
How exactly are all of these things broken?

**Comment by Amelia0010** [comment]
Instruments just plain up don't accept anything.
Centcomm announcements do the annoying \&#39; thing instead of apostrophes, the same with the ID cards.
The request consoles make a message saying "\<i> [message] \<i> instead of having it be italicized

**Comment by Cruix** [comment]
Put \ in front of control characters to make github stop formatting them.
Ironically this is the very reason that input is sanitized in-game.

**Comment by Cruix** [comment]
How are agent ID's broken?

**Comment by Amelia0010** [comment]
Apostrophes show up as \&#39; or something similar. The person who had this was named "o\&#39;malley", or "o'malley"

**Comment by Cruix** [comment]
Your fix does exactly the same thing

**Comment by Amelia0010** [comment]
I can't fix the ID's, i'm bad

**Comment by ghost** [comment]
noob

**Comment by Amelia0010** [comment]
1\#39;m an un1337 n00b

**Comment by Amelia0010** [comment]
cruix's prs are better

**Comment by ghost** [comment]
take this L

**Pull request closed without merging**
