### PR TITLE
Gets rid of gibbing abductor glands. Moves traitorabd into the traitor gamemode folder

### PR DESCRIPTION
**Pull request by Super3222**
Fixes https://github.com/yogstation13/yogstation/issues/1213.

#### Changelog

:cl:
rscdel: Abductor glands that gib their owners are GONE.
tweak: Bodysnatcher gland deals brute damage instead of gibbing.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
this allows item duping and other shit just remove it

**Comment by Super3222** [comment]
For some reason Birdstations not letting me remove it. I'll try to find a way around it

**Comment by ShadowDeath6** [comment]
The glands are probably part of the map somewhere

**Comment by Super3222** [comment]
I tried that, but a window kept popping up telling me there was an error in a variable somewhere. Thus - it wouldn't let me open the map even to make changes to it.

**Comment by Time-Green** [comment]
Birdstation is loaded on the repo or something. Someone with owner acces must fix it

**Pull request closed without merging**
