### PR TITLE
Gives ocular wardens a gaze beam

### PR DESCRIPTION
**Pull request by Time-Green**
Requested by: @AdamElTablawy 
Sprite by: @Kmc2000 
:cl:
rscadd: Ratvar has given his ocular wardens laser eyes, which scare the heartbeating crap out of their victims
/:cl:

schermopname 406

### CODE REVIEW

**Comment by ghost** [comment]
that looks like crap

**Comment by ghost** [comment]
also you spelled 'wich' wrong and changelogs like that are bad

**Comment by Super3222** [comment]
Looks good. You should talk to KMC about making a "blur" effect around the line to create that intensity feeling.

But anyway - you don't really need the sound tag because that implies a new sound is being added to the repo.

**Comment by Jc1469** [comment]
So you're not only giving a visual indication of a warden targeting you, but also an audio one..? 

Seems a bit un-necessary to have both to me.

**Comment by Super3222** [comment]
I'm not sure what's unnecessary about this. In any case it looks good to go. But as required we need that other PR to go.

**Comment by Time-Green** [comment]
I set alpafade to 1 in the other PR, so this can safely be merged.

**Pull request merged**
