### PR TITLE
Fixes Zombie Implant backfire

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

The Zombie Implant side effect backfired and, made the implant a pain rather than something that actually helps you.

Now, you'll never see it, because I removed it.
#### Changelog

:cl:
rscadd: The Syndicate has doubled their profits lately by pawning off a NT nuclear device. They managed to gather a few heads and improve their zombie implant. Zombie implants will no longer drain your nutrition levels.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
this isn't a revert, this is a fix

**Comment by Super3222** [comment]
> this isn't a revert, this is a fix

I reverted the drawback completely.

**Comment by ShadowDeath6** [comment]
why do any traitor items have drawbacks, you should know better :^(

**Comment by Super3222** [comment]
i made a boo boo :^ (

**Pull request merged**
