### PR TITLE
gives cogscarabs slabs regardless if ratvar is present

### PR DESCRIPTION
**Pull request by ShadowDeath6**
#674

they're supposed to be base builders yet they can't build structures u wot

:cl: ShadowDeath6
rscadd: Cogscarabs get a slab regardless if Ratvar is present or not
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
> they're supposed to be base builders yet they can't build structures u wot

/tg/ says else wise.
https://github.com/tgstation/tgstation/blob/e7dea1eb4bc5c26d80635ad3c17dc04bdc79571c/code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm#L112

Note that this will give cogscrabs the ability to use tomes, which is too much. The cult is already crazy strong, they don't need ghost roles getting access to their strength.
They already have a clockwork RCD which can only be used by cogscrabs, leave it at that.

I get it they're drones but, this upsets the balance of the game. They don't get slabs for a /good/ reason, Shadow. /tg/'s been through the last couple of months balancing out this mode. We've maybe had it for the last 1-2 weeks? This seems like a hugbox tbh

Artificers, Juggernaughts, and Harvesters cannot mess with their tomes or create runes within good reason.

**Comment by ShadowDeath6** [comment]
Artificers, Juggernauts, and Wraiths can all interact with cult things and/or provide decent firepower. Artificers can provide support in healing and AoE stuns to supplement other constructs.
We're not giving slabs to anima fragments, and frankly I would prefer for cogscarabs to serve more of a purpose than "the clock floor spreading machines / PASSMOB gun spammers", which in my opinion is a dumb feature anyway.

**Comment by Super3222** [comment]
> Artificers, Juggernauts, and Wraiths can all interact with cult things and/or provide decent firepower.

So can cogscrabs.

> Artificers can provide support in healing and AoE stuns to supplement other constructs.

Cogscrabs are literally the ideal basebuilding assistant that you need. They have tools to deconstruct the station and put up clockwork walls, amplifying the efficiency of other structures near by, and helping out the cult **massively**.

> We're not giving slabs to anima fragments, and frankly I would prefer for cogscarabs to serve more of a purpose than "the clock floor spreading machines / PASSMOB gun spammers"

Which is why the ion rifle has an AoE effect.
And you'd prefer to buff the hell out of a ghost role which already has a decent purpose in the game.

**Comment by ShadowDeath6** [comment]
Cogscarabs have no niche

they're literally just clock cultists but worse

Their only merit is that they can run away from people easier and they're still permafucked by tasers and stunbatons where anima fragments aren't.

They're not special in any way. Any clock cultist can do what they do and more because they can't utilize the actual backbone of the entire mode. Proselytizers are good, sure, but clicking walls and floors only goes so far when the rest of the cult has to manage the caches, other machinery, and everything else.

**Comment by Super3222** [comment]
> Cogscarabs have no niche

no they do. but you don't see it.
they have brass tools that move 2x faster than normal ones
and a toolbox which has 28 storage slots.
and their RCD is really good

ideally they're goal is to expand the clockwork base. /NOT/ create the machinery but, make it more efficient.

> they're literally just clock cultists but worse

Again, untrue. they have a different dynamic, one that's centered around base building.

> Their only merit is that they can run away from people easier and they're still permafucked by tasers and stunbatons where anima fragments aren't.

again untrue. faster tools, larger toolbox, and a powerful rcd.

'waaah but super i can't operate a slab'
tough shit. that's the cultists job to deal with, not yours. again, your role is not to create traps, machines, or cast spells. that's the cultist's job. your job is to make sure everything is working at top efficiency. that's their purpose shadow, that's how changelingrain implemented it into the game, and guess what, it works. i don't want to come out like an asshole but seriously, get use to it.

the only slab-cogscarab action I see would be something like this: https://github.com/tgstation/tgstation/pull/19326

otherwise no hugbox

**Comment by ShadowDeath6** [comment]
why do you keep saying they have an RCD? they have a regular proselytizer, they can't break down walls or do shit, it's not anything special

> their tools can do things slightly faster

wow, borgs can too (and before you say b-but this maegs them able to cut down rwalls better than clock cultists can xdddd, engiborgs with RCD can just eat the rwall)

> larger toolbox

that's definitely game changing

What niche do they fill that a clock cultist can't do one hundred times better

**Comment by Super3222** [comment]
> why do you keep saying they have an RCD? they have a regular proselytizer, they can't break down walls or do shit, it's not anything special

I know but, I like calling it a golden RCD. It converts metal walls and floors into clockwork gold.

> wow, borgs can too (and before you say b-but this maegs them able to cut down rwalls better than clock cultists can xdddd, engiborgs with RCD can just eat the rwall)

Base.
Building.
And I'll get more into that below,,

> that's definitely game changing

Use your head.

> What niche do they fill that a clock cultist can't do one hundred times better

Oh well idunno shadow

they have their clockwork RCD which will LITERALLY convert metal (rods, plasteel, normal metal) into replicate alloys which they can use to power their proselytizer. Add that with the fact they have tools which are 2x faster or how you put it "exactly like borgs", and any cogscarab that knows their stuff will become a great asset to the team.

no this really is a big hugbox and, it's a really dumb one. they do not operate slabs within good reason, and this buff will fuck up the balance of the mode.

i thought this would clear it up earlier:

> create traps, machines, or cast spells
> machines, or cast spells
> cast spells

probably the last thing i want to see

oh and inb4, you see a lone cogscarab camping in bar maint with tons of structures set up, a proselytizer that never dies and, burnt to death corpses of every officer that's tried to come in.

cogscarab's are dependent on a base and should stick to it. do not make them independent. :-1:

**Comment by ghost** [comment]
Cogscarabs are not spawnable clock cultists, dumbass. They exist to assist the cult, instead of being the cult.

You don't get to spam 50 cogscarabs with tomes and completely make converting humans absolutely unnecessary because you have a shitton of super speedy tiny-hard to click drones with all access and clock cult powers (including all scriptures because you made 50 cogscarabs) and can make more of themselves indefinitely with those same tomes. They would steamroll so hard. It'd be like giving artificers jugg punch and the ability to manually soulstone people and make them constructs themselves, no cultists required.

This would make them incredibly overpowered. They can use all the spells that would fuck security over, can make infinite of themselves with their newfound cachespamming wallspamming abilities so components would be no limit whatsoever for them, and use their all access to just charge into the armory, grab the guns and go ham on security before they can react.

This would happen almost every time. It's ridiculous and overpowered.

Cogscarabs already have a role-a SUPPLEMENT to clock cultists, in that they exist to improve and improve only on a currently existing base by making replicant alloy, prolyterilizing, ect. I would MAYBE agree to giving them the ability to make tinkerer's caches and maybe clockwork obelisks or ocular wardens on their own, but that's it. They are supplementary base builders-if the only cultists left in a clock cult are cogscarabs, the cult is fucked, similarly to how if the only cultists left are juggs or artificers  ect, they are also fucked unless there's a convert rune drawn and they can get someone over there in time and convert them.

This is a bad change and motivated only by salt in that you couldn't solo as a cogscarab-and they're already insanely powerful in comparison to regular humans. Their only weaknesses are that they can be stunned (easily avoided due to tiny sprite and blending in p well on cult floors) and that they can't solo cult.

**Comment by Alek2ander** [comment]
Give syndie drones a spellbook

**Comment by ShadowDeath6** [comment]
well if people make a paragraph and a :-1: the PR is automatically denied

**Pull request closed without merging**
