### PR TITLE
Adds bodypart hotkeys

### PR DESCRIPTION
**Pull request by Time-Green**
Requested by @ArgyleSweatshop / Maya / @LarissaMayrink

Adds hotkeys for the bodyparts
**NUM1 right leg
NUM2 groin
NUM3 left leg
NUM4 right arm
NUM5 chest
NUM6 left arm
NUM8 head, eyes and mouth** 
:cl:
rscadd: You can now use the numpad to select bodyparts
/:cl:

Also steals a proc from https://github.com/tgstation/tgstation/pull/21039

### CODE REVIEW

**Comment by matskuman5** [comment]
Rscadd: You can now use

Use? Use what? What can I use? Can I use anything? Can I use EVERYTHING? Can I use someone? What does "use" even mean?

Shit PR

**Comment by Time-Green** [comment]
arghhhhh
Probably because I am not a coder because I dont have a coder rank

**Comment by Cruix** [comment]
Why are there changes to skin.dmf?

**Comment by X-TheDark** [comment]
Because these are hotkeys. Hotkeys are defined in the skin.dmf file. Unfortunately, he seems to have added these hotkeys via Dream Maker, which (upon saving it) made unnecessary alterations to the **entire** file (changing some variables to something)...so this would need to be redone manually.

I've had this problem before, when I ported hotkeys being instant in our old codebase. Hotkeys would be best to be defined manually, instead of using DM.

**Comment by Time-Green** [comment]
oh

**Comment by Super3222** [comment]
@Time-Green Merge conflicts.

**Comment by Time-Green** [comment]
Yeah sorry, I thought x was going to manually merge it because of the key binds, but he did an x and dissapeared again

**Comment by LarissaMayrink** [comment]
Wait... reopened, did you fix it? god time, i love you.

**Comment by Cruix** [comment]
It looks like this broke the skin
untitled

**Comment by Time-Green** [comment]
jesus, editting this manually is a pain in the ass

**Pull request closed without merging**
