### PR TITLE
Shit PR

### PR DESCRIPTION
**Pull request by matskuman5**
# Toilet rework!

Toilets are now flushable and have proper disposal pipes!

The stalls now have locks!

The toilets have a proper flushing sound!

:cl:
rscadd: NanoTrasen engineers have replaced the old toilets with the new HT-452 models! These ones can actually flush!
rscadd: Locks have been added to the bathroom stalls.
/:cl:

### CODE REVIEW

**Comment by McDonald072** [comment]
:hankey:
You need to change the toilet path on all maps

**Comment by Super3222** [comment]
Clogging toilets will be fun.

**Comment by Time-Green** [comment]
I'm impressed matsk. Did this work correctly?
Also, make sure we can flush people down the toilet

**Comment by matskuman5** [comment]
The toilets work pretty much exactly the same as disposal bins now. So you can flush people down toilets.

You can also still beat people with the lid and swirlie them.

I'd also make them cloggable but I don't know enough code to do that :cry:

**Comment by Cruix** [comment]
Make it so they can only accept tiny items

**Comment by LarissaMayrink** [comment]
>being chased by sec
>emag on my pocket
>esword on my bag
>flush both
>you got no proofs son, i'm clean
Now i want to gimmick a drug dealer who carries a few hundred space drugs patches all the time

**Comment by Slinky5890** [comment]
Where do the flushed things end up. Still in disposals or in the janitor office or something?

**Comment by matskuman5** [comment]
It goes to the cargo office, like normal disposals

**Comment by Groudonmaster** [comment]
Didn't we all shit on eph for trying to do something similar

**Comment by Super3222** [comment]
No Eph was literally considering adding shit mechanics to the game. This PR only makes teolits flushable.

**Comment by McDonald072** [comment]
I think you accidentally half the game

**Comment by Mrcreepssss** [comment]
wait does that mean eph failed to add shit?

**Comment by Cruix** [comment]
The 81,000 line removals are probably because you made the map non-tgm, do the map changes with fastdmm instead.

**Comment by matskuman5** [comment]
>The 81,000 line removals are probably because you made the map non-tgm, do the map changes with fastdmm instead.

FastDMM is shit and has no basic features like copy and paste, or editing instance variables

**Comment by Cruix** [comment]
Fastdmm can do both of those things

**Pull request closed without merging**
