### PR TITLE
Vampire Mode II: The New PRssus

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

A game mode featuring atrocious vampires attacking the crew and advancing towards their objectives.

Depending on the amount of blood a vampire collects they will automatically unlock new sets of abilities/skills. Sometimes new, and sometimes strengthening old ones.

I fixed all of the problems Cruix mentioned in the last PR. I also took the initiative of commenting out broken abilities (ghost rend, ghost vision, cloak of darkness) so that this PR can be merged faster. I DID try to fix them, but couldn't figure out anything in time.

#### Changelog

:cl:  
rscadd: We've finally added Space Vampires to the game!
rscadd: Vampires have their own mode (in rotation).
rscadd: The more blood they absorb, the more abilities and traits they unlock!
rscadd: The crew should be on the lookout because there's no telling what those vampires might do!
/:cl:

### CODE REVIEW

**Comment by Koffheatalt** [comment]
merge this

**Comment by ghost** [comment]
List the abilities here for the uninformed.

**Comment by Super3222** [comment]
Sure!

The beginning of the round (0 blood):
Bite - drains blood from your target, this blood is collected for the use of unlocking more abilities/traits & for using abilities
Gaze - short stun, is fired with middle mouse button click
Bloodtracking - traces who was recently bleeding from sniffing blood spills
Digital Tracking - toggle used to mask yourself from the AI's tracking system
Digital Visibility - toggle used to mask yourself from the AI's cameras.

Basic (100)
Clear stuns - clears your stuns, and pumps adrenaline into you
Hypnotize - puts people to sleep in 4 seconds, pretty loud

Novice (200)
Basic vampire eyes - your eyes are more adjusted to darkness
Ash Reanimation - if blood crosses your ashes you will be reborn

Skilled (300)
Radio malfunction - deactivates all nearby radio devices
Bat transformation - you can now morph into a bat, you'll be able to seep through airlocks in this form as well
Coffin - you will be able to assign a coffin as your vampiric bed. while sitting in this coffin you'll be able to regenerate health and blood (I advise all vampires to take apart the wood table in arrivals and make a coffin their self instead of going to the chapel)

Average (400)
Agonizing Shreik - powerful scream breaks all nearby windows and computers
Bat Swarm - summons six to eight angry vampire bats

Adept (600)
Stronger clear stuns - old one is upgraded, this one contains omnizine
*ghost rend and cloak of darkness would have been on this level

Advance (800)
Strong Vampire Eyes - thermal vision + flash protection
Charm Creature - turn a simple mob (or hostile) into your vicious vampire pet

Master (1000)
Set Coffin Turf - sets a turf as the destination for where you want your coffin to go.
Teleport Coffin - instantly teleports your coffin to the set turf

**Comment by Super3222** [comment]
Travis failed for some weird reason.

**Comment by AsV9** [comment]
I know, @Super3222. Been trying to fix it for an hour now.

**Comment by Ratvar** [comment]
Can you ash reanimate yourself with blood mist grenade set to go off on your death?

**Comment by Super3222** [comment]
;)

**Comment by Super3222** [comment]
;)

**Comment by Ratvar** [comment]
;)
;)
;)

**Comment by Ratvar** [comment]
...can you use advanced blood grenade to become unkillable. Like, those reusable one.

**Comment by ghost** [comment]
Seeing as the solution is 'clean the blood', no. Also, the vampire starts off with 0 blood when reborn, so he's gotta work from the ground up.

**Comment by Zostroll** [comment]
So can you take blood from monkeys? From humanised monkeys? Is anything stopping you from ordering 20 blood pack crates and then hooking em up to a braindead and draining them?

**Comment by ghost** [comment]
About as much as there is stopping a changeling from manufacturing 15 monkeymen in genetics and absorbing them all. It's risky, time consuming, and leaves evidence. Plus, once you get that done, you still actually have to kill people.

IV drips are extremely slow too. Short of very carefully using a monkeyman as a battery over the better part of twenty minutes, a vampire is just going to blitz through five monkeymen or so and now that's five dead bodies that are definitive proof there's a vampire with access to genetics, just like finding a bunch of husked monkeymen proves there's a ling.

**Comment by Ratvar** [comment]
Ling horrorform now can gib any body they want without creating skeletal remains in process, so, no finding husks - just crowbar floor
 Neither changelings need to absorb anyone to get access to their BEST abilities, while vampires do to get any high tier powers at all. Don't say horrorform is better then maxspeed adrenal armblade, and don't say that finding 15 sucked corpses will help you with thermal vision++ vampire who can cast his parasting over,over and over while phasing through all doors.
There is a big difference between manufacturing 15 monkeymans just to buff your horrorform+shield+unlock cuffremove and getting all vamp abilities unlocked for free, getting permanent flashproof thermals, et cetera

**Comment by Super3222** [comment]
I can make bite not work on monkey-ified humans.

**Comment by Alexandria404** [comment]
How many spawn? What is their end goal? What is the win condition? Do rules need to be added/thought over?

**Comment by Super3222** [comment]
> How many spawn?

3 vampires for 30+ pop. After counting to 60 the game will create 1 more vampire for every 15 more players.

> What is their end goal?

They get normal traitor goals, alongside gaining a certain amount of blood.

> What is the win condition?

Since their individual antags it's completing all of their personal objectives.

> Do rules need to be added/thought over?

I cannot think of a scenario where rules would need to be implemented. I don't think they need a metashield either because it's pretty obvious someones a vampire if they're biting you. Unless @AdamElTablawy wants any rules added.

EDIT: @Alexandria404 I'd probably have regulate a policy where they have to bloodsuck their victims after killing them.

**Comment by ghost** [comment]
Follows the same rules as changelings do in relation to absorbs, @Alexandria404 

Because vampires do unlock more powers as they drain blood, and some abilities cost blood to use, they ARE going to be consistently snacking on people, so it's moreso that you'd have to be looking for the obvious vampire who's just eating for the sake of eating, and not for accomplishing his objectives (which usually includes assassinate + blood req, and no, spending blood doesn't mean you have to get more to accomplish obj)

**Comment by Super3222** [comment]
I can't fix the merge conflict anytime soon. Also, merge zombie mode before doing anything with this.

**Pull request closed without merging**
