### PR TITLE
Removes dreaming

### PR DESCRIPTION
**Pull request by Cruix**
I don't like dreams, most of the people I have spoken to do not like dreams, and it seems like they are not going to be improving in the near future.

:cl:
rscdel: Removed dreaming.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
best pr ever

**Comment by Oakboscage** [comment]
Yes please. Took you long enough.

**Comment by Kmc2000** [comment]
merge the dream rework?

**Comment by Ratvar** [comment]
merge the dream rework?

**Comment by Time-Green** [comment]
I am gonna take a little more time to work on the dream rework, to really figure out a way to have it be truely stable. I requested the old one be removed, since it's just shitty.

**Comment by Kmc2000** [comment]
Speedmerge please then!

**Comment by ghost** [comment]
the dream re-work is super unstable, you're doing a super dumb thing for a feature that doesn't need it. (you can just use cameras) so whatever you do in the end there will always be enough issues to make the dream rework not worth it.

**Comment by Time-Green** [comment]
Floyd can you please fucking stop? It's hurting my feelings

**Comment by ghost** [comment]
well i'm sorry that's not my intention but you're putting the coolness of this feature over the actual practical use. i just dont get why you ignore every comment about using cameras over moving the ckey to a new body. i think dreaming is fine as a feature but moving over the ckey is just always gonna be too large of a hazard to be used for dreaming imo

**Comment by Time-Green** [comment]
I've been ignoring it due to me taking it personally and being bad at dealing with critics.
Reason I did it the way I did was to introduce something new, and I want as many possibilities as possible. + I really want a way to suspend people in temporary bodies without stuff going weird. MYbe I'll put up a seperate PR when I actually find a stable way to get it done

**Comment by monster860** [comment]
With dreams, there's no way to know if you're gonna get medical'ed or if you should just disconnect.

**Comment by ghost** [comment]
if you die you can just ghost.

**Comment by Kmc2000** [comment]
Next time time, please add a preference for it too  Not bein able to see medical stuff happening is annoying

**Comment by Super3222** [comment]
No, don’t add preferences to new ideas/features. People should embrace change, not find a way to dodge it.

**Comment by Jc1469** [comment]
the preference is called cancel-camera-view

**Pull request merged**
