### PR TITLE
Adam nightmares become my nightmares with conflicts

### PR DESCRIPTION
**Pull request by LarissaMayrink**
**Its NOT DONE yet, but its close enough. Most stuff that got cut will be readded on later pr's.**
The objective of these changes and additions is to make space more interesting and giving mining(and cargo, i guess) more interactions, variety on where and how to mine, what and how to fight and more stuff to explore, but now in space.

0. **What has been added**
-31 new deep space ruins
-one more zlevel added to the list of zlevels where space ruins can spawn and increases the number of spawned ruins per round
-KSS13 and other static deep space stuff got made into 5 different deep space ruins
-Adds variants to the mining wing
-Adds the asteroid field
-Adds the tinystation
-Makes asteroids gravity lacking(they are too small to have gravity)
-Makes asteroid fauna capable of walking in such gravity lacking places(aka: Goliaths and broodlords now have magboots)

0.1 **What has not been added but is done and bugged af**
//it has all been fixed already//

0.2 **What is no longer being added now and why**
Tinystation variants: The ammount of problems that i'm facing when trying to fix the snowflake items for the other variants is really big, so, i will add them in a later date so that said problems won't delay this pr for too long.

The big old (but modified) asteroid and its mining wing variation: No problems with these but without the random ruin generator there is not much sense in having it.

A random ruin generator for the asteroid: Here is the problem, i just found a better way of doing this without the need to use my potato code, so, i got rid of it and will rewrite it to match how the code deals with lavaland.

The trading hub: There is not much sense in having this without the events, so it got removed from z6.

Smuggler, pirate, raider and infiltrator events: This feels too disconnected from this changes so i will make it as a separated pr.

1. **The mining wing and its variants**
My addition makes the mining wing into a modular part of the station that gets randomly selected btween 3 variants during roundstart. Each variant has its own shuttle, mining target and ruins to wich it can dock(if said ruins spawn).

_**The Lavaland Lander**_
Its our current mining with no alterations besides where miners spawn at roundstart and a couple extra chairs. It has a small 6 seat shuttle that can land at lavaland.
http://imgur.com/qVJUppV

_**The Mining Bus**_
  This variation has 5 emergency space suits, 5 magboots for asteroid mining and a mining medic office complete with the snowflake mining medic hardsuit and the mother jaunter, but no magboot because the medic hardsuit has a jetpack, and like so he doesn't need a magboot. 
  The shuttle has 5 seats and 4 cargo tiles, it can move into the asteroid field, all randomly spawned asteroids floating in deep space and lots of deep space signals without a clear origin.
http://imgur.com/AayKCg3

_**The Asteroid Lander**_
  This variation has almost the same equipment as the lavaland version but with the mining medic office being added to the wing itself. 
  The shuttle can land at the asteroid, a few random ruins if such spawn and to two variants of the asteroid field.
http://imgur.com/nhFBDg6

2.**The Asteroid Field**
The asteroid field is a 320x320 zlevel which contains the tinystation(IF it spawns) and the asteroid field(always spawns). 
It can be reached through the mining bus, sometimes the asteroid lander and by launching yourself out of an airlock and hoping you will stumble over it.
It has 4 variations done and 6 more to be fixed of the doublespawning problem caused by god knows what.

3.**The Asteroid**
  Its almost the old asteroid, it has the same format but no stablished base, its a lawless land filled with pirate and smuglers hideouts, independant mining enterprises that may or may not be hostile, space slugs that want to suck your brains out and a few /youbetternotfind/ xeno lifeforms.

4.**Tinystation**
The tinystation is a VERY small independent station(up to 64x64 but mostly just as big as the mainstation bridge). It has 6 variations(Lizard, Plasma, Robot, Clone, Soviet, Plant) and btween 1 and 5 ghostroles based on the variation. 
They are mostly neutral but can still be raided by the mainstation for whatever resources they have, some of which are 'unique' stuff, things that the station can't aquire easily. 
Some variations get a shuttle that can go to the asteroid field where they can mine and later use said ores to trade for tech and equipment on a vending machines. While other variants get a trading shuttle that can travell to the station(and maybe a tradehub, but i'm not sure if i'm adding that)

Notes:
Map changes: z3 and z4 are now empty, z4 is used for spawning deep space ruins together with z7-9 and the white ship was moved into z6. Boxstation mining wing got deleted and a landmark placed over it to spawn the mining wing variations.

Great thanks to @AshCorr for the help everywhere, @Cruix for his framework which saved me from the abomination i had made, @Time-Green for a lot of help with tinystation and @Kmc2000 & @Execoud for mapping ruins.

:cl:
rscadd: Mining and deep space additions
/:cl:

### CODE REVIEW

**Comment by Chuggachar** [comment]
I like everything except even more god damn ghost roles.

**Comment by LarissaMayrink** [comment]
@Chuggachar Don't think about it like more ghost roles but alternatives as you won't have all of them at once, like, if the lavaland lander spawns ghostroles on deep space won't have a way of interacting with the station, and the same goes when a shuttle that doesn't leads to lavaland spawns. So the station itself will never get swarmed with ghostroles while not stopping peeps who got murdered or died due to incompetence at work from joining as a ghostrole somewhere and mining/farming isolated from the world until the round is over.

**Comment by Kmc2000** [comment]
cool

**Comment by Cruix** [comment]
You should really split these up as much as you can so they are not all held up by a bug in a single one.

**Comment by ghost** [comment]
i'll look at this later but this is less ass than expected

that being said NONE of these ghost roles should be able to get to station

**Comment by LarissaMayrink** [comment]
@AdamElTablawy on lavaland we got the heremit, bard, prisioners and golems who all can join the station crew, and for 3 of those their single objective is to find the station with the tools they have, plus the ashwalkers single motivation is to kill everything, which includes the miners, invading the mining wing and swarming the station, so, don't try shitting over my ghostroles as they are way lessened spiritual sucessors of what we already have on lavaland(except by the ashwalkers, i haven't added a antag ghostrole)

**Comment by LarissaMayrink** [comment]
@Cruix i'm already holding up some parts of it, thats why this looks 'incomplete' if compared to what i had said a few weeks ago on coder. The problem is that i need to at least add enough stuff to space to make it interesting after taking away half the static space stuff.

**Comment by LarissaMayrink** [comment]
I increased the number of space ruins per zlevel to 3-5, now each round will have btween 12 and 20 deep space ruins which increases the odds for one of the 59 ruins to appear in a round to about 27%.

_Also //free miners in 1/4 of all rounds//_

**Comment by LarissaMayrink** [comment]
I'm going to fix this, eventually, i'm just lazy and have been mapping stuff because the current fields aren't good enough.

**Comment by Super3222** [comment]
Larissa if you need help to fix the merge conflicts I can do it with you. I know short cuts to fixing maps.

**Comment by ghost** [comment]
deadpr

**Pull request closed without merging**
