### PR TITLE
WIP Minsky Station For Testing and Abuse pt.2

### PR DESCRIPTION
**Pull request by MayhemSailor**
Not Ready for Release
Minksy Station, Working Name, Map in progress

Minsky Station is provided for community feedback as the station comes near to completion.
The following are still being placed in the map (forgive me, I'm slow!)

    Security Camera Network - In progress
    Disposals System - Not Started
    Nav Beacons (for bot navigation) - Not Started

Download, look, test, break.

Images:

**Arrivals**

Changed from a shuttle to an arrivals "pad" including ion shower effect upon arrival.
Arrivals Engineering Outpost to the north west, Security Checkpoint is central, and what will be Arrivals Triage in the North East
 
**Command**

Just north of Arrivals is the Command Section. At the North is the Bridge, with the Captain's Cabin underneath to the West, and the Vacant Office to the right. South of the Captain's Cabin is the Heads of Staff Meeting area, and across is the HoP office. To the extreme South East you can see one of the Transit Terminals. Each major department has one of these across from its main entrance.

**Medical**

Station West is occupied by medical. In the North East is Chemistry, which has had a slight enlargement. To the West is Medical Supplies, then Psychiatry followed by the CMO office. In the extreme North West is Medical EVA. One of the concepts for this station is decentralizing EVA. Each major department has a fully functioning cycling airlock (no more spess wind for EVAs). Surgery has had a storage added that is stocked with blood and spare organs. Cryogenics is a proper department, with extra tubes added and the required expansion in the air system. The Treatment Area has been enlarged and separated between Standard Care to the East, and Advanced Medicine to the West. The Paramed Station is in the South East of the Medical, with an expanded Genetics to the west of that. Two cloning stations and a separate cryogenics for their use  is included. The morgue features the Body Dump disposals outlet, which is a direct connection to Robotics (Helping the janitor out a bit). Virology can be found in the South West of Medical.

**Library, Chapel, and Giftshops**

Station Northwest houses the Library, Chapel, and the station's giftshops.

**Security**

Station Security is located at Station North and has seen a significant overhaul. Perma has been expanded to four cells, and an assortment of prisoner enrichment has been added. The Labor dock is west and essentially remains unchanged. Brig Control is East of that and North of the four jail cells. Prisoner release can be controlled by button action operating the doors to limit officer interaction with the paroles. North of the main entrance is Prisoner Processing, with the HoS office directly north of that. In the inner South East is the access observation and two protective custody cells for voluntary interment. The Detective and Lawyer Offices round out Security South East. The Interrogation Suite has the new Security Intelligence room just to its east of that. This room features communications monitoring of all station channels, as well as telecommunications interface, and a teleporter for rapid deployment. The Armory and Equipment room has seen major overhaul as well, and has been integrated with the new Security EVA.

**Dorms, Theatre, and Bar**

Station North East is occupied by the Dorms, an grand theatre, and a new bar setup. The bar is actually what inspired most of the station. The vast windows can be shuttered by the bartender in case of emergency breech. Also, included in the bar is a food delivery outlet, with a direct connection to the kitchens.

**Engineering**

Main engineering occupies the northern half of Station East. From the east is the equipment room, power generation, the SMES room, The CE office to the north of the new Engineering Control Room, along with Engineering EVA. Telecoms is more integrated, but still left apart for ease of operations.

The southern half of Station East is Atmospherics, which has departed from the cut&paste style of atmosias featured in previous NT designs. The North East of Atmospherics is the Atmosia Service Desk, with canister storage in its own separate room to the East. The far East is the tank loop, with mixing and the mix tank taking their own individual areas.

**Cargo**

Cargo is located in Station South East. The Cargo Office is center West, with the Stock Office to its South. The QM has his office to the East of that with the Mining Dock to the South East. The center strip is occupied by Deliveries, both standard and telepad. The Cargo Bay is located to the North East

**Research**

Research has also seen a significant design shift. The firing range has been attached to the research security post in the North East, with R&D to the south of that. Xenobiology occupies the South East of Research with Toxins taking up the South West. It should be noted that the piping in this area has seen the most improvement. The RD office is located in the heart of RD, and comes equipped with everything they need to do research without bothering the rank and file. Telescience has been relocated to the North West, with spare room for building machinery.

Across the hall to the North East is the new Robotics Suite. With a separated surgical area, and patient processing. Also just to the North West is the AI Core, which one of the transit tubes traverses quite safe from the turrets, we might add.

**Kitchen, Cafe, and Hydroponics**

And finally, the food service areas occupy Station South West. With the Kitchen and Cafe to the South, Hydroponics and chicken coop to the North of that, and the Station Garden dome finalizing the connection to Medical at Station West.

Changelog
:cl
rscadd: adds minskystation wip
/ :cl

### CODE REVIEW

**Comment by Dragonforcefive** [comment]
What exactly is this?

**Comment by monster860** [comment]
You should use fastdmm

**Comment by MayhemSailor** [comment]
With the looming possibilities of map rotation, and no one stepping up to port disc, this is the disc inspired yog-native station.

Also, I have no idea what fastdmm is, but I intend on finding out.

**Comment by Super3222** [comment]
Looks beautiful.

My only criticism is that the hallways get stretched out pretty wide which is nightmare for security catching greytiders and antags trying to kill someone in the hallways.

If you can't find a way to shorten it, I'd suggest putting unmovable decorations that correspond with the department they're near.

Via science would have that royal plasma tank (that I made earlier) - talking about how it was one of the very last models of the original plasma canisters miners and scientists used to soak up plasma.

**Comment by MayhemSailor** [comment]
Super, are you talking the length of the halls, or their width? Most of the halls maintain a 3/4 tile width.  The one super straigh hallway is outside of research, but I've been toying with some ideas to corrugate it to keep stray fire from being an issue.

There's plenty more decor to go in, has the Royal Tank been merged yet?

**Comment by Super3222** [comment]
@MayhemSailor I'm talking about those giant pieces of space in front of every division.

**Comment by MayhemSailor** [comment]
@super3222 there is 0% chance of those pixel art atriums changing in basic form/function. They're meant to be challenging, however each division has a "lockdown" that physically separates its 'front doors' from access, but maintenance access is a whole other question.

**Comment by ghost** [comment]
oh boy let's see how this goes]

# Arrivals

meanwhile on 'HELP POWER IS OUT AND I'm TRAPPED ON ARRIVAL SHUTTLE' station 13 there's no fucking way out to run and it's so far deep in space that if something goes wrong-EG bolted doors-you can't smash some windows and run you're just stuck

also i do like the arrivals landing pad idea

these windows are gonna be hell when some assfuck changeling/revenant inevitably starts screaming/space dust

too many space exits in arrivals, there ar elike fucking 5

the maint is weird and linear but big and also just sort of...not needed i guess

# Command Hallway

captain's office chairs too far away from wooden tables

blast doors OUTSIDE of the glass windows instead of on top of them

head of staff meeting room should not be so near cap's office or have a door in it, get ird of door
>hop office in an area so fuckign far away from the station

bridge front  looks like a mushroom penis

unnecessary camera over comfy chair in bridge front

why is there a comfy chair and some buttons far away from front of bridge and all like jfc just put the buttons there that thing just looks completely weird 

fireaxe is in a weird place

# Service Area

maint is weird and linear, again, like come on this is the dullest maint since yogbox

light tiles are ugly

clerk's office white floors contrast really badly with your dark floors

library maint is barren as FUCK

is that tiny wood room by chapel supposed to be the old bar because if that is i'm gonna need to go to the bar

# Security

front of security is tighter than a duck's asshole how is anyone going to get through this many blast doors and rwalls

what the fuck is with the random thick walls by law office

>'warden are you watching the brig cells' 'no i'm watching the armory' 'go watch the cells' 'ok' 'WARDEN ARMROY BOMBED'
  how can anyone watch the brig cells when they're stuffed into a tiny ass corner surrounded by thick walls until we port /tg/'s camera updates that makes watching prisoner cells possible

did you label any of the cameras to have name because if all the names are 'brig cell camera 1' 'brig cell camera 2' i will shit out my eyeballs and eat them

no gulag labor teleporter, 0/10, also tiny and squished and inaccessible

hos office has no carpet

also has no privacy shutters to avoid being assblasted by carp or lasers

security equipment room is weird

meanwhile on 'guys where's interrogation' station 13 like why the fuck is interro and all that so secluded and hidden

too many intercomms in the teleporter room

>A TELEPORTER ROOM why

what the fuck is with all the vents by the armory that's gonna make some killer space wind

lawyer office has one lawyer cabinet and not 2

det office has two camera consoles and-are there gonna be two fucking detectives or something because otherise that's too much equipment

all the armory hardsuits are by the area ops are gonna bomb into the armory from

all these fucking arilocks god help anyone not an engineer when the ai goes rogue

permabrig-everyone is dead to space carp editiion

like seriously if some dust or a carp breaks a window the wind will fuckign suck everyone into shocked grilles 50000 times

# dorms theatre n shit

dorms needs a door into theatre

theatre is pretty ncie i guess but get rid of the metal and glass and put down some shit like sunglasses look at the metastation theatre

> N O  M A I N T E N E N C E S P O T S 

seriously it's just like an unending long line of maint-AKA 'where the fuck do we hide' for antags

bartender doesn't spawn behind bar counter

WHY DOES BARTENDER HAVE A FUCKING ICE CREMA TRUCK

>2 booze barrels 

you know the booze barrels explode like syndibombs if a blob eats them right

again, no doors in below bar maint

random sealed maint area that's empty by bar

>BANANIUM sTATUE

are yous ards
t

as
t [uspgs'dguspo[g

you're aware if someone's riding a disposal pipe that's literally IN THE WALL they're going to fuckgin die right

# Engineering

front rwalls are too thick

YOU MADE EVERY DEPARTMENTA SATELLITE BUT DIDN't MAKE A SATELLITE FOR TCOMMS

singularity EMPs are going to assrape the SMES and release it

there is ZERO MAINT in all of engi

# cARGO

where are the disposal pipes going to come in/go/did you even add a grinder because if everything's a sat any space wind is gonna turn 'jumping into disposals' to ''HELP SPACE'

>cargo telepads when those have been out of use for a long time

why is the autolathe so far in? Ddi you add a public autolathe anywhere else on the station?

mining shuttle is gonna be absolute hell to leave for ashwalkers/podmen/anyone without a mining id due to being psuhed into space, might wanna make ti a tad bigger

cargo warehouse needs to be accessible on the cargo shuttle bay\

# Science

>PUBLIC TELESCIENCE
you fucking madman

you absolute madman

also why is R&D so far in why si the most vital science department everyone will nag so far in

no science maint to murder in

tbh i like metastation's xenobio maint, add something like that

# Robotics

I like robotics, I dislike the lack of a robotics maint

AI sat is nice too

except it's really small

and the turrets

and the fact that it's basically a shtity copy of boxstation's AI core except with a shit upload

upload turrets trigger me hard

upload APC too far in

upload doesn't have UPLOAD BOARDS

no borg chargers in ai front area

no liquid foam dispensers

why do you have TRANSIT TUBES leading DIRECTLY INTO THE MOST SECURE AREAS ON THE STATION JESUS FUCKING CHRIST

someoen's gonna fucking push a syndicate bomb into that tube and just LAUGH

what's worse is that this is the TUBE THA TLEADS TO MEDBaY

# Kitchen

**You gave it a bar sign you dense mother fucker.**

# medbay

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**deep breath**

aAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa

WHAT THE FUCK IS THIS

>MORGUE DISPOSAL PUSHY THING

>NO MONKEY CuBE BOXE SIN GENETICS

>TOO MANY TUBES  AND SLEEPERS

>VIROLOGY CHEM LABS!!!!!

>ILLEGAL IMPLANTS, DEMON HEART, SURGERY TOOL ARM BELOW VIRO







AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA


# the station

if some fuckwit unwrenches just one of those transit tubes it's a shuttle call because the station is cut in half 

space carp random event/meteor random event is god help us all

did you even THINK about blob before you made this map becaus eif a blob spawns it's gonna be breach city


hwo the fuck does sec get anywhere

how the fuck does anyone get anywhere

this station on lowpop is gonna suck more ass than a syrian hooker trying to get enough money to flee the war

**Comment by MayhemSailor** [comment]
Adam, while the particulars in how you present you feed back leave much to be desired, I believe I can find some constructive items in here. I'll have followups shortly.

**Comment by Time-Green** [comment]
I like the whole map, but have one major concern:
It's all connected to space. In the event of a carp out break or meteors everyone but the ones with EVA suits would die.

**Comment by MayhemSailor** [comment]
@AdamElTablawy 

**Arrivals**
The pad room has been shifted to provide for player escape options in the event of power loss or door bolts being dropped. That was a good catch:


**Maintenance _omnia circum_**
Maintenance is by no means complete. There is a reason it is "barren as fuck" as it still remains an underdeveloped feature. I'd rather have the station areas complete and build it from there.

**Security**
The front of security is certainly made to be secure. I think you should read up on this, as it is built from the same concept as the British had for maintaining the defense of Singapore: [https://en.wikipedia.org/wiki/Battle_of_Singapore](Battle of Singapore, 1942). You'd see there are obvious strengths and some major weakness built in. I did not want security to be impenetrable, just defensible from the obvious method of assault.

As far as the vents in the armory go, I'll assume you are talking about this:

Outlined in red are the functional vents for the cycling airlock (outlined in whole in white). They are only on to pressurize or depressurize the airlock. As you can see I have already shifted the Security EVA suits, per your suggestion. I will be looking into shifting the brig to the right side of security to help with the warden watching the areas, but I felt that it would give Prison Officers an actual meaningful job. As far as cameras Each has been given a proper name and I've verified their network lists. Brig Control has monitors tied to the cameras in both the Prison and the Brig.

The dock has been expanded somewhat, but its odd that you complain about a teleporter in station intelligence, but not one in the dock? I think the shuttle suffices personally, but if there are more asks for a gulag teleporter I am happy to place one.

Speaking of Station Intelligence, all of those intercoms are set to a different secure channel, for security to monitor, if someone should choose to do so.

Consider the recommendation of the HoS office having shutters complete.

**Engineering**

SMES room was an oversight of mine. I'm playing with the layout now, and will have it at least the same number of tiles away as can be found on box.

The front is going to have hollow walls just like science does, just haven't done it yet.

I'm horribly surprised I didn't hear any vitriol over atmospherics, although that may just be an oversight on your part.

**Research**
R&D is far in, but there are the input/out put belts for mineral deliveries and to get the goodies from the scientists. I've been playing with a couple different layouts to science in general, but I'll take a look at metastation and see what I can glean from there.

The AI "satellite" is under the same thing, it was a basic copy and paste. I have a shell built  does like metastation, leaving the tube running through a redesigned AI upload, but physically separating the AI core from the station. 

**Medical**

Man, I love seeing you REEE. Its a highlight of my day really. Monkey Cubes will be placed into genetics. The chem labs in viro are literally just mutagen, and yes theres a body dump from robotics to the morgue, no more need to be dragging the bodies through the halls. Both that and the one I have going from the kitchen to the bar are not meant to be people movers, but I assure you I survived a trip through both.

More to follow, but for now I can't.

@Time-Green 

Most of the windows are placed interior of the station. From where I've noted the event spawns, you wont have carp migrations showing up in the interior space.

For meteor and other breach events, I've been pondering how to keep the overall look and not make it a death sentence. I can say that all windows are getting heavy firelocks for emergency containment, but there's still more that can be done.

**Comment by monster860** [comment]
It's a great map, but there's some minor cabling/piping issues.





You're missing a cable **and** a pipe under this door:


There's some useless yellow cables under the windows here:


You're missing a pipe under this door:


I don't think you need this random pipe under the table.


Missing pipe under cargo door


Last I checked, vents should be connected to **supply** pipes, not scrubbers

**Comment by MayhemSailor** [comment]
Thank you for pointing those out, I've fixed them in the working file.

**Comment by MayhemSailor** [comment]
Security layout has been reworked, addressing concerns over the location of the armory in relation to the wardens office. File will be updated shortly.

**Comment by MayhemSailor** [comment]
AI Core has gone from the box station cut&paste special to a new design loosely based on box. Bunker Core:


Will be included in next file update.

**Comment by oisin100** [comment]
You should still use the TGM tools even if no-one else is working on the map yet, as if you dont convert the map someone else will have to in future. It also means that other coders can make PR's to your repo for you to accept without making conflicts.

Also, Make sure that when you're adding in the firedoors that you use the half tile doors and not the full tile doors.

If a crewmember were to take the service duct could they not potentially see into the AI's core? http://prntscr.com/dc6qbs Its been malf AI's meta for a long time to always hack their Core APC, If players can see the core through the duct it would kill that meta.

**Comment by MayhemSailor** [comment]
@oisin100 current design you cannot see into the AI core itself, just the upload, as is the same with the core on box station.

The full tile firelocks I only intend on using in the windows with space on one side for breach containment, or are those things an issue?

**Comment by Kmc2000** [comment]
boner inducing

**Comment by monster860** [comment]
Borer inducing

**Comment by Super3222** [comment]
Don't mind the tgstation2.dm merge conflict. It's only happening because I changed our base map name to Yogstation :+1: Good luck on this

**Comment by ShadowDeath6** [comment]
Just read super's comment sorry

**Comment by Time-Green** [comment]
Re-open when you're continueing this.

**Comment by EthanMalakay** [comment]
Wasn't nanotrasen like, cheap bastards? They wont let no one to build such an expensive station :v

**Comment by Super3222** [comment]
press f to pay respects

**Comment by Mrcreepssss** [comment]
i have some feedback, though it's all gained from the screenshots

# 1st, breach-city
as this one is gonna be a deathtrap on space-based events, i'd reccomend giving each department some basic self-sufficiency things. like a SMES unit, and a chamber with EVA suits somewhere. and perhaps some sort of public teleportation system so you don't have to walk all the way it's quite long hallways i can only imagine.

# 2nd, maintenance.
some areas have like none, others have waaaay too much, so much it's basically just empty rooms. not NT style.

# 3d, AI core external assault defenses.
if someone break in through space you cant even see it! add cameras all around it thats for sure. with motion alarm probs but then DO move the airlock there more north  so people dont randomly trigger it. also it's gonna be WAAAAY easier to assault from the outside, there's only space. as long as you got EVA suit you can basically get into core just like that. and the SMES unit is a bit unprotected to my liking, i mean you only need maint acces now instead of bridge to get it... maybe it needs some external (push?) turrets?

# 4th, kitchen area,
add doors east of cafeteria, so you don't have to make that awkward bend to go through. also please make some of the cafeteria windows doors, i mean it's surrounded by a public hallway.

# 5th, bar area,
i'd like to see those big bulks of maint gone, perhaps make that into the EVA suits area/area SMES from my first suggestion? also i'd like to see small maint shafts between dorms/theatre and theatre/bar area to make it so you don't have to walk through the entire area to go from maint to maint, would add a little bit more "flow" to it. also make the bar entrance a bit smaller. it's WAAAY too big!

# 6th, SCIENCE!!!
i kinda agree with adam that the front-placed telesci and the back-placed RnD are a bit of an issue, perhaps you should have them swap places? you could give RnD a service desk then too! and no need to use radio for asking for RnD stuff.

# 7th, ALL HAIL CARGONIA!
i think the area layout is kinda stupid, i'll just say what it'd like it to be like.
i'd like QM's office to be at cargo teleporter, cargo bay to be the area where QM's currently is, mining at current cargobay and the teleporter at current mining. it'd make more sense i think. also the big and cool shuttle would have the glorious dock.
BTW. WTF IS THAT HUGE SHIP JUST OUTSIDE CARGO? not mad about it just confused...

# 8th, medbay.
it's pretty good, nice maint bit many sleepers and cells but not too shabby.

# 9th, chapel/library/cleric.
well if that small blotch east of chapel is supposed to be old bar as others think i'd prefer it moved to that big empty area west of chapel and north of library. further i noticed a lack of chapel crematorium and office?

# 10th, birdige
mainly switch conference room and vacant, preferably i'd have HoPs in current conference, vacant in current HoP and conference in current vacant. it just makes more sense to me.

# 11th, engineering
i like the way tcomms has that hallway that extends, but i don't like how that hallway attaches to engineering, and CE office looks forced in there. perhaps you should place CE's where the Tcomms hallway attaches and put the attachment a bit back? if you wouldn't mind i'd like the whole engi hallways a bit more to the main ones so both CE office AND sec office can attach to both atmos and engi.

**Comment by Mrcreepssss** [comment]
also, where is custodial closet? and holodeck?

**Pull request closed without merging**
