### PR TITLE
changes 2 letters to fix photocopying secret documents

### PR DESCRIPTION
**Pull request by Jc1469**
wow.
#1593

### CODE REVIEW

**Comment by ghost** [comment]
You aren't supposed to be able to photocopy documents.

**Comment by Jc1469** [comment]
except clearly you are because there's code specifically for doing it. it was just coded wrong.

**Comment by ghost** [comment]
except you're not because /tg/ removed it a while back

and it's a stupid idea, as well

**Comment by Jc1469** [comment]
https://github.com/tgstation/tgstation/blob/d8020e435a9c532d5ecbfa92bb336b59a9f249a7/code/modules/paperwork/photocopier.dm#L131

You done?

**Comment by ShadowDeath6** [comment]
Lol tg remoobed et

**Comment by matskuman5** [comment]
Good work John

Also Adam, we're not TG

**Comment by GrayRachnid** [comment]
Now fix taking pictures of the blueprints

i bet the picture code is fun.

edit: nevermind ignore this

**Comment by Time-Green** [comment]
@GrayRachnid 
Taking pictures of the blueprints is not a bug, and removing it is easy as hell.

**Comment by ghost** [comment]
We ARE /tg/.

We're a clone of /tg/ code with some minor changes. That's all. We have no outstanding unique features-the most different thing we have so far is the lavaland ruins.

Cybermen don't count.

When we make a change, we should base it off /tg/'s changes, because we are a clone of /tg/.

Here's a guideline to making a change.

-Would this change work for /tg/ or has /tg/ done it?

If so, proceed to the next step.

-Would it work for /tg/ if everyone is autistic?

If both of the above are true, the change will work, because the only real difference between us and /tg/ is that our playerbase is stupid. You know it. I know it. Everyone knows it. Almost everyone is an unrobust idiot and the ones that aren't take advantage of the ones that are.


Finally, here's a fucking reason not to photocopy documents.

The 'get blue documents do not lose your documents' objective exists.

If you photocopy your red docs, give it to the other guy and keep your own set you 'win' because you have a set of blue documents in your backpack.

Hence, /tg/ removed it. We should too. High risk items should not be able to be duplicated or reproduced ad-infinitum.

The documents are high risk items.

Making them able to be reproduced ad infinitum is a bad idea.

Do.

Not. 

Merge.

**Comment by Jc1469** [comment]
Yeah, adam, go away. It's a bug, it's fixed.  Feel free to make a PR removing it after, but til' then, fuck off. 
Thanks.  


# Oh and TG never removed it.  Again, you done?

**Comment by Stealthkibbler** [comment]
@Jc1469 
I am the president and founder of the Adams Yogstation Github of SS13. We just started powercreeping here on Yogstation. Henceforth known as Adam station. Since you're now trespassing on our private property, which includes the entire Github, I demand that you and your kind leave immediately. I have tasked super squads of badgers to ensure that you vacate in a timely and efficient manner

**Comment by ShadowDeath6** [comment]
tempted to make a "we aren't tg" label for every pr I need to tell adam in

**Comment by Cruix** [comment]
Fixes get merged whether we are tg or not

**Pull request merged**
