### PR TITLE
Medical Doctors now have access to cloning.

### PR DESCRIPTION
**Pull request by Super3222**
#### Intent of your Pull Request

Gives Medical Doctor's access to cloning. To be fair, /tg/ has already done this and it hasn't been a problem since. I don't think it's going to be a problem here.

We have Geneticists. Yes I get that, in fact I love people filling in their own roles and staying in that spot. But if that's the case why does the window to the cloning room get busted every round.

##### Changelog

:cl:
tweak: MD's have access to cloning.
/:cl:

### CODE REVIEW

**Comment by Frostben** [comment]
YEESSSS!!! YEEESSSSS!!!!! WOOOOOOOOOOOOHOOOOOOOOOO!!!! FINALLY MEDBAY DOESNT HAVE TO BE LOOKED AT FUNNY BY THE GENETICISTS WHEN THEY SEE A BUSTED WINDOW!!!!

**Comment by Jc1469** [comment]
balance police see access to door change.

balance police do not like.  as this extends to anyone with base medbay access, not "medical doctors".

just call a fucking engineer or get the AI to bolt it open.

**Comment by Super3222** [comment]
I'll add a new access level.

**Comment by ShadowDeath6** [comment]
med storage access is restricted to doctors, use that

**Comment by Super3222** [comment]
restricted to doctors, but not to geneticists.

**Comment by ShadowDeath6** [comment]
>making new accesses for no raisen

yes hello police can I ban super permanently forever thanks :ok_hand:

**Comment by Super3222** [comment]
You don't understand how req_access works... If I add the medical storage access then geneticists can't get in.

**Comment by Slinky5890** [comment]
Y    E    S

**Pull request merged**
