### PR TITLE
Removes John being stupid

### PR DESCRIPTION
**Pull request by Groudonmaster**
John is stupid

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
oops >:^)

**Comment by Time-Green** [comment]
This is good. Leaving yourself in the code is very bad practice.

**Comment by doerakpoes** [comment]
This sounds very good

**Comment by Cruix** [comment]
Sadly this cannot be merged as it removes a vital part of the codebase's code infrastructure and the entire program would collapse without it

**Pull request merged**
