### PR TITLE
Removes Devil

### PR DESCRIPTION
**Pull request by Super3222**
's shitty bug in the codex gigas

my second commit will remove the chance of getting "sin influenced" or whatever.

Fixes https://github.com/yogstation13/yogstation/issues/2248

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:angry:

**Comment by LarissaMayrink** [comment]
bad, evil, no, leave, don't be mean

**Comment by X-TheDark** [comment]
Multiple readings of Codex is a bug, so this fix is fine by me. That clickbait, though.

**Comment by Slinky5890** [comment]
Pahahahahaha

**Comment by Mrcreepssss** [comment]
dat name tho, looks like atleast shadow fell for it, i can't tell if larissa did though.

**Pull request merged**
