### PR TITLE
Fixes 3 bugs

### PR DESCRIPTION
**Pull request by Time-Green**
closes https://github.com/yogstation13/yogstation/issues/1778
:cl:
fix: Fixes wallets becoming invisible with head ID's inside
fix: Fixes people with fly limbs becoming invisible
fix: Fixes the clerks office being called gateway
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
cool

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
cool

**Comment by Time-Green** [comment]
dammit, why is this not compiling? It worked fine on muh lo-
Oh its because of metastation and shit...

**Comment by ShadowDeath6** [comment]
only 3 bugs smh

**Comment by Penguaro** [comment]
So this fixes #1778

**Comment by Time-Green** [comment]
@Penguaro Yep

**Comment by Penguaro** [comment]
@Time-Green If you add Fixes #(issuenumber) in your PR, it will automatically close that issue when the PR gets merged. It also makes a note of the reference in that issue so if someone finds that issue they'll see someone is already working on it.

You can also do it via the Commit Message
See for more info https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by Time-Green** [comment]
Cruix just told me about the fixes/closes things.
I still appreciate it tho, as all help is always appreciated

**Pull request merged**
