### PR TITLE
Adds a high quality whetstone to tendril crates.

### LINKED ISSUE #906: Poor tendril drops.
The tendril drops a sad trombone implant that has no sprite and can only be picked up with a right/alt click on the opened crate. You then can't really do anything with it. It also takes up the hand slot you picked it up with until you drop it. It is worse than useless.

### PR DESCRIPTION
**Pull request by Zostroll**
FIxes #906 

Replaces the sad trombone in implant with something useful.

:cl: Zostroll
rscadd: Adds high quality whetstones.
rscadd: Replaces the sad trombone implant in tendril cheats with a high quality whetstone.
/:cl:

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Your commit messages are bad. They should very briefly describe what changes the commit is making in two lines or less.

**Comment by Zostroll** [comment]
@Ephemeralis Better?

**Comment by Ephemeralis** [comment]
If you changed them via interactive rebase, you need to force push for the changes to take effect.

**Comment by Zostroll** [comment]
What?

**Comment by ghost** [comment]
Jesus christ no this is so op

Fire axes doing more damage than an esword no pls

**Comment by Zostroll** [comment]
Got any other ideas for what to replace the sad trombone implant?

**Comment by Super3222** [comment]
The wizards cursed heart. Shadow redid that one, just add some bio research points to it like maybe 6 or 7.

**Comment by ghost** [comment]
wiz cursed heart is in the tendril

i dunno maybe an item that makes hostile mobs  excluding megafauna non-hostile to you temporarily when used in exchange for some health via clone damage

**Comment by Super3222** [comment]
@Zostroll Stop using the web editor to make changes. Ask on the Disxord and we can help you set up TortisoeGit.

Also, how about adding clockwork gear that won't explode in your face.

Inb4 secret deep hidden lore about a nation ruled by Nairse and a nation ruled by Rat'Var fighting for domination over lavaland, awakening the elder god Legion that kills them all and turns everything into the hellscape that is lavaland today

**Comment by Zostroll** [comment]
What's wrong with the web editor?

**Comment by ghost** [comment]
MAKE IT DROP 3 GOLIATH HIDES

**Comment by Super3222** [comment]
The web editor is less flexible than everything else. It's also extremely messy and, you can't test your PR's with it so it's only good for very small changes and tweaks that won't completely change something.

ToritoseGit has a variety of features like being able to update multiple files under one commit, which makes for a proper PR.

And do not put 3 Goliath skins there lol. That's boring.

**Comment by ShadowDeath6** [comment]
put 4 goliath skins in there

also I'm making a new item for the chests so hold your horses

**Comment by Zostroll** [comment]
Adam you are such a troll.

**Comment by Super3222** [comment]
If you're keeping the whetstone, maybe lower the force to like 15-18. So it can still come in handy.

**Pull request closed without merging**
