### PR TITLE
kills miner salve stuns

### PR DESCRIPTION
**Pull request by ghost**
#### Changelog

:cl:
rscadd: Miner salve no longer stuns.
/:cl:

no hardstuns for chem, thank you very much

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
lmao

**Comment by BOBsHERE** [comment]
okay, add some better chem mixes then.

**Comment by ShadowDeath6** [comment]
try using chems that are poisonous instead of stunning chems

**Comment by BOBsHERE** [comment]
so we get either horribly lethal or horribly slow. Just make the damn chemicals harder to make instead of useless.

**Comment by ghost** [comment]
nope

no stun chemicals for chemistry, we're done

**Comment by EMT321** [comment]
I dont think this is the nerf chemistry needs.

**Comment by X-TheDark** [comment]
I wonder if I should even approve this.

**Comment by ShadowDeath6** [comment]
Powergamers btfo

**Comment by Cruix** [comment]
Reverting this so the PR gets 24 hours

**Pull request merged**
