### PR TITLE
Mapmerges the syndie lavaland base, and removes the bombs

### PR DESCRIPTION
**Pull request by Amelia0010**
🤔 

:cl:  
rscdel: The syndicate has stopped putting explosives inside of their impenetrable bunkers!
/:cl:

### CODE REVIEW

**Comment by Koffheatalt** [comment]
why would you do this

**Comment by Koffheatalt** [comment]
you can teleport in with telescience

**Comment by ma44** [comment]
To be fair, you can legit remove ALL the lava using some fancy things. In addition, the bombs should be removed from the testing room instead, as usual mixes will cause the base to explode.

**Comment by ghost** [comment]
@Koffheatalt you can't teleport in with tsci

it has a noteleport flag

nobody can enter it from the front either @ma44 we walled it off because we're retarded

**Comment by ma44** [comment]
>not just using the chem dispensers to make thermite to then kill the reinforced walls, using the sniper rifle or tools

**Comment by Cruix** [comment]
Please provide a reference video of you doing that on the live server.

**Comment by ghost** [comment]
@ma44 The walls are indestructible walls. They are not rwalls. This was a mapping change by matskuman.

Short of a phazon, nothing can enter the base.

**Comment by Zostroll** [comment]
Yeah Adam is correct you can't destroy those walls with anything other than the SM shard sword, admin delete or maybe the staff of door creation? Also I was pretty sure those bombs got there payloads changed to fake ones? Like the fake payload on the free mining ship.

**Comment by Amelia0010** [comment]
they didn't, otherwise I wouldn't be trying to remove them

**Comment by Zostroll** [comment]
My bad.

**Comment by Amelia0010** [comment]
I'm closing this as to not cause merge conflicts with the dynamo map PR

**Pull request closed without merging**
