### PR TITLE
Fixes adminheal not unhusking people.

### LINKED ISSUE #344: Admin healing a husk does not restore the character
So, when you get admin healed after your were husked from either over pressure or lack thereof, you turn into a walking husk. You are simply unknown, however, when you speak, you speak with your character voice. Your character has grey skin and the standard blood stains instead of your usual fleshy self.

### PR DESCRIPTION
**Pull request by Cruix**
Fixes #344

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
question does this also fix ling heal not unhusking

**Comment by Cruix** [comment]
Actually yes that was unintended

**Comment by ShadowDeath6** [comment]
nice

**Comment by Cruix** [comment]
I am fixing it to not do that. Making lings un-husk on regenerate is a buff to them and that is for another PR.

**Comment by ShadowDeath6** [comment]
why, it just forced them to buy fleshmend

**Comment by Cruix** [comment]
Because it is hilarious to watch a ling get up just before being cremated and running down the hall as a husk. You can just monkey form if you want to fix it.

**Comment by ShadowDeath6** [comment]
monkey form is still a ling point wasted

**Comment by Groudonmaster** [comment]
I like this function though. Remove fun tag please

**Comment by Cruix** [comment]
If you want to do this for adminbus you can add 64 to disabilities and regenerate icons.

**Comment by TheSadFox** [comment]
Removs fun for retmins ;_;

**Pull request merged**
