### PR TITLE
Adds more ambience

### PR DESCRIPTION
**Pull request by Super3222**
Lavaland (https://clyp.it/gluhp1yl)
- Added to lavaland

Nice Ambience (www.vocaroo.com/i/s1rNBRbKYGUq)
- Added to medbay

Abandoned Teleporter (www.vocaroo.com/i/s1gIEBNW4M33)
- Added to the abandoned teleporter
- Added to explored and unexplored ruins (due to its call to mystery)

#### Changelog

:cl: Kayozz11
rscadd: Adds a new ambience sound to medbay!
rscadd: Adds a new ambience sound to the abandoned teleporter and lavaland ruins!
rscadd: Adds a new ambience sound to lavaland in general!
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
these are all really good, but how long are they compared to the other ambiences?

**Comment by kayozz** [comment]
Shadowdeath6 - thanks. If there's any problem with the length of the audio then I can easily trim them or expand them / loop them. I can pretty much do this on the fly.

**Comment by kayozz** [comment]
Lavaland 42 seconds.... Can easily trim it if needed.
Nice ambience 56 seconds - Can cut it in half if needed or trim it with fade outs (might be tricky, if need be I can just re-edit it or start the composition again?)
Abandoned teleporter 56 seconds - same as the above. Can cut in half, fade our or re-edit... 

Or basically for the last two 14 bars looped once or 28 bars total.

**Comment by kayozz** [comment]
Ok so... I've looked through the other ambience sounds. The detective office songs are about 30 seconds, some of the more general ambience is about 12-15 seconds. So mine are between 10-20 seconds longer, although as I say they can easily be trimmed in half if it's a problem.

Also noted for when I start work on other sounds. I'll try and keep them shorter.

EDIT: The morgue 'ghost' ambience is a minute long. So mine are shorter than that at least..

**Comment by matskuman5** [comment]
Even if Super's retiring I want my ambience, goddammit

**Pull request merged**
