### PR TITLE
Replaces all windows and walls in Lavaland and its shuttles with refined walls

### PR DESCRIPTION
**Pull request by Tenryumi**
Too many times now, lavaland mobs have aggroed people through windows in Lavaland. In addition to that issue, why does a high-value Nanotrasen mining station have _less_ protection than the Lifebringer Vault?
## The mining station

dreammaker_2016-10-16_18-18-22
dreammaker_2016-10-16_18-18-31
## Gulag

dreammaker_2016-10-16_18-18-38
## Lavaland shuttles

dreammaker_2016-10-16_18-17-36
dreammaker_2016-10-16_18-20-23
# Reason for this change / Why it's needed:

Too many times now, I've seen lavaland mobs aggro people through windows and destroy more than just the station. They also destroy the mining shuttle, forcing everyone to wait for engineers to come to the mining shuttle to come to the shuttle and fix the breaches. This is not fun for anybody involved, antags and non-antags alike.

I imagine that there are so many windows because the original mapper wanted to impress newcomers to lavaland with the dramatic chance in scenery once a new player docks there. That's well and good, but that novelty wears off its welcome very fast when the windows are broken constantly.

Perhaps with this change, miners will finally be able to find a proper sanctuary in the mining station.

**Also I have been trying for two days now to get `Run Map Merge - TGM.bat` to work as it should. I must apologize for the massive change in additions and deletions.**

:cl:
tweak: Nanotrasen engineers have used resources obtained from Lavaland to improve the protection and integrity of its walls, and have improved the protection Lavaland stations' and shuttles' walls provide.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
b-but I liked the windows

**Comment by Karinrine** [comment]
I'm looking forward to this; I died once as a shaft miner while AFKing in the station to a goliath busting through the windows.

**Comment by Time-Green** [comment]
When I asked for this change, I meant the mining shuttle, by creating a new subtype of Rwalls.

**Comment by Alek2ander** [comment]
:-1: against the spirit of nanotrasen

Put up forcefields instead - a dangerous and fail-prone way to solve a problem is the best way!

**Comment by Tenryumi** [comment]
Unlike the change made to #1037 , it seems the necessary change to this PR will take a little longer to make.

**Comment by Super3222** [comment]
How are people suppose to look at the beautiful lavaland landscape from a view?

**Comment by ghost** [comment]
> can't look outside
> 
> no windows
> 
> hugbox rwalls that simplemobs can't break through
> 
> fucking you over if you lose your ID so you can't break through a window to get into the mining station and there's an ash storm
> 
> Fucking over ashwalkers/prisoners/podpeople/golems who need to break into the mining station windows to get in

fucking shit change man

**Comment by Tenryumi** [comment]
Closing this PR to find a better, different alternative to fixing this issue.
@Time-Green I will keep your suggestion in mind and do so.

**Pull request closed without merging**
