### PR TITLE
Revert "Disabled the borer event."

### PR DESCRIPTION
**Pull request by Super3222**
Reverts yogstation13/yogstation#689

If you want to make administration "easier" just ask in this PR and, I'll see what I can do.

### CODE REVIEW

**Comment by Time-Green** [comment]
Make people able to punch them out of their head

**Comment by ShadowDeath6** [comment]
port banhammers banning you if you suicide with them

**Comment by Super3222** [comment]
@Cruix Any problems?

**Comment by Super3222** [comment]
22 days later

**Comment by ShadowDeath6** [comment]
22 days later

**Comment by Super3222** [comment]
there's just no point anymore

**Comment by Super3222** [comment]
but on the other horizon, there is!

**Comment by ShadowDeath6** [comment]
uh

**Comment by Super3222** [comment]
no really cruix, are you going to merge this pull request or are we really going to drop one of our most prominent features

**Comment by ShadowDeath6** [comment]
Heated reopen this fuccboi

**Comment by ShadowDeath6** [comment]
22 days later

**Pull request closed without merging**
