### PR TITLE
Slightly improved the NTscript IDE

### PR DESCRIPTION
**Pull request by Altoids1**
Babby's first PR! Does two, pretty minor things:
-Adds bold for the first error of the ones that are listed, because it's usually the first one that's the problem
-Adds a timestamp for the compilation, so it's obvious that compiling went OK and that the script is live.

#### Changelog

:cl:
rscadd: Minor changes to the NTscript IDE, adding a timestamp-on-compile and some bolding.
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
I love you

**Comment by Altoids1** [comment]
[Uh](http://i.imgur.com/sCNiVX3.png)

Fuckin' github, I cannot revert that commit
No idea why the check didn't pass; it's just one line of code

**Comment by Cruix** [comment]
Travis was complaining because the changelog script crashed for some reason.

**Comment by Cruix** [comment]
You should not have multiple unrelated changes in a single pull request, because it gives the impression that you are trying to sneak in something that people do not like with something they do, even if that is not the case. It also makes it more difficult to look through the repository's PR history.

You should also never commit a change to your master branch, because if the pull request is not accepted, it is very difficult to clean your master branch and be able to make clean PRs again. The only thing that you should ever do with your master branch is pull from the yogstation repository master branch and make new branches off of it.

**Pull request merged**
