### PR TITLE
Adds the genetics medical first aid kit, improves medkits

### PR DESCRIPTION
**Pull request by ghost**
Medkits contain some useful chemicals.

Medkits of the normal and brute variety include quality medical bandages instead of the shitty versions.

Burn kits contain burn bandages and ointment as well, but less burn patches.

Brute kits contain bandages and bruise packs as well, but less burn patches.

Genetics medkit contains mutadone and mannitol pills.

Tactical kit contains a health analyzer as well.

Antitox kit contains calomel as well.
#### Changelog

:cl:
rscadd: NT medical officials have instructed a more stringent medical policy for research stations. Medical kits contain a wider variety of treatment options.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
eat a dick

**Comment by ghost** [comment]
you better frcdycking complile now you litlt ehsit

**Comment by Ephemeralis** [comment]
Hey the quality bandages are like.. 60 or 80 limb healing or something, I forget. Are you sure you want them that beefy?

**Comment by ghost** [comment]
brute patches heal 350 damage in total

50 on immediate application and 300 over time due to stypic in body on mob life

90 is piddles, esp since it's delayed

**Pull request closed without merging**
