### PR TITLE
Port: Refactors weather into a subsystem

### PR DESCRIPTION
**Pull request by Time-Green**
Requested by @AdamElTablawy , all credits go to @Xhuis 

Original PR: https://github.com/tgstation/tgstation/pull/19003

"Weather has been refactored from a weather control machine on the lavaland z-level into a subsystem. All existing weather has been changed to accommodate this change, and their code has been optimized by using addtimer() instead of sleep().

The new subsystem also supports adding weather to any z-level; for instance, if you made a weather called /datum/weather/rain_storm and made it target z-level 3 with a 100% probability, the rain storm would occur as much as possible with 5-10 minute intermissions. These intermissions take into account the weather's duration."

:cl: Xhuis
tweak: Makes weather a subsystem
/:cl:
And yes, I tested this.

### CODE REVIEW

**Comment by ghost** [comment]
Make sure to include the fixes that came after the initial PR.

**Comment by ghost** [comment]
once time-green ports this i'll port the fixes and all, i just needed this initial thing done

**Comment by Super3222** [comment]
In the process you've completely deleted the usefulness of barometers.

**Comment by Super3222** [comment]
You forgot to re-add the content we already had attached to the weather system. For example: Barometers

**Comment by ghost** [comment]
nobody liked them and this is necessary for the radiation refactor @Super3222

**Comment by ghost** [comment]
not one person has crafted a barometer to date

**Comment by ghost** [comment]
not one

**Comment by Super3222** [comment]
> crafted barometer.

You can't craft them. They're mining only.

I have seen **MULTIPLE** people use barometers. In fact, it's one of the most useful things associated with mining. In fact I was just playing as a miner this morning, and found out that there were more miners than just me running around with one.

It also wouldn't be hard to put back together. The code that you deleted is still there. If you need help contact me on Discord, Time. Don't tell me that removing new content just to port something is a good idea.

**Comment by matskuman5** [comment]
Not cool to remove other peoples code just because you didn't like it, Adam

**Comment by Time-Green** [comment]
I am so sorry, I forgot all about the barometers, I'll fix that. It's almost christmas so I don't know when.
I straight up copied some parts, since I thought there were no changes to it.

Super, I love your barometes, this is a horrible mistake

**Comment by Time-Green** [comment]
I absolutely can't get this to work. I am closing it, as I just can't do it.
If anyone else wishes to continue with this branch, PM me

EDIT: Cruix is porting it

**Pull request closed without merging**
