### PR TITLE
[s] Halloween

### PR DESCRIPTION
**Pull request by utahclock**
Adds Candy bowls to map, and adds trick or treat bags to spawns.
:cl:utahclock
rscadd: Adds Halloween fun.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Did you use your master?

**Comment by Cruix** [comment]
Oh my

**Comment by Cruix** [comment]
I was going to do a merge anyway so this is fine.

It's failing because there is golf stuff on the map but not in the code.

**Comment by utahclock** [comment]
Ah derp. Welp. Im off computer cant fix now. But i suppose you can just add
bowls from code to map.

**Comment by utahclock** [comment]
Reason why it merged like 50 commits. Is cause halloween branch is outdated
and behind current main branch that inpulled from

On Oct 30, 2016 12:02 PM, "Jen Slayton" utahclock@gmail.com wrote:

Ah derp. Welp. Im off computer cant fix now. But i suppose you can just add
bowls from code to map.

**Comment by Cruix** [comment]
Your golf PRs didn't update the DME

**Pull request merged**
