### PR TITLE
Makes Janitor fun again

### PR DESCRIPTION
**Pull request by Oakboscage**
Makes floors stay wet for a reasonable amount of time.

Refer to issue #2109 .

### Intent of your Pull Request

Fixes issue #2109 

#### Changelog

:cl:
rscadd: Buffed mop reagent amount.
/:cl:

### CODE REVIEW

**Comment by LarissaMayrink** [comment]
200 fucking ticks, whats your damm problem

**Comment by LarissaMayrink** [comment]
200, if we assume that it goes at 1u per tick thats 20s with 0% distortion, and, by being able to mop the floor multiple times thats enough to keep a tile wet for as long as it takes for nich to get woo wooed by void. Your janitor fantasies are worse than my fanfics

**Comment by Oakboscage** [comment]
Actually wet_time maxes out at 300 no matter how much you mop it. Also wet_time depends on how much water the mop contains when you mop it so assuming regular janitor work (you don't wet the mop for each tile) only one in 5 tiles would have the full 200, the rest having fractions of that as it degrades. So you would have single tile wetspots that stay for a bit longer. 

This is actually pretty close to how janitor used to be before they ruined it. Wet floor signs will actually have a purpose again and the crew will have a reason to walk.

**Comment by Jc1469** [comment]
balance police do not view this as a balance change, and instead view it as a "why the was it changed to begin with?" change

**Comment by LarissaMayrink** [comment]
>you don't wet the mop for each tile
Unless you want to fill a corridor with wet floors, which you are not able to right now but your change will make it possible again. Its nor like it is hard to click once on the cart after each tile, and its not like you can't do it even while you are already moping.

**Comment by Oakboscage** [comment]
Well if a janitor is just wetting floors for no reason and not putting up signs, security can scuttle over and arrest him for creating a workplace hazard, just like in the good old days.

I realize this is going to step on some toes due to getting in the way of some dank powergaming and validhunting.

**Comment by matskuman5** [comment]
:+1:

**Comment by LarissaMayrink** [comment]
How is giving the janitor back the possibility to wet entire hallways going to get in the way of validhunting?

**Comment by ShadowDeath6** [comment]
as long as this doesn't make water from spraybottles make the floor wet

**Comment by Oakboscage** [comment]
Unless I've really fucked something up this only affects mopping so liquids applied by any other methods are unchanged.

**Comment by Slinky5890** [comment]
You've been campaigning for this for so long. I'm glad you've become the change you wish to see in the world.

**Comment by Cruix** [comment]
This has horrendus implications for thermite, plasma, and every other reagent that reacts with turfs, and in return only improves the griefing ability of a legal grief tool for the janitor that also happens to be the worst tool he has for its actual intended purpose.

**Comment by Oakboscage** [comment]
Well this sure had some unintended consequences, back to the drawing board.

**Pull request closed without merging**
