### PR TITLE
maybe makes the map changes ross did work.  who knows

### PR DESCRIPTION
**Pull request by Jc1469**
@05rhardy 's mess

v94nz8mpqsc0sr2eebyjog 1

:cl:
rscadd: The detective now has more space.  The lawyers might too.
/:cl:

### CODE REVIEW

**Comment by Xantam-13** [comment]
I got bored and decided to re-vamp them. 

More shots;
https://image.prntscr.com/image/1lHrkJ04Q2i8YrNJ8bccKQ.png

https://image.prntscr.com/image/UrKWZIrKQkay0CmMHuFiaA.png

https://image.prntscr.com/image/IyocmTR1T0O4DmaAteGdRg.png

**Comment by Partheo** [comment]
Rip matsku

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Why not have the tables above the lawyers' chairs so they can have more than one client st once

**Comment by tsit9** [comment]
I personally like matsku's design for the law office more.

**Comment by matskuman5** [comment]
YOU COME TO MY HOUSE

**Comment by Jc1469** [comment]
YOU COME TO MY HOUSE AND MAKE DETECTIVE'S OFFICER BIGGER TOO.  WOW. YOU MUST BE better than me.

**Comment by Partheo** [comment]
Just waiting for Episode V from Matsku now. You need to one-up him!

**Comment by AsV9** [comment]
Closing this due to merge conflicts. If you want this to be merged, feel free to fix the conflicts and open a new pull.

**Pull request closed without merging**
