### PR TITLE
Unties the knot holding together the cable restraints

### PR DESCRIPTION
**Pull request by Super3222**

### CODE REVIEW

**Comment by Kmc2000** [comment]
And you told me off for vague PR and commit names...

**Comment by Super3222** [comment]
> And you told me off for vague PR and commit names...

whats vague about this

**Comment by ShadowDeath6** [comment]
fuck your commits super

**Comment by Super3222** [comment]
> fuck your commits super

It's relevant to the issue, and 10x better than the "fuck ass titty shit cunt" commits or the "updated [insert  file here]".

**Pull request merged**
