### PR TITLE
Adds new species options

### PR DESCRIPTION
**Pull request by Kmc2000**
Refer to issue #0.

### Intent of your Pull Request

Type here what the purpose of your PR is. Also set the issue number above, or delete the line if this PR is not related to an issue. You can type "Fixes issue #6" and issue 6 will be automatically closed as your pull request is merged. Much easier for everyone if you do that.

image
image
image
image
image
image
image
image
image
image

image

#### Changelog

:cl:
rscadd: FoxMcCloud, Adds in a new species check them out!!!
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Hail satan

**Comment by ShadowDeath6** [comment]
please god no this isn't even a meme at this point

**Comment by Kmc2000** [comment]
image

**Comment by Jc1469** [comment]
I see no, hear no evil, black writing's on the wall 
Unleashed a million faces, and one-by-one they fall 
Black-hearted evil, Brave-hearted hero 
I am all, I am all, I am 

I... I... I... I am
Here we go, buddy, here we go, buddy 
Here we go, here we go, buddy, here we go 

Go ahead and try to see through me, do it if you dare 
One step forward, two steps back, I'll be there
(One step forward, two steps back)

Do it! Do it! Do it! Do it! 

Can you see all of me?
Walk into my mystery
Step inside, and hold on for dear life

Do you remember me? 
Capture you or set you free
I am all, and I am all of me
(I am, I am all of me)

I am! I am, I'm all of me 
I am! I am, I'm all of me 
I am! I am, I'm all of me 
(Here we go)

I see and feel the evil, My hands will crush 'em all 
You think you have the answers, I'll laugh and watch you fall 
Black-hearted evil, Brave-hearted hero 
I am all, I am all, I am 

I... I... I... I am
Here we go, buddy, here we go, buddy 
Here we go, here we go, buddy, here we go 

Go ahead and try to see through me, do it if you dare 
One step forward, two steps back, I'm here 
(One step forward, two steps back)

Do it! Do it! Do it! Do it! 

Can you see all of me?
Walk into my mystery
Step inside, and hold on for dear life

Do you remember me? 
Capture you or set you free
I am all, and I am all of me
(I am, I am all of me)

I am! I am, I'm all of me 
I am! I am, I'm all of me 
I am! I am, I'm all of me 
(Here we go)

I am, I am everyone, everywhere 
Anyhow, anyway, anywhere, anyday 
I am, I am everyone, everywhere 
Anyhow, anyway, anywhere, anyday 

I am, I am, I am...
I am, I am, I am... I am!

Do it! Do it! Do it! Do it! 

Can you see all of me?
Walk into my mystery
Step inside, and hold on for dear life

Do you remember me? 
Capture you or set you free
I am all, and I am all of me
(I am, I am all of me)

I am! I am, I'm all of me 
I am! I am, I'm all of me 
I am! I am, I'm all of me 
(Here we go)
I am, I am, I'm all of me 
(Here we go...)

I am, I am all of me

**Comment by Super3222** [comment]
just because shadow doesn't like it

**Comment by AsV9** [comment]
no super

**Comment by Kmc2000** [comment]
I feel opressed.

**Comment by Wraithcraft** [comment]
This is truly the way to save Yog.

**Comment by Mrcreepssss** [comment]
yush

**Comment by Mrcreepssss** [comment]
the onlly way

**Pull request closed without merging**
