### PR TITLE
ore redemption memechine now only says its done shit to request consoles on the current zlevel. aka none if it's not on the station.

### LINKED ISSUE #1682: Ore redemption machine in golem base alerting scientists
When golems deposit ores into their machine, it alerts science on the requests consoles, making them go to cargo to find nothing there. This has severla times resulted in scientists shouting at cargo for stealing their ores when in all actuality there never were any ores.

### PR DESCRIPTION
**Pull request by Jc1469**
fixes #1682

### CODE REVIEW

**Comment by drderp3635** [comment]
How will we see all the scientists run back and forth, and start pointless fights with cargotechs now?

**Comment by Cruix** [comment]
QM needs a button that sends a fake message

**Comment by Super3222** [comment]
Next time, make a better commit message (to start off at least).

**Comment by YogsMcree** [comment]
Cruix it's called the one iron ore at the mining airlock

**Comment by Super3222** [comment]
> QM needs a button that sends a fake message

Maybe emagging the ore redemption machine should do something like this

**Comment by ShadowDeath6** [comment]
You do want your first commit to be understandable though, everything else can be "adjkdbfke", trust me I am code

**Pull request merged**
