### PR TITLE
sleeps "I live again" for 3 seconds on borgspawn

### PR DESCRIPTION
**Pull request by Amelia0010**

### CODE REVIEW

**Comment by matskuman5** [comment]
Why...?

**Comment by Amelia0010** [comment]
because it's either this, no roundstart animations, or everyone hearing "I live again" on roundstart

**Comment by AsV9** [comment]
Really smart questions that have been asked so far, right @nichlas0010?

**Comment by Notamaniac** [comment]
Something something branch name

**Comment by Amelia0010** [comment]
First you come for my commit names, and I abide.
Then you come for my PR names, and I abide once again.
But when you come for my branch names, I draw the line.

**Review by ThatLing — APPROVED** [review]

**Comment by Amelia0010** [comment]
I can make this less snowflakey, hang on

**Pull request closed without merging**
