### PR TITLE
Expands material stacking [Ready]

### PR DESCRIPTION
**Pull request by Partheo**
This PR adds a bit more to the material stacks I added earlier. All materials have now been moved from items.dmi to materials.dmi, a new file. All materials also now have 10 sprites, from a single sheet to a full 50-tall stack.

I did a bunch of merging stuff which still feels like code magic to me, so let me know if there's anything I did wrong. It's messy and I still don't understand it fully, but I think it's correct.
I also tested all this and it functions fine. The ORM also works.

This is branched off of #2395 so that's why there's some overlap.

materials

:cl: Partheo
imageadd: Added more stacking sprites to metal, plasteel, glass, and reinforced glass
imageadd: Wooden planks have a new sprite, and now stack as well
bugfix: Stacks dispensed from the Ore Redemption Machine now display the proper sprite
imageadd: The mining suit camera has a new sprite.
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
why does the new camera look so much like a handheld camera

**Comment by Partheo** [comment]
@jc1469 I was going for a retro look. At least it doesn't have buttons.

**Comment by Partheo** [comment]
Merge conflicts solved. Those damn pigeons blindsided me

**Comment by ghost** [comment]
merge this beauty

**Comment by Partheo** [comment]
Thank you

**Pull request merged**
