### PR TITLE
New Holy Weapon: Genesis

### PR DESCRIPTION
**Pull request by Super3222**
Alright, time for a holy weapon that's not a direct reference to a TV show.

This is a new null rod choice called Genesis.

It works somewhat like a godhand, where you can't take it off and it's extremely visible.
However, with this one allows you to input "messages" into it.

These messages can only be used by hitting someone with the weapon.
The message's font is rather font and varies between green or red depending on your intent.

On help intent, the message will be green, won't do any damage, and will play the holy soundtrack (what admins get from prayers / what players get from admins I believe).

On disarm or grab intent, the message will be red, and make the victim's speech jitter a little.

On harm intent, play the same sound which burn type weapons play, the weapon will actually HIT you, and the message is red.

Other Notes:
- Does not work when you hit yourself
- This'll run on a short CD

Example:

:cl: Super3222
rscadd: New Holy Weapon!
rscadd: Introducing Genesis (definitely not a reference to anything)! You input messages into it, and those messages can be transferred to people that you touch with them.
rscadd: When you receive a message from genesis it's in pretty BIG text.
rscadd: Genesis's color and effect relies on it's intent. Harm intent does ... actually nevermind. Have fun figuring it out yourselves!
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
no suicide message? lame, :-1:
the item is pretty cool though

**Comment by FluffySurvivor** [comment]
:+1:

**Comment by GrayRachnid** [comment]
The dizziness is OP. Remove that, seriously. :-1: 
Otherwise looks good :+1:

**Comment by ParagonPrime** [comment]
> traitor chaplain
> spawn minibomb
> run up to sec officer
> hit with null rod on blue
> "allahu akbar"

**Comment by ghost** [comment]
Adminlogging for choosing the message so we know if someone chooses NIGGERNIGGERNIGGERNIGGER ect

A character limit so nobody pastes the entire bee movie script

Some fucking delay between use so that you can't spam someone to death with it-perhaps a 10 second delay between transmitting messages?

**Comment by ShadowDeath6** [comment]
there is a delay

also suicide message WHEN

**Comment by ParagonPrime** [comment]
absolutely no text limit

i demand my constitutional right to run up to someone and display a glorious enormous ASCII image of the lenny face

**Comment by Super3222** [comment]
They already send logs into the game, I'll see if I can do a little more to make genesis monitoring easier for admins.

Also:

> A character limit so nobody pastes the entire bee movie script

Complimentary lmao.

I'll also work up a custom suicide message for genesis. A hint... it'll be another reference to the show

**Comment by FluffySurvivor** [comment]
The limit is too short

**Comment by Super3222** [comment]
After using an online character counter... yeah 35 is definitely short. Keep in mind that Genesis messages are intended to be single commands though. Nothing more than maybe a sentence and a single phrase.

**Comment by ShadowDeath6** [comment]
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

**Comment by FluffySurvivor** [comment]
> After using an online character counter... yeah 35 is definitely short. Keep in mind that Genesis messages are intended to be single commands though. Nothing more than maybe a sentence and a single phrase.

B-but muh memes?

**Comment by Stealthkibbler** [comment]
reminds me of the game God hand

**Comment by ghost** [comment]
How much damage does this do? 15?

**Comment by Cruix** [comment]
Looks like it does 18 damage.

**Comment by ghost** [comment]
Make it do 15-16.

**Comment by oisin100** [comment]
> Make it do 15-16.

It does the same amount of damage as a null rod, It needs no nerfing.

Screenshot please.

**Comment by Super3222** [comment]
It looks like the godhand sprite and/or the ei-nath hand.

**Pull request merged**
