### PR TITLE
Fixes a deep fryer bug

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
:cl: Fun Police
bugfix: Deep fryers no longer make items tiny.
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
Rip fun

**Comment by ToGWtF** [comment]
I am angry.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Hangry?

**Comment by Ratvar** [comment]
Hangery

**Pull request merged**
