### PR TITLE
Completely Meaningless Brig-Tweaks

### PR DESCRIPTION
**Pull request by ActualRory**
## Completely Meaningless Brig-Tweaks: Attempt Two Electric Boogaloo

Insignificantly small modifications made to brig.

Added Security Departmental Wrench, Medical gets one, why can't Security?

I submitted a PR for almost identical tweaks last night, but had overlooked the map-merge tools. Therefore I retracted said PR and put together this one. Should work just fine now. Definitely check over my code and changes, though.

_This is most definitely not a first foray into the wonderful world of SS13 Coding to get a handle on things. This is, in fact, a large-scale revolution that will change the way Brig is structured irreparably. /s_

SecWrench Sprite: https://i.imgur.com/xrc1CvN.png
MedWrench Sprite for comparison: https://i.imgur.com/ch1DWad.png

#### Changelog

:cl:  

**rscadd:** Added Security Wrench to brig in two locations.
**rscadd:** Added Security Toolbox. Functionally identical to mechanical toolbox.
**imageadd:** Added Security Wrench Icon.

**tweak:** Replaced default brig wrenches with Security Wrenches.

**tweak:** Replaced Mechanical Toolbox in brig with Security Toolbox.

**tweak:** Added 2x Pocket Fire Extinguisher to Security Vending Machine.

**tweak:** Added fire extinguisher cabinet to wall outside execution chamber. Area previously devoid of fire-fighting ability. Useful if electric chair goes haywire or in case of riot.

/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
so many changelog entries for such a small addition 🎉

**Comment by ActualRory** [comment]
[Too many changelog entries?](https://i.imgur.com/x7XERTd.jpg)

**Comment by Partheo** [comment]
Yeah, way too many entries. You could use a single entry to describe your changes.

But if the new meme is Rory = too many changelog entries then I'm fine with it.

**Comment by Partheo** [comment]
You can leave it as is for the jokes, but if you want to do it properly then "Security has been outfitted with extra fire extinguishers and new department wrenches." would do just fine.

**Comment by Alexandria404** [comment]
More importantly, did you add a custom suicide to the wrench?

**Comment by ActualRory** [comment]
Happy to leave change-log as-is for the comedic factor.
Will be done neatly and properly next time.

No custom suicide for wrench! Alas, this was as unambitious as possible to get a handle on things.
Perhaps in my next PR I'll sneak in a custom suicide for the wrench.
Next PR will nonetheless have more style, wit, and/or memes. Probably.

**Comment by ShadowDeath6** [comment]
needs images

**Comment by ActualRory** [comment]
Added sprites, nothing fantastic as it's nothing you see closely and I'm not an artsy type.
Basically a slightly changed med-wrench sprite.

**Comment by Partheo** [comment]
I'll going to resprite wrenches in general at some point, I'll do these as well.

**Comment by Cruix** [comment]
If you want the wrench to be unique there should be only one.

**Comment by ActualRory** [comment]
Got some conflicts now, changes too small to be worth rejigging.

**Pull request closed without merging**
