### PR TITLE
Fixes

### LINKED ISSUE #2590: if you are muted by a changeling you can still use *custom to talk things while normal ME/say is muted
image
Custom is really outdated, why is it still here?

### LINKED ISSUE #2595: nukeop shuttle got no toxin kit
Problems with dealing with radstorms, hits from rad crossbows, toxins, et etera

### PR DESCRIPTION
**Pull request by matskuman5**
closes #2595 

fixes #2590 

:cl:
tweak: The nukeop shuttle now has a toxins first aid kit.
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
I'd rather they just go to medbay.  Them shooting eachother shouldn't really be something they get supplies to deal with.

**Comment by matskuman5** [comment]
>Them shooting eachother

radstorms

**Comment by Jc1469** [comment]
:thinking: do radstorms affect their shuttle? if so, make it not.  
otherwise they should just not be standing in a radstorm

**Comment by Jc1469** [comment]
also I can't tell but does this replace a normal medkit or add a new one

**Comment by X-TheDark** [comment]
This replaces an existing brute kit (of which there were 4).

**Pull request merged**
