### PR TITLE
Fixes Fore Port Solar wires

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request
So basically, all of the solars look like this:
image

Except for the Fore Port Solars (above arrivals) which look like this:
image

I've edited it to not look as horrible and bad:
image

#### Changelog

:cl:
Fix: The Fore Port Solar wires now look like all the others
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
horrible and bad is intentional so people have to work to wire solars.

balance police do not support this catastrophic balance change


also nice first screenshot

**Comment by Amelia0010** [comment]
I already fixed it, god dammit john

**Comment by simonset55** [comment]
udklip
I would like to know what that means, because it looks like you're deleting the whole codebase

**Comment by Time-Green** [comment]
Nich, did you use mapmerge?

**Comment by Amelia0010** [comment]
No, I did not, but I will redo it using mapmerge

**Pull request closed without merging**
