### PR TITLE
<font size="18" color="yellow">SirCodey is dumb</font>

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
hue

### CODE REVIEW

**Comment by X-TheDark** [comment]
I suggest you stop this.

**Comment by Time-Green** [comment]
I suggest you give me a picture because I am curious how it looks now.
Also, bad mcdonald.

**Comment by Super3222** [comment]
Don't do this again.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
@Time-Green Imagine "NAR-SIE HAS RISEN" but bigger and eye-destroyingly yellow.
@Super3222 It's fixed anyway.

**Pull request closed without merging**
