### PR TITLE
Lobby Music: The Rejiggening

### PR DESCRIPTION
**Pull request by ActualRory**
Removes:
Getlucky 8-Bit: https://www.youtube.com/watch?v=CfMMlT8Lyns&ab_channel=FloatingPoint
Nuclear Mission Jam: https://www.youtube.com/watch?v=0iXfWWrwrlQ&ab_channel=xRussianYulia17x
Musique d'intro n°2: https://www.youtube.com/watch?v=pInBXkt3jvQ&ab_channel=Kavar222

Also disables title2.ogg from the lobby music circulation, as it is already heard often enough in-game.

Adds:
~~System Shock Theme: https://www.youtube.com/watch?v=6CalFsdE4tA&ab_channel=JaneDutohlav~~
XCom Enemy Unknown Theme: https://www.youtube.com/watch?v=zkWtthtbQQ8&ab_channel=AST

Cowboy Bepop OST 1 (Rush): https://www.youtube.com/watch?v=l8wWa3O9cUo&ab_channel=videmaxni5
Cowboy Bepop OST 1 (Tank): https://www.youtube.com/watch?v=n2rVnRwW0h8&ab_channel=videmaxni5

And by popular demand...
Don't Stop Me Now: https://www.youtube.com/watch?v=KKny_ia8Fvo&ab_channel=pongaplayandsing

:cl:  
sounddel: Removed three lobby songs.
soundadd: Added four new lobby songs.
/:cl:

### CODE REVIEW

**Comment by ActualRory** [comment]
Realised that System Shock suffers from the same problem as getlucky did.

They're both under three minutes, which means they end up just being silent.
Hunting a replacement.

**Comment by Partheo** [comment]
Both Bepop themes and Don't Stop Me Now are fantastic, worth the PR just to get them in.
Don't care too much for the system shock and XCom ones.
I'm fine with the removals, those themes weren't great.

Overall good PR!

**Comment by ghost** [comment]
someone send rory an mp3 of ape odyssey

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
How big are these oggs? Last time songs were changed there was a lot of complaining about size and how players would have to wait 3 more seconds while joining for the first time

**Comment by ActualRory** [comment]
In total this will increase things by ~2MB.

That's working off the top of my head, but it shouldn't be much more than that if it is at all.
It adds ~8MB and removes ~6MB.

If you believe the 2MB increase in size is an issue I can remove a song from the list, most likely systemshock.ogg, this will make the size negligibly close to the original size.

**Comment by ActualRory** [comment]
Removed 'systemshock.ogg'.
Size change is now negligibly small.

**Comment by simonset55** [comment]
Where's his coconut gun, that fires in spurts?

**Comment by ActualRory** [comment]
Going to make a new PR that only consists of the sound of a coconut gun repeatedly firing in spurts.

Forgive me for my gross negligence Simon.

**Comment by ActualRory** [comment]
Must go make these changes posthaste.

**Pull request closed without merging**
