### PR TITLE
Shuttle calls lengthened remake.

### PR DESCRIPTION
**Pull request by ghost**
The shuttle will take 20 minutes to arrive on blue, 30 on green, and 10 on red. 

Green shuttle calls are called 'crew transfer' shuttles.

Mostly to deal with 'theres an antag CALL IT' shuttles.
##### Changelog

:cl:
rscadd: Shuttle times have been lengthened.
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
20 green, 10 blue, 5 red.
20 green, 15 blue, 10 red.

change or riot.

**Comment by AndySok** [comment]
Yogstation becomes Tau Ceti confirmed

**Comment by Bittern12** [comment]
So we just have to sit through rounds where everything is broken and nothing is going on except avoiding being spaced or burning to death for 20 minutes? 
 No please.

**Comment by Jc1469** [comment]
still no.

Shuttle being called for dumb reason is an OOC issue. Admins should be dealing with it, not the salt fairy.

**Comment by ghost** [comment]
Admins can't deal with it.

@aphielanis You know that's not the case.

**Comment by matskuman5** [comment]
What in gods name

Red alert almost never gets activated due to heads being busy/incompetent/dead.

10 minutes is a good amount of time, 20 minutes is just silly

**Comment by ghost** [comment]
nope matsu, nope

it's because people call the shuttle for no reason all the time

**Comment by matskuman5** [comment]
Then we'll get people calling the shuttle for no reason, except it takes 10 minutes longer to arrive

**Comment by ghost** [comment]
good

**Comment by Notamaniac** [comment]
Really torn up on this PR, while there needs to be less incentive to immediately call the shuttle (which isn't adding more rules, adding more rules is bad and should be frowned upon), all this PR does is encourage you to call the shuttle sooner since you have to wait longer, and only really gives antags 10-5 extra minutes to complete their objecitves. And it makes recalls so much more painful to sit through.

**Comment by ghost** [comment]
On the contrary, people will be reluctant to earlycall the shuttle before the antags are dealt with due to the risk of a painful recall. Additionally, earlycalling to the extent of calling as soon as it's available because 'we might need it' is powergame, so.

**Pull request closed without merging**
