### PR TITLE
Fixes the KA from shaking with a wide guard

### PR DESCRIPTION
**Pull request by Time-Green**
This wasn't intentional and I thought it was the gun equivelant of w_class
:cl:
Fix: the wide grip doesnt make your screen shake anymore
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
About time.
Speedmerge

**Review by KrabSpider — COMMENTED** [review]
I believe the issue is you removed the weight variable, and just left it as is. I am not sure though.

**Comment by Amelia0010** [comment]
I believe the issue is that changelogs broke travis.

**Comment by Amelia0010** [comment]
If you merge master into this, travis shoooooouuuuld compile

**Comment by Time-Green** [comment]
I made this in the web application. I cant do that... 
*sigh*

**Comment by Time-Green** [comment]
Dont merge yet, I forgot to put it on the KA

**Comment by Zostroll** [comment]
This gonna get fixed soon?

**Comment by Time-Green** [comment]
PR can be merged just fine, ignore the conflict

**Comment by Zostroll** [comment]
@AsV9 you gonna merge this?

**Comment by AsV9** [comment]
image
nice meme

if you want to fix this commit history and these 147 included files, feel free to open a new pull request

**Pull request closed without merging**
