### PR TITLE
FUCK YOU

### PR DESCRIPTION
**Pull request by ghost**
Changelings have their removed stings back 
#### Changelog

:cl:
rscadd:  Changelings have some removed stings back.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
The stings were removed for a reason and I do not want them back in the game.

:-1:

**Comment by X-TheDark** [comment]
Welp, at least this is up for discussion, obviously.

Against.

**Comment by ghost** [comment]
literally a meme pr

**Comment by RoboticVodka** [comment]
wew

No.

**Pull request closed without merging**
