### PR TITLE
Adds Ultra preference for CMO

### LINKED ISSUE #2208: CMO cannot into ultra
The head-role _ultra preference_ whitelist... thing...

Anyway, it doesn't seem to apply to CMO. All other heads can still be set to Ultra.

### PR DESCRIPTION
**Pull request by X-TheDark**
fixes #2208

No idea how I missed this...

Also no idea if you should consider me Back or Missing In Action still.

#### Changelog

:cl:
bugfix: Chief Medical Officer can now be set to Ultra for people whitelisted for the feature.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
this is the part where jesus visits the disciples before actually being resurrected

**Comment by Iamgoofball** [comment]
what the fuck is this shit

**Comment by Alek2ander** [comment]
Corruption, favoritism, and pandering to cliques
:+1: :100: 
###### as long as I'm on the list

**Comment by Iamgoofball** [comment]
lame as fuck

**Pull request merged**
