### PR TITLE
wizard zambies

### PR DESCRIPTION
**Pull request by Amelia0010**
Summon magical events can now create zombies.
:cl:
rscadd: Summon Magical Events now has a chance to summon spooky zombies!
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I really want the zombies to be magical and have some sort of spell, but to be honest that’s a terrible idea

**Comment by Amelia0010** [comment]
i'd say that suddenly turning into a brain eating monster that can't die properly is magical

**Comment by drderp3635** [comment]
Give all the zombies one spell that all of them know

**Comment by Kmc2000** [comment]
literally wizards that are zombies, it's insane.

**Pull request closed without merging**
