### PR TITLE
what the fuck time

### PR DESCRIPTION
**Pull request by Amelia0010**
what the fuck time

@Time-Green explain yourself

### CODE REVIEW

**Comment by Amelia0010** [comment]
okay thanks Travis

**Comment by ShadowDeath6** [comment]
can you explain what this pr is

**Comment by Time-Green** [comment]
Wait what is this. Is this the one where I drew dicks as broken icons?

**Comment by Time-Green** [comment]
Oh, apparently I forgot to remove some dmi's when I was exporting them. soz

**Comment by Amelia0010** [comment]
>can you explain what this pr is

Time left DMI files in the main folder.

**Pull request merged**
