### PR TITLE
borgs can't be flashed while stunned

### PR DESCRIPTION
**Pull request by ShadowDeath6**
death to autismo chainstunning

:cl: ShadowDeath6
tweak: Borgs can no longer be flashed while stunned.
tweak: To compensate for this, flashes now stun for ~10 seconds every time rather than a random amount between 5 and 10.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
Make it so humans cannot be chain stunned either

**Comment by ShadowDeath6** [comment]
if stunbatons stunned for upwards of 10 seconds and blinded and muted I would do so

**Comment by Cruix** [comment]
How is that any different?

**Comment by Jc1469** [comment]
I agree with this entirely. Whenever borg stuns got buffed, borg became a dead borg. Ling emp scream? ded. can't move can't see can't do shit.

Being stunned as a borg is bullshit, being chainstunned.  thats some thrilling gameplay. can't even :b help this dick is stunning me. 

Fuck the humans.  Rogue borg gets called out; rogue borg either gets locked and ignored, stuck in lock purgatory for all eternity, locked and beaten the shit out of because IS ROGUE AAGH even though it can't do shit, or blown up.  Or stunned and beaten the shit out of because IS ROUGE AAGH while being blind, deaf, unable to move, unable to do anything but boot up minesweeper.

**Comment by ShadowDeath6** [comment]
if you want me to compare it to an item for humans, imagine if there was an item that had an 100% chance to KO you for 10 seconds immediately and could be spammed around 7 times in a row on said victim while they were KOed. This PR makes it so you can't stun them again while they're KOed.

**Comment by Cruix** [comment]
Stunbaton
Taser
Flashbang
ClownPDA
Bananapeel
Beepsky
All of the above +cable cuffs

**Comment by ShadowDeath6** [comment]
I said KO, meaning you can't hear anything or talk at all, essentially being morphined / bullshit RNGed by a dual esword to the head, not knocked to the ground.

**Comment by Cruix** [comment]
Why does being deaf and mute even matter? If someone wants to kill you and stuns you, the best you'll get is one frantic cry over the radio before you have your headset taken off or you are dead.

Even without this buff, cyborgs have numerous huge advantages over humans - there are far fewer things that can stun them, they cannot be restrained, they effectively have twice as much health since they don't go into crit, and their AI gets a real-time feed on their health and location, even when they are dead. Flashes, the most common method of stunning them, require you to be in melee range and click on them, and each time you stun them the flash has a higher chance of burning out forever.

This just means that anyone without the ion rifle or an emp kit has basically no chance of killing a borg before it gets unstunned and either arrests you on the spot or zips away and locks you in wherever you are.

**Comment by ShadowDeath6** [comment]
Why do we even have a salty label? i ded accomplishes so much more
 

Would you rather me just decrease the stun time on the flash? It's brainlessly easy to kill a borg when you hit them with a flash while they're literally unable to dodge, and it's either the stun time of a taser or twice that long. All antags have their own methods of killinf borgs outside of gang and rev and you're going to get quintuple teamed by them anyway during both those modes so it really doesn't matter, and rogue borgs have a button that either renders them invalid until the AI notices (but sometimes can't do anything because they just cut the robotics console) or a button that completely removes them from the round by blowing them up.

**Comment by Time-Green** [comment]
I added the tag because your branch is literally called:  this_is_a_salt_pr_but_also_personally_I_think_it's_a_valid_one

**Comment by ghost** [comment]
This is a fine PR, honestly. 

But I should get around to removing chainstuns for most things.

Alternatively, you could make flashes be weaker on successive hits from borgs, with the reasoning that their optical sensors are adjusting to the flash, so that the same flash within say, 30 seconds, stuns for half the time, and then half that again

**Comment by ShadowDeath6** [comment]
can we get a testmerge of this in its current state to see how it affects gameplay? It's hard talking in hypotheticals.

**Comment by Jc1469** [comment]
Thing is, in the time you flash a borg, say you flash it at medbay. You can then outrun that borg, and lock it down.  Humans don't have permanent lockdown buttons.  They also don't have a remote detonate button.

All this talk about balancing it to affect both.. no?   
Borgs are immune to most forms of stuns, yes.  They're not immune to a permanent lockdown and remote detonation; and have no way TO BE immune to it.  No hulk, no borg bomb suit but we should totally add that as an illegal module.

TG even ditched the sec borg, unless they went back on that at some point.  Sure, our borgs are pretty op.  But a shit borg is a shit borg.  If the player is bad, the player fails.  

Blob ended up getting re-buffed because unless THE CREW was shit, the blob was more or less guaranteed to lose.  The blob's ability to play didn't matter because of all of the nerfs.

Right now, a borg is only as good as the person playing it.  And flashes are fucking broken as fuck against them. "Don't let the humans near you then xd." We only have one borg with ranged capabilities of defending itself. And surprise surprise, it's the type that gets DETONATED if someone calls it rogue for trying to disable them, because nobody wants to fucking deal with a real rogue sec borg, so better safe than sorry.

**Comment by ShadowDeath6** [comment]
@Cruix is a test merge in the forseeable future or should I just give up now

**Comment by Cruix** [comment]
I'm doing a big testmerge soon and I will add this in.

**Comment by Super3222** [comment]
Did anyone get any feedback whatsoever?

**Comment by ShadowDeath6** [comment]
I have no idea how long this was testmerged for.

**Comment by ShadowDeath6** [comment]
zzzz...

**Comment by Super3222** [comment]
we either need a system where players can drop feedback or we need people paying attention to the server.
testmerges with no feedback are useless.

**Comment by BOBsHERE** [comment]
I flashed a few borgs during the test merge. It was pretty difficult to deal with. The borgs would just run away the moment they could, then come back and chain stun you. Borgs are already difficult to deal with. That said, it wasnt the end of the world.

**Comment by ShadowDeath6** [comment]
The problem is that it's going to get shit on because secborgs are an anomaly that can ruin your round with stuns that their laws don't shit on and the range that other borgs lack (obviously not minerborg but that does damage so they can't do it anyway) so it's the only borg that makes this pr unbalanced in the borg favor rather than being a nice change so borgs aren't permafucked

**Comment by Cruix** [comment]
Maybe someday when secborgs don't exist

**Pull request closed without merging**
