### PR TITLE
Drones can not use guns or click on living things

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
tweak: Default drones can no longer attack or drag living things or use guns.
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
SYNDI DRONES HELLO?

**Comment by Kmc2000** [comment]
Removes fun

**Comment by Cruix** [comment]
This only affects default drones, not syndrones or cogscrabs.

**Comment by ghost** [comment]
w/b F R E E D R O N E

**Comment by Cruix** [comment]
Fixed freedrones

**Comment by Dagdammit** [comment]
Sounds good. Will this include blob?

**Pull request merged**
