### PR TITLE
Adds rubber pigeons

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd (sprites by kmc)
rscadd: adds rubber pigeons
/:cl:

they're cooler than rubber chickens

https://streamable.com/lwuso

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
No pix no clix

**Comment by ghost** [comment]
i'm making a video rn

**Comment by Jc1469** [comment]
emag to make rubber turn into flesh and become real pidgeon that flies around and generally annoys everyone?  that's how emags work right?

**Comment by ghost** [comment]
yes

**Comment by Partheo** [comment]
No video no likeo

**Comment by ghost** [comment]
there's a video right there

**Comment by Partheo** [comment]
no

**Comment by matskuman5** [comment]
no

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Do you accept constructive criticism

**Comment by Iamgoofball** [comment]
Nice username

**Comment by ghost** [comment]
yes i feed on this so called constructive criticism

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
They fucking suck

**Comment by ghost** [comment]
and youre autistic. congrats I made them for you.

**Comment by Kmc2000** [comment]
I see no reason why you shouldn't add them

Speedmerge

**Comment by drderp3635** [comment]
But like

Y tho

**Comment by Notamaniac** [comment]
They sound like hellspawn

**Pull request merged**
