### PR TITLE
Porting over Ephemeralis's medical rework from Yogstation.

### PR DESCRIPTION
**Pull request by Super3222**

### CODE REVIEW

**Comment by X-TheDark** [comment]
Do we also spruce up the code as we port it? For example, this PR could use alot of `src.var -> var` type of sprucing.

**Comment by oisin100** [comment]
Ach, Ill get travis working.

**Comment by Bawhoppen** [comment]
Before you do anything I still say you guys should just run pure tg code for a little bit, to get the full experience

**Comment by Super3222** [comment]
that was a bad commit message. what I meant was src.var -> var

**Comment by X-TheDark** [comment]
@Bawhoppen Regardless of whether or not we keep certain /tg/ features, we still need to port our own into the new code.

Also, relevant (basically says that we are actually rebasing, no-joke/serious mode) : https://forums.yogstation.net/index.php?threads/yogstation-split-2016.10630/

**Comment by Bawhoppen** [comment]
yes I know, but you should run pure code for a little bit to try the full experience is what I'm saying

**Pull request merged**
