### PR TITLE
Removes clothing from absorbs/DNA-sting

### PR DESCRIPTION
**Pull request by Amelia0010**
Requested by @alexandria404

Clothing is no longer saved by absorbs/DNA-stings

:cl:  
tweak: DNA-sting/absorbing as a ling no longer brings over their clothing
/:cl:

### CODE REVIEW

**Comment by Alexandria404** [comment]
Nice, like it a lot. Thanks a lot.

**Comment by matskuman5** [comment]
Make an evolution ability that gives it

**Comment by Amelia0010** [comment]
that's work thouuuuugh

**Comment by ShadowDeath6** [comment]
why is this needed

**Comment by Time-Green** [comment]
Eh, I don’t like it. Removes another way of finding lings

**Comment by Alexandria404** [comment]
Makes spotting them a lot easier however, since they now need the full gear of their disguise, non bloody, and they cant change disguise in a heartbeat, since they´d need to change clothes.
Also ups the paranoia and removes an in my opinion cheesy lingcheck.

**Comment by ShadowDeath6** [comment]
it's literally just quality of life, lings get none of the benefits from the flesh disguise and the drawback is that  you can check them if they're a ling. All it does is make it less annoying to transform into someone else, and removing it doesn't change anything aside from encouraging lings to absorb one person and then never changing disguise ever.

**Comment by grubstank** [comment]
The whole point of lings is that they can rapidly shift disguises. There's hardly any paranoia in ling rounds as it is - nerfing them like this is really going to suck away the little paranoia that's left. Big -support from me, unless clothes absorption is added as a dirt cheap adaptation/evolution

**Pull request closed without merging**
