### PR TITLE
[Critical][Speedmerge][PRIORITY:EXTREME] MASSIVE BUGFIX, LAG FIX, PERFORMANCE INCREASE

### PR DESCRIPTION
**Pull request by Kmc2000**
Refer to issue #0.

Fixes a type error which caused the honkbot to randomly, and without reason, be removed from the theatre. THIS IS A CRITICAL ISSUE

Cruix merge my goddamn PR (tm)

#### Changelog

:cl:
rscadd: Re-adds honkbots
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
:+1: approved

**Comment by Kmc2000** [comment]
:+1: Thank you CRUIX, please merge

**Comment by Kmc2000** [comment]
Yeah these are good changes :+1:

**Comment by Kmc2000** [comment]
^Proof that cruix actually said this...


Idk he must have deleted his comment or something smh

**Comment by ShadowDeath6** [comment]
:weary:

**Comment by Super3222** [comment]
LMAO KID :joy::joy::joy: I'M LITERALLY DYING

**Comment by Super3222** [comment]
AHAHAHA MASTER BRANCH SACRIFICE

**Pull request merged**
