### PR TITLE
Adds cargo shutters

### PR DESCRIPTION
**Pull request by Partheo**
image
image

Now you can stop fucks from climbing onto the table. Not access-restricted so people that flush themselves down disposals can still get out.

:cl: Partheo
rscadd: The Cargo Mail office now has privacy shutters.
/:cl:

### CODE REVIEW

**Comment by Alek2ander** [comment]
:-1: Why would you want to stop assistants digging through the trash? Not a high sec area

**Comment by Partheo** [comment]
Neither is the chef's kitchen.

It's an area they don't have access to. Plain and simple. If they really want to get in they can go flush themselves down disposals.

**Comment by ghost** [comment]
cargo powercreep

**Comment by ToGWtF** [comment]
-1 

now AI can stop EVERYONE who tries to disposal themselves to escape.

**Comment by Partheo** [comment]
@ToGWtF You realize they can just press the button and leave, right?

**Pull request merged**
