### PR TITLE
Improves toilets [FIXED]

### PR DESCRIPTION
**Pull request by matskuman5**
Refer to #2235 

This just fixes the merge conflicts

:cl:
rscadd: NanoTrasen engineers have replaced the old toilets with the new HT-452 models! These ones can actually flush!
rscadd: Locks have been added to the bathroom stalls.
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
Do I need to fix those errors halp

**Comment by Frostben** [comment]
Ooh! These can flush? Does that mean we can put small and tiny items in toilets and flush them through disposals instead of using a disposal unit?

**Comment by matskuman5** [comment]
Yes.

And uh, you can flush people down it as well

**Comment by Frostben** [comment]
Yessssss!!!! Best pr to date

**Comment by matskuman5** [comment]
Goddammit I was worrying why the fix wasn't working

Then I realized I forgot to push the commit...

**Comment by Super3222** [comment]
I'm going to test this.

**Comment by Super3222** [comment]
I tested this. 

Locker room:
It seems like objects that you flush down the toilet come back up the last one. I went down the toilet myself, and it threw me back out the last one too.

Dormitories:
It seems like both toilets are fully functional.

**Comment by matskuman5** [comment]
AAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

WHYYYYYYYYY

I'll make a new PR in a bit

**Pull request closed without merging**
