### PR TITLE
Atmospheric Technician Tweaks

### PR DESCRIPTION
**Pull request by Super3222**
Fixes https://github.com/yogstation13/yogstation/issues/516
Fixes https://github.com/yogstation13/yogstation/issues/521

:cl: Super3222
rscadd: Added one pair of magboots to atmospherics. It's over a pile of gasmasks and hazard vests. It was never clear on why NT decided to put it there.
tweak: Buffed atmospheric's water tank a little: Volume has been increased from 200 to 250
rscadd; Adds another atmospheric locker to atmospherics. We have 3 not 2
/:cl:

Where to find it:

### CODE REVIEW

**Comment by Cruix** [comment]
Where is the SSU now?

**Comment by Super3222** [comment]
Screenshot wasn't suppose to be cut short... but it's right past the middle wall at the bottom of the picture. Inbetween an atmospheric technician wardrobe & a spaceheater.

**Comment by FluffySurvivor** [comment]
> It was never clear on why super decided to put it there.

fixed it for you

**Comment by Super3222** [comment]
Too bad. It follows the canon. I'll switch it around in a sec.

**Pull request merged**
