### PR TITLE
Blob tweak

### PR DESCRIPTION
**Pull request by Time-Green**
In my previous PR, I forgot lasers.
Now lasers instadestroy blob tiles and welding tools 2 hit them.
:cl:
tweak: Normal blob tiles can be instashot with lasers again
/:cl:

### CODE REVIEW

**Comment by Slinky5890** [comment]
Damn, I was liking the superbuffed blob

**Comment by ShadowDeath6** [comment]
bad pr this makes xray lasers even more op against them grr

**Comment by Jc1469** [comment]
I don't think you're going to find a place to _balance_ the blob.  Blob tiles dying in 1 laser is pathetically weak.  Blob tiles dying in 2 lasers means you can only kill 5 blob tiles per gun.  Imo all nerfing should be done to the reagents and maybe spore/naut damage.  That said, the naut is only as strong as the reagent.

**Comment by Time-Green** [comment]
This is what ot originally was anyway

**Comment by ghost** [comment]
no it wasn't @Time-Green 

originally it was 2 lasers to kill 1 tile

**Pull request merged**
