### PR TITLE
Fixed borer event

### LINKED ISSUE #2582: Borers are broken
Mins were talking about it on discord, apparently it never triggers and when spawned by admins nothing happens

### PR DESCRIPTION
**Pull request by MacHac**
Fixes #2582.

The event that spawns borers was failing silently; I fixed two issues that were preventing it from functioning normally.

- pollCandidates() sleeps for 30 seconds, so the event would try to start 15 extra times on separate threads (one for each tick of sleep.)  I moved the actual borer selection out of the start function to the less-picky tick() (and added a check to make sure that block of code is only executed once.)
- The arguments given to pollCandidates() were wrong, so the returned list would always be empty.

#### Changelog

:cl:   
bugfix: Cortical Borers, once thought extinct, have begun reappearing on space stations throughout Nanotrasen territory.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
closes https://github.com/yogstation13/yogstation/pull/2990 I assume

**Comment by MacHac** [comment]
Oops.

**Comment by ThatLing** [comment]
I liked your fix more though.

**Comment by MacHac** [comment]
@ThatLing 
Then you should take my fix, but your PR already has an established balance discussion in progress.  Not much point in migrating to a second PR over 7-8 changed lines of code.

Plus, I don't really feel like spending two weeks arguing for/about this. :) I thought this would be a quick and uncontroversial fix, which is part of why I started working on it in the first place.

**Pull request closed without merging**
