### PR TITLE
Re-adds Roxie

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

For all the newbies who weren't around when Roxie was in the code:

#### Changelog

:cl:
rscadd: Adds Security's one-and-only Roxie!
/:cl:

The Roxie I put down on the map was pathed after the tactical corgi, so there's a bonus towards making her sentient.

### CODE REVIEW

**Comment by Jc1469** [comment]
no :latin_cross: you have no power here satan

**Comment by ShadowDeath6** [comment]
Cool
While you're at it can you fix https://github.com/yogstation13/yogstation/issues/2009

**Comment by Jc1469** [comment]
not sure why removing memekitty is relevant to adding plastic dog

**Comment by Chuggachar** [comment]
Get a new sprite already I made that one ages ago and it is pretty bad.

**Comment by Frostben** [comment]
lol are those teats at the stomach area?

**Comment by Super3222** [comment]
> Get a new sprite already I made that one ages ago and it is pretty bad.

And here I was, beginning to think that the OG spriter left yogs completely!

**Comment by Cruix** [comment]
The harness changes the sprite of the corgi when you put it on, and it gets put on in New(), so overriding the icon in the type definition won't work.

**Comment by Notamaniac** [comment]
RECTANGLE LEGS

**Comment by Kmc2000** [comment]
Keep.

Roxie


as

she

was

created.

.


.

**Comment by ghost** [comment]
add sergeant araneus the spider

**Comment by Cruix** [comment]
Just add normal Roxie, not a tactical corgi.

**Pull request closed without merging**
