### PR TITLE
Revert "OOC tags"

### PR DESCRIPTION
**Pull request by oisin100**
Reverts yogstation13/-tg-station-yog-rebase#58

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
you know your headcoder is a gangsta when he merges with failed travis 1 second after opening

**Comment by Super3222** [comment]
The DB failed to operate with the code.

**Comment by FluffySurvivor** [comment]
I know, it's just funny.

**Comment by Super3222** [comment]
What I mean is the database in the game failed to operate with the code.
Which is why it's being reverted, because the database went wonky.
So it was wrongfully reverted.

**Pull request merged**
