### PR TITLE
Fixes NTSL, but, like, more so.

### PR DESCRIPTION
**Pull request by Altoids1**
### There were more bugs and I fixed them

So the new comment hotfix doesn't completely work, since it actually overskips the comment syntax by 1 place, meaning long-comments that are inlined into code weren't working, so I fixed that.

I have additionally fixed the Type Mismatch bug, as well as improved some of the error messaging around that error while I was there.

It's fixed, for sure this time. I promise. Really.

#### Changelog

:cl:  

bugfix: Nanotransen will now, for sure this time, stop distributing faulty telecomms equipment.

/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Make your changelogs make sense and describe what they actually do instead of in-jokes newer players won't understand.

**Comment by Amelia0010** [comment]
TCOMMS STOP NO WORK, K?

**Comment by Altoids1** [comment]
Nich gets it

**Comment by AsV9** [comment]
image
pls work off branches

**Comment by Altoids1** [comment]
But it has master in the name. That makes it the better branch, clearly.

**Pull request merged**
