### PR TITLE
Gives RPD an in hand sprite, and fixes ooc being logged thrice

### LINKED ISSUE #2468: OOC is logged 3 times.
msg = pretty_filter(msg)

    log_ooc("[mob.name]/[key] : [msg]")

    var/raw_msg = msg

    msg = pretty_filter(msg)

    log_ooc("[mob.name]/[key] : [msg]")

    if((copytext(msg, 1, 2) in list(".",";",":","#")) || (findtext(lowertext(copytext(msg, 1, 5)), "say")))
        if(alert("Your message \"[raw_msg]\" looks like it was meant for in game communication, say it in OOC?", "Meant for OOC?", "No", "Yes") != "Yes")
            return

    log_ooc("[mob.name]/[key] : [raw_msg]")

`

### PR DESCRIPTION
**Pull request by Amelia0010**
fixes #2468 
Makes the RPD use the in hand sprite of the RCD, instead of having none, since they do look similar

image

and finally, fixes OOC being logged thrice in the admin logs, now it gets logged if the user actually sends it

### CODE REVIEW

**Review by X-TheDark — APPROVED** [review]
No issues in the code.

**Comment by matskuman5** [comment]
what is changelog

what is atomize

**Comment by Cruix** [comment]
Ooc is logged multiple times so that admins can see what the message looks like before and after it is filtered

**Comment by Amelia0010** [comment]
I can readd that then? if you want?

**Comment by X-TheDark** [comment]
I think it should be logged before pretty filters and whatnot. Just the original message.

**Comment by ShadowDeath6** [comment]
atomize your prs, the tcomms sprites are bad and I don't like them mixed with fixes

**Comment by Amelia0010** [comment]
I just didn't want to make 7000 prs for something small

**Comment by ShadowDeath6** [comment]
makes 1 pr for fixes
makes 1 pr for sprites

that way I can downvote the pr without downvoting fixes

**Comment by ShadowDeath6** [comment]
:+1:

**Comment by Amelia0010** [comment]
Sorry, I'm still shit at this

**Comment by Cruix** [comment]
These should still really be split up

**Pull request merged**
