### PR TITLE
Minor botany additions.

### LINKED ISSUE #400: Unstable Mutagen in biogenerator
[Note]: # as a botanist unstable mutagen is almost a necessity to have a good shift, and if you frequently play botanist dealing with the chemists can often times be one of the most frustrating ordeals. 

Examples: 
You walk up to the chemist and ask for mutagen but they are afk.

You ask for mutagen and the sorry waste of a human life hands you A SINGLE GOD DAMNED BOTTLE. you look back at him and contemplate if its worth more to embed your hatchet in his chest, stab out his eyes and make the mutagen yourself, then it is to ask the disgrace a second time.

You the botonist ask the chemist to make you mutagen, and the chemist asks you why you need mutagen, (insert most of the last paragraph)

Recommendation:
Add bottled mutagen to the biogenerator for 100-200 biomass or liqiud that goes into the container

Alternate solution: make absolutely terrible chemists valid

### PR DESCRIPTION
**Pull request by TheSadFox**
Adds 5 droppers to Nutrivend. It was a thing back before rebase.
Adds 30u mutagen bottles to biogenerator, 600 points per bottle.

Fixes #400

:cl: Foxy
rcsadd: Re-added droppers to botany Nutrivend.
rscadd: Botany can now create mutagen using biogenerator.
/:cl:

Babbies first PR.

### CODE REVIEW

**Comment by Super3222** [comment]
A part of this PR removes inter-dependence among departments. :-1: Boo
Which is one reason why the grinder was "broken" long ago (no use for miners anymore, right?) & why we never merged rezadonuts (which was for xenobiology, no use for cyro anymore, right?).

**Comment by TheSadFox** [comment]
Have you played botanist lately and tried to get mutagen from chemistry?

If the quality and competence of chemistry improves one day i'd be happy with removal of this. But as it is now, you either get nothing becouse the motherfucker behind the window is mute, autistic and completely ignores you, or takes 30 minutes to make you one 30u bottle and then refuses to make any more.

**Comment by B1gb3ast** [comment]
but I as chemist whip this up before you get there.
Hell when I'm bored I bring it to you.
Hell a chemist usually Always gives it to you.
NO SUPPORT NO FUN THINGS NO REZADONUTS NONE OF DIS

**Comment by TheSadFox** [comment]
Being forced to pray to god for a competent chemist to pick the job to actually be able to play your own is not something i consider to be fun. B1g, i dare you, play a botanist for a few rounds and tell me how did it go.

Optionally, if many people will be opposed to biogenerator thingy, i'll put a few bottles in the vending machine. This would allow them to do some mutating even if chemistry has downs, and they might start their own mutagen farm if cargo orders them bees, which is far more likely to happen than competent chemistry.

**Comment by Super3222** [comment]
Still bad in the sense that you'll be adding in an item that's only positioned for one use.

And instead of minimizing cooperation between departments, try expanding it. Via, adding 1-2 bottles of mutagen to a botany crate at cargo.

**Comment by FluffySurvivor** [comment]
:+1:
relying on shit chemists is bad

**Comment by TheSadFox** [comment]
C'mon guys give more opinions on the mutagen thingy and how would you prefer it to be done.

**Comment by drderp3635** [comment]
Well being the one who asked for it I can say that if everyone knows how to play and is present it really isn't necessary, but nowadays that rarely happens to be the case. Also at a cost of 600 biomass it would still be usefull for chemist to make some bottles at the round start to get a botanist on thier feet

**Comment by ShadowDeath6** [comment]
floral somataries for botany when

**Comment by TheSadFox** [comment]
More opinions ples.

**Comment by FluffySurvivor** [comment]
pulse rifles for botanists when

**Comment by TheSadFox** [comment]
> pulse rifles for botanists when

`/obj/machinery/computer/arcade/proc/prizevend()
    if(prob(0.0001)) //1 in a million
new /obj/item/weapon/gun/energy/pulse/prize(src)`

Just play arcade for those.

**Comment by Zostroll** [comment]
Doesn't 100% potent gat fruit drop pulse rifles?

**Comment by Stealthkibbler** [comment]
I think people dont understand, this doesnt remove the chemist option it just adds an alternative so you dont get fucked by no/bad chemists. People can still easily cheat it and go to chemistry and ask for an early bottle, but if chemistry is shit then that makes botanys job lackluster since they probably have to break into chemistry and most of the time medbay is defended by a rapid response autismo of a CMO that runs under the agenda of "If you break in you get nothing".

Infact I dont think I've seen a chemist who even bothers to make mannitol at roundstart, most of them just make death fuck chemical concoctions which eventually melt their entire work station down and kill themselves.

**Comment by Time-Green** [comment]
I get high on lsd and kill myself.

**Comment by GrayRachnid** [comment]
:+1:

**Comment by TheSadFox** [comment]
> GrayRachnid commented 41 minutes ago 
> :+1:

Glad you admit that removal of the mutagen in first place was a horrible idea.

**Comment by GrayRachnid** [comment]
> Glad you admit that removal of the mutagen in first place was a horrible idea.

Free shit is bad shit

**Comment by TheSadFox** [comment]
Feedback is ded. Either merge or close this.

**Pull request merged**
