### PR TITLE
No more c4 insta-dead bullshit

### PR DESCRIPTION
**Pull request by Jc1469**
still Fixes #bullshit
also when someone copypasted the plastic file for c4 they left out a few things like c4 being put on a locker instead of in it. but thats not what this pr is for
:cl:
tweak: C4 and X4 are heavy as fuck and weigh down things they are placed on, making them unable to effectively embed inside of a person. They also don't go on bolas because fuck that.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
You should check for 'embed_chance' in conjunction with sharp.

**Comment by Jc1469** [comment]
From the testing I was doing, every object has an embed_chance. 45, I believe.  Sharpness is what determines if it can actually embed or not.

**Comment by Super3222** [comment]
Alright, I checked and yeah everything has a 45% chance to embed. IS_SHARP doesn't have to do with it though. Anywho, can you implement a similar change for bolas.

**Comment by Jc1469** [comment]
I know of a few ways around this, but if it gets to the point where people figure out ways to still do it, more power to them I guess.

**Comment by Ratvar** [comment]
smthngsmthngspeargrenadesblackpowderchl3mines,chemist can freely make something 1000% better then C4 bolas in half a minute.No C4 sharpitems means you cannot C4 captain rapier?No C4 for some summonitem miner weapons,nu,nu,bad. Nerf C4 bombing people into gibs with ease,maybe?

**Comment by enailz** [comment]
Removes fun

**Comment by ghost** [comment]
@Ratvar what did you even such say

also 'this is op so this other op thing should stay' isn't an argument

**Comment by enailz** [comment]
Nerf the c4 throwing star throw distance and we good.

**Comment by Jc1469** [comment]
Melee range unsurvivable death? No.

**Comment by ShadowDeath6** [comment]
Bombs are bad good pr

**Comment by Cruix** [comment]
For an object to imbed on throw the throw_speed has to be at least 4.

**Comment by drderp3635** [comment]
C4 throwing star is a meme that rarely even works, because c4 takes ages to plat and if you miss you are royally fucked. Bad PR.

**Comment by Ephemeralis** [comment]
Just make C4 TD -1 while attached to an embedded object. Trivial fix, keeps fun, nerfs unfun.

As in, actually -1, not 0 or whatever.

**Comment by Alek2ander** [comment]
This is literal snowflakery.
Make c4-ed items lose their embed chance instead, or forbid attaching c4 to items of weight class 3 or lower or something like that.

**Comment by Cruix** [comment]
It is snowflaky but so are legcuffs in general.

**Pull request merged**
