### PR TITLE
Language Update

### PR DESCRIPTION
**Pull request by Super3222**
Revisions:
- Seperated bitflags that were associated with hear() and say() for language amoung species to a new file called languages.dm
-  Phytosians now have their own special language which they can use (:P Hello fellow phytosian!).
- Borgs will no longer be able to speak "human", however they are still able to understand human. They will speak borg instead.
- Language is now accessible in your character set up.
  There will be a primary language option that is unchangeable, being english.
  Humans start out speaking english and understanding english only.

However to some races there is an option for a secondary language. When you choose a secondary language, you can only UNDERSTAND it not SPEAK it.
Cyborg is the default secondary language for all humans.

So you're probably wondering 'what are all of my options for a secondary language?'

Well currently everyone's options are quite thin. But don't worry, maybe in the future we'll expand on our language inventory.

Like I said earlier, only some races will be getting a secondary language. It will be every roundstart race but, Phytosians.

On the other side, Phytosians will have two primary languages that they can speak and understand. English and Phytosian.

As you can see, language is unchangeable for Phytosians. This means they will never be able to speak with borgs right? Yes?

Well you're almost correct.

Service borgs will be able to play the "translator" part. Being a service borg allows you to speak and understand borg, human, and phytosian.

So what does this mean of the future? Well, I have no idea. You guys paint your own history in game.

Currently the code for how languages are assigned is pretty hardcoded, but I left a quick comment on how to get around that. So if anyone else makes a language in the future they won't be entirely confused.

If this feature gets frozen I'll be okay with that with the rebase and all.
#### Super3222

:cl:
experiment: The Language system has been implemented to affect gameplay. 
tweak: Your round-start character will have a "primary language" which they can speak and understand, and a "secondary langauge" which they can only understand.
tweak: Humans will be unable to understand borg speech unless they have chosen "cyborg".
experiment; Phytosians will have two forced primary languages. English and Phytosian. Phytosian is spoken with .P at a short range to communicate with other people that may understand phytosian.
experiment: Phytosians cannot choose a secondary language.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
Also what's the russian letter for P?

**Comment by Super3222** [comment]
Also, I need the russian letter for P.

**Comment by oisin100** [comment]
Interesting, Ill review this a bit more later.

**Comment by ghost** [comment]
Infinite thumbs down to making borgs not speak human, that's fucking retarded. 

No.

Read my initial suggestion, not...this ew.

**Comment by Super3222** [comment]
@AdamElTablawy 

You don't understand a thing I wrote.
Borgs speaking borg is fine. They'll still be able to communicate with humans as long as HUMANS themselves choose to understand BORG over PHYTOSIAN. That's something that'll stay that way.

In the instance that the do, then humans and borgs will be able to speak and understand each other as much as they do now. That is because humans understand borg, and borgs understand human.

Anyway, despite the controversy this is merge-ready.

**Comment by oisin100** [comment]
Borgs need to be able to speak both human and borg.

No language for unathi?

**Comment by Super3222** [comment]
The point of this was to make cross ways between actual communication within the game.. 

All humans will not be able to understand borgs is the point, sacrificing that necessity to be able to listen on Phytosian's speaking their own tongue. Otherwise, it's exactly the same as it is now. Nothing changes at all. Humans that want to be able to understand Phytosian will not be able to understand borg. And that's ONLY if you choose to, otherwise it defaults as cyborg. Of course, Phytosians will not be able to understand borgs at the cost for their new language.

And no language for unathi.

**Comment by MacHac** [comment]
Unathi should have obnoxious hissing speech, and plasmaman speech should be loud rattling occasionally interrupted by comments about the importance of a calcium rich diet.

How come phytosians are the only ones to get their own language?

**Comment by Super3222** [comment]
A race with their own language would have been pretty neat, but then I got more and more suggestions of giving each and every roundstart language their own language to speak with.

And you know what, maybe I'll remake this so that humans get to choose ONE language which they can understand from the roundstart races. Just maybe. It's not in my best interest to do so, because the idea is ridicolous.

**Comment by Super3222** [comment]
I'll close this for now.

**Pull request closed without merging**
