### PR TITLE
Ghost Event Notifier

### PR DESCRIPTION
**Pull request by Time-Green**
Most events notify ghosts and give them a follow link if there's something to follow.

It's just a small message in deadchat, no sound or anything
:cl:
rscadd: Ghosts get notified about random events
/:cl:
I must say, it's really satisfying being able to follow the nullrod and see it tear the station into pieces

### CODE REVIEW

**Comment by ghost** [comment]
The madman finally ported it!

Did you port the auto-debris tracker as well?

**Comment by Time-Green** [comment]
Ported what?
Are you telling me I could've just fucking ported this?
fuck me

**Comment by simonset55** [comment]
Kek, pretty sure TG has had this for a while. Could probably have ported that

**Comment by Time-Green** [comment]
Can you read?
Also, this one has something /tg/ doesn't have: my narration

**Comment by Time-Green** [comment]
All issues were adressed.

Follow links weren't actually broken. Immovable rod just goes of to another z-level half the time, wich kills it.
PDA didnt work because there were no PDAs, virus didnt work because there was no one to infect etc

I guess someone not me has to test it, but it works fine so honestly I wouldn't bother

**Pull request closed without merging**
