### PR TITLE
Yog Rebase 2.0

### PR DESCRIPTION
**Pull request by oisin100**
Why did we rebase to TG when we had VORE?

:cl:
rscadd: Rebsed to VORE.
/:cl:

any coders can make PR's to my repo to contribute Yog features.

### CODE REVIEW

**Comment by AndySok** [comment]
My name is Smug Anime Succ now.

Fite me

**Comment by RoboticVodka** [comment]
Rebase with Vore, remove ERP rule.

**Comment by ShadowDeath6** [comment]
lines changes: 1 million

**Comment by AndySok** [comment]
But seriously , add "MEME ZONE" label or close this request.
It's not funny

**Comment by ShadowDeath6** [comment]
> it's not funny
> you're the one who asked it

:triumph:

**Comment by AndySok** [comment]
> you're the one who asked it

Hey , it was Potato's idea , not mine

**Comment by oisin100** [comment]
I had my fun.

**Pull request closed without merging**
