### PR TITLE
JEXP

### PR DESCRIPTION
**Pull request by Super3222**
Fixes https://github.com/yogstation13/yogstation/issues/434
Fixes https://github.com/yogstation13/yogstation/issues/490

Changes:
- The database is set up as |ckey|job|count instead of |ckey|job1|job2|job3| and you get the point
- JEXP will only effect byond accounts that aren't older then 2+ months (within 56 days of the current date??)
- JEXP now has it's own subsystem.
- JEXP no longer makes a job completely inaccessible, but instead makes it so you cannot set specific job (heads excluding captain, security officers, and warden) priorities over low.
- Each requirement makes it so you only need to play the job once. Cargo and QM once for HoP, Chemist, MD, and Geneticist once for CMO, Security Deputy once for Security Officer, etc etc
- JEXP is currently disabled, like I planned in the last commit, I am going to wait a week and a half before actually making it a thing
- No more exemption lists. They're unnecessary.
- Less hardcode, JEXP now uses config. Like mentioned earlier, all values are 1, meaning you only need to play a job once if you are restricted you know.
- Subsystem carries most of those global jobs / variables and what not.
- Admins can only reload or toggle jexp
- The only way you won't gain "jexp" is if you're AFK.
- Every time a new player logs in, their jexp is automatically reloaded.
- When you check your jexp stats for whatever reason, it automatically reloads

Stuff that's not exactly JEXP but, follows it somewhat:
- There is only ONE security deputy slot now. With 2 day minimal age for new players that want to get an experience of the brig and all. Spawn in the security office as well.
- Deputies are basically lawyers regarding access and authority, and have almost no real gear to make an arrest. Their goal is basically to learn from other people / officers, not to take their jobs.
- Deputies will NOT have maintenance access OR access to the weapons closet. 
- **Security Officers now spawn inside of the security office (within the brig) instead of at their stations.**
- Prison Officers are no longer "deputies" but, still serve as the "Wardens assistant". I feel like this job is going to get removed in the future but, for now they're basically mini wardens. They have light access to their office / the flashers and hard suits, they require an age of 7 like security officers and wardens. No access to the armory for obvious reasons.
- A prison officer is best helping the warden secure perma prisoners and gulag prisoners alike. They do not have maintenance access for a reason, their goal is to serve the brig only.
- HoS now has a pet again. ROXIE! I wasn't able to find Sgt. Arachnid.

:cl: Super3222
rscadd: JEXP! Credit goes to MSO for helping me scavenge this and IamGoofBall, sorta, for pointing out what was wrong with it.
rscadd: Really, don't mind this. It's just a code-based security system to direct new players coming to SS13 away from head roles. This will only affect new byond accounts (2-3 month old) and you'll barely ever see it.
rscadd: !NEW JOBS!
rscadd: Security Deputies - A job for new players to learn the ropes of the bridge. With minimal access, their goal is to basically shadow officers around and assist them when needing. Their gear is also minimized, so don't be expecting to handle out real arrests without someone helping you.
rscadd: Prison Officers - A job earlier brought into the game by KMC. The idea behind it was to create an assistant for the Warden, which is exactly what it is now. Their goal is to serve the brig, and always listen to what the warden has to say. It's basically a second hand for brig control and, best played policing an active gulag or perma in my own opinion. But, that can be handled within the game.
tweak: Security Officers will now spawn within the security office!
rscadd: ROXIE'S BACK! The ol' girl's waiting for you in the HoS's room.
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Add a chastity belt to it so goof can't fuck it again pls

Also if this gets merged then rip brig officer pr

**Comment by Super3222** [comment]
What's wrong with prison officers? They still serve somewhat of a purpose.
We should also be careful with growing security.  I think we have 6 officer slots + warden + HoS + 2 deputies + detective + prison officer.
So 12 positions in total (but 7 jobs in one division) And given if brig medics become a thing, 13 (with 8) jobs).

**Comment by Notamaniac** [comment]
Isn't there a timer on the jobs so new players can't pick head positions right off the bat?

**Comment by FluffySurvivor** [comment]
how about we scrap the whole deal and instead reward heads that have a lot of experience with stuff like special skins for their items/clothing?

**Comment by TheSadFox** [comment]
> There are two security deputy slots now. With 2 day minimal age for new players that want to get an experience of the brig and all. Spawn in the security office as well.

So, what outfit are they going to use when their jumpsuit was repurposed for a brig officer?

**Comment by Super3222** [comment]
> So, what outfit are they going to use when their jumpsuit was repurposed for a brig officer?

That's up to KMC honestly, and I'll change it to whatever he wants me to (since he sprited the deputy outfit originally).

**Comment by AsV9** [comment]
I like this a lot more than I liked the old system. +1 from me.

**Comment by Iamgoofball** [comment]
You addressed all of my complaints. :+1:

**Comment by Kmc2000** [comment]
I'm gonna make a less swanky deputy outfit. The fashion police deemed it too nice for noobsec

**Comment by Kmc2000** [comment]
Officer shitsec reporting for dep-duty

**Comment by Jc1469** [comment]
I still don't see the need for this.  

Security doesn't need another bunch of job slots, _aka the deputy job_,  they're already the most **_powerful_** department.
Temp-Jobban heads that show to be utterly incompetent and unable to do their basic departmental duties.

> JEXP will only effect byond accounts that aren't older then 2+ months (within 56 days of the current date??) 

Good thing everyone ONLY makes a byond account to play ss13, right.

You'd think after last time, you'd realise.  People just outright don't want this shit.  Admin activity and all that really is the only issue.  Bad heads get jobbanned, warned, forced to improve.  Adding a timed limit does absolutely nothing.

**Comment by Super3222** [comment]
@Jc1469 The intention of JEXP is the same as the old system.

I've always been trying to work on softening security so the division doesn't get bloated, while also putting pieces where they should be. Mind you, I do see much potential for security deputies within the game and look forward to their implementation within the game. I'll work them out with prison officers, which were basically ripped deputies, which I have already discussed with KMC.

I feel like you don't realize how minimized / less strict this JEXP is compared to the old version. Restrictions are limited to the count of one and, when it's merged it'll still be disabled allowing players to NOT be bugged.

> Good thing everyone ONLY makes a byond account to play ss13, right.

This system still is doing it's job in some areas. Despite what you think John, there's nothing wrong with more security (not actual in-game security, but to the server). With it being more east to adjust, anyone can bend and fabricate it into what they want. I'll leave that up to the results that decide, because everything's at the barebottom currently.

And despite it's shortcomings it's still going to get the job done. There's a reason towards why it was salvaged, and that's because it wasn't impossible to implement.

**Comment by Super3222** [comment]
This is merge ready now.

**Comment by X-TheDark** [comment]
Why is a new HoS pet mixed into this PR?
Plus, disappointed that it's speak aren't phrases from the sechailer. At the very least let HoS put a sechailer on Roxie and have her use the sechailer when she decides to speak.

**Comment by Super3222** [comment]
I was adding a ton of new security features in and thought adding Roxie back wouldn't be all bad.

That also sounds fun X but, would have to go into another PR to keep this one from being bloated.

**Comment by utahclock** [comment]
merge when ?

**Comment by Super3222** [comment]
this is a month and a half old pr

**Comment by Super3222** [comment]
merge conflicts act 7 coming soon

**Comment by Cruix** [comment]
I swear I will get the database set up for this sometime this week

**Comment by Super3222** [comment]
More merge conflicts. Just what I needed.

**Comment by X-TheDark** [comment]
At least it now shows what files conflict. :+1:

**Comment by Super3222** [comment]
@X-TheDark Seems like we're experiencing those problems.

**Comment by vladlds** [comment]
#234

> Security Officers now spawn inside of the security office (within the brig) instead of at their stations.
> tweak: Security Officers will now spawn within the security office!

They can just use radio to get to know each other and set up a plan.
Spawning at departments gives ability to act immediately since round start, please don't change it.

**Comment by Super3222** [comment]
> They can just use radio to get to know each other and set up a plan.
> Spawning at departments gives ability to act immediately since round start, please don't change it.

Yes, but it makes more sense for security to spawn at their meeting room. Specifically so they can coordinate with each other from the get-go, formulate plans, meet each other in person, etc etc. They get to know their team.

This worked in the past, and I don't see why it had to be changed in the first place. If the problem is "security officers never guard their post", than that's the HoS and Wardens fault, not the code's fault. We can't re-arrange a players mentality. Whether they work at their post or not is up to them. We still have people today that get up and leave their department, and never come back.

Anyway, this was one hell of a coding experience, but every time I fix this it gets ignored for 2 more weeks, within those two weeks a bunch of PR's which change the same exact file I use in this PR are merged, and than that leads into a spiral of more conflicts. If this was a gamemode, or something that'll actually affect people in game I would've held onto it. But it's just too small, and it's been too long.

**Pull request closed without merging**
