### PR TITLE
message shows when shadowlings are getting burnt in the light

### PR DESCRIPTION
**Pull request by ShadowDeath6**
he does it for free

### CODE REVIEW

**Comment by Cruix** [comment]
This breaks tactical shadowling cloning / SE injection stealthlings

**Comment by ShadowDeath6** [comment]
they already show up as big black men when you take em out of cloning, the least you could do is let them pop out in the dark

**Comment by doerakpoes** [comment]
Good job jelly

**Comment by Jc1469** [comment]
Kinda hurts sling stealth as a whole really.  Slings can someones sneaky beaky like past people with lights in maint, while taking a tiny bit of damage, un-noticed because what is an eyes.   Now they can't really do that.

**Comment by ShadowDeath6** [comment]
They only take damage when they're entirely visible, so there's not really a stealth aspect at that point. The main reason this was made is because drones have been accidentally burning shadowlings by repairing broken lights and can't tell if they're shadowling since they can't examine people anymore

**Pull request merged**
