### PR TITLE
New space ruin, the Hippie Van

### PR DESCRIPTION
**Pull request by matskuman5**
Tiny new space ruin, basically a hippie van with ambrosia, drugs and a fluff note

image

:cl:
rscadd: NanoTrasen space explorers have discovered a small new ruin.
/:cl:

### CODE REVIEW

**Comment by Keekenox** [comment]
This is what ruins should be, Simple interesting little thingies.

**Comment by ShadowDeath6** [comment]
>not features ported from hippie put into a van

dropped

**Comment by Cruix** [comment]
> No space guitar

Closed

**Comment by Time-Green** [comment]
> No dead admiral hippie inside

Banned

**Pull request merged**
