### PR TITLE
Fixes SSU's not accepting their original contents.

### LINKED ISSUE #618: [Bug] Explorer suits can't be put back into suit storage
They give the a message saying you place them in but do not go in.

### PR DESCRIPTION
**Pull request by AshCorr**
:cl:
bugfix: SSU's now accept their original contents when emptied.
bugfix: Survival Suits can now be placed in Lavalands SSU's
/:cl:

Fixes #618

### CODE REVIEW

**Comment by Super3222** [comment]
After the first :cl: you should place your ckey so, people can recognize who fixed the bug.

**Comment by oisin100** [comment]
> After the first  you should place your ckey so, people can recognize who fixed the bug.

My Ckey is the same as my github username.

**Comment by AshCorr** [comment]
> After the first  you should place your ckey so, people can recognize who fixed the bug.

My ckey is my github username

**Comment by oisin100** [comment]
It defaults to the github username.

**Comment by Super3222** [comment]
Oh, seems like I'm out of date.

**Pull request merged**
