### PR TITLE
Ports space hotel from tgstation to Yogstation, makes exile implants block teleporter use

### PR DESCRIPTION
**Pull request by Tenryumi**
YAY FOR DEAD PEOPLE GETTING EVEN MORE SPAWN ROLES!!

o9zwbzd

# WHAT WAS ADDED:

- The *"Twin-Nexus,"* an **isolated** hotel stationed in space, spawned and positioned in the same way space ruins are. This has been ported directly from /tg/code with (currently) no modifications made whatsoever, as it seems fine as it is to me. Of course that can be changed if need be. 

*Purpose: I've added this ruin as per the request of an [interested party](http://i.imgur.com/Pog5sS5.png). Along with this, the hotel would give not just one, but **7 ghost spawns**! This is great because it provides more ways for ghosts to get back into the round while offering the option to not spawn in Lavaland.*

- A special security outfit exclusively only to the one hotel security guard.

*Purpose: The outfit itself is an awesome reference, but also this outfit is used in tgcode. On top of that it wasn't much of a hassle to port at all, and more clothing variety is always appreciated.*

# WHAT WAS CHANGED:

- Users with exile implants are now unable to use the station's teleporters.

*Purpose: Holy shit, this wasn't a thing before?! With this, those whom are exiled are ACTUALLY exiled and can now no longer return to the station via teleporters.*

___

Since this hotel is likely unfamiliar to Yog players, I will give details to the hotel here as well.

#  IMPORTANT HOTEL FEATURES:

- Ghosts can click the sleepers inside to join the hotel's staff, or as staff security. **These spawns are not antagonists.**

- **A teleporter room!** This will allow people to teleport to and from the hotel using the teleporter at the Station, but of course this will only work if the Station's teleporter has been activated. This may not be okay with Yogstation players however for obvious reasons, and this could be removed if need be.

## OTHER HOTEL FEATURES:

- 6 lovely guest suites with 2 separated beds in each suite. Each are complete with a bathroom with all bathing equipment.

- A laundry room!

- A janitor's closet with a surprisingly wide selection of janitorial equipment. The only things that seem to be missing are the traps and Pimpin' Ride.

- Fully functioning electrics systems with two pre-assembled solar arrays. Unlike the Station's solar arrays, the wires outside here have already been set.

- A Mini-"Brig." Only 1 Hotel security officer can spawn, so naturally there are only accommodations for one officer. However there are two holding cells styled after classic earth jail cells. Complete with non-private toilets right next to the windows!

dllhost_2016-11-20_22-13-41
 This is all the medical equipment in the entire hotel.

- One hardsuit unit, held in a small engineering room with other essential engineering equipment/

- A HUGE kitchen and butcher room, and a laughably small bar with no bar drink dispensers; only a drink vendor, blender and a shaker. Let's hope a space bar spawns nearby, huh?

- A pool. Oh dear... I'm unsure as to whether or not that will work on Yog.

___

There may be (and probably will be) assets from tgstation that will be needed to also be ported in order for this hotel to fully work (sprites it seems are all that will be needed.) However I will open this PR as I dig through /tg/'s repository for the aforementioned sprites. 

### Please provide feedback for desired modifications!

### CODE REVIEW

**Comment by Tenryumi** [comment]
check errors as expected tho so WHEEE OFF I GO, OFF TO FIND THOSE ASSETS

**Comment by Time-Green** [comment]
Could you add a botany room?

**Comment by Dragonforcefive** [comment]
Seems cool. I mean, I'd spawn just to explore the hotel. But I think some players will get really bored really fast. I mean, what happens? Is it basically like an extended round on station?

**Comment by utahclock** [comment]
I like

**Comment by Tenryumi** [comment]
@captainblobfish Basically? Yes. However hotel staff could easily interact with the station via their teleporter hub, provided the station's hub is activated as well.

**Comment by Dragonforcefive** [comment]
Yeah, but that may open up issues of meta. Maybe one of these players were killed by an antag and want revenge. Maybe they know something.

**Comment by ghost** [comment]
No, they can't.

@captainblobfish @Yewmi 

Trying to go to the station as hotel staff is an instant ban. They have giant text saying 'dO NOT GO'

**Comment by Dragonforcefive** [comment]
I would think going back to the station as hotel staff wouldn't be good. I didn't like that idea anyways. Maybe people on the station can enter the hotel.

**Comment by ghost** [comment]
@captainblobfish 

That's why the hotel has a teleporter.

Station crew go to the hotel. Hotel staff do not go to station.

**Comment by Tenryumi** [comment]
How about we have them spawn with an exile implant then? That could help address this potential issue.

**Comment by Stealthkibbler** [comment]
Exile is possibly the best option to prevent them from doing that, you can easily change it by editing the spawners and there should be an "implants" var that you can edit. I'm not sure what exile is defined as soooo, you'll have to test it a few times. Unless they're designed the same way walkers are and their gear is coded and not spawned in.

**Comment by Stealthkibbler** [comment]
Although I am somewhat against porting this because it will probably just end up being animal hospital 2.0 where people dont want to roleplay and will attempt to leave the hotel.

**Comment by ghost** [comment]
trying to leave the hotel results in a ban, so

**Comment by Super3222** [comment]
I would suggest make one of the ghost roles spawn as a traitor, excluding the security one, which in turn would turn the entire space ruin into murder mansion.

But than there's that teleporter which ruins everything.

**Comment by ghost** [comment]
that'd be boring as fuck someone spawns and everyone just murders the other one and it's done within minutes

not to mention like...who would play it they'd get the hotel staff and ghost until they got triatot then sec shows up and kills eac hother


jesus uck you fucking morons how fucking autistic do you haeve ot be IT's NOT THIS HARD

# IT IS A FUCKING HOTEL PEOPLE FROM THE STATION GO AND COME AND NOBODY ON THE HOTEL CNA EVER LEAVE

**Comment by ghost** [comment]
# DON'T GIVE THEM EXILE IMPLANTS YOU MORONS JESUS CHRIST EXILE IMPLANTS DON'T OD ANYTHING TO NON-GATEWAY AND WOULD FUCK EVERYTHING UP IF THEY DID THEY GET BANNED IF THEY LEAVE THE HOTEL YOU DON'T NEED TO CODE IT IN IT"S A FUCKING RULE AND IT SHOWS UP IN GIANT TEXT THEY CAN'T LEAVE THE HOTEL HOW STUPID ARE YOU

**Comment by Super3222** [comment]
You have no idea how fun it was Adam. Murder mansion was also a pretty popular and classic byond game. There's also hundred different ways which it could work. The code can easily be changed, measurements can be easily fastened in, and a murder mansion play on can be created with fucking ease.

Hell, it could even be an admin-toggable thing for GHOSTS just like CTF with absolutely NO respawns. It'll probably take placing this map somewhere on z2, and some asking around.

On the other hand the map looks amazing. I'm sure people are going to run around it, and get their fill. It seems like a great place to hang out. I hope this gets implemented. I'd love to play as sec, and jail crewmembers who're breaking into places. Shake hands with the station's HOS, and trade off antagonists I caught.

**Comment by Stealthkibbler** [comment]
>No timers on the cells

please merge this, I've seen it all.

**Pull request closed without merging**
