### PR TITLE
New Join UI

### PR DESCRIPTION
**Pull request by Amelia0010**
Ports the join-round UI from Para. It's supposed to look like this:
image

Currently, it looks like this:
image

I purposefully didn't include the "active people" bit, but if there's support for it i'd add it in again
#### Changelog

:cl:  
tweak: The latejoin UI has been tweaked, and now splits jobs into departments, courtesy of Paradise
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
ugly

**Comment by Alek2ander** [comment]
Only if the job preference screen is changed to match.

**Comment by AlpacaGoesCrazy** [comment]
```
.jobs
{
	margin: 0 auto;
}

.jobsColumn
{
	display: inline-block;
	text-align: center;
}
```

Change `.jobs` and `.jobsColumn` in `/html/browser/playeroptions.css` to the above and you will be golden

**Comment by Amelia0010** [comment]
@Alek2ander This is the join & preferences UI side by side:
image

Not sure what you'd want changed tbh

**Comment by ShadowDeath6** [comment]
Looks ugly and also isn't color coded like our current one is, :-1:

**Comment by Alexandria404** [comment]
Nice

**Comment by ShadowDeath6** [comment]
what's our current join UI? I'd like this one to be color coded like the preferences menu rather than it looking like what it does now

**Comment by Amelia0010** [comment]
This is the current UI. Of course some jobs are missing, as it's taken from an on-going round, but w/e:

image

**Comment by Partheo** [comment]
Please make all boxes in the same column share the same width.

**Comment by Amelia0010** [comment]
Added a 4th colum so it balances out a bit more in the "height" section. 

image

**Comment by Amelia0010** [comment]
@AshCorr @AsV9 Travis died

**Comment by Zostroll** [comment]
I think it looks good. I wouldn't mess with the character set up though.

**Comment by ghost** [comment]
What Paradise PRs gave them theirs?

**Comment by Amelia0010** [comment]
https://github.com/ParadiseSS13/Paradise/pull/4826

**Pull request merged**
