### PR TITLE
Dynamo maps

### PR DESCRIPTION
**Pull request by AshCorr**
Ports dynamic runtime maps from TG.

Original PR https://github.com/tgstation/tgstation/pull/24171

Travis probably wont like this.

### CODE REVIEW

**Comment by Amelia0010** [comment]
Why did I get label powers again

**Comment by Amelia0010** [comment]
Dynamic maps*

**Comment by AshCorr** [comment]
You were talking about ranks whilst i was typing the commit message :/

**Comment by AlpacaGoesCrazy** [comment]
does this mean we will get map rotation soon?

**Comment by AshCorr** [comment]
> does this mean we will get map rotation soon?

Pretty much what this entire pr does.

**Comment by Time-Green** [comment]
Holy shit nice

**Comment by Amelia0010** [comment]
I helped create this PR btw. I supplied sweets and hugs

**Comment by AshCorr** [comment]
The juan million lines changed....

**Comment by Amelia0010** [comment]
the dream is real

**Comment by AshCorr** [comment]
Wait wha, how do you have access to my repo...

**Comment by Amelia0010** [comment]
that's not important

**Comment by AshCorr** [comment]
:thinking:

**Comment by Amelia0010** [comment]
:^)

**Pull request merged**
