### PR TITLE
Wizard's den, centcomm, the seed vault and abductor ship doesn't kill plants anymore

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Wizard's den, centcomm, the seed vault and abductor ship doesn't kill plants anymore.

#### Changelog

:cl:  
fix: Phytosian wizards won't die in their den anymore!
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
What about plantman ruin? If anyone walks/creates light here plantmans start to die, slowly

**Comment by Amelia0010** [comment]
The plantman ruin has lights, this was easier than adding lightframes all over centcomm and the wizard's den.

**Comment by KrabSpider** [comment]
@nichlas0010 the ruin for some reason, has bugged lighting. You will barely survive in there without a flashlight

**Comment by Partheo** [comment]
Can confirm what Krab has said.

**Comment by Ratvar** [comment]
You forgot holodeck

**Comment by Amelia0010** [comment]
bring a bloody flashlight. All the other ones don't give you the ability to just leave, but god, just dont enter the holodeck or bring a flashlight

**Pull request merged**
