### PR TITLE
Explorer hoods will delete now to prevent undroppable hoods. Also allows laz injector to be emagged. 

### PR DESCRIPTION
**Pull request by ghost**
you're all fat

##### Changelog

:cl:
fix: The explorer hood will delete when dropped now to prevent undroppable hoods.
rscadd: Emag the laz injector to make it malfunction. Have fun.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
This will delete the hood whenever it gets retracted back into the cloak.
Inventory code is generally shit.

**Comment by ShadowDeath6** [comment]
How does the TED work? Use that

**Comment by ghost** [comment]
It works the same. There's no predefined way to do this. 

I can't exactly make it store the armor values either. The only thing I can think of is some really gimmick ass shitty thing of making applying goliath plates to the helmet qdel it and turn it into another repathed helmet and change the suit's retracted helmet to something else but that's awful.

I guess miners will just have to deal with 'don't retract the hood.'

**Comment by ShadowDeath6** [comment]
I'd rather it bug out when decapitated than bug out when retracted, you toggle the hood a lot more often than you get your head cut off

**Comment by Super3222** [comment]
Fixing a bug by adding in another bug obviously isn't going to pass.
There are also ways to do this. Like checking for whether the hood is on the ground in the first place, and qdeling it from there. HELMETS already do this.

**Comment by ghost** [comment]
then if there's a way to do it you do it

**Pull request closed without merging**
