### PR TITLE
Remodels the law office [FIXED]

### PR DESCRIPTION
**Pull request by matskuman5**
Those bookcases are filled with Space Law
:cl:
tweak: Nanotrasen architects have remodeled the Law Office.
/:cl:

### CODE REVIEW

**Comment by Slinky5890** [comment]
I feel like the walls should be left alone. Looks weird that there's suddenly wood walls

**Comment by Jc1469** [comment]
Take a screenshot of the entire hallway.  Including the detective's office.

**Comment by matskuman5** [comment]
Last time everyone loved it #2359 :(

**Comment by ghost** [comment]
Cool, it's *completely unfitting.*

**Comment by matskuman5** [comment]
This is how it looks now

**Comment by Jc1469** [comment]
what is the world coming to when the lawyers room is bigger than the detective's office, the most technical security role.

**Comment by matskuman5** [comment]
I'm out. Goodbye

Fuck you Nich

**Comment by ghost** [comment]
r-r-rekt

also you can just make a new branch and copypaste your old branches office over the new branches office, lazy knob.

**Pull request closed without merging**
