### PR TITLE
Nerfs the changeling LSD sting

### PR DESCRIPTION
**Pull request by Amelia0010**
WELCOME, LADIES AND GENTLEMEN, TO NICH'S SALT PR SHOW. IN THIS EPISODE, WE'LL BE LOOKING AT THE CHANGELING LSD STING.

### Intent of your Pull Request

Nerfs the changeling hallucination sting by reducing the amount of mindbreaker it injects. It now cuts the amount of mindbreaker in half, meaning I'll only crash every 30 seconds for 5 minutes, instead of 10!

#### Changelog

:cl:
tweak: the changeling LSD-sting has been nerfed
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
I wouldn't bother.  The worse part is the crash, which I'm pretty sure is caused by dreams when they fake knock you out.

And dreams will be gone soon.

**Comment by ShadowDeath6** [comment]
buttblasted

**Comment by ghost** [comment]
They can just sting twice, then.

**Comment by Time-Green** [comment]
@Jc1469 the crashing isn't caused by dreams, people were crashing long before dreams were added

**Comment by Amelia0010** [comment]
> They can just sting twice, then.

Which would double the amount of chemicals they need for the same effect, which I believe is called nerfing it.

**Comment by ghost** [comment]
Alright mr. smartass, here's my point.

this is pointless, because a ling will still just spam sting and chem regen is fast enough for this to be barely noticeable.

Increase chemical cost too, and then they can't dualsting quite as easily.

**Comment by X-TheDark** [comment]
If hallucinations crash the game, wouldn't it be better to just replace the whole mechanic with something else?

**Pull request closed without merging**
