### PR TITLE
Ports everything I've done

### PR DESCRIPTION
**Pull request by X-TheDark**
**READY FOR MERGING**

Everything relevant that I've done for Yogs has been ported. Every port has been individually tested : compiles, launches and works (at least at the level of "this does what it's supposed to do". bugs may crop up due to interactions).
- [x] Ports Drones passing through doors without opening them + fixes (doesn't include undroppable drone toolbox): https://github.com/yogstation13/yogstation/pull/115 + https://github.com/yogstation13/yogstation/pull/821
- [x] Mech batteries remember their removed battery charge and set the next inserted one to the percentage of the removed one. Bonus : removes all unnecessary src mentions: https://github.com/yogstation13/yogstation/pull/169 + https://github.com/yogstation13/yogstation/pull/296
- [x] Ports active magboots and traitor shoes not slipping on lube : https://github.com/yogstation13/yogstation/pull/213
- [x] Ports Odysseus Syringe Gun scanning medbay sleepers for reagents : https://github.com/yogstation13/yogstation/pull/229
- [x] Ports Odysseus Syringe Gun being rearm capable : https://github.com/yogstation13/yogstation/pull/352
- [x] Ports whatever buffs Assault Syndiborg is missing + infinite taser fix : https://github.com/yogstation13/yogstation/pull/314 + https://github.com/yogstation13/yogstation/pull/1232
- During porting new proc was necessary : /obj/item/proc/unequipped(mob/user) that removes all actions the item has from the user
- Cyborg modules now properly support action buttons - putting them into module slots puts buttons on UI, removing from module slot removes buttons.
- [x] Improves Slime Person slime split to use a list of bodies, instead of being awkwardly tied to previous body via var : https://github.com/yogstation13/yogstation/pull/381
- [x] **Ports Job Whitelist system and fixes** : https://github.com/yogstation13/yogstation/pull/699 + https://github.com/yogstation13/yogstation/pull/736 + https://github.com/yogstation13/yogstation/pull/1020
- [x] Riot shields no longer block projectiles : https://github.com/yogstation13/yogstation/pull/1004
- [x] Power sink buffs : https://github.com/yogstation13/yogstation/pull/986
- [x] Detomatrix no longer blows up ever : https://github.com/yogstation13/yogstation/pull/983

This includes some of the miscellaneous functions used by the systems.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Feel free to PR that second one about mech batteries on tg main branch, that one would be accepted

**Comment by X-TheDark** [comment]
Will do!

**Comment by Bawhoppen** [comment]
The others ones would potentially be accepted aswell, but every single thing on tg is a federal issue so you'd have to fight and bribe people to get it merged

**Comment by X-TheDark** [comment]
Federal issue, eh? Haha.

**Comment by X-TheDark** [comment]
Welp, porting over Cyborg LMG + Replicating ammo in Grenade Launcher wasn't as simple. Had to **add obj/item/proc/unequipped()** that removes all actions associated with the item from the user.

Good news are:
- Cyborg LMG fire-mode cycling and Grenade Launcher replication are now action buttons.
- Cyborg modules now properly support action buttons (they add them to the UI when you put them into the module slot and remove them from UI when you remove them from module slot into storage).

**Pull request merged**
