### PR TITLE
renames the faggot

### LINKED ISSUE #358: Rename the meatball
Fix the meatball name so it's meatball, and not f*ggot. Sick of hearing chefs spamming that term because "is da name of da food hurr durr"

### PR DESCRIPTION
**Pull request by Stealthkibbler**
fixes #358 

:cl: Stealthkibbler
tweak: The Meatball no longer triggers sensitive people
/:cl:

### CODE REVIEW

**Comment by MacHac** [comment]
The triggering is a feature.
If you genuinely have a strong opinion on what a meatball is called, you should get back in your bubblewrap padded hole and stop playing spessmans.
Besides, you're throwing away a perfectly good conceptual link between the word 'faggot' and one or more meaty balls.  What are you, some sort of conceptual link destroying meatball?

**Comment by Stealthkibbler** [comment]
@MacHac meh, people dont like the word faggot, just like how council got triggered when time said he wants to kill genderfluids. We live in a special world with speshul snowfleks.

**Comment by ParagonPrime** [comment]
this is fucking insane

**Comment by FluffySurvivor** [comment]
fyi nobody gets offended by banned words but it became a tradition to just banhunt those that say the words, by admins and players alike

**Comment by ParagonPrime** [comment]
you guys are ridiculous

**Comment by TheSadFox** [comment]
> fyi nobody gets offended by banned words but it became a tradition to just banhunt those that say the words, by admins and players alike

T'is so true.

**Pull request merged**
