### PR TITLE
Makes ei nath less cancer

### PR DESCRIPTION
**Pull request by ShadowDeath6**
inb4 "oh shadow but wiz is supposed to be op"
https://github.com/yogstation13/yogstation-old/pull/1153

:cl: ShadowDeath6
tweak: Ei Nath now instantly kills its victim instead of gibbing upon use, but using it on someone who is dead will gib them normally.
tweak: Slime people are more easily dismembered but can reattach their limbs
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
oh no

**Comment by ShadowDeath6** [comment]
why is the online editor such a piece of garbage

edit: it is I who is the piece of garbage, apply_damage only works on humans

double edit: no, it does indeed work on all mobs

**Comment by FluffySurvivor** [comment]
mandatory i ded tag

**Comment by ShadowDeath6** [comment]
I realized my mistake

**Comment by GrayRachnid** [comment]
but wiz is supposed to be op

:-1:

**Comment by Jc1469** [comment]
oh shadow but wiz is supposed to be op

Seriously.

**Comment by ghost** [comment]
Wiz can be op without being cancerous

Hilarious overpowered shit is good-see staff of animation. Instant click gib isn't even fun.

If ei nath sent someone flying down the hallway until they hit a solid object then gibbed them it's be fine as a oneclick gib but otherwise it's just not fun for anyone compared to other spells.

**Comment by Stealthkibbler** [comment]
Cant we just make it so it turns people into the dreaded cluwne?

**Comment by Super3222** [comment]
How to make Ei Nath fun:
- Make it throw someone flying down a hallway like adam says
- When they hit a solid object, each one of their limbs dismembers
- 'Bowling ball striking a set of pins' sound is played after that happens

**Comment by oisin100** [comment]
Make Ei' Nath tear all the targets limbs off, Or do adams suggestion.

**Comment by Time-Green** [comment]
It should punch their fucking brain out

**Comment by ShadowDeath6** [comment]
that's literally what it already does, time

**Comment by Time-Green** [comment]
I mean, as in their body stands still, and then their brain gets shot away in the direction the wizard was facing. That way you could pop the brain back and clone/defib them, or if the wizard cares enough, he could collect them.

**Comment by ShadowDeath6** [comment]
ei nath no longer does 500 damage but blows off every limb but head, also slime people have easydismember but also easy limb attachment, that won't be abused at all

**Comment by ShadowDeath6** [comment]
Also the new ei nath looks really good if I do say so myself

**Comment by Cruix** [comment]
I'm good with this. Going to merge it soon if no one objects.

**Pull request merged**
