### PR TITLE
Re-adds JEXP

### PR DESCRIPTION
**Pull request by Super3222**
# Re-adds JEXP and I don't give a shit about what ANYONE says

### CODE REVIEW

**Comment by Super3222** [comment]
also cruix is my brother

**Comment by Mrcreepssss** [comment]
what's JEXP?

**Comment by Super3222** [comment]
It was a project that was done around a concept players on Yog was throwing around. It required people to play a job X amount of times before playing a head position. I decided to code it, but I was way over my head, and I didn't bother to read into what I was doing and the project went overboard. Remade it shortly a second time, was praised somewhat, but none of the maintainers bothered to look at it, I got tired of merge conflicts, realized I was beating a dead horse so I closed it.

Right now? It's a reminder to me that I should always look into major projects from a players perspective. Some things sound great in theory, but once you bring in reality they get convulted and you realize how much time you could've or did waste designing it.

**Comment by Mrcreepssss** [comment]
okay, i'm not entirely sure what exactly you're saying about it:
"Right now? It's a reminder to me that I should always look into major projects from a players perspective. Some things sound great in theory, but once you bring in reality they get convulted and you realize how much time you could've or did waste designing it."
sooo it's a bad idea? but then why are you trying to get it back?
i think it sounds like a good idea, though what about players who already have played the roles necessary amount of times before this got merged?

**Comment by Mrcreepssss** [comment]
also, the way you bring this from the beginning (title and about cruix) looks like you're abusing power, so be carefull with that i reccomend.

**Comment by Super3222** [comment]
This was an April fools gag. Check the "changes" section for more.

**Pull request merged**
