### PR TITLE
Electric chairs can de-convert revs now!

### PR DESCRIPTION
**Pull request by Amelia0010**
:cl:
rscadd: Electric chairs now have a 50% chance of deconverting revs!
/:cl:

### CODE REVIEW

**Comment by AsV9** [comment]
also 170 burn damage :zap:

**Comment by Amelia0010** [comment]
That's what it was before :^)

**Comment by ghost** [comment]
kind of pointless, because at that rate you'd have a better chance just beating them in the head until they deconvert

**Comment by ShadowDeath6** [comment]
probably not going to be used that much but if it encourages security to electrocute people it's gonna be a :+1: from me

this is also entirely useless because you're probably going to leave them dead anyway and 170 is too much to defib

**Comment by Amelia0010** [comment]
just get a bunch of burn patches and mass electrocute ⚡️

**Comment by Oakboscage** [comment]
This is some good shit

**Review by AsV9 — APPROVED** [review]
Don't see how anything could possibly go wrong here.

**Comment by Super3222** [comment]
I like.

**Pull request merged**
