### PR TITLE
Who the thirteen flying cocks thought a no-drawback easy to make healing chemical that metabolizes in fifteen minutes was a good idea?

### PR DESCRIPTION
**Pull request by ghost**
Seriously, this shit was incredibly potent and can pretty much outheal almost anything, and to top it off it wasn't even alcoholic. You could chug 300u of this stuff and not have to worry about going into crit for the next thirty minutes. 

At least now it's alcoholic, which is fitting, because all its component drinks are very strong too.
#### Changelog

:cl:  
tweak: Hearty Punch is now significantly more strong of an alcohol to balance out its insane healing power.  
/:cl:

### CODE REVIEW

**Comment by Zostroll** [comment]
It is made quite infrequently.

**Comment by Notamaniac** [comment]
Uuuh if I'm reading the code correctly all this will do is just keep you from dying since it needs you to be unconscious and below 0 health, which is probably why no one used it, or will ever really use it.

**Comment by ghost** [comment]
It’s the strongest and most potent healing chemical in the game and rigorously abused on tgstation. It effectively makes you unable to go into crit it’s so good at healing. It’s not used on yogs because yoggies are stupid.  But they will start using it eventually.

**Comment by ghost** [comment]
@zostroll 

If it is ever made or used is irrelevant. The fact remains that it exists.

**Comment by Notamaniac** [comment]
Just for the record, this doesn't heal while in near crit, but you can sleep to trigger the heal, which can get you out of crit with 1-7 health,potentially more if you've taken burn/tox/oxy since this heals at 7 points of each damage type per tick. With the 7 heal per tick, it can let you survive beatings with low damage weapons, and potentially live through a full barrage of a laser gun if you get shot slowly enough.  

Yeaaah a nerf is probably needed, with this you won't be able to rely on it during a fight (vomiting, dizzy, tox damage, ect.), though you might be able to use it on someone in deep crit, which should probably be the essence of bar drinks, niche uses.

**Comment by Ratvar** [comment]
Fix botany nutriniments working on plantmans without overdose, give charcoal OD treshhold

**Comment by ghost** [comment]
@Ratvar Out of scope, irrelevant to PR.

**Comment by Ratvar** [comment]
"Who the thirteen flying cocks thought a no-drawback easy to make healing chemical that metabolizes in fifteen minutes was a good idea" - you with phytosians and plant nutriniments, silly. Your PR asked question, I answered.

**Comment by ghost** [comment]
If I have no idea what you just said and it’s still out of scope for this pr.

**Pull request merged**
