### PR TITLE
Ports the craftable baseball bat from tg

### PR DESCRIPTION
**Pull request by Stealthkibbler**
ported directly from tg 
https://github.com/tgstation/tgstation/pull/19144/
coded by Lzimann, sprites by Keekenox

10 force baseball bat that knocks people back 1-2 tiles when you hit them.

:cl: Stealthkibbler
rscadd: Nanotrasen has signed a brand deal with a big league space baseball team, their signature baseball bats can be crafted with 5 wooden planks
/:cl:

### CODE REVIEW

**Comment by GrayRachnid** [comment]
remove knockback

**Comment by Stealthkibbler** [comment]
@GrayRachnid while im at it lets remove every stun in the game and give antags crayons instead of double eswords, then just to be sure, lets also remove stamina damage. Because special effects on weapons is a big no no :^)

**Comment by GrayRachnid** [comment]
https://github.com/tgstation/tgstation/pull/19264

**Comment by Stealthkibbler** [comment]
@GrayRachnid 

> a 10 brute weapon that actually costs things to create is pretty useless
> 
> don't ruin spaceball forever

I'd very much rather keep the knockback, it's what separates it from other weapons and makes it unique. Removing the knockback turns it into one of the worst items/weapons in the game meaning that its pretty much no different than a rod.

**Comment by GrayRachnid** [comment]
> The only useful thing the knockback does is let you chainstun people by slamming them into walls which is hilarious but also basically a 20 force stunbaton

**Comment by Stealthkibbler** [comment]
@GrayRachnid This is due to how walling impact works, could put in a hit delay I guess but I dont know how to code so you'd have to bother someone who can actually be fucked doing that.

**Comment by FluffySurvivor** [comment]
:+1:

**Comment by ToGWtF** [comment]
mfw i coded this for Yogs, you guys shot it down, and keek took his sprite to TG

**Comment by oisin100** [comment]
> The only useful thing the knockback does is let you chainstun people by slamming them into walls which is hilarious but also basically a 20 force stunbaton

Seems pretty ridiculous, I dont agree with this PR. Fit it, close it, or convince me.

**Pull request closed without merging**
