### PR TITLE
Blob rounds now end on blob death

### PR DESCRIPTION
**Pull request by ghost**
mulligan = cancer

:cl:
tweak: Blob rounds now end on blob death
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
nice.

these are configs, council or headcoders to have to edit it

@Cruix @X-TheDark

**Comment by Jc1469** [comment]
Is this based on the shit admins have been forcing afterwards or on just base blob mulliganing traitors?

**Comment by ShadowDeath6** [comment]
blob normally mulliganning traitors is what people usually complain about, because the round is already fucked at that point due to massive power loss / breaches / everyone has guns

**Comment by Jc1469** [comment]
I mean the fact that recently admins have been spawning different antags, like in some situations, a nukeop team after the blobs are dead. Along with loads of fluff announcements about how everything is fine.


And for the record, winning at that point is utter horseshit against nuke ops because everyone is out of place either repairing damage from blobs or scrambling to get their guns back to the armory before they get fucked by security.

**Comment by Cruix** [comment]
I'm going to disable continuous rounds for wizard and blob during this testmerge.

**Comment by Time-Green** [comment]
Perhaps implement a voting thing?
It's also stupid to have the round end once you've actually made progress in something

**Comment by drderp3635** [comment]
this is pretty damn annoying for people who do progression based jobs to just work 20 minutes for nothing

**Comment by Jc1469** [comment]
It's also fucking dumb when the station is fucked and admins choose to mulligan.
Or when they choose to make it extended and then spawn, I dunno, a fucking nuke team when people are busy trying to repair the entire bottom half of science.

The pros outweigh the cons heavily.

**Comment by Jc1469** [comment]
Not sure what part of what you did caused it, but I think the recent wizard changes messed up the wizard part of this, @Cruix

**Comment by Dagdammit** [comment]
I strongly preferred blob functioning like a big midround event, now it's a big midround event followed by arbitrary round end.

**Pull request merged**
