### PR TITLE
Bluespace Conciousness Translocater

### PR DESCRIPTION
**Pull request by ghost**
Still working on the wizard staff (read: waiting on sprites) but I will include it in this when I finally get the sprites.  Otherwise this just adds the BCT which is admin only.  Gonna bug Nich to add this to centcomm.

:cl:
rscadd: Adds the bluespace consciousness translocater and a new mindswap staff to wizards
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Aaaaaaaaand test merge shit is still in here.  I'll fix that as well.

**Comment by Partheo** [comment]
Clean up your master branch boi

**Comment by ghost** [comment]
It's pretty bad hah!

**Comment by Kmc2000** [comment]
A. what does this do?
B. Why are you messing with vents in the same PR?

**Comment by ghost** [comment]
Well it adds a gun that swaps peoples' minds.  You store an imprint of a mind the first target that is hit and when you hit a second they swap.

The vents etc are because I accidentally merged testmerge into my master and will be removed when I get to it.  Mostly just waiting on sprites before I fix stuff.

**Comment by ghost** [comment]
He basically just made the wizard mindswap a gun, despite what I told him about it being a bad idea.

**Comment by Koffheatalt** [comment]
If it's only spawned on centcomm I don't see the problem

**Comment by ghost** [comment]
Oh you just know some goofball's going to spawn it for players.

**Comment by CrazyDrakkon** [comment]
Like THAT would be the worst idea in the Centcom armory?

**Pull request closed without merging**
