### PR TITLE
[Critical] [speedmerge] Kmc's clockwork updates

### PR DESCRIPTION
**Pull request by Kmc2000**
Fixes a heavily outdated clockwork feature, the pepe meme.

Pepe is old, and stale, and thus, must be buried, goodnight sweet prince

But who will answer the call...

HERE COME DAT BOI

O SHIT WADDUP

Datboi is a clean replacement for lord pepe who recently devolved into "the facebook frog"

Merge now, see instant improvement, no bugs, no mess

🆑 Kmc2000
 rscadd: Updated the meme element of the game as such that it is slightly more up to date
/🆑 

PS me chainsawing it used an outdated icon, i animated it to look a lot smoother

### CODE REVIEW

**Comment by Kmc2000** [comment]
And for those who think this isn't needed

Think again



^Search interest

**Comment by TheSadFox** [comment]
Making cock cult even more op :-1:

**Comment by Super3222** [comment]
H   U   G   B   O   X
U
G
B
O
X

**Comment by ShadowDeath6** [comment]
that massive drop tells me that dat boi has lost popularity faster than pepe ever did

also

> > > > > > > > implying that the amount of times searched proves anything other than the amount of normies that don't know what it is

**Comment by Kmc2000** [comment]
WHAT MATTERS IS THAT HE FRESH RITE NOW

I'll update it to suit the latest memes

**Comment by GrayRachnid** [comment]
no

don't add this

**Comment by Stealthkibbler** [comment]
tg has pepe, we have dat boi, yeeeeee.

**Comment by ghost** [comment]
you are a disgusting human being

**Comment by Kmc2000** [comment]
> adam

<3

**Comment by Kmc2000** [comment]
Wait why did i make this again..?

**Comment by oisin100** [comment]
I like pepe.

**Pull request closed without merging**
