### PR TITLE
[s] Fixed being able to wrench girders onto lava tiles.

### PR DESCRIPTION
**Pull request by Cruix**
People were building lava bridges by wrenching a girder, adding metal, and deconstructing the wall.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
"""""""fix""""""""

**Comment by McDonald072** [comment]
""""""fun removal"""""""

**Comment by Super3222** [comment]
This is the definition of bug abuse. Please merge

**Comment by ghost** [comment]
BOOOOOOOOO, IT's A FEATURE AND KOR LIKES IT

**Pull request merged**
