### PR TITLE
when you run out of stuff to bother the admins with

### PR DESCRIPTION
**Pull request by AsV9**

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
pretty sure it was done like that so multiple "god"s don't answer the same prayer, muh immershens, etc etc

**Comment by AsV9** [comment]
99% of prayers are ignored so w/e

**Comment by TheSadFox** [comment]
> 99% of prayers are ignored so w/e

Think bout fixing this!

**Comment by AsV9** [comment]
good luck

**Comment by FluffySurvivor** [comment]
:+1:
can AOs/coders get SM perms too pls

**Comment by TheSadFox** [comment]
> good luck

Re-add me to admins.txt and i'll take care of it.

**Comment by Super3222** [comment]
I'm not staffing for Yog but, Shadow has a point. If someones already answering the prayer, that notification would come in handy. And if prayers are usually ignored, then there'd be no point towards taking away the notification?

**Comment by AsV9** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
