### PR TITLE
Added cardboard recipe to the biogenerator.

### PR DESCRIPTION
**Pull request by Cruix**
Somehow I forgot to PR this ages ago.
:cl:
rscadd: The biogenerator can now make cardboard.
/:cl:

### CODE REVIEW

**Comment by Zostroll** [comment]
Why?

**Comment by Cruix** [comment]
Because it makes sense.

**Comment by X-TheDark** [comment]
Buff to cardborg (disguise yourself as a borg to other borgs). :+1:

**Comment by ShadowDeath6** [comment]
pretty sure cardborgs are bugged right now and nobody sees you as a borg except yourself

**Comment by Alek2ander** [comment]
Food made of cardboard
Cardboard made of food
Welcome to the future

**Comment by Zostroll** [comment]
When was the cardboard borg feature added?

**Comment by Dagdammit** [comment]
Not normally important but makes sense.

**Comment by ShadowDeath6** [comment]
merg dis

**Pull request merged**
