### PR TITLE
Yogstation is now 512 compatible!

### PR DESCRIPTION
**Pull request by Kmc2000**
Refer to issue: #all of them

### Intent of your Pull Request

Yogstation now compiles on BYOND's newest 512 version, this will need extensive testing before merging, so please do play around with it. This should also HOPEFULLY mean that 512 users can also play properly without crashing! which is annoying.

BYOND's 512 Documentation was used to track these down. http://www.byond.com/docs/notes/512.html

ITEMS THAT WERE EXPLICITLY EDITED CODE WISE:
The mecha syringe gun
The soulstone

These will need extensive bug-testing.

Why the million map changes you ask?

Well the map was corrupted by the 512 thing, so I just copied it over to a new map file and renamed it to un-fuck it.

MAINTAINERS READ ME:
Yes this will be a pain to clear up on, but the sooner we do this, the fewer map changes we have to redo and override when 512 becomes standard.

#### Changelog

:cl: Kmc2000
rscadd: Had to change the Yogstation map file, if you are a mapper, you'll have to re-do your change once this is merged!
rscadd: ALSO MAPPERS: Update your mapmerging tools before committing a change, or it'll crash your byond whenever you try and open a mapmerged file.
experimental: Yogstation now works on BYOND 512
/:cl:

### CODE REVIEW

**Comment by simonset55** [comment]
wew?

**Comment by Amelia0010** [comment]
wew.

**Comment by Ratvar** [comment]
god hep you

**Comment by Amelia0010** [comment]
@Kmc2000 m a p m e r g e

**Comment by Kmc2000** [comment]
@nichlas0010  Don't think that's required here? it's changing the entire map, no?

**Comment by Kmc2000** [comment]
Well that's slightly less horrible :)

**Comment by Amelia0010** [comment]
yes, but it needs to be in the TGM format, or any future mapmerges will change the entire map as well

**Comment by Kmc2000** [comment]
To my knowledge, byond 512 automatically mapmerges, can't hurt though.

**Comment by Amelia0010** [comment]
w e l p

**Comment by Kmc2000** [comment]
Nich was half-right. Mapmerged with the working TG mapmerge suite.

**Comment by ShadowDeath6** [comment]
saying yog is or will be compatible with anything is a gross exaggeration

**Comment by Alexandria404** [comment]
Can´t be avoided, even if it´s a pain.

**Comment by Amelia0010** [comment]
ok nvm this confclits

**Pull request closed without merging**
