### PR TITLE
AO now has access to monitor-all-tickets so they can see tickets.

### PR DESCRIPTION
**Pull request by Jc1469**
kill me

### CODE REVIEW

**Comment by Slinky5890** [comment]
Will this still let them reply?

**Comment by Jc1469** [comment]
No, it wont. :smile:

**Comment by Slinky5890** [comment]
Well that's all good then! Don't see why you'd have a problem with them just viewing tickets.

**Comment by Jc1469** [comment]
I forgot the verb existed because I always had it enabled, and it auto-enabled when I was given a rank again. I wanted to them to see _tickets_ just not the ticket menu.

**Comment by ShadowDeath6** [comment]
commit name

**Pull request merged**
