### PR TITLE
Terminal wires and cable cuffs are now customizable

### PR DESCRIPTION
**Pull request by Time-Green**
The wire color an APC was constructed with will be the color of the terminals wires.
colored wires terminal

Also adds a color2code converter. It turns color into their html code.

Also makes cable cuffs colored. 

image

🆑
rscadd: Makes terminal wires customized
rscadd: Adds a color2code converter
rscadd: Colored cuffs. They are colored based on the cable they were made of.
tweak: You now craft cable cuffs by clicking cable in-hand
tweak: Removed the fading terminal sprite and gave it alpha instead
/🆑

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
This PR is good and color2code is very good, nice work

**Comment by Super3222** [comment]
I like it. We should do this with cable cuffs too tbh.

**Comment by Time-Green** [comment]
Awesome idea! I'll start progress once I am home.

**Comment by Time-Green** [comment]
Props gonna go up tomorrow. I'll add it to this PR. I got the code done, but I thought it'd be smart and copypaste my code to another branch. It wasn't.

**Comment by Time-Green** [comment]
Anyone knows why it's pissing of travis? It compiles and is up-to-date with the master branch. 
Is this one of those things you need to fix from the host?

**Comment by Cruix** [comment]
Meta and dreamstation have some of the old alternate colored cable cuffs on the map, and now they are undefined.

**Comment by Time-Green** [comment]
Ah, I'll fix that in a sec

**Comment by Time-Green** [comment]
Merge ready!

**Comment by matskuman5** [comment]
#Timeforheadcoder2017

**Pull request merged**
