### PR TITLE
Removes the bloody academy

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

The wizard academy is completely useless. At this point, all it's used for is sending 27 space wizards to the station, completely cocking up whatever may be going on in the round. Literally noone is harmed by removing this.

And yes, this PR was made off of salt.

#### Changelog

:cl:
fix: The academy no longer exists
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
please

**Comment by kayozz** [comment]
Also floor is lava cucks the AI with 0% chance of escape...

**Comment by Cruix** [comment]
Remove the map template datum, not just the map

**Comment by Slinky5890** [comment]
just remove the teleporter

**Review by X-TheDark — CHANGES_REQUESTED** [review]
Instead of deleting the map, please comment out the template
`/datum/map_template/ruin/space/wizard_academy`
in
`code/datums/ruins/space.dm`

That will make it easier to restore/update if someone decides to fix it.

**Comment by Kmc2000** [comment]
No thank you

**Review by X-TheDark — APPROVED** [review]

**Comment by Time-Green** [comment]
There's absolutely fucking nothing to do but teleport 50 space wizards into the bridge

**Pull request merged**
