### PR TITLE
Fix borer event

### PR DESCRIPTION
**Pull request by ThatLing**
Borers now work again. This also slightly nerfs the event by reducing the amount of borers spawned. This took way too long for a meme.

:cl: ThatLing and MacHac
bugfix: The borer event can now happen again.
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
I love 'em changeling revives, heals and speed duplicating. Please don't.

**Comment by ThatLing** [comment]
Either borers should be completely removed or fixed. It shouldn't be left broken like this.

**Comment by Amelia0010** [comment]
y tho

**Comment by ShadowDeath6** [comment]
don't add not a bug tag for things that are bug fixes please

**Comment by Amelia0010** [comment]
funpolice

**Comment by grubstank** [comment]
Why are they considered broken

**Comment by Time-Green** [comment]
They can changelong revive their host

**Comment by Ratvar** [comment]
Borer situation WITHOUT event, just with XENOBIO SUMMONING BORERS:
Can changeling revive their host the moment they drop dead, can give host maxspeed, purge chemicals, heal all damage types, including brain, clone and alcohol poisoning. So, they are better then ling healing, in most cases.

Can communicate with every other borer in existance, which means all antags are revealed to everyone, can take control over people, can SUICIDE people, can talk/emote with host's body (+into radio) even when they don't control it, so they can scream ";Help traitor maint" while host robusts the attacker - pAI on steroids.

Have innate parasting, so they can stun and wiggle into your head guaranteed, but mostly use it after they wiggle out of their host, stun someone and let host kill it/take control over and kill themself, or to flee when someone cuts head of their alive host off, then crawl into vent/attacker and suicide attacker, then crawl back into host corpse and revive it.

They are encouraged to ignore them being nonantags cause... hey are made in xenobio, any summoner can give them orders, so they are potencially antags who can kill and infect everyone they want, or are made to FUCK antags up, be it taking control over cultist and killing yourself or just healing anything traitor tries to shoot. "You are forever grateful to Gray Tider and will do anything he says"

Hae innate ability to weaken, mute, blind and paralyse their host as "punishment".

Tons of bugs related to swapping minds back and forth, including giving people ghostvision/ghostradio, deleting people, swapping hosts with borers, cloning borers into host bodies, sugar doesn't do real shit as they still can talk with your body and so.

Oh, and they reproduce.
Fix borer event by removing all traces of borer from game/cutting reproduction, pleease.

**Comment by ShadowDeath6** [comment]
-ling revive takes all 250 chemicals which takes unbelievably long if the host is dead because chemical gain is halved
-healing from chems is slower than ling healing, and it takes borer chemicals to heal the host so it isn't infinite all the time (I'll probably address this if borers aren't removed since stockpiling chems and then giving your host tons of healing at once is pretty powerful, although in my experience keeping your host dosed up enough leaves you pretty low)
-borers should prioritize their host over revealing antag to every other borer considering it can put them in danger
-borers being able to suicide people is a bug so it shouldn't really be a concern balance wise (it still is a bug though)
-stunning is pretty annoying and I've both been on the receiving and the giving end of that cheese so I'll probably do something about that as well

the only real thing I can forsee being a long term issue is the bugs, balance is really easily changed

this pr itself is a bug fix though so removal and changes are out of its scope

**Comment by grubstank** [comment]
I think borers should be totally managable if we push out some bugfixes. From a balance perspective, having two players in one body SHOULD give that body extra power - perhaps not 2x as much, but enough to warrant having one player be a glorified spectator/chem dispenser.

Maybe the balance can be adjusted through increased nutriment consumption? Tying chemical production more directly to nutriment consumption would make borer play much more strategic, and in depth on every level. 

As it is, it seems like the majority of players on the server will attempt to outright kill borers rather than allowing them in.

**Comment by Moja10** [comment]
I have mixed feelings about the borer event working. I think their reproductive abilities are nuts in particular, on top of what's already been mentioned. I think things like suiciding your host as a borer should definitely be looked into before they are slapped back into the game with random events.

**Comment by Super3222** [comment]
Nice job! :+1: Also people need to stop worrying. There are lots of ways to nerf borers. The first place to look at is their mind control ability, and maybe make it require a certain length of time in the host before use.

**Pull request merged**
