### PR TITLE
Re-adds Cryosting

### PR DESCRIPTION
**Pull request by ShadowDeath6**
haha u thought

Cryosting now puts bolamine in your blood to make you slow as fuck as well as dizzying

kinda tempted to add confusion but resonant already does that

:cl: ShadowDeath6
rscadd: Re-adds cryosting but instead makes it slow you instead of freezing you.
/:cl:

### CODE REVIEW

**Comment by RoboticVodka** [comment]
Sounds more like a stamina sting honestly why even call it a cryosting?

**Comment by utahclock** [comment]
yo know the word cyro means cold right

**Comment by ghost** [comment]
ass-sting no

bring back fake armblade sting

**Comment by ShadowDeath6** [comment]
This was an ironic meme.

**Pull request closed without merging**
