### PR TITLE
Medical layout v1.0

### PR DESCRIPTION
**Pull request by Pyrotechnics2**
### Intent of Pull Request

I have made this change do to medical was small and crammed together. With this rough(hence why its v1.0) update you will see what I am going for and how medbay will look when I iron out all of the small issues with this update

#### Changelog

~v1.0
-Layout of medbay was moved
-CMO office was moved to the center of medbay
-Cryo was moved to right side of medbay with reason of it should be a last resort as a treatment option 
-Sleepers were placed below chemistry and of the left side of medical
-Surgery was moved to below Cryo
-Patient care rooms are across from Surgery to allow them to be used as recovery rooms

### CODE REVIEW

**Comment by utahclock** [comment]
Pictures please.

**Comment by Pyrotechnics2** [comment]
Here are pictures of changes

http://imgur.com/a/uK3VM

**Comment by utahclock** [comment]
Genetics looks a bit screwy. And I dont see psychiatrist office.

**Comment by utahclock** [comment]
Chemistry looks funky. And i dont see medbay sec office either

**Comment by Pyrotechnics2** [comment]
Indeed, i removed shrinks office, however I can put it back in in place of medical break room. What about chem is funky and yes I did remove the security office in medical as I never saw it used

**Comment by utahclock** [comment]
Ive used sec office many times while rolling sec. There is no clear path to equipment in chem its blocked bt tables. I dont think we are removing the psych dr so he still needs office.

**Comment by Pyrotechnics2** [comment]
Alright, I can re add those and the chem stuff isnt blocked I don't think i'm looking at it in the editor

**Comment by utahclock** [comment]
capture _2016-11-23-20-43-17

This are here is put together poorly imo not enough room to move.

**Comment by ghost** [comment]
main medbay is emptier than shadowdeath6's sex life

sleepers are put in a stupid place with too much room

cryotubes are ugly af put in that area and also why the fuck is the 'HELP HES IN CRIT' room so far away from medbay

main med vendors and entry area looks like crap

no psychiatrist office

no easy access vendors

chemistry is really shittily put together and asymmetrical and in a weird spot

break room is tiny 

why is the fucking entry medbay area so huge

no multiple surgery rooms which is something people've been whining for for a while

what the eighty flying dicks did you do to the wiring are you TRYING to give me a heart attack

why is the CMO office surrounded by three sets of windows growing out of the wall like a fucking tumor and most of those windows are blocked by fucking vending machines


0/10 should be part of a map called 'abortionstation'

**Comment by ShadowDeath6** [comment]
eat my cock adam

also this map has way too much open space, this looks bigger than sec

**Comment by Alek2ander** [comment]
So instead of common areas being cramped you made useful areas cramped
👌

**Comment by RoboticVodka** [comment]
I can't help, but think this looks almost exactly like the Medbay on Para.... Except worse.....

**Comment by monster860** [comment]
Okay, let's forget the fact that this looks exactly like Paradise's medbay..

I loaded your PR in my map editor, and I don't see the changes at all. Soooooo yeah, that might be a bit of a problem.

Also, you need to mapmerge.

**Comment by Pyrotechnics2** [comment]
Ladies gents, thank you for your shoot downs they help but it would be better if you told me how you wanted it changed. and mr. AdamElTablawy if I didnt think this form github form was meant to be mature I would have many words for you, however I am working on a new repo that will be posted on here so yall can look at updates as I go

**Comment by ghost** [comment]
well

we don't want it changed

that's the thing

you took something that was fine and then peed all over it while howling 'MAP CHANGES'

**Comment by Time-Green** [comment]
@Pyrotechnics2 Are you continueing this?

**Pull request closed without merging**
