### PR TITLE
Added an admin verb to locate all items of a type

### PR DESCRIPTION
**Pull request by Cruix**
mcplayerface: Admins I lost my gangtool spawn me a new one
admin: It is in your box
mxplayerface: oh
<b>Your ticket has been marked as resolved. </b>

### CODE REVIEW

**Comment by Zostroll** [comment]
You can already do that with querys.... And in a more getto way with view vars.

**Comment by Slinky5890** [comment]
@Zostroll nothing wrong with making things easier

**Comment by Kmc2000** [comment]
Add this, queries lag and are complicated and not many people know how to work them

**Comment by MayhemSailor** [comment]
Upvote!

**Comment by Mrcreepssss** [comment]
... REEEEEEEEEEEEEEEEEE keep the strawman playername consistent! first it's MCplayerface then it's MXplayerface! REEEEEEEEEEEEEEEEEee ;)

**Pull request merged**
