### PR TITLE
replaces all red cables with yellow cables, and yellow with orange

### PR DESCRIPTION
**Pull request by Tenryumi**
## FOR ALL FRUSTRATED ENGINEERS REPLACING CABLES OUT THERE!

dreammaker_2016-10-25_23-58-25

dreammaker_2016-10-25_23-58-33
# WHAT WAS CHANGED:
- ALL red cables on TgStation have been replaced with yellow cables

_Purpose: Red cables on red pipes. It's so, SO hard to make out where the cables begin, end, were the gaps are, etc. Yellow is a great contrasting color to red, and now the cables stand out much more not only against the pipes, but in the dark too!_
- ALL _previously yellow_ cables on TgStation have been replaced with orange cables.

_Purpose: Orange is a more appropriate color for the cables connecting to more high-risk machinery, anyway. The color is commonly used for warning signs, after all._

:cl:
tweak: All red cables on the station have been recolored to yellow, and all previously yellow cables are now orange.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
So many times I search for missin red wires on a red pipe, it's shit
+1111111111

**Comment by ShadowDeath6** [comment]
I prefer red.

**Comment by Tenryumi** [comment]
@ShadowDeath6 As do I, honestly. But making an engineer's job easier to do takes more priority, and it simply makes more sense for the cables to stand out.

**Comment by Dagdammit** [comment]
At the title I was like "what this sounds dumb" but holy shit that's genius 10/10.

**Comment by Tenryumi** [comment]
there, no merge conflict :^)

**Comment by Tenryumi** [comment]
wait...
...
oh no...
chrome_2016-11-03_00-22-51
OOOOH NOOOOOOO
fixing this tomorrow

**Comment by Super3222** [comment]
@Yewmi You might have to re-do this PR.

**Comment by Tenryumi** [comment]
It seems so... Re-doing this PR due to GitHub freaking the fuck out on this branch in particular. The branch is beyond repair.

**Pull request closed without merging**
