### PR TITLE
Let AIs use multiple data huds at the same time

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
rscadd: AIs can now use their medical, security, and diagnostic huds at the same time.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/issues/2036

Can you try and find out what's causing this since there are still bugged medhuds? I have no idea why it's happening

**Comment by Cruix** [comment]
I will try

**Comment by Mrcreepssss** [comment]
:DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Mrcreepssss** [comment]
@ShadowDeath6 in that issue it said that it was tied to suit sensors.

**Pull request merged**
