### PR TITLE
Revert "Made the singularity attracted to mass."

### PR DESCRIPTION
**Pull request by ghost**
It was reasonable to try.

It was less reasonable to keep. Singulo being released is an immediate, game ending GG that also makes the power beacon kinda useless all things considered.

And yes, sing being released should be a game ending GG-and it normally is-but singulo bullrushing the AI and the entire station chewing every particular corner is a bit much.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:^)

**Comment by BOBsHERE** [comment]
How about giving it a 1/4 chance of being attracted to mass when it moves? Then it may still eat the entire station, but it will be a slower death. Also, i wish there was a better way to stop a singularity. Right now the tech on BOH's is really high and is rarely achieved nowadays.

**Comment by Cruix** [comment]
As it is it has a 60% chance of being attracted to mass per movement, so making it 25% would not change too much.

**Comment by ShadowDeath6** [comment]
make it .00000000000000000000000000000000000000000000000001%

**Comment by Super3222** [comment]
So I sorta predicted the outcome.

**Comment by Ephemeralis** [comment]
Adjust the chance to 1/6 or 1/8 and it should be more reasonable. I can forsee the sing lingering around the fringes of the station that way, still causing serious damage while keeping the core of the station intact.

**Comment by BOBsHERE** [comment]
just had the singularity released two rounds in a row. If it gets free right now the station is doomed.

**Comment by EMT321** [comment]
Why not decrease the singularity speed by say, 1/4, and maintain current tracking? Make it a slow unstoppable force that can be ran from.

**Comment by ghost** [comment]
@EMT321 that would a. Make eball and nar'sie weird and b. Still have sing beacon useless

**Pull request merged**
