### PR TITLE
Ports wizard academy to space ruins, tweaks map to make it yogstation friendly

### PR DESCRIPTION
**Pull request by Tenryumi**
### This is the Wizard Academy, ported from /tg/'s away mission of the same title.

fortress of wiznerdrey
_apologies for the low image resolution, this map is massive and it'd just be too time consuming to get a full screenshot on the default zoom setting._
- Map size: 103x113 (size reduced to fit better as a space structure spawn)

Since this map hasn't been seen on Yogstation, I'll give a breakdown of what wacky bullshittery this arcane deathtrap has to offer.
# NOTABLE MAP FEATURES (Unchanged:)
- Magicarps are all over the outskirts of the academy. Probably guard dogs. Er, guard carps.
- Magic equipment. I'll list all of them further down this description.
- MANY hostile, angry wizards, greedily guarding said magic equipment. they can and will shoot fireballs at any enemies not allied with the Wizard Federation (wizard players are not attacked.)
- **A WIZARD GHOST SPAWN ROLE.** Ghosts have the option to spawn as a defender of the Wizard Academy. They are tasked with acting as the guardian of the magic bullshittery the Wizard Federation has hoarded. **It is not a one time usage spawner,** however it will only work if the wizard that spawned from it (if any) is dead or braindead. This will very likely need either a major tweak, or removal entirely. That will be up to you guys to decide.
- A teleportation rune network . It seems ANYBODY can use them, but their destinations are pre-determined and cannot be changed.
- Magical SMES cells that appear to generate power from magic, which powers the APCs onboard.
- Magically controlled, tiny singularities, encased in glass. They're seemingly much weaker versions of Lord Singuloth. All they seem to need to be contained is a thin layer of refined glass.
- A botany room with Kudzu and blue-space tomato seeds(**!!!**)
- A demonic basketball court.
- A communications room, with parts to assemble a fully functional T-Comms.
- A cellar with a Nuke Ops mask, gloves and turtleneck.
### THE MAGIC ITEMS HELD THEREIN:
- A **soulstone shard**
- A **Die of Fate**
- A **Gem-Encrusted Hardsuit**
- 2 **wands of Fireball**
- The **Lens of Truesight** (gives x-ray vision)
- A **Deck of Tarot Cards**.
- A **Wand of Polymorph**.
- A **Ritual Knife.**
- A **Wicker doll** (a voodoo doll.)
### THE GUARDIANS OF THE TREASURES:
- 6 space bats and 2 giant spiders protect the Tarot Cards.
- A skeleton and morph guard the ritual knife.
- 2 wizards protect one fireball wand.
- 2 wizards protect the Lens and soulstone shard.
- 1 wizard protects the Wand of Polymorph.
- _**Nobody**_ is watching a fireball wand, nor the hardsuit, wicker doll, and Die of Fate.
- 3 Space bears guard the Nuke Ops clothing.
# WHAT I HAVE CHANGED:
- There was a gateway in the bottom-most area. I've replaced this with a teleporter assembly. 

_Purpose: in case somebody would actually want to go to the station or back to the academy. Given the ghost spawn role in the same map area, this or the spawner may need to be changed. That, and Yogstation doesn't use the Gateway._
- Many of the asteroids have been moved closer to the station in order to compress the map further. 

_Purpose: This way there will be more room in the rest of the space Z-level around it._
# "WHAT THE FUCK NO NO NO NO NO"

Yes. I know. This has a LOT of risky, powerful items hidden inside. I do not intend for this PR to be merged immediately. I instead intend to open this PR for collaboration with all of you in order to balance this area out so this place _can_ be used on Yogstation.
### Please, give your advice for balancing this place out in the comments. I and many other people (I did ask players about this!) would love to see this place become accessible on Yogstation!
# EDIT: REGARDING THE GHOST SPAWN ROLE:
- They spawn with a special wizard exile implant, **preventing them from leaving the acedemy.**
- **Defenders only possess 3 spells: Etheral Jaunt, Magic Missile, and Fireball**
#### Changelog

:cl:
rscadd: The Wizard Headmaster has become less diligent in maintaining the invisibility spell concealing the Wizard Academy...
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
I really like it. The powerful items need to match the huge risk of going there. All the carp, wizards, and other traps will make it nigh impossible to loot everything. 

Is the spawner similar to ash walkers or other lavaland ghost roles?

**Comment by Time-Green** [comment]
We should start using away missions again.
Probs have it rotate every round and do something with assasinate objective not to make them impossible.

**Comment by Tenryumi** [comment]
@Time-Green Away missions require a gateway.
I've been told that the reason that Yogstation doesn't use gateways is because it puts a lot of pressure on the server's processing and can cause a lot of lag for everybody.

**Comment by ShadowDeath6** [comment]
The wiz doesn't get a spellbook with teleport, does he? That might be a problem.

**Comment by Tenryumi** [comment]
```
/obj/structure/academy_wizard_spawner/proc/summon_wizard()
...
    var/obj/item/weapon/implant/exile/Implant = new/obj/item/weapon/implant/exile(wizbody)
...
    current_wizard = wizbody
```

It seems the wizard cannot leave the area, as they have an exile implant automatically put into them upon spawning.

**Comment by Yewmi** [comment]
Perhaps I should add a new spellbook made _specifically_ for this area, granting the wizard a more limited choice of spells. **DEFINITELY NOT TELEPORT THOUGH.**

**Comment by Super3222** [comment]
Tarot Cards and Wand of Polymorth are too much imo. Those are extremely powerful weapons, even if it's on a random remote space ruin which has mobs protecting them.

**Comment by Nickvr628** [comment]
With player controlled mobs it will be very well defended. Combined with the remoteness of the facility I feel that the risk vs reward is good.

**Comment by Cruix** [comment]
The wizard spawn is broken, it is trying to use the wizard mob as the poll time. You have to fix https://github.com/yogstation13/yogstation/blob/f589a9ca72e7273ba8d85d7d115da0ad4de6ce75/code/modules/awaymissions/mission_code/Academy.dm#L94 by adding a poll time before current_wizard or changing it to "mob = current_wizard".

**Comment by Tenryumi** [comment]
Thanks, I didn't know that!

**Pull request merged**
