### PR TITLE
Added signal technician job

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
rscadd: The signal technician job slot is now available. Their job is to make sure that telecoms is working at peak efficiency at all times, rebuild it when it inevitably gets bombed by redsuits, and write annoying NTSL scripts.
/:cl:

To facilitate the job of a signal technician, there is a new access level, tcomms admin. Engineers are still able to access the satellite and telecoms machinery, but they can no longer use the computers (as it was, engineers had to hack the door to get into the computer room, but they could unlock the traffic console with their ID). Naturally the CE and captain get this access too.

A signal technician's uniform is basically a roboticist's uniform in green instead of red. It provides marginally more protection against cold than a normal jumpsuit, and the CE's jumpsuit has be upgraded identically. Signal techs also get a slightly modified engineering winter coat so they can go into the server room without an EVA suit:
sigtech stuff

I also rearranged the tcomm satellite a bit, adding a toolbox, signal tech locker, a pipe dispensing machine, a rack with some gloves and internals on it, and rearranged some areas so the AI won't be alerted every time the signal tech moves between rooms, only when they enter or leave the satellite. Also messed with door accesses a little so techs can get from the satellite to the central hallway.

While I was at it I also extended some areas so that all the air injectors sitting in space are actually powered.

Old:
old_tcomsat

New:
new tsat

### CODE REVIEW

**Comment by Tenryumi** [comment]
pda-signaltech
Quickly made a signal tech PDA icon so their PDAs can be different from that of roboticists.

**Comment by ShadowDeath6** [comment]
too small a job, me no like

**Comment by X-TheDark** [comment]
This is way too minor and specific to be a separate job, in my opinion.

**Comment by EMT321** [comment]
I see no harm in this, only fun.

**Comment by Super3222** [comment]
The way I look at this is how people look at paramedics from medical doctors - it's just another part of a job taken over.

Imagine if we had a paramedics room, without paramedics, which medical doctors could enter in and go through all the time. They'd almost never do that.

Having a signal technician isn't going to cost us anything, and NTSL is a giant gateway into almost limitless fun. And as the CE - I wouldn't mind some random nerd implementing useful NTSL scripts or even standing around and making sure telecoms is functioning properly.

And better yet - people would be screaming "LYNCH THE SIGNAL TECH" when the NTSL scripts go haywire. So another thing, over than viruses, that gets you torn limb from limb by an angry crowd.

**Comment by ShadowDeath6** [comment]
this is like adding a xenobiologist job

**Comment by Alek2ander** [comment]
Both APCs are in Satellite Control - you left Satellite Access without one

**Comment by Super3222** [comment]
> this is like adding a xenobiologist job

only the CE can access this room so it's not really comparable to adding a xenobiologist job. 

But hey, for anyone that's still in disbelif look at it this way:
How many times do they CE's actually use this room instead of doing all of the work normal engineers are suppose to be handling? They have a ton of responsibilities, and a ton of places to be at and working. The ones who are using this room for the entire shift are the ones with a dependable bunch, or are ignoring their job and trying to "coordinate" their team without even looking at the damage.

this job will also give a platform to all the nerds obsessed with NTSL without having to quarrel with the duties and responsibilities of the CE. Hell, it'll give a fix to some of the newbies that are interested in meddling with NTSL scripts.

and for that I give my :+1:

if you still think the CE should have total control over this room - well they still do. It's like me being the CMO - walking into the virology lab and making my own viruses. If I want to step in and take over, than I can. I'm your boss.

if you're thinking about the AI running NTSL scripts - Shut up AI, law 2.

**Comment by supernoodles13** [comment]
The only problem I can see with this is if there are two signal techs.  since there is only one console to work with.

**Comment by Slinky5890** [comment]
I feel like the only way this job would be something they can work all shift on and not just have them set up a code then fuck off for the rest of the round is to have those telecomm glitches repairable and maybe add extra challenges to tcomms (Though i'm not nearly creative enough to come up with new tcomms ideas)

**Comment by Kmc2000** [comment]
You mean engineers?

Add the outfits and stuff in tcomms and their PDAs in a little hidey hole but there's no need for a legit job like this to be roundstart IMO.

It's a very specialised job so it just sounds like itll get shat all over

**Comment by Super3222** [comment]
we should at least testmerge it (merging it onto an updated branch?) to see the players reactions from it. 

I'm seeing it go in two different directions - one way. no one knows what the fuck they're doing. other way. people begin to grasp and learn NTSL, and fool around with it, while throwing shit together on telecoms and possibly making their own radio channels.

**Comment by Dragonforcefive** [comment]
I like this idea, though I agree with supernoodles. And while this job seems interesting, there has to be a bit more I think. Maybe a way to improve T-Comms, or maybe creating new encrypted frequencies. Though I can definitely see the abuse of power that may occur with this. Someone could screw over the stations COMMS by screwing up the coding, which could be detrimental to the station the entire round. And let's be honest, consider all the other roles that aren't really required. Does the clown technically need to exist if we use the logic of what they do roundstart and what they do during a round? Do we need the mime or librarian? What about the psychiatrist or lawyer? The most important out of all of these are the lawyers, and even they're not a necessity to the game. Yes it's specialized, but so is the virologist's job. If more things were implemented in with the job, it'd be a pretty damn neat job to have. But of course, all of this is in my opinion.

**Comment by Time-Green** [comment]
I like it, but I did see some people say it was boring.
Maybe give it a little lounge with arcades? I mean, it's in space, not like anyone needs that space. (Space joke)

**Comment by MaxBurakhovich** [comment]
I like it, but i think that signal tech should be a unique job (like clown or mime) because 2 techs will try to upload different scripts and there is only one console to work with. Also i think that there should be some "test" server where you can test your script without any influence on station channels.

**Comment by Cruix** [comment]
At the moment it is unique, unless the HoP opens a new slot. The test server is a good idea.

**Comment by matskuman5** [comment]
Sounds like a good idea. Don't think it's TOO specialized, but they could use something more to do. Maybe add some more random events like ion storms that just scramble the speech slightly so it's not debilitating but signal techs have something to do?

**Comment by Dragonforcefive** [comment]
I haven't played as Signal Tech. yet. But so far, I know a few people liked the role. I'm going to try the job out ASAP, but I need to learn more about scripting.

**Comment by monster860** [comment]
You should probably use dmitool merge driver to resolve this morgue conflict.

**Pull request merged**
