### PR TITLE
Adds 1u and 1/3u options to chem dispenser

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
tweak: You can now fill up a chem beaker with 1/3u and 1u of a chemical
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
Interesting.

**Comment by Cruix** [comment]
Beakers are now more precise than droppers

**Comment by monster860** [comment]
Actually the most precise thing is a chemmaster

**Comment by Cruix** [comment]
The chemmaster uses the same transfer options as the beaker that is in it

**Comment by monster860** [comment]
You also have a "custom" button in there so you can transfer any amount

**Comment by Cruix** [comment]
Then why does it need 1 and 1/3 options?

**Comment by monster860** [comment]
You have those options in the chem master not the dispenser

**Comment by ShadowDeath6** [comment]
1u I'm fine with, one third seems kind of weird. Why not one half? Why not any fraction?

**Comment by AshCorr** [comment]
> 1u I'm fine with, one third seems kind of weird. Why not one half? Why not any fraction?

Yea... Could we just use rational numbers? which saves us having ungodly chem quantities which have a ton of decimal places.

**Comment by Mrcreepssss** [comment]
yeah, keep it to one and not three, if you really want it that badly use three 1u transfers

**Comment by matskuman5** [comment]
^ seconded

**Comment by ghost** [comment]
use 3 1u transfers to get 1/3

yes that makes sense @Mrcreepssss

**Comment by Mrcreepssss** [comment]
ehhhhm @AdamElTablawy  i get the impression you misunderstood me as your comment makes no sense to me (it seems sarcastic), what i said that to get 3 unit transfer you can just use three 1 unit transfers.

**Pull request closed without merging**
