### PR TITLE
Removes extraction sting, changes absorb objective

### PR DESCRIPTION
**Pull request by Amelia0010**
Absorb objective changed to somewhere between 2 and 10, depending on server pop. for every 5 pop, the amount increments by 1, up to a max of 10, at 50

Closes #2656 Closes #2765 

#### Changelog

:cl:  
rscdel: Extraction Sting has been removed from changelings, absorbing is now necessary
tweak: absorb objective scaling changed, for more information check github
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
Make it one for every ten, not five

**Comment by Alexandria404** [comment]
There are discussions going on in council about how to address the issue.
Nich was not aware of it at the time.
Please don´t merge it for now as we are still considering possible directions.

**Comment by Alexandria404** [comment]
After repeated, repeated talks, the conclusion from council seems to be majority is fine with it if the numbers are lowered to 1 for every ten.

**Comment by retrosquid64** [comment]
I think not having the extraction sting is good, makes changeling rounds more paranoia filled.

**Comment by Ikoden** [comment]
It's a good change yet there is one problem that I see. I think that people on low pop (of course on other pops too, yet it would be the biggest problem on low pop) will see it as a permission for murderbone absorbing. "Oh, I've already got 3 absorbs. I've finished everything else, so let me be an even better ling by absorbing some more people.", "I've absorbed 2 people, why not absorb 6 people.", "If absorbing people is an objective, then I can totally absorb as many as I want and it certainly does not constitute murderbone." - I can see those as thought processes of many people. Just my 2 cents.

**Comment by Amelia0010** [comment]
it's now 1 for every 10, and if people see "kill 2 people" as "let me kill 14 people to be good" then they should just die

**Pull request closed without merging**
