### PR TITLE
More dynamic combat with hotkeys

### PR DESCRIPTION
**Pull request by LarissaMayrink**
### Intent of your Pull Request

Adds hotkeys for each body part so that combat(and surgery) may be done easier and faster, it will also open up the possibility of actually changing aim during combat for the extra effects(disarms, cutting arms off, extra knockdown from the legs) instead of the current head aim spam.

I hope i did this right.

Edit: I didin't

#### Changelog

:cl:
Update: Still trying to get the last errors fixed at mob_movement.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
that cl either won't work or will be super terrible in-game, just make it like

add: numpad1 = right leg
add: numpad2 = groin
and so on

**Comment by LarissaMayrink** [comment]
@ShadowDeath6 It works really smoothly on tg, and i expect to work just like that on yog as it is based on tgcode.

**Comment by LarissaMayrink** [comment]
Oh well, now i got why it won't, i will fix when i'm back from work, in retrospective that was a lazy way of doing it.

**Comment by LarissaMayrink** [comment]
I fucked up, starting over. I will come back when my compiled version is actually working.

**Comment by ShadowDeath6** [comment]
when I did that I meant the changelog, not the code itself
I can't tell if it'd work or not

**Pull request closed without merging**
