### PR TITLE
Removes unused ab-use center area

### LINKED ISSUE #2304: Abuse still exists
Abuse center is still a jump to area choice but in reality it's just a single orange tile. Either rebuild it or remove it because I'm bad at mapping.

### PR DESCRIPTION
**Pull request by matskuman5**
Fixes #2304 

Couldn't get the TGM thing to work properly.

:cl:
fix: Removes the empty AB-USE CENTER from the "jump to area" list.
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Can you put it in main centcomm, like one tile of it. So much easier to jump to than centcomm dockd

**Comment by Cruix** [comment]
I wish there was some ease way to know if there was a key regeneration or if you just accidentally modified 800 tiles.

**Comment by Super3222** [comment]
@matskuman5 You've got merge conflicts. Also is this PR necessary?

**Comment by matskuman5** [comment]
Oh great, merge conflicts. I don't really care about this PR

**Pull request closed without merging**
