### PR TITLE
Golf fixes (fixed version)

### LINKED ISSUE #1436: Golfclubs don't make a sound when you bash people.
Bashing someone with a golf club provides no sound to any players.
This should make a some sort of sound as any item hurting someone does.

### PR DESCRIPTION
**Pull request by matskuman5**
Refer to #1438 

Fixes #1436 

:cl:
bugfix: Golfclubs now make noise when beating people, as well as some other small fixes regarding the club
tweak: The captain's putting green is anchored by default, so you can start golfing at round start!
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
Misclicked

Reopening

**Comment by oisin100** [comment]
I think you messed something up..

**Comment by matskuman5** [comment]
What do you mean?

**Comment by matskuman5** [comment]
That close and coment thing is fucking stupid, at least make it say "Are you sure" before it fucks everything up

**Comment by Cruix** [comment]
What are you talking about I never have problems with it

**Pull request merged**
