### PR TITLE
Ported Yogstation april fools clown weapons.

### PR DESCRIPTION
**Pull request by Cruix**
They are all admin spawn only.

Includes:
Bananium nuclear bomb
Waterflower full of lube
Combat noslip banana shoes
Energy sword that slips people
Boomerang energy shield that slips people you throw it at
Banana with a peel that explodes
Teargas grenade that gives everyone fake moustaches that cannot be removed for two minutes
Dark H.O.N.K. mech with a bananapeel-bomb launcher, tearstache launcher, and honkerblast

### CODE REVIEW

**Comment by Cruix** [comment]
Yogbot are you okay?

**Comment by ShadowDeath6** [comment]
make boomerang eshield a regular op item when

**Comment by TheSadFox** [comment]
> remove eshield when

FTFY

**Comment by Super3222** [comment]
I love these weapons. If only people truly appreciated the power of the honk

**Pull request merged**
