### PR TITLE
Readds weapons at CC

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Adds a tonne of weapons to centcomm, for end of round grief.
image

#### Changelog

:cl:  
rscadd: Centcomm now comes equipped with an arsenal of deadly weapons for use against syndicate agents!
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
I'm probably gonna remap centcomm at some point when I find the time.
The amount of work Adam put into his wonderful project turns me off from doing it, however.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Adam himself said this map was a shitty meme pr that got merged for some reason

**Comment by Partheo** [comment]
Exactly.

**Comment by Alexandria404** [comment]
Quality PR :ok_hand:

**Comment by ghost** [comment]
i can't believe you made centcomm EVEN WORSE than i did but you've fucking done it

**Comment by Amelia0010** [comment]
I don't care for the aesthetics of CC, I just know that EORG is 90% of what CC is used for, and making it better is more important than it looking at all good :^)

**Comment by Amelia0010** [comment]
fuck it, i'm removing adam's shitty CC as a whole, so shuttles can fucking fit

**Pull request closed without merging**
