### PR TITLE
Syringe Gun Rework

### PR DESCRIPTION
**Pull request by Time-Green**
Changes the way you use syringe guns COMPLETELY.
 --------------------------------------------Introducing darts!------------------------------------
-Syringes can't be loaded into syringe guns anymore, but darts can

-Darts can be filled with syringes, no worries

-Medical and combat darts, the combat ones pierce through thick clothing and can be reloaded

-Adds them to autolathe/protolate

-Gives armory a rapid syringe gun with boxes of syringes with: Morphine, mutadone and empty ones.

-Sleeping darts spawn in medbay storage

-Removes the piercing needle in favor of darts

-Chemistry spawns with a box of empty medical darts

-CMO has a box of mutadone darts to battle hulks

-Only 3 types of chemical can be inserted into a dart. This is the prevent instakill deathmixes. 
     (You can still kill people with only three chem. This can be vareditted.)

-Combat darts allow 5 chems

:cl:
rscadd: Introduces darts! They are the new syringe gun ammo!
/:cl:

naamloos

### CODE REVIEW

**Comment by Bittern12** [comment]
Poor description- I looked through his code and it's boxes of darts, one box is sleeping darts and the other is anti-hulk.
 I can't tell where on the map it's supposed to go but I do hope it's in a secure place and not just a place where everyone in medbay can access it, if it's medstaff accessible I am against, if it's CMO only access then I am totally for it. -It's a gun and the security mechanic of guns is that we lock them up and make ammo obscure to acquire.

**Comment by Time-Green** [comment]
Aphielanis, I was still writing

**Comment by Bittern12** [comment]
Sorry about that.

 It looks like a good job I'm just kind of iffy on giving a syringe gun to security when they already have many weapons and chemicals really isn't their department.

 Also their sec training isn't exactly medical training so what would they know about over doses or effective doses versus body mass? It just seems like too much of a Medical/Science weapon that Security should have to ask them to barrow than something that should be default in the armory.

**Comment by Time-Green** [comment]
I went with it mainly in case of hulk problems. Imagine if they were to stop a medbay gang with hulks, then that syringe gun would be their saviour. 

If it's not liked, I'll just remove it from there.

**Comment by Bittern12** [comment]
What about when people are legit antagging with hulk though? Sec already has a ton of guns, sometimes on antag rounds hulk can be the thing that levels the playing field for the antag.

 You have a good point too though. So let's just sit back and see what people think.

**Comment by BOBsHERE** [comment]
Someone flag this as controversial. this is a massive nerf to go on top of adams massive nerfs. Not needed.

**Comment by Time-Green** [comment]
This PR was made as more of a rebalance, as to stop instakill deathmixes.
You could basicly shoot someone once with a syringe and they would drop dead within 3 seconds, no resistence possible.

You're against this PR because it prevents you from death mixing people. Wait? It doesn't. To make up for it:
The combat darts penetrate clothing and you can still kill with one chemical. Hyposprays are completely untouched. For now.

**Comment by BOBsHERE** [comment]
Its a bad PR. Syringe guns are already balanced by their difficulty of use, limited ammo, high prep time, and fucking ridiculously easy counters. This PR should be closed.

**Comment by BOBsHERE** [comment]
Just take chemists off the antag list while you're at it. Make them like the HOP.

**Comment by Time-Green** [comment]
I was thinking of raising the allow chemicals in combat darts to 2-3 chems. 
Can another coder/admin tell me if I should?
I can't take pure serious due to him being extremely one-sided.

**Comment by Time-Green** [comment]
Combat darts can now hold 2 kinds of chemicals.
Serious critics are appreciated

**Comment by BOBsHERE** [comment]
You admit in OOC that you never play chem. You see one or two good chemists who can make use of the current system without ever trying to do it yourself and assume its easy. You said things like "oh just hit them with four darts" like that's actually an intelligent sentence. Or "oh, just stun them first" thereby removing the entire point of being a traitor chemist. Once someone is stunned, they're effectively dead so anything you do after they are stunned is irrelevant. Chem has so many hard counters its stupid. Even the best chemical mix that doesn't use fire kills fairly slow. You also don't care about the time investiture it takes to make the chemicals, the odds of you being caught making said chemicals by anyone paying attention, and the fact that you're the only department really capable of poisoning someone. Once they yell "chemist rogue" you cant just go back to your department like you can with science. Once you run out of syringes (which you do, fucking syringes are easy as hell to dodge and they take time/attention to reload) then you are are screwed because you got ousted by using shitty time green approved poison mixes. One chemical is not going to kill anyone, ever. Even three chemicals is pretty pathetic. Poisoning someone in the arrivals hallway and watching them walk slowly all the way to medbay, have a chat with the CMO, then heal at their leisure is stupid. Not to mention the fact that they will be screaming "chemist rogue" the entire time. 

Now lets start on the fact that most of the poisons currently available suck dick to begin with. There are no strong poisons available without using the traitor TC purchase. They've been nerfed into the ground. Hence the skill gap where a good chemist uses multiple poisons to stack their... oh wait, you're removing that. Again, not a good PR. Chemistry  has been nerfed a metric fuckload of times in the last few months and it is in no way overpowered or in need of a nerf.

**Comment by Time-Green** [comment]
You're saying it's easily counterable and hard to make.
I can recall pretty easy you having a deathmix and ephedrine like 20 seconds into the round.

And easily counterable?
It's extremely easy to get the first hit. People don't immidiatly run away when they see a random chemist walk around. All it takes is the first shot, and they're completely lost with no chance of living. One shot, and you're muted and slowed down, then after 3 seconds they are dead. 

How is this fair? Are you just protecting your way of playing? These aren't rational thoughts, I can understand if you think it's to much and could find some sort of middleway. But all you're doing is protecting your instakills without any valid arguments, just for yourself.
You could argue I am doing the same, hell, maybe I am. But I am at the point that everytime I see Bob Blitzer playing, I stay far away and in insulated clothes. Any other player doesn't, and has literally 0 way to counter it.

**Comment by BOBsHERE** [comment]
you cant mute someone without mute toxin, which takes uranium and you will almost never have this because science IMMEDIATELY grabs it. The other option is perflorodecaline, which literally heals your target of the most common type of poison damage, oxygen loss. Again, your ignorance is showing. 

Ive made valid arguments. Not to mention we have to GET the syringe guns from the greedy medbay staff who are immediately suspicious if you ask for it, and belligerent if you run in and try to take one. Again, i know what im talking about because Ive played more chemistry then the next three contenders combined. 

But lets address your biggest gripe i guess, the fact that if i get the first hit you're most likely going to die. No shit. You already fucked up letting an antag get the first hit. You're dead. Hope you had suit sensors. That's how the game works. If i stun you, you are dead. Period. Maybe they clone you, maybe not. But you are dead. If you're security and you are trying to arrest the chemist without a hardsuit, you deserved to die for your lack of foresight. If you're some random job on the station and i get the first hit on you then why in the hell do you think you deserve to survive the situation?

**Comment by Time-Green** [comment]
That's your way of thinking. And I don't think that way, alot of people don't.
Salt raging isn't going to make things better. Please stop commenting. I'll wait for a senior coder or higher to work out the balance.

**Comment by Notamaniac** [comment]
At least when you tase someone, you have to follow up with cuffs/weapon, which gives people the chance (however small) to escape or be rescued.

I'm pretty much biased against chemistry, so I can't really put anymore input  than DEATH TO ONE SYRINGE DEATHMIXES

**Comment by Stealthkibbler** [comment]
@Time-Green I would not let pure-man or bob hold too much weight to this, they will complain against any chem changes or nerfs that disallow them to faceroll as an antag chemist.

I've seen rounds where antag chemists take on all of sec with the chem deathmixes and a syringe gun, frankly, it's overpowered that antags can just 1v1 all of sec with a single use syringe gun, not to mention the ability to mass produce ephedrine now so you're basically stun immune. Chemistry has the biggest powercreep on the entire station at the moment, with the ability to overcome any obstacle; there isn't any legit counter to dealing with antag chemist unless you powergame or metagame the shit out of them and taze search, labor camp or consistently arrest them for taking a step outside of chem. You just can't take that risk of letting a chemist anywhere near you, one syringe and you're dead with no way of saving yourself.

There's also the silent dart gun that traitors get, but whats the point when you can concoct a death cocktail that literally kills in seconds, the shit chem can make is worse than the old ling stings.

I also assume traitors will get access to the combat darts basically meaning traitors will still have access to the ability to steamroll people anyway at the cost of tc so I mean, these nerfs will only apply to nontraitor chemists anyway.

**Comment by Time-Green** [comment]
I talked about it with matsk and super, we agreed to allow 3 chemicals for the medical dart.

**Comment by ghost** [comment]
Close this. Pureman has raised all the necessary points. I am against this.

**Comment by ghost** [comment]
@Time-Green You of all people don't get to tell people to stop commenting.

You, who raises the shittiest points on every PR, don't get to tell someone raising valid criticisms to stop commenting.

The one thing i'm looking forward to is valid fucking criticism, and you get it, so don't disregard it.

Your balance is crap.

The mechanics are crap.

If you want to balance syringe guns make the syringes not penetrate armor clothing, so you need to use other clothes.

Suck it the fuck up. If a chem needs a nerf i'll nerf it. Syringe guns don't need to be changed.

**Comment by ShadowDeath6** [comment]
Syringe guns are immense fucking cancer, don't even deny it. 
I've seen more than a few times when someone auto-loses because WHOOPS you hit me with a single syringe filled with 2u of literally every poison ever and you just die because you can't counter that unless you have epinephrine AND charcoal AND antitoxin on hand, and you can mass produce them via R&D or if you really can't wait you just get 2 FOR FREE in med storage. 
Maybe have syringe guns transfer only 5u of shit into the person, it doesn't make sense that being shot in the arm with a syringe transfers more reagents in one hit than being injected with one by hand. This PR might not be the best way of fixing the dumb shit, but at least it's a step in the right direction .

and seriously, this isn't a "stun" syringe, this is a 20 toxin damage per tick syringe. "OH SHADOW IF YOU GET STUNNED THAT MEANS UR ALREADY DEAD >:^)^)^)^)^)"
wrong, because you can call for sec or someone can walk by to save you from getting your ass toolboxed or whatever, or if the guy invests in like half their TCs they can kill you before you say "halp gorg mellings killing me". Deathmixes are literally death in one shot, period. There is no possible way you can survive it unless you are immensely lucky and someone realizes that you're being poisoned to death, and if they don't realize, or you don't get help, then you're fucked. Hell, I could get a deathmix and a syringe gun, dress up as unknown, then shoot you in the head with it and just follow you until you drop dead, because you're guaranteed death and the only noise that happens is the pop of the syringe gun and your critted body hitting the floor 9 seconds later.

**Comment by ghost** [comment]
Wear a fuckin biosuit or something.

I don't deny that on yog where people can't dodge the slowest moving projectile in the game maybe they need a nerf.

Not this nerf.

This nerf just means they're STILL lethal and has no effect aside from making it slightly more complicated and doesn't affect the real issues.

You can either-

1. Make syringe guns less available/unavailable to normal crew.

Or 2. Nerf the chemicals.

This has no real effect AND it's spaghetti code. Bad PR.

**Comment by Time-Green** [comment]
Not allowing people to combine literally 10 chemicals to instantly kill someone is quite a nerf. Now they can still kill someone with it, but they will need to do more then one syringe. Or just make sure the target doesnt run off.

**Comment by Super3222** [comment]
As Shadow puts it, this is a step in the right direction.

Since I started playing chemistry has always been an OP department where you can brew you strongest concoctions like last whisper and kill someone in less than 5 seconds. Hell, during my first few weeks of fooling around in chemistry I got a note for abusing it to kill a hulk. And I literally shot them with one syringe before they pummeled me to death, then fell over as well.

Likewise, you should let traitors buy a box of darts that look like the normal ones but don't have a limit on the amount of chemicals it can hold. Maybe make it come with the dart pistol which Stealth noted is completely silent.

Also, as Adam said before, make armor block syringes.

**Comment by ghost** [comment]
They don't need more than one syringe. 5u CLF3 5u Lexorin 5u Beepsky Smash is a stun + they're on fire and burning + Suffocating.

Done.

**Comment by Time-Green** [comment]
Then I'll just set them to one chem. That was the original idea.

**Comment by ghost** [comment]
And ignore all the feedback complaining about that? Yeah, sure.

We don't need to make the station less lethal for nonantags and more lethal for antags if you give traitors X TC darts.

giving traitors buyable darts is dumb. The entire point of traitor is being able to complete your objs without being forced to rely on special snowflake gear from your uplink and instead using natural station deadliness.

Besides, you're nerfing the weakest gun in the game. No nerf on spraybottles or grenades which is how bob gets most of his kills.

Not to mention setting it to one chem STILL doesn't make it hard to kill people and you're just going down the nerf chain until you realize the problem is with chemistry and the fucking health system, NOT the syringe guns.

The CHEMICALS are what makes it overpowered. Our shitty health system is what makes it overpowered.

Rework those.

OR, make syringe guns, I dunno, LESS ACCESSIBLE? That's an option. Keep their current lethality but make them way less accessible.

**Comment by ShadowDeath6** [comment]
or just uh
make the syringes stuffed in syringeguns only transfer 5u rather than use darts

**Comment by ghost** [comment]
or make chemicals obey logic and make retarded chemicals like clf3 burn through syringes

**Comment by BOBsHERE** [comment]
So this has 28 comments and is still not flagged as controversial.

**Comment by Super3222** [comment]
> So this has 28 comments and is still not flagged as controversial.

Controversial is usually tagged on when a multitude of people show an open unanimous dislike for a PR which may result in the OP changing a few mechanics, redoing the PR, or outright closing it. Or it's tagged whenever someone (that's not me because I do the other thing) feels like they should be on there. Anyway, 28 comments ago you were the only one showing a dislike for it.

You should honestly take one of Adam's suggestions though, Time. One dart is still enough to kill someone. Just earlier, I saw a CMO get shot with 15u of CLF3 and get husked. Hell, if CLF3 is still buffed it should take 5u of it to kill someone or get them in a position where they're good as dead.

**Comment by ghost** [comment]
This is controversial. Lots of people dislike it. Only time green likes it.

Hell, Cruix even said he's not merging it.

**Comment by ghost** [comment]
this also doesn't affect dart shells, you moron

you've changed nothing

**Comment by ShadowDeath6** [comment]
More like ad-hominem el tablawy

**Comment by Stealthkibbler** [comment]
Nerf chem, make the powergamers cry, reserve death chems for actual antags who want to creatively use their mixes for taking down targets, they shouldn't be able to wipe out entire groups of people with a single syringe gun/dart gun in under a minute. By this I mean normal traitor, it's not like normal chemists can just make 100/100 u grenades that can leave brig in an eternal blaze or anything; atleast you can avoid said eternal damnation by leaving the affected area, get hit with 15units of phlog or clf3 and you may as well suicide and disconnect to save yourself the time of even attempting to survive. What's that normal syringe gun isn't STEAMROLLING all of sec for you enough? there's such a thing called a rapid-fire syringe gun, have fun with more than 50 units of phlog in your system.

You people are defending a prehistoric system that has not been re-balanced or reworked in fucking years. the chem powercreep is by far the most cancer I've seen in SS13, worse than genetics or stim viro.

@Time-Green Also make the sleepy darts use chloral, morphine takes almost a minute to kick in and by the time they drop they've probably already caved your skull in.

**Comment by ghost** [comment]
@ShadowDeath6 that was actually a clever one

**Comment by Cruix** [comment]
This only addresses one of many chemical delivery methods, and gives sec another toy to counter one of the very few things that counters them.

**Pull request closed without merging**
