### PR TITLE
changes medbay up a bit, opinions needed

### PR DESCRIPTION
**Pull request by Kmc2000**
People were suggesting making medbay larger.

### Intent of your Pull Request

What this does is make medbay a bit more "open plan", meaning that there are fewer partitions between rooms, it also increases the walking space in there.

Testing and feedback would be appreciated.

#### Changelog

:cl: Kmc2000
rscadd: Medbay has been revamped check it out.
/:cl:

### CODE REVIEW

**Comment by Chuggachar** [comment]
It looks bad and there isn't even less partitions really, you've basically made the room slightly bigger then moved everyone around for no reason and made it look ugly. You've also got a wall shower floating next to an O2 can and 3 fire alarms within like 5 tiles of each other.

**Comment by ShadowDeath6** [comment]
no thanks it just creates more space and moves stuff

**Comment by ShadowDeath6** [comment]
closes after 3 hours :thinking:

**Comment by Kmc2000** [comment]
We'll see what kayozz does , this was an idea.

**Pull request closed without merging**
