### PR TITLE
Added NTSL jobban

### PR DESCRIPTION
**Pull request by Cruix**

### CODE REVIEW

**Comment by Jc1469** [comment]
haha nice.  I mean, yeah, it works.  A lot better than just signal tech banning I guess.

**Comment by Jc1469** [comment]
So what sparked this?

**Comment by Time-Green** [comment]
can you not be a cunt? At least not to the guy merging our PRs

**Comment by Jc1469** [comment]
How is asking a relevant question being a cunt?

**Comment by Cruix** [comment]
Nothing in particular made me want to do this.

**Pull request merged**
