### PR TITLE
fixes a grammar issue with tables

### PR DESCRIPTION
**Pull request by ghost**
it's can't not can not
##### Changelog

:cl:
rscadd: Table grammar fixed.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
smh

**Comment by Super3222** [comment]
....

**Comment by matskuman5** [comment]
Best pull request in a long time

**Comment by monster860** [comment]
This is the most pointless thing ever
 Its like changing colour to color, they are both correct

**Comment by X-TheDark** [comment]
"Can't" is a contraction of "cannot" (or more rarely "can not") and all of those forms are equivalent to one another. In this case, it's not even a case of American/British English spelling differences.

EDIT : Added "i ded" label on behalf of English.

**Comment by ghost** [comment]
yes i know can't is a contraction of cannot or can not

but it's also ugly to look at otherwise

**Comment by ShadowDeath6** [comment]
I agree, can not is worse than cannot or can't

**Comment by X-TheDark** [comment]
¯\\\_(ツ)_/¯

**Pull request merged**
