### PR TITLE
qdel()'s all of those extra maps

### PR DESCRIPTION
**Pull request by Super3222**
I've been meaning to do this for awhile. We shouldn't be getting conflicts from maps that we never use, and most likely never will.

I did, however, leave ministation and metastation in. I might come back to remove ministation though, because metastation is the only other station that we were planning on using.

#### Changelog

:cl:
rscdel: Deletes asteriodstation, birdstation, dreamstation, and efficiencystation.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
Travis is going to throw such a fit.

**Comment by matskuman5** [comment]
Fuck yes!!!!!!

**Review by AshCorr — CHANGES_REQUESTED** [review]
You need to update the travis config to not compile the removed maps

https://github.com/yogstation13/yogstation/blob/master/.travis.yml

**Review by AshCorr — APPROVED** [review]

**Comment by ShadowDeath6** [comment]
remove metastation and we're golden

**Comment by Partheo** [comment]
Can this be a thing please

**Pull request closed without merging**
