### PR TITLE
[S] Fixes crashing

### PR DESCRIPTION
**Pull request by Time-Green**
Ports: https://github.com/FTL13/FTL13/pull/840 by @monster860
:cl: monster860
fix: fixes crashes
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Merge please

**Comment by monster860** [comment]
I see you decided to port my tgcoder-free implementation

**Comment by Time-Green** [comment]
We desperately needed this due to certain recent events

**Comment by ghost** [comment]
i told you make me admin so i can see whats doing it :^)

**Pull request merged**
