### PR TITLE
let's the det's suit contain police batons

### PR DESCRIPTION
**Pull request by Amelia0010**
:cl:
tweak: the detective's suits can now hold his baton!
/:cl:

the armour still can't hold the baton, which I suppose is the tradeoff for being armoured :/

### CODE REVIEW

**Comment by Jc1469** [comment]
the most fun part of being detective is losing your baton and shooting people for stealing it. this is a huge removal of fun both from the detective and others.

**Comment by Amelia0010** [comment]
You can still lose it though...

**Comment by Jc1469** [comment]
much less if you have somewhere to put it that isn't your backpack full of your masterful disguise pieces

**Comment by Amelia0010** [comment]
well, if you disguise yourself then you won't be wearing the suit, will you

**Comment by Jc1469** [comment]
yes but if I wear my disguise in the brig I'll get perma'd for having murdered the detective(this has happened) so I have to keep my disguise in my backpack and then people wont be able to disarm me in the brig and cause a shitstorm because of questionable bad balance decisions.

**Comment by ghost** [comment]
lets

not let's

**Pull request closed without merging**
