### PR TITLE
Freeminers

### PR DESCRIPTION
**Pull request by Cruix**
Some enterprising miners have found the metastation white ship and spent all their space-savings refurbishing it into an asteroid mining vessel.

freeminer

This brand-new relic of a ship comes fully equipped with:
* Two miners to don their suits, dig, and die because they forgot to turn on their internals
* An engineer with a build-your-own-ripley kit
* A captain who is supposed to stay on the ship but of course will always steal a suit and die in space, stranding everyone on the ship because only his ID can move it
* Lots of <I>EXCITING LORE</I> and a handy self-destruct device that no one will ever turn on just to grief
* Enough parts to build an ore redemption machine that no one will notice and instead run off to the station to steal theirs
* A large amount of booze for you to poison yourself with after you realize that you already cleared all of the asteroids and there is nothing left for you to do except try to find the great secret of the derelict that does not actually exist because no mapper has touched the derelict since the days when balance was a thing and loot was not overpowered

This PR is something like six months old at this point and has been testmerged several times.

:cl:
rscadd: The white ship will occasionally spawn as a mining ship.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
cru

the only good part of metastation

speaking of "free" and "miner", when are we bringing back miner drones?

**Comment by Time-Green** [comment]
Dont think mining drones would work all too well on lavaland. Multiple reasons.
Also. 👍

**Comment by Kmc2000** [comment]
😂 cruix I love the sarcasm

May as well merge, people were wondering wjere it went

**Comment by Super3222** [comment]
Decent content. 9/10

**Comment by LarissaMayrink** [comment]
FINALLY IT'S BACK. But, are you sure THIS TIME there are enough materials to build a ore redemption machine? because the last time it was needed to raid derelict for the materials

**Comment by Cruix** [comment]
Last time you did not read the paper telling you how to redeem the ore. Now all the parts are in a single crate right next to the machine frame.

**Comment by LarissaMayrink** [comment]
Cruix, it was missing a console screen, noone ever found one without the need to get on derelict.

**Comment by Cruix** [comment]
If you went to the derelict looking for a console screen, you probably did not read the paper.

**Comment by Iamgoofball** [comment]
this is pretty similar to dwarves honestly but minus the features

**Comment by Cruix** [comment]
If you want to add dwarves, add dwarves. This is for people who miss the mining asteroid.

**Comment by Lightning38088** [comment]
Wait you said 2 miners, a cap, and a engi. Whats the sleeper pod in the medbay area? a medic?

**Comment by ShadowDeath6** [comment]
Probably a real sleeper

**Comment by Cruix** [comment]
It's a normal sleeper for injecting people with chemicals

**Comment by Mrcreepssss** [comment]
yay! **starts making out with the asteroid like the weirdo he is**

**Pull request merged**
