### PR TITLE
Adds rune scimitar to necropolis drop table, with new sprites and sound

### PR DESCRIPTION
**Pull request by Tenryumi**
If they can add a meat hook to Lavaland that is a direct reference, I'd like to add my own direct-reference item! What this item lacks in new mechanics it makes up for in its distinct sound and sprite that somehow fits in surprisingly well as an icon.
# This is the Rune scimitar.

image
### Inhand sprites (with nude spessmens for reference:)

**Left hand:**

image 
image 
image 
image
## STATS:
- Damage type: **Brute**
- Damage per hit: <strike>**20**</strike>  **25** because 20 was a little too weak compared to other weapons on the drop table
- **Sharp**!
- You may be able to sell it for 30k
# REALLY IMPORTANT THING:
- I did not create the sprite nor the sound the sword uses. Both were [directly ripped from a game near and dear to my heart](https://youtu.be/JkR7zClEkAo).
### EDIT: However, I DID hand-draw the inhand sprites!

I think the only thing that may need changing on this item is the sprite, as its dark color palette might clash with the theme of bright colors most SS13 items have.
#### Changelog

:cl:
rscadd: A new sword from another world has been added to the possible loot from tendril chests.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
Can you replace the sad trombone (broken) implant with this?

**Comment by Tenryumi** [comment]
Sure. Doing so now.

**Comment by utahclock** [comment]
no in hand sprites... Fail.

**Comment by ShadowDeath6** [comment]
<strike>not to be a shitlord but the icon does not look very good, it's super generic and low quality.</strike> sprite is fine, just needs inhands

also needs inhands and maybe a meme reference in its attack verbs or something

**Comment by X-TheDark** [comment]
Did you even read the description on the weapon (the code)? It's actually exactly how a reference should be like and it's pretty good.

**Comment by ShadowDeath6** [comment]
yeah but I want more meme references while slicing someone to death

**Comment by Tenryumi** [comment]
I was concerned that the references would be a little too niche to be understood, but sure. I'll throw in some 2006 colloquialisms in there.

**Comment by ShadowDeath6** [comment]
gud :+1:

**Comment by Tenryumi** [comment]
I'll get to drawing those inhand sprites... @ShadowDeath6  @utahclock BLUH.

**Comment by Tenryumi** [comment]
I actually rather like how these inhand sprites turned out!

**Comment by ShadowDeath6** [comment]
ooga booga where da screenshots at

**Comment by Tenryumi** [comment]
Oopsies, right.

**Comment by Super3222** [comment]
I would say 25 damage is a little much for a one-handed non-heavy weapon.
But it is coming out of a necropolis crate. So :+1:

**Comment by Tenryumi** [comment]
@Super3222 I thought the same thing. then I remembered there's also a possible drop of a free 30-damage esword and space suit.
<strike>just be glad i didn't choose to add one of the godswords</strike>

**Comment by ShadowDeath6** [comment]
Make this a chap weapon :^)

**Comment by Tenryumi** [comment]
I mean... I could add in a Saradomin / Zamorak godsword so the chaplain can scream about **"HOW MUCH ZAMORAK / SARADOMIN (respectively) FUCKING SUCKS"** in the radio.

**Pull request merged**
