### PR TITLE
radbow port

### PR DESCRIPTION
**Pull request by ToGWtF**

### CODE REVIEW

**Comment by Bawhoppen** [comment]
suggestion: pr this as a seperate weapon on tg code, then just edit the uplink

**Comment by Bawhoppen** [comment]
or I could pr it for you if you'd like

**Comment by ToGWtF** [comment]
@Bawhoppen Not my code, the guy who made it is a butt who didn't wanna help us rebase

**Comment by Bawhoppen** [comment]
well I can sweettalk the maintainers if you want to get it pushed through despite lacking mergetokens

**Pull request merged**
