### PR TITLE
mulebots can no longer be pAI controlled

### PR DESCRIPTION
**Pull request by ghost**
pAI controlled stun murder robot no thank you

it's like an all access beepsky but with more murder

if something can't be weakened normally it jsut chain stuns constantly and they can't move

me no likey

it's literally the same reason beepsky isn't allowed to be pai controlled

#### Changelog

:cl:
rscadd: Changelog template, please edit me.
/:cl:

### CODE REVIEW

**Comment by MayhemSailor** [comment]
10/10 has been abused far too much recently.

**Comment by Zostroll** [comment]
Just make them unhackable to murder if they have a pai in them. I like having a  mulebot stead.

**Comment by ghost** [comment]
still stunning

**Comment by ghost** [comment]
also you killing me with a mulebot is the exact reaosn i made this PR suck my diiiiiiiiiiiiiiiiiiiiiiiiiick

**Comment by ShadowDeath6** [comment]
good

**Comment by drderp3635** [comment]
Oh god thank you, they nerfed it but it was still godawful strong

**Pull request merged**
