### PR TITLE
adds defines for abominations

### PR DESCRIPTION
**Pull request by ShadowDeath6**
bottom text

### CODE REVIEW

**Comment by Super3222** [comment]
@ShadowDeath6 You've got merge conflicts

**Comment by ShadowDeath6** [comment]
hrrrgh

**Comment by monster860** [comment]
How to fix this fuck:

```
git fetch yogstation13
git checkout master
git merge --ff-only yogstation13/master
git push
git checkout helpers
git merge master
```

At this point, edit the `is_helpers.dm` file so it looks correct

Then do
```
git commit
```
Then close whatever text editor it shows. If it shows you a text editor inside the console, you may want to locate a tutorial on exiting vim.

**Comment by ShadowDeath6** [comment]
I know how to fix merge conflicts, I'm just working on another project at the moment. I'll fix this soon.

**Comment by Super3222** [comment]
Goddamnit, now you're giving ME merge conflicts.

**Pull request merged**
