### PR TITLE
buffs syndie toolbox

### PR DESCRIPTION
**Pull request by ShadowDeath6**
it no longer is bad

:cl: ShadowDeath6
rscadd: Syndie toolbox fits in backpack
rscadd: The combat gloves found in the syndie toolbox are called black gloves but their desc is a tell to what they are
/:cl:

### CODE REVIEW

**Comment by AndySok** [comment]
yes

**Comment by BOBsHERE** [comment]
yes

**Comment by killerx09** [comment]
I wouldn't mind you increasing the force on the toolbox o be honest.

**Comment by Super3222** [comment]
Don't increase the force. Rest of the changes are good.

**Pull request merged**
