### PR TITLE
Adds juices to citrus fruits

### PR DESCRIPTION
**Pull request by ArgyleSweatshop**
It's always bugged me that these fruits don't contain their juices. Botanists can now make triple citrus, as a side effect.

### Intent of your Pull Request

Now you can get the benefit of juices from eating the fruit. Also, realism. . .potentially speeds up any attempts to make citrus fruits cause puckered fruits? Not much reason to explain. 

#### Changelog

:cl:
rscadd: Added lime juice to limes. 
rscadd: Added lemon juice to lemons.
rscadd: Added orange juice to oranges. 
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
You get the juice by juicing the fruit. Wich is dumb so
👍

**Comment by ShadowDeath6** [comment]
Afaik botanists could always make triple citrus

**Comment by GrayRachnid** [comment]
Yeah, 'juicing' the fruits instead of 'grinding' them always gave the juice.

**Comment by ghost** [comment]
Now they can make plants that come naturally equipped with triple citrus.

More to the point, botanists can now successfully create plants that contain corgium, spawning corgis on harvest.

EAch plant would contain corgium, which would immediately generate a corgi when harvested.

As yield for plants can be increased exponentially, leading to hundreds of plants harvested from one, this could lead to mass lag due to corgi spawn spam.

**Comment by ArgyleSweatshop** [comment]
1. Yes, juicing the fruits provides the juice, but eating a fruit should confer juice benefits.

2. Adam, you are completely wrong about that. Corgium requires several reagents still unobtainable in hydroponics- such as stable plasma, oil, welding fuel, and oxygen.

**Comment by ShadowDeath6** [comment]
I think tg made a triple citrus plant and hasn't had any problems like that

**Comment by Time-Green** [comment]
I can make fucking strange reagent and mutagen plants, I think corgium aint that bad.

**Comment by Super3222** [comment]
There's a random item in maintenance that can spawn an infinitely amount of corgis. Corgium is the least of our concerns.

**Comment by Super3222** [comment]
Also can you remove those questions inside of your changelog? They're not important.

**Comment by drderp3635** [comment]
Botany can already slaw shitons of mobs with biogen monkeyccubes and a fire extinguisher

**Pull request merged**
