### PR TITLE
Nerfs detective's revolver brute damage from 15 to 10

### PR DESCRIPTION
**Pull request by X-TheDark**
As requested by @GrayRachnid

### CODE REVIEW

**Comment by Zostroll** [comment]
The revolver is suppose to be op...
Edit: I realised you were nerfing the dets gun not the syndies gun. Go ignore my comment.

**Comment by X-TheDark** [comment]
Yeah, my bad for not clarifying that.

**Comment by FluffySurvivor** [comment]
The damage isn't the problem. It's the double form of CC in it (50 stamina and a stun). 

You should reduce the stamina to 25 so it takes more effort for a full stamina stun.

**Comment by X-TheDark** [comment]
Gray's concern was basically critting people in one clip (90 damage + bleed). I'd like more feedback about the stamina damage, if it is an issue.

**Comment by george99g** [comment]
I don't see a problem with the stamina damage. I'm also okay with the damage reduction.

**Comment by FluffySurvivor** [comment]
You can easily crit people with it because  one initial shot= no escaping

**Comment by Super3222** [comment]
There's a reason why this gun was given to a non-security investigator.

Stamina damage is the last thing that needs a nerf, because it separates the detective's gun from other lethal revolvers and gives it some actual purpose. It's stun isn't that long, in fact it lasts for a bit. The reason it does stamina damage is to make sure the guy you're shooting is down.

In Fluffy's eyes, apparently I need to shoot a guy trying to attack me with an esword 4 times in order to handcuff them (as the detective). ( (15 + 25) + (15 + 25) + (15 + 25) + (15 + 25) Do the math yourself, man ).

And guess what? With this nerf, I'd need an extra shot too.

Brilliant idea, so now I need 5/6 of my entire clip to stun a guy.

Obviously I don't agree with this. :-1:

At least you aren't trying to replace their gun with a stun revolver.

**Comment by X-TheDark** [comment]
Just for clarification sake, do you not agree with the brute damage nerf or Fluffy's suggestion of halving the stamina damage?

**Comment by Super3222** [comment]
I don't like how it's nerfing the Detective's revolver and, I especially don't agree with Fluffy's stamina suggestion.

Getting shot up with 6 bullets directly should leave you at a very critical state. All guns in this game are dangerous (aside from maybe 1 or 2 silly ones).

**Comment by Jc1469** [comment]
I was the one that originally brought up the detective's revolver being OP, seeing how often I play it.
That gun can end a wizard round, heck, end any antag, with 5 bullets.   If you even need to hit them with the 6th, the bleeding will have them in crit regardless.  Stamina and weakness don't need touching.  The goal is to make it less lethal, not make it so the detective actually needs to go get a fucking taser.

**Comment by ShadowDeath6** [comment]
I never liked weapons that stunned and did damage in the same shot, it just felt too easy, especially since the det's revolver fucks you over 3 ways (long stun, damage, and stamina crit), but this is a pretty decent way of handling it

**Comment by FluffySurvivor** [comment]
dets revolver = taser laser and disabler all in one

**Comment by Super3222** [comment]
:+1:

**Comment by darkwahn** [comment]
And here I was going to try to push for Det's gun not being a toy at all anymore.

**Pull request merged**
