### PR TITLE
Made the singularity attracted to mass.

### PR DESCRIPTION
**Pull request by Cruix**
The singularity is now attracted to objects and non-space turfs. Requested by Adam.
:cl:
experiment: the singularity is now attracted to the station and flies away into space far less often.
/:cl:

### CODE REVIEW

**Comment by Groudonmaster** [comment]
Why

**Comment by Groudonmaster** [comment]
Why

**Comment by ghost** [comment]
loose singularities 90% of the time eat solars and fuck off into space

now 'OH FUCK SING LOOSE' is a thing rather than a meme

**Comment by Time-Green** [comment]
This is great. And now we need tesla to follow ghosts.

**Comment by ShadowDeath6** [comment]
decrease the price on the singlo beacon please

**Comment by Groudonmaster** [comment]
What the fuck is wrong with you no. Someone close this PR all this is going to do is force a round to restart when some dumbass new engineer rolls and manages to start the engine without the field up.

**Comment by X-TheDark** [comment]
Just like the good old days, back when singularity's pull wasn't gimped.

**Comment by ShadowDeath6** [comment]
in all honesty this is probably a bad change since instead of at least having the chance of the singlo eating some of engi then fucking off if it's released, the entire station is literally a singlo beacon every single round and it will decimate literally everything since unlike the tesla it flat out destroys stuff it's attracted to.

**Comment by Groudonmaster** [comment]
I repeat. Fuck off with this pr

**Comment by Time-Green** [comment]
Let's make it attract to the clown then?

**Comment by Groudonmaster** [comment]
I can live with that

**Comment by Super3222** [comment]
@Cruix Any test results from this?

**Comment by Cruix** [comment]
Station was eaten multiple times.

**Comment by utahclock** [comment]
i like idea of it being attracted to clown

**Comment by ghost** [comment]
:+1: for clown

**Comment by Super3222** [comment]
you say "yeah attract it to the clown"
but in reality, I don't see that happening unless in process() somewhere there's a check for a guy w/ a clown occupation and, if the sing is too far away it'll start moving in their direction

**Comment by X-TheDark** [comment]
This seems reasonable enough to at least try.

**Pull request merged**
