### PR TITLE
Toxin Mixing Piping Optimization.

### PR DESCRIPTION
**Pull request by MayhemSailor**
#### Optimization changes for piping in Toxins Mixing.

The use of hidden piping and a jumbled set up lead to confusion for some new to the advanced sciences of bomb manufacture. This change optimizes the layout, and changes pipe types from hidden to visible to ensure there is minimal confusion when working with gaseous plasma.

Old on the left, new on the right. The lighting has been fixed since screencap.

##### Changelog

:cl:
rscadd: NT Engineering Division has had their pipefitters in to optimize toxin mixing for the lowest common denominator among the science staff.
/:cl:

### CODE REVIEW

**Comment by MayhemSailor** [comment]
From DM:

**Comment by AsV9** [comment]
Looks OK. Have you tested it works? I mean, there is no reason to suspect it shouldn't but pipes are weird and it's good practice.

Easy to make mistakes..

**Comment by MayhemSailor** [comment]
Yup, I tested it while I was grabbing the screencap, works like a charm, or at least as well as toxins mix normally works

**Comment by Time-Green** [comment]
Never had problems with this, but I can imagine doing so.

I like it.
Could you place something down to kinda decorate?

**Comment by Stealthkibbler** [comment]
The warning lines should coat all the way around the piping, it looks rather off with only one side having warninglines. You can rotate them by creating a new instance and editing the DIR variable, the DIR works from 1-10, some numbers in DIR will do nothing. Generally the even numbers will rotate warning lines properly, try 0, 2, 4, 6 and 8 to see if it rotates the lines to your desired direction.

Even though its designed around the intention that you're generally going to be working on the pipes in one direction, it just looks ugly to have the lines only curve around one side.

**Comment by MayhemSailor** [comment]
@Stealthkibbler the tiling has already been fixed see my latest comment before this.

@Time-Green while I haven't had many issues, I've dealt with enough tickets at this point I think the change is warranted. What would you suggest for decor?

**Comment by Alek2ander** [comment]
>ensure there is minimal confusion when working with gaseous plasma.

This is not the Nanotrasen way

**Pull request closed without merging**
