### PR TITLE
Event Blob is a pain.This should make it less so.

### PR DESCRIPTION
**Pull request by R3DGL4R3**
This'll make it less common.
:cl: R3DGL4R3
tweak: Changed the weight and timer to be a bit more balanced as event blob is basically a FUCKING round ender.
:cl:

### CODE REVIEW

**Comment by TheSadFox** [comment]
I doubt this will change anything considering the event seems to ignore all of its requirements (minute one blobs happening all the time).

**Comment by Kmc2000** [comment]
Remove blo- I mean great idea

**Comment by R3DGL4R3** [comment]
Well lets decide here and now.Should we just rip it clean out of the random event section till we figure out what the issue is?It really is a gamechanger.

**Comment by R3DGL4R3** [comment]
@oisin100

**Comment by ShadowDeath6** [comment]
blob is besto

**Comment by Super3222** [comment]
Red please make a changelog with this change.

For example:
`:cl: R3DGL4R3
tweak: blah blah blah
/:cl:`

**Comment by FluffySurvivor** [comment]
👎

**Comment by oisin100** [comment]
Alright, Im fine with the increased spawn time.

But, with the increased spawn time its no longer necessary to decrease the weight.

**Comment by R3DGL4R3** [comment]
Changes made Ois-senpai

**Comment by FluffySurvivor** [comment]
why did u yell in the changelog

**Comment by oisin100** [comment]
Fluffy, did you not realize that YELLING IS FUN!?

**Pull request merged**
