### PR TITLE
Ports HippieStation's Bloodsplattering

### PR DESCRIPTION
**Pull request by Super3222**
#### Intent of your Pull Request

It works.
https://github.com/HippieStationCode/HippieStation13/pull/1026

##### Changelog

:cl:
rscadd: We have Hippiestation's blood splattering effect. Credit to CarbonHell
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
whats the differences?

**Comment by Super3222** [comment]
When you hit someone with a tough weapon blood will splatter over the turfs behind that person. It will also result in other objects or structures getting bloody. It leaves blood stains on walls as well.

**Comment by matskuman5** [comment]
AWESOME

**Comment by Super3222** [comment]
⏳

**Pull request merged**
