### PR TITLE
Updates silver_sulfadiazine and stypic powder to not heal over time

### PR DESCRIPTION
**Pull request by ghost**
remake of my old pr that i closed and deleted for some reason???????????????????????????????????????
#### Changelog

:cl:
rscadd: Stypic Powder and Silver Sulfadine do not heal over time, but still heal on immediate application.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
good job

**Comment by Ephemeralis** [comment]
I like.

**Review by X-TheDark — APPROVED** [review]
I like this change.

**Comment by Cruix** [comment]
Let the record show this was up for seven days with no negative feedback.

**Pull request merged**
