### PR TITLE
Stops transfomation sting from transfering SE

### PR DESCRIPTION
**Pull request by AsV9**
### Intent of your Pull Request

The intent of the transformation sting was never to allow for you to load yourself up on a shitton of disablities, then transform-sting someone and instantly render them unable to fight back.

The intention of the sting was to cause confusion and chaos.

#### Changelog

:cl:  
tweak: Transformation stings will now no longer transfer SE DNA.  
/:cl:

### CODE REVIEW

**Comment by george99g** [comment]
Hi Hardy.

**Comment by ghost** [comment]
RIP disability sting. IIRC, this function was re-added intentionally.

I'd suggest that it still transfer POWERS, but not disabilities. So that you can turn everyone into superpowered hulks, but you can't zap them into blind deaf mute idiots.

**Comment by AsV9** [comment]
@AdamElTablawy 
image
idk this code hasn't been touched for two years, and that was a bugfix.

and yeah I could probably make it transfer powers only but that seems like a lot of overhead and probably requires atleast some hacky code.

**Comment by ShadowDeath6** [comment]
transformation sting's use is to make people paranoid, not as a weapon to cripple people before killing them

**Comment by ShadowDeath6** [comment]
another idea- make a genetic sting that only transfers powers/disabilities of someone you've absorbed and have it be balanced differently to this one

**Pull request merged**
