### PR TITLE
Makes the AI laws randomize at roundstart

### PR DESCRIPTION
**Pull request by Amelia0010**
"But nich, the config on github already says we have randomized laws" I hear you say, and you're entirely right. Which is why you need to edit this line: 
https://github.com/yogstation13/yogstation/blob/76e09bc18546053ec995ede9d14bb5a6f55ac4ec/config/game_options.txt#L257
to actually be 2. It's currently 1 in-game, because someone decided to edit the config without also editing the git.

image

#### Changelog

:cl:  
experimental: The AI now starts with a random lawset, choosing between Asimov, corporate, and station efficiency.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I think we've previously come to a consensus to not make paladin or robocop default, ESPECIALLY paladin. I would prefer that they stay not default. :-1:

**Comment by Amelia0010** [comment]
Okay, I removed the two laws which literally makes this PR do nothing, but I'd still like random laws, and I can't make a PR about that because council updates the config without also doing it on git 😕

**Comment by Partheo** [comment]
I think we've previously come to a consensus to make paladin and robocop default, ESPECIALLY paladin. I would prefer that they stay default. 👍

**Comment by ShadowDeath6** [comment]
I would rename the pr and have it say that it adds robocop and paladin then and contact the council to fix it

also the closing and reopening thing was a mobile problem my bad

**Comment by Amelia0010** [comment]
PR body and title fixed to represent what it's supposed to do 👍 

And I assume Ash'd change the config when she stumbles upon this and possibly merges it.

**Comment by ShadowDeath6** [comment]
:+1: 
I'm also not saying you can't have a pr adding them but I would make it after this is implemented in the config comsidering how controversial they were originally

**Comment by ghost** [comment]
I would like 3.5 paladin among defaults at least.

**Pull request closed without merging**
