### PR TITLE
Shadowlings can now enthrall implanted people

### PR DESCRIPTION
**Pull request by ghost**
but it takes longer (25 seconds to be exact)
:cl:
tweak: Shadowlings can now enthrall implanted people
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
it was removed for a reason.

the reason was they were too strong.

they steamroll regularly. 

implanting at least provides a counter.

**Comment by Jc1469** [comment]
b a l a n c e  
p o l i c e  
s a y  
f u c k   
n o :policeman: :-1:

**Comment by ghost** [comment]
i see that you have given everyone who dislikes your PR a negative vote rather than bothering to say why you disagree with them or why this PR is a good idea

in return, here is a dick 

8=======D

Go fuck yourself with it.

**Comment by ghost** [comment]
closed become adam is being adam

**Comment by ghost** [comment]
also your dick sure is small, adam

**Comment by ghost** [comment]
not what your mother said last night

**Comment by ghost** [comment]
An admin resorting to CoD squeaker jokes? SAD.

**Comment by ghost** [comment]
im laughing right now as adam rants in OOC

**Comment by ghost** [comment]
i'm not an admin

**Comment by ghost** [comment]
i thought you were the nerd who mass bans nerds

**Comment by Mrcreepssss** [comment]
eh if this is gonna get added it should take alot longer than this. perhaps as long as resisting outt cuffs? or longer, probably  longer.

**Comment by ghost** [comment]
So, 2 minutes?

**Comment by Mrcreepssss** [comment]
well if it's even longer and you're prevented from stunning/disarming them yourself you'd need external help to do it or they'll escape so basically you need someone to guard you.

**Comment by Jc1469** [comment]
reminder that this PR isn't even open.

**Comment by Mrcreepssss** [comment]
i know just like to share my thoughts.

**Pull request closed without merging**
