### PR TITLE
Fluff medicine mix description

### PR DESCRIPTION
**Pull request by ghost**
Fluffs up the chemistry mixing to make it look nice

i hope i didnt fuck it up

### CODE REVIEW

**Comment by Time-Green** [comment]
Sadly, there's a feature freeze.

**Comment by oisin100** [comment]
Good lord Adam. Did you even test this?

All text must be enclosed in quotation marks.

You did
`mix_message = The mixture rapidly turns into a gross, thick liquid.`
When it should be
`mix_message = "The mixture rapidly turns into a gross, thick liquid."`

**Comment by ghost** [comment]
FIXED

**Comment by ghost** [comment]
WHAT WHY DID IT FAIL

**Comment by ghost** [comment]
wait why was it closed @oisin100

**Comment by utahclock** [comment]
references to things not in game ie mango and bleach. also a few grammar errors. and BO should be body odor.

**Comment by ShadowDeath6** [comment]
> gross, cool purple

what a meme

you might want to mix up a lot of these messages to make them look slightly less dumb sounding, just read them aloud in your head or something, jesus adam

**Comment by Alek2ander** [comment]
This is directly taken from goon, isn't it?
:+1:

**Pull request merged**
