### PR TITLE
changes "dna extracted" objective to "lifeforms absorbed" objective

### PR DESCRIPTION
**Pull request by ShadowDeath6**
:cl: ShadowDeath6
tweak: Changelings now need to absorb lifeforms with the Absorb ability (or devour, if you're into that) in order to complete their "extract DNA" objective.
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
#2656 as a more boring and less murdery objective

**Comment by ShadowDeath6** [comment]
unless you're geneticist you're going to have to kill more people than in #2656

**Comment by Ratvar** [comment]
make monkeyhumans not count? Getting maxtime horrorform and objective cause you threw mutadone nade at 100 botany/R&D monkeys/ was geneticist is ehh

**Comment by AlpacaGoesCrazy** [comment]
Can you probably reduce number of required absorptions? Objective which requires murdering 5-7 people is pretty much murderboning considering there is more then one ling

**Comment by ShadowDeath6** [comment]
sure

**Comment by Slinky5890** [comment]
This will need to be something discussed with council before merging I feel. It totally changes the gamemode and, with the rules as they are right now, a ling could walk into medbay with an armblade, shield and armour and slaughter everyone in relation to their absorb objectives. I much prefer mcdonald's idea of having it be to absorb certain people instead

**Comment by ShadowDeath6** [comment]
unless there are only 2 people in medbay I don't think that will be an issue

also mac's pr is just an assasination objective

**Comment by ghost** [comment]
add to your description that it lowers required absorb count to 2-3

**Pull request closed without merging**
