### PR TITLE
Adds a bobross painting to the cap's office

### PR DESCRIPTION
**Pull request by Amelia0010**
image

Credit where credit is due: https://github.com/ParadiseSS13/Paradise/pull/7670

#### Changelog

:cl: Kluys
rscadd: Bob ross painting in the captains office called "calming painting".
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Discusting

**Comment by ToGWtF** [comment]
>Not hiding captains safe behind it

**Comment by Wilchenx** [comment]
looks awfull


stop this nich

**Comment by drderp3635** [comment]
it doesn't fit the style of ss13

**Comment by Zostroll** [comment]
That does not fit anything else we have in game at all. All five of the comments on this are negative maybe just close it.

**Comment by Amelia0010** [comment]
All comments are negative, yet there are only upvotes 😕

**Comment by matskuman5** [comment]
Council downvote

replace it with a space-related painting, like in Picard's office, and hide the safe behind it

**Comment by Time-Green** [comment]
Replace it with a sexy painting of the nuke disc

**Pull request closed without merging**
