### PR TITLE
Sentient simple animals no longer attack twice

### PR DESCRIPTION
**Pull request by Cruix**

### CODE REVIEW

**Comment by X-TheDark** [comment]
How in the world did you figure this one out?

**Comment by Cruix** [comment]
I'm the one who broke it with tactical animals.

**Comment by Ephemeralis** [comment]
Insidious. Good to know for future projects.

**Comment by ShadowDeath6** [comment]
Thank you father

Reminder that slaughter demons did 60 damage per hit because it hit twice

**Comment by ShadowDeath6** [comment]
please merge this ASAP, double attacks are omega cancer

**Pull request merged**
