### PR TITLE
[DNM] Ports /TG/ Lighting

### PR DESCRIPTION
**Pull request by oisin100**
Ports /TG/ Lighting
Ports Rotatium

Some things are broken right now such as observing and parallax, ill fix them soon.
Ill probably be using all the same coloured lights TG does, but if you want anything to have a coloured light then let me know.

Todo list

- [x] Port lighting
- [ ] Port lighting fixes
- [ ] Port ALL of the TG subsytem updates
- [ ] Fix the metric ton of bugs.

_PS: sorry cruix :(_

### CODE REVIEW

**Comment by Time-Green** [comment]
Please don't, oisin I really appreciate you trying to port it, but it's ugly as hell.

**Comment by Super3222** [comment]
If I remember correctly, /vg/ initially created this lighting system. /tg/ ported and modified it to fit their codebase.

**Comment by ShadowDeath6** [comment]
I think super was working on something lighting related? Not sure

Also this is buggy as hell and I dislike the way that it looks so it's a no from me :-1:

**Comment by oisin100** [comment]
If anyones wondering, this is what it looks like 

http://prntscr.com/elo3yk
http://prntscr.com/elo45b
http://prntscr.com/elo4om
http://prntscr.com/elo4zr
http://prntscr.com/elo5aq

And yes, the original system came from /TG/

**Comment by Time-Green** [comment]
I really, really dont like it. But we can do a test trial to see if people like it

**Comment by Super3222** [comment]
It's not THAT bad. I wouldn't mind having it, and I wouldn't mind _not_ having it. The ultimate decision would come from the community's reaction, I guess.

> I think super was working on something lighting related? Not sure

I was, but since Oisin was planning on going through with this I agreed to it. If this doesn't work out we can try tacolighting... and then make a meme food that looks like a taco, but after every bite changes color.

**Comment by Lightning38088** [comment]
I like it (maybe the few ones who do)

**Comment by ghost** [comment]
I love it too, and time green's opinion isn't worth much anyway

**Comment by matskuman5** [comment]
>implying adam's opinion is worth more

**Comment by ArgyleSweatshop** [comment]
This looks extremely ugly to me. Like, unbearably bad... light shouldn't look like that.

In a game where we have uniform square tiles that are viewed from above, that lighting just does not work.

**Comment by ShadowDeath6** [comment]
just looked at it again and I still think it looks awful, it looks like the shadowling smoke ability but everywhere there's a little bit of dark and since smoothing is so bad on it it just turns into a bunch of black splotches where maint meets a wall corner

**Comment by Kmc2000** [comment]
👍 

I really like this, but our sprites look too ugly for this to work, maybe port all of goonstation's sprites and then this?

**Comment by Mrcreepssss** [comment]
though i think it'd be kinda awesome it doesn't fit with the uniform squares of the game, and indeed the sprites would need reworks for this to look good, i say perhaps an inbetween if possible? also how would this work with darkvision and Slings?

**Comment by ghost** [comment]
@Mrcreepssss Go play on TGstation or VGstation.

It will look like that.

It looks terrible because Oisin has SS13 shittily rendered-it's actually a lot nicer looking than it seems.

That applies to most of the naysayers, including @Time-Green and @ArgyleSweatshop 

It works perfectly fine for a game where we have uniform square tiles that are viewed from above. Oisin just has it shittily rendered. Again, go take a look at VG or TG to see what it actually looks like, which is amazing.

Additionally, colored lights, which look very nice.

As for shadowlings, it's the same as usual. No change. Why would you think there would be one? A tile that's light in our system would be light in this one, and a tile that's completely black, which is the only dark shadowlings can tolerate, would be the same otherwise. 

It won't corrode into horrible ugly blobs at the corners, and if it does that's just because of a bad port rather than anything else, which can be fixed. Again, you're looking at oisin screenshots and saying 'bad', when the reality is his rendering of everything is piss-awful.

Darkvision also works the same. I still don't get what your issue with it is.

**Comment by Time-Green** [comment]
I played /tg/ and the light looks ugly aswell

**Comment by ShadowDeath6** [comment]
Even on tg code it looks splotchy and ugly near corners though unless a very recent fix happened

**Comment by Time-Green** [comment]
Oisin, could you keep the coloring but remove the smoothing?
The coloring is great, just the smoothing of lighting is bad, wich you cant really do much about.

**Comment by oisin100** [comment]
Havent had the time to finish this, I might re-open this again later.

**Comment by Time-Green** [comment]
I found it why it's so ugly
You can fix this by going in the upper lift corner
icons > scaling > and set to point sampling
That fixes it, and makes it look beautiful

ashleigh pls we need this im sorry

**Pull request closed without merging**
