### PR TITLE
gives ling mimic voice by default

### PR DESCRIPTION
**Pull request by ghost**
wait so why the fuck can't lings mimic voices by default

here now they can thanks.
#### Changelog

:cl:
rscadd: Changelings have the ability to mimic voices by default.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Set chemical regen slowdown to 1.5

**Comment by vladlds** [comment]
why don't they have arm blade by default

give it some chemical_cost to activate at least

**Comment by ShadowDeath6** [comment]
https://github.com/AdamElTablawy/yogstation-1/blob/aa1cde6b1e406b08047b3a1844505be924837c4a/code/game/gamemodes/changeling/powers/mimic_voice.dm#L24

set that to 1 rather than .5

**Comment by ghost** [comment]
@ShadowDeath6 Why? No. 

@vladlds Why? The original mimic voice didn't have one.

**Comment by ShadowDeath6** [comment]
So it drains chemicals instead of slowing regen

**Comment by ghost** [comment]
why

**Comment by ShadowDeath6** [comment]
because giving it 4free and 4infinity time is dumb, investing DNA into it at least made it something you could use infinitely

**Comment by Super3222** [comment]
Shadow's right. Buff the cooldown, Adam. This has been up for two weeks already @AdamElTablawy

**Comment by Cruix** [comment]
It does not have a cooldown, you can use it however much you want with no restrictions except that it slightly lowers you chem regen rate while in use.

**Comment by ShadowDeath6** [comment]
@Cruix I'm asking him to make it actually drain so you can't permanently have it up, investing DNA made that irrelevant but if they have it regardless then it needs to have some sort of drawback to being used continuously

**Comment by Super3222** [comment]
On second thought it doesn't really matter. The outcome of using it continuously will get your ass tracked by the AI.

@Cruix I'd suggest merging this, and we'll see how it goes from there

**Comment by ShadowDeath6** [comment]
> get your ass tracked by the AI

I think mimic voice can't be tracked

**Comment by Cruix** [comment]
Mimic voice doesn't affect AI tracking, you would need to buy digital camo as well. And no one buys digital camo.

**Comment by Super3222** [comment]
Let's merge this

**Comment by ShadowDeath6** [comment]
@Cruix how did the testmerge go? can this be merged?

**Pull request merged**
