### PR TITLE
[s]Bugfix #24

### PR DESCRIPTION
**Pull request by utahclock**
Bugfix #24 :)

### CODE REVIEW

**Comment by AsV9** [comment]
totallyinconspicuoustitle

**Comment by Cruix** [comment]
Thank god that's fixed it's been around forever

**Comment by utahclock** [comment]
Dont merge yet i need to fix a couple things with floors.

**Comment by Time-Green** [comment]
What even is this? Did you delete the whole map?

**Comment by utahclock** [comment]
Things are fixed

**Comment by Super3222** [comment]
This needs to be PR'd to the special branch or turned around, and added implemented into the code without deleting the old map. Take the latter, and you'll need to edit which map zlevel 1 should generate. I'll show you where that can be arranged.

**Pull request closed without merging**
