### PR TITLE
OOC tags

### PR DESCRIPTION
**Pull request by Super3222**
For anyone on the staff team.
Dictates people's ranks from all the way at the Council to Retmins.

For instance, if your rank is Council than your ooc tag will be [Council].

If you're a moderator, your ooc tag will be [Moderator].

I commented out the coder ranks because soon we won't even have those.

### CODE REVIEW

**Comment by Super3222** [comment]
Currently there's a check for donators that's commented out because the donator system was not merged yet.

**Comment by FluffySurvivor** [comment]
> I commented out the coder ranks because soon we won't even have those.

;_;

**Comment by Time-Green** [comment]
Now I can't call my self an administrator anymore ;_;

**Comment by oisin100** [comment]
Less Memes please, Your missing half a dozen ranks.

Im not standing for Coder ranks being removed any time soon anyway.

**Comment by Super3222** [comment]
I double checked and it seems all the ranks are there.

**Comment by oisin100** [comment]
> I double checked and it seems all the ranks are there.

Sorry, I shouldn't be reviewing code at 2 o clock in the morning...

**Comment by Super3222** [comment]
I'm going to check for merge conflicts (if that's what is halting this PR from being merged).

EDIT // Pushed updates.

**Pull request merged**
