### PR TITLE
Adds a paper to the morgue to stop people from sending critted people to the gibber

### PR DESCRIPTION
**Pull request by matskuman5**
Been seeing this too much lately. IIRC we had this before but it was lost in the /tg/ rebase

:cl:
rscadd: A guide has been added to the morgue on how what the different lights mean. This will hopefully decrease the number of critted people being sent to the gibber.
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
Even better, make examining the tray tell you what the light means

**Comment by ShadowDeath6** [comment]
hugbox! :angry:

**Comment by Cruix** [comment]
Also, red lights are not always unclonable, it just means that the player is not currently in their dead body.

**Comment by ShadowDeath6** [comment]
@matskuman5 

papi

**Comment by matskuman5** [comment]
Ah fuck... uh...

What do I do to fix the merge conflict?

**Comment by Cruix** [comment]
With something this small it's probably best to just remake the PR

**Pull request closed without merging**
