### PR TITLE
adds warden to the whitelist

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Comes from this thread https://forums.yogstation.net/index.php?threads/add-jobs-to-ultra-whitelist.15017/ and Oak's strong desire for this to be a thing.

#### Changelog

:cl:  
tweak: wardens are now also whitelisted
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
ah yes, a role of vital importance.

**Comment by ActualRory** [comment]
A solid addition to the whitelist.

**Comment by drderp3635** [comment]
Add clown/mime to whitelist when?
They are the two most vital members of the station and require absolute competence(mime) or absolute incompotence(clown) to function correctly.

**Comment by Amelia0010** [comment]
I considered adding a seperate whitelist, only functioning for librarian. There is of course only one person who's competent enough to be on said whitelist

**Comment by Ratvar** [comment]
Librarian whitelist is the only one you need. Heads and AI don't need any.

**Pull request merged**
