### PR TITLE
ports /tg/ allowing you to explode drones

### PR DESCRIPTION
**Pull request by ghost**
everyone hates griefer drones so now you can blow them up with the robotics console like the little shits they are

tbh if it keeps getting worse i'll just add them to pdas too so everyone can explode drones
#### Changelog

:cl:
rscadd: You can blow up drones from the robotics control console now.
/:cl:

### CODE REVIEW

**Comment by Tenryumi** [comment]
I'm okay with this.

**Comment by Time-Green** [comment]
make them maxcap for the lulz

**Comment by ghost** [comment]
Can you fuck off, Time-Green?

**Comment by ShadowDeath6** [comment]
dislike this change, now having murderboner antags removes people trying to actually help the round as drones

**Comment by Super3222** [comment]
this is needed. given their peculiar mobility compared to humans, being able to be printed at the start of the round, and how they can always fly under doors it's only fair if they're on the same drawing board as borgs in terms of weaknesses

**Comment by ShadowDeath6** [comment]
how about we remove drone dispenser spam instead

**Comment by Kmc2000** [comment]
:+1:

**Pull request merged**
