### PR TITLE
removes eating organs

### PR DESCRIPTION
**Pull request by ShadowDeath6**
I saw an issue on hippie about this and I felt prompted to do it here because why not

this is made with the online editor and I'm going to be gone for five days so I can't compile until then anyway

### CODE REVIEW

**Comment by LarissaMayrink** [comment]
Huh, but why?

**Comment by ShadowDeath6** [comment]
if you take one bite of an organ accidentally it renders it completely useless

also encourages deepfry / chef recipes for what it's worth

**Comment by LarissaMayrink** [comment]
But that makes sense, if you bite a organ it won't work. Also Deep frying doesn't make a item edible if it wasn't edible before being deep fried, not on yog, so, you can't just eat a deep fried id, the id will drop at your feet and thats all. The same goes for a non edible organ, it would just drop at your feet like everything else.

Also, you mean this issue?
https://github.com/HippieStation/HippieStation/issues/2449

**Comment by ghost** [comment]
then fix the issue somehow else, don't remove edibleness. Lower the bitesize for example

**Comment by Kmc2000** [comment]
Delet this

**Pull request closed without merging**
