### PR TITLE
adds webhook messages for last admin leaving, de-adminning, and no admins at roundstart

### PR DESCRIPTION
**Pull request by Amelia0010**
This currently doesn't do anything, as yogbot hasn't been set up to do this, but i'll do that as soon as this is merged

### CODE REVIEW

**Comment by Alexandria404** [comment]
I don´t speak coder, please translate.

**Comment by Amelia0010** [comment]
wen admen leaf srvr, srvr sent msg bot.

bot no do thing yet, but me mak dat suun

**Comment by Alexandria404** [comment]
And it alarms admin chat then I assume? Nice.

**Comment by Amelia0010** [comment]
nut yet, dat part is in yogbutt. butt wen dis b merge, i mak yogbutt bit.

**Pull request merged**
