### PR TITLE
Ninja nerf

### PR DESCRIPTION
**Pull request by Time-Green**
Ninjas now cant attack while in stealth.
:cl:
tweak: Ninjas cant attack while stealthed
/:cl:
PR atomized due to popular demand by literally only adam

### CODE REVIEW

**Comment by Kmc2000** [comment]
Eh, they're super rare and designed to be OP and fun for whoever is playing them, I don't think they need balance to be frank.

**Comment by Jc1469** [comment]
>ninja can't murderbone
>ninja can't kill while stealth
>everyone is now valid because it can only kill blatantly.

No.  Good job undermining the tribunal decision though.

**Comment by Time-Green** [comment]
It's called stealth for a reason, not i-am-invisible-and-can-now-go-kill-the-whole-escape-shuttle-without-consequences-stealth

**Comment by Time-Green** [comment]
They still got their insta KO sword, stun gloves, teleport, invisibility, hyper speed and a near infinite amount of shurikens

**Comment by ShadowDeath6** [comment]
don't they turn visible when they attack someone

**Comment by Notamaniac** [comment]
Reading code I can't see anything about cloak being disabled then they attack.

Personally yeah, getting murdered by an invisible ninja feels really cheap and doesn't really take much effort from the end user apart from "keep moving and don't let my cell run out". And on the receiving end you either have to hope you have a gun and enough ammo left to blindfire or pray that the ninja runs out of power.

**Comment by Chuggachar** [comment]
Losing invisibility on attack would be nicer than just entirely disabling the attack

**Comment by Time-Green** [comment]
You'd rather have me do a check for every time someone attacks, to check if they are wearing a ninja suit and are in stealth?

**Comment by Ratvar** [comment]
Moe clunky code for better gameplay? Hell yeah.

**Comment by Super3222** [comment]
I agree with Adam on the last PR. Making the ninja flicker, long enough to reveal his location, is a step in the right direction.

**Comment by Kmc2000** [comment]
@Time-Green  Do the check on the afterattack of the ninja sword instead? you wouldnt need to have every attack checked for ninjasuits?

**Comment by Cruix** [comment]
It would be almost as bad with a toolbox, and worse with a stunbaton.

**Comment by X-TheDark** [comment]
I'm not going to close this or anything, but please don't make branches on main yogstation repo, that's what your forks are for.

**Comment by Time-Green** [comment]
I'll close this when DCS gets merged, then I CAN have it make you visible on attack without shitcoding

**Pull request closed without merging**
