### PR TITLE
The RSF now prints fake cash instead of real cash.

### PR DESCRIPTION
**Pull request by Super3222**
#232
#### Super3222

:cl:
tweak: Nanotrasen News Reporter, Timato Vegetable, is on the scene where the QM is being publicly arrested for commanding a service borg to print him an infinite amount of money to profit from cargo exports. Space Cash printed from service borgs has been officially legalized, and precautions have been taken place.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Please make a changelog about service borgs being arrested around the country for making fake money.

**Comment by Super3222** [comment]
Done

**Comment by MacHac** [comment]
it's a feature

who the hell wants to play serviceborg anyway?  even with the moneyprinter, unless cargo supervises robotics, they hardly ever get them.

**Comment by Super3222** [comment]
You obviously play service borg to forcefeed humans drinking beverages until they're too drunk to give you a proper command

**Comment by MacHac** [comment]
Look at it this way.
RSF prints 10 credit bills.  Those are nearly worthless.  On a standard (high cap) cell, you need to recharge twice before you can print 1000 credits.  That's what, 1000 points?  It's not that fast.

**Pull request merged**
