### PR TITLE
blob stuff 

### PR DESCRIPTION
**Pull request by ShadowDeath6**
ports all the changes we had to blob chemicals
also makes flammable goo ignite on any burn damage
also makes electromagnetic web make pulses on attacking instead of using emp_act
also, blob splitting is back

keep in mind that I couldn't feasibly check the blob splitting since my computer has a really hard time putting two keys on a local server

@X-TheDark since you dealt with blob splitting and the like

:cl: ShadowDeath6
rscadd: Re-added blob splitting
/:cl:

### CODE REVIEW

**Comment by FluffySurvivor** [comment]
sentient blobbernauts is good, keep it

and nerf the new blobchem pls

**Comment by GrayRachnid** [comment]
Yeah, don't remove sentient blobbernauts

**Comment by ShadowDeath6** [comment]
new blobchem is actually weaker than the other ones
also sentient blobbernauts are stupidly powerful and you can spam them with no drawback

**Comment by GrayRachnid** [comment]
There is drawback, you can only have 1 blobbernaught per factory, and you can only have one factory per node(Or within 7 tiles of another factory). 
They're also not that powerful, their health stinks and if they leave the blob area they lose health a lot faster when taking damage.

**Comment by ShadowDeath6** [comment]
Dunno, sentient blobbernauts AND more overminds might be a tad powerful, I'll wait for more feedback before changing anything.
cue requires feedback tag xddd

**Comment by Time-Green** [comment]
You can log in on guest if you need multiple keys.

**Comment by ShadowDeath6** [comment]
> you can log in on guest if you need multiple keys
> 
> > > "keep in mind that I couldn't feasibly check the blob splitting since my computer has a really hard time putting two keys on a local server"

it's more spec issues, my computer shits out on me

**Pull request merged**
