### PR TITLE
Adds fake Marisa hat to donor hats

### PR DESCRIPTION
**Pull request by Tenryumi**
This is probably the most useless PR I will ever make.
But I just LOVE that hat, and I think other donors would too.

:cl:
rscadd: The fake Marisa hat has been added to the list of fancy donor hats.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
good hat

**Comment by Tenryumi** [comment]
TRAVIS NO!!!

**Comment by Tenryumi** [comment]
... @X-TheDark oops... Thank you though!

**Comment by X-TheDark** [comment]
You can thank Adam, I'm pretty used to fixing minor mistakes like this by now.

**Comment by Zostroll** [comment]
Pictures?

**Pull request merged**
