### PR TITLE
stops erts from being little shits

### PR DESCRIPTION
**Pull request by Kmc2000**
### Intent of your Pull Request

Stops ERTs from running out of the ready room and getting access to OP gear like the freedom station (OP gun vendor) and the marauder that's just laying around.

#### Changelog

:cl: Kmc2000 with the fun police
rscadd: Stopped ERTs being able to leave their ready room to access centcom and get OP gear
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
just make the door start with a blast door, KMC

**Comment by Kmc2000** [comment]
OK that's a better idea

**Comment by LarissaMayrink** [comment]
Huh, the ERT is a admin triggered only event, so, isn't it just as easy to say /hey, don't steal from the freedom station or the marauder/

**Comment by Kmc2000** [comment]
@LarissaMayrink  No, it really isn't

Players are shitheads

**Comment by Kmc2000** [comment]
There is no reason to not merge this, you can open it manually if you want them to get OP gyrojets, marauders, and reticences.

**Comment by LarissaMayrink** [comment]
honestly i'm mostly saying this beause if this gets speed merged one day before cruix is back it will break half the existing prs one day before the next mergewave

**Comment by Cruix** [comment]
untitled
This is my reason not to merge this

**Comment by Cruix** [comment]
Leave a comment

**Comment by ghost** [comment]
use mapmerge

**Pull request closed without merging**
