### PR TITLE
Made the syndicate base ruins inescapable

### PR DESCRIPTION
**Pull request by Cruix**
Removed mindslave implants from the xeno facility
Re-added the xeno hive ruin

### CODE REVIEW

**Comment by Stealthkibbler** [comment]
Dude theres a poll up for this and why remove the mindslave implants?

**Comment by ghost** [comment]
Boo. No fair.

Xenos can't mMAKE it to the station without admin intervention/miners fucking up and some spice is good for rounds.

It doesn't often fuck things up either, round wise. And the rare xeno rounds that do happen, well, they happen.

And removing the mindslave implants also shits things up further.

Altogether, i'm against this without a coherent reason.

**Comment by Time-Green** [comment]
CHANGELOGS REEEEEEEEEE

**Comment by Cruix** [comment]
https://forums.yogstation.net/index.php?threads/syndicate-xenoscientists-report-by-xbobsherex.12553/
That is enough reason for me.

**Comment by Alek2ander** [comment]
Give xeno ruins weapons a xeno facility firing pin that doesn't work outside.
Maybe give them a set of normal mining weapons so if they're bored they can go out for the true lavaland experience.
If you want to lock it off completely just put it on z2, no need to take a chunk of lavaland for an isolated area.

**Comment by Stealthkibbler** [comment]
@Cruix It happened once and the player responsible was told not to do it again. The xenos actually very rarely even get to mining, let alone escape the facility. This was just a single person grabbing all the weapons, leaving the base and rushing to the mining base. That's all it was.

Do you want to re-texture all the tiles to HUGBOX while you're at it Cruix?

**Comment by BOBsHERE** [comment]
Nooo, don't make it inescapable and dont remove mindslave. Its a good ruin with good potential for spicing up a round. The round in question was only terrible because of late night lack of admins. Xeno rounds are fun. And having the syndicate occasionally lead an army of xeno's against the crew sounds goddamn awesome.

**Comment by Cruix** [comment]
The base was always meant to be a tutorial ruin and not have any impact on the rest of the round. If I had thought otherwise, this would not have been merged in the first place, for the same reason as the space mercenaries.

This game is primarily about paranoid people working on a space station, not about lavaland, and certainly not about scientists that start with more guns than there are in the armory and AB-USE room combined overrunning the station with their mindslaved xenomorph pets and then getting banned for three days.

**Comment by ShadowDeath6** [comment]
mindslave allows for some semblance of rp, but using it to get out of the ruin and raid the station is godawful and should not be encouraged. should never have added doors that can be corroded or hacked in the first place.

**Comment by Super3222** [comment]
It happens every week, guys, and it's always a shitshow.
The first time it happened I wanted to remove those doors, but Adam practically told me that only adminbuse could get them to the station.

I come on again today this morning to find out that """""a new player""""" managed to send an entire horde of aliens onto the station, hauling the round for 30~ minutes, with 0 admins on to take care of it without the shuttle being called.

Cruix already gives out all the reasons for why it should be removed.

And I'm going to say what I said last time.
Even if getting to the station is a rare chance, letting them roam around lavaland is just as bad.
You're effectively fucking over innocent miners who have to deal with 10+ leaping antagonists who can stomp them all in 10 seconds.
Oblivious miners with 0 effective equipment to properly deal with them, and given the amount of monkies / humans in that ruin you're making it impossible to counter. 

Xenomorphs aren't fair to fight. Every other ghost roles so far has been fair to fight for miners. For every challenge on lavaland, I've seen at least a miner or two climb over it. I have yet to see a single miner defeat a legion of xenomorphs with a giant queen screaming in the background, and a group of syndicates with automatic firearms and laserguns.

The ruin is great, it's actually one of the most well mapped out ruins we have, but to have ghost roles that's at this point built up to become strong enough to _very easily_ massacre everyone on lavaland and the station completely fucking over the round is too much. What sinks the nail into the coffin is the fact that miners can't do anything against them until it's already too late.

**Comment by Super3222** [comment]
It happens every week, guys, and it's always a shitshow.
The first time it happened I wanted to remove those doors, but Adam practically told me that only adminbuse could get them to the station.

I come on again today this morning to find out that """""a new player""""" managed to send an entire horde of aliens to the station, hauling the round for 30~ minutes, with 0 admins on to take care of it without the shuttle being called.

Cruix already gives out all the reasons for why it should be removed.

And I'm going to say what I said last time.
Even if getting to the station is a rare chance, letting them roam around lavaland is just as bad.
You're effectively fucking over innocent miners who have to deal with 10+ leaping antagonists who can stomp them all in 10 seconds.
These are oblivious miners with 0 effective equipment to properly deal with them, and given the amount of monkies / humans in that ruin you're making it impossible to counter. 

Fighting xenomorphs as a miner isn't fair. Every other ghost roles so far has been fair to fight for miners. For every challenge on lavaland, I've seen at least a miner or two climb over it. I have yet to see a single miner (or even a team of) defeat a legion of xenomorphs with a giant queen screaming in the background, and a group of syndicates with automatic firearms and laserguns.

The ruin is great, it's actually one of the most well mapped out ruins we have, but to have ghost roles that's at this point built up to become strong enough to _very easily_ massacre everyone on lavaland and the station completely fucking over the round is too much. What sinks the nail into the coffin is the fact that miners can't do anything against them until it's already too late.

Ruins are generally made for the miners entertainment from challenges or scenery/loot or both (yes i know the syndicate viro is still out there). The xenomorph facility isn't entertaining to the common miner. You get close to it, you get killed in two shots.  Otherwise, out comes a horde of xenomorphs to pick off the under equipped miners one-by-one.

**Comment by Stealthkibbler** [comment]
@Super3222 OOOOOOH POOR INNOCENT MINERS WHO COMMIT GENOCIDE ALMOST EVERY ROUND, OOOOH POOR POOR MINERS WHO CAN 3 HIT ANY HUMANOID IN 3 KA SHOTS. OOOOOOOOOWEEEEEEEEEEEEEEEEEEEEEE

**Comment by Super3222** [comment]
@Stealthkibbler Come on man. I've never seen a miner with a KA survive being clawed to death or spamdisarmed by 5 pouncing hunters unless they run into lava or a chasm. Plus everything else I stated.

**Comment by ShadowDeath6** [comment]
Good luck killing 5 aliens who are faster and onehit gg you while not dying to everything else in lavaland

Don't even try and defend this, stealth

**Comment by Stealthkibbler** [comment]
I'm defending it because a lot of players actually enjoy the escape factor of the ruin and the ability to go out into the wastes. It's why I put up a poll, because it would be nice to know how many people are against or for its removal.

**Comment by Stealthkibbler** [comment]
http://puu.sh/tnLoZ/fed505c9d2.png

lmao 'remove the exit'

**Comment by Super3222** [comment]
@Stealthkibbler You're talking about the players who get to BE the killer antagonist, not the players who get steamrolled for absolutely no reason.

**Comment by ShadowDeath6** [comment]
tbf we should really remove all aspects of anything from lavaland getting to the station without a miner doing it for them

**Comment by Stealthkibbler** [comment]
@Super3222 And? People who get steamrolled by walkers bitch and complain but you've never given a shit about their opinions and walkers can fuck the station about as hard as xenos can.

**Comment by Super3222** [comment]
Xenomorphs are 10x stronger than ashwalkers. There's no denial on that. Xenomorphs also can take people BACK ALIVE without needing to kill them.

Ashwalkers also got nerfed after their ash resistance was removed by Adam, and I personally nerfed some of their armor values. (tbh they need some better features ATM)

I really don't understand how you think it's fair that miners alone have to deal with the outpour of 10+ xenomorphs, and on TOP of that 3-5 syndicate scientists with insanely powerful guns. Do you honestly think that they could win? Would they even be able to counter it before they get released? They won't.  At least with ashwalkers they could run away with them. Xenomorphs are some of the fastest antagonists ever, in no comparison to ashwalkers. Lasers and flamethrowers are the hard counters xenomorphs, nothing accessible to a miner with a KA. And how are they suppose to juke the syndicates with nuke op grade equipment+? Should we really be telling miners to go fuck themselves?

**Comment by Stealthkibbler** [comment]
It's only the hunters that are that fast and more often than not you can easily avoid them by just standing near lava since they can jump into it. Also the one thing that kills walkers kills xenos just as easily, combat shotguns, which cargo can and will order en masse if they get wind of walkers or xenos.

**Comment by Super3222** [comment]
It's still getting removed because the threat of xenomorphs and nukeops+ is way too overwhelming. If it wasn't than this PR wouldn't have been created

**Comment by ShadowDeath6** [comment]
all the aliens go fast, the hunters have speed -2 or something rather than -1.

>combat shotguns being a counter to xenos

hahahahahahahahahaahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha
I hope you're joking

**Comment by ShadowDeath6** [comment]
also remember that this was expressly said to be a testing and tutorial ruin in the original comment that added them, so no bs saying "oh but it was intended to happen because round lol" 
>add: The Syndicate now have a Xenomorph testing facility on Lavaland, the purpose of this is to tutor players on the dangers of xenos while also giving players the chance to play as the xenos and learn how they work. This should hopefully make more players accustomed to xeno rounds when they occur.

**Comment by Stealthkibbler** [comment]
@ShadowDeath6 Nothing but happy accidents

players like it, less than a handful of people are openly expressing their dislikes about it and for the record combat shotguns are extremely overpowered which is why keek orders a fucking shitload of them for cargo almost every round 

@Super3222 Actually this pr was created because one person decided to bumrush the station with all the weapons and a bunch of xenos and so because of that one person a concept and intended feature of the ruin that other players find fun and enjoying is now being completely removed.

Also FYI the purpose of the ruin was somewhat changed when the exit was added, and you autists only have yourselves to blame for your ignorance of not questioning or even attempting to discuss how or why that should or shouldn't have been added. There was literally zero discussion for that change and so it went in and now when one or two people go _"WAAAAAAAAAAAAAAAAH XENOS WAAAAAAAAAAAAAAH"_ you're all suddenly like _"oh wow a type of antag that literally happens once a year because of lazy staff is now happening on a weekly frequent basis, we can't have FUN so lets remove the ability for that to happen because like the other autists on yogs we get extremely ASS BLASTED by a single out of the ordinary occurrence"_

https://github.com/yogstation13/yogstation/pull/1484

Also
votelmao
gnome

**Comment by Super3222** [comment]
This is getting sad.

If the purpose of the xeno facility is to level up your xenomorphs, gather up a horde of them after mindslaving the queen, and eventually take over lavaland, than it's not Cruix who you should be blaming but the actual idea it'self. How on earth is that a good idea? WHY is that a good idea? That is a TERRIBLE idea.

> one person decided to bumrush the station with all the weapons and a bunch of xenos

This has happened more than once.

> Also FYI the purpose of the ruin was somewhat changed when the exit was added, and you autists only have yourselves to blame for your ignorance of not questioning or even attempting to discuss how or why that should or shouldn't have been added.

If that's how you feel than consider this your discussion.

> There was literally zero discussion for that change and so it went in and now when one or two people go

One of two people is an understatement for the majority of miners that complain about getting fucked over by xenomorphs.

Not to mention the crew who has to deal with them.

I don't understand what your mentality for this feature even is. Are you giving miners a challenge or are you just fucking them over because there's a random chance that it can ever happen? Is it a **punishment** for not stopping the xenofacility scientists (which is impossible to rule as a punishment - given that YOU added turrets so that NO ONE could get into the facility).

Lavaland shouldn't be ruled like this. Antagonists such as xenomorphs and nuclear operatives with gear as heavy as they are shouldn't be crossing with miners. All ghost roles that oppose miner should be placed on equal footings so there's a chance for either side to win. The thing with Xenomorphs is that you cannot deny that they're powerful, if anyone knows how powerful Xenomorphs are than it's me, and I'm telling you that they should not be able to fight miners. It's not fair unless they are NPC bots roaming back and forth spitting acid. Sentient mobs are always powerful, but when you're a xenomorph it's one of the easiest things in the world. Given every factor you can take into xenomorphs it's just too unbalanced.

If we want to set up field directions for lavaland than we should be setting them here and now based on logic and reasoning. The only point you've brought up for how on EARTH miners would be able to counter xenomorphs is combat shotguns. Combat Shotguns.

As much as I love to hear other peoples opinions and see how they feel about features, that poll is not the overwhelming majority of the server. In that same thread with the poll the magnitude of the situation isn't expressed at all.  This is not only a decision being made on our github, but it also a decision being made by our Head Coder who is as well a Council Member. So I willingly doubt 

> because like the other autists on yogs we get extremely ASS BLASTED by a single out of the ordinary occurrence"

If that's your attitude than understand that this is becoming more frequent than a single out of the ordinary occurrence. It's stupid to think that the only person to blame for why xenomorphs are ripping everyone's heads off is because miners had 0 chance to prepare or defend themselves for such an attack. I don't understand why you think it's fair for xenomorphs to "play nice" with their masters, obey them, grow a beefy hive, and than go on murderbone hunts just because it exists and therefore it's a feature.

Honestly at this point I feel like you're arguing just for the sake of arguing. It's getting removed because lavaland is built for miners - not for a bunch of salty ghosts to level the round with one of the most easily respawnable antagonists ever. We have ashwalkers for that, and hell. They're not as efficient or as fast as xenomorphs are.

**Comment by matskuman5** [comment]
Isn't Lavaland basically Thunderdome at this point? A place for ghosts to respawn and murderbone?

**Comment by Super3222** [comment]
> Isn't Lavaland basically Thunderdome at this point? A place for ghosts to respawn and murderbone?

Sounds like something we don't want.

Most lavaland roles aren't meant to murderbone. They're suppose to introduce ghosts to interesting narratives to take over.

**Comment by ShadowDeath6** [comment]
The majority of ghost roles are meant to act as tutorials. 
Ashwalkers- basic combat shit, this is the most subject to grief for obvious reasons
golems- R&D and mining
podpeople- botany
viro and chem syndies- I wonder what this could be hmmmmmmm
xeno syndies- xenos shit

**Comment by Stealthkibbler** [comment]
@Super3222 Yeah well 'we' isn't the playerbase and the playerbase obviously enjoys it so y'know this change is just codersalt, cruix didnt even try to start a poll or anything on it, he pre much instantly put this up without any concern for what players thought.

**Comment by ShadowDeath6** [comment]
too bad headcoder says it's shit so it gets btfo

**Comment by Cruix** [comment]
My understanding of this ruin was that it would be completely isolated from the rest of the round, and apparently my understanding was wrong. I would not have merged your PR in the first place if I had understood you correctly, for the same reason I did not merge the space mercenary ruin, and I would not have started a poll for whether or not I would have merged it.

Because I am the one who merged your pull request, I am just as responsible as you for every line of code you put in it, if not more so, and I have decided that I do not want to be responsible for this particular ruin existing in the codebase as it was. If you don't think that this is the way it should be, petition Hardy or the council to have me replaced and I will accept their decision without argument.

**Comment by Stealthkibbler** [comment]
Cunt I'm not playing some dumb politicial 2d spessmens game to revert a shitty pr change, i had a good dosage of that cancer when I was staff.

**Pull request merged**
