### PR TITLE
Changes minedrone verbs to action buttons.

### PR DESCRIPTION
**Pull request by Cruix**

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
do they keep the verbs as well

**Comment by Super3222** [comment]
No, verbs are replaced with action buttons in this PR.

**Comment by ShadowDeath6** [comment]
pls don't do that, action buttons are bad

**Comment by Cruix** [comment]
TG yelled at me and said that they would not accept it if they were verbs.

**Comment by ShadowDeath6** [comment]
time to never play minedrone ever again

**Comment by X-TheDark** [comment]
We're not TG, though.

**Comment by ShadowDeath6** [comment]
I'm going to :-1: this since it removes the verbs :^(

**Comment by ShadowDeath6** [comment]
why not just have both

**Comment by Alek2ander** [comment]
Verbs are shit, action buttons are not

**Pull request merged**
