### PR TITLE
you devour the mouse, you don't devours it

### PR DESCRIPTION
**Pull request by Amelia0010**
:100:

### Intent of your Pull Request

Fixes a very tiny grammar mistake.

#### Changelog

:cl:
spellcheck: you devours the mouse
/:cl:

### CODE REVIEW

**Comment by simonset55** [comment]
what if i dos devours mouses

**Comment by nazitra** [comment]
to devours or not to devours

**Comment by Amelia0010** [comment]
apparently spellcheck is a changelog option. Whodda known

**Comment by Ratvar** [comment]
Bad PR, do not merge, playerbase won't accept, it conflicts with new cheeseling PR too

**Comment by ghost** [comment]
i put all my language skillpoints in DreamMaker and forgot to put any in English

**Pull request merged**
