### PR TITLE
Replaces frisbee and boomerang sprites with something slightly less shitty

### PR DESCRIPTION
**Pull request by Notamaniac**
How did someone go up to a PR and say "Yup! These sprites look TOTALLY fine." There's a fucking ellipse tool in DM. YOU CAN MAKE UNIFORM CIRCLES WITH THESE.

These are still mediocre but at least they're uniform

frisbee

boomerang

And just for reference, THESE are the old ones
holy

shit

:cl:
rscadd: After a month of shipping frisbees and boomerangs with horrific manufacturing defects, Green Inc. has finally decided to up the budget dedicated to fabricating these toys by 10%.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
What's wrong with the old sprites? They look good to me.

**Comment by Notamaniac** [comment]
No no, I'm clearly mistaken. The original sprites are clearly pieces of masterwork art that must be framed in history. I should close my PR in shame and burn my laptop to the ground along with my house.

**Comment by ShadowDeath6** [comment]
old boomerang was passable, frisbee was terrible

these are improvements

**Comment by Partheo** [comment]
Heh. If you hadn't done it, I probably would have eventually. The old sprites were garbage, sorry Time. 

I would make them both slightly bigger, especially the Frisbee. Boomerangs are quite big IRL and that Frisbee sprite is about the size of an donut in-game.

**Comment by Notamaniac** [comment]
Eh if I get around to it I'll make the frisbee about two pixels wider. I just wanted to avoid making giant human sized duct tape rolls.

**Comment by Time-Green** [comment]
Well, you might want to fix the computer screen crack icons aswell...

**Comment by Notamaniac** [comment]
OP updated, I get this stupid thing where after looking at something for too long I can't tell if it's bad or not so someone slap me with reality if the frisbee looks out of place.

**Comment by Super3222** [comment]
> How did someone go up to a PR and say "Yup! These sprites look TOTALLY fine."

coder-sprite standards have been an all time low since the beginning of time

but anyway good job re-doing these. they look great.

**Pull request merged**
