### PR TITLE
I͈ ̹̮a̘̲m̸̱̪͖̰̳ ̖̰̣̰͕̯̗͠t̺̪̪͙h͙e̝̬ ̝̻́y̖͉̰̤̥͙é̞͎̟͕̙͚a̻͕̖̠͢s̖͔t̢̟̪͚̗͈͚ ̺͙̳̕o̰̙̮͓͈̪͝f̻̩̱͖̤ ͇͍͙t̛̖̪h͚̦̣͖͘o͠u͚̗̭̟͎͈͍̕g҉̬͓h͔̞̟̦̗̜t͡s̠͔͇̬̬͢ ̘͎̻̩̖ͅͅa̴̝͇͓̭̜̦͓n͚d͚̗̦̫̠̩̖ ̴͕͖̤ͅm̟̤͙̺͚̭͡i͙n̹̮̪̺̦̹d̙̩͡

### PR DESCRIPTION
**Pull request by Kmc2000**
Ktl and several others asked for this

I obliged.

This PR replaces all humans with snail people.

This is phase 1. of the announced greatestRP changes (see: announcements)

I hope that this enhances your roleplaying experience, gamers :)

Images:

https://i.gyazo.com/3084ea7d3191324f5a40a1437cc11b4f.mp4

https://i.gyazo.com/763625c16184729e7fef7c2d7fe0cece.mp4

Everything works as normal, hairstyles, eye colour, they are all working on the snails.

#### Changelog

:cl: Kmc2000
rscadd: Snail people are now in the game
rscdel: Removed shitty humans 
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
speedmerge naow

**Comment by Shardj** [comment]
Confirmed better than tg rebase

**Comment by DLCabbose** [comment]
Daw geez

**Comment by Jc1469** [comment]
even as a late april fools pr this still wont get merged because of :ice_cream:

**Comment by Kmc2000** [comment]
I really like books

**Comment by Kmc2000** [comment]
And this place is a treasure trove

**Comment by ThatLing** [comment]
Snails killed my dog

**Comment by simonset55** [comment]
It's pretty hot actually

**Comment by Shardj** [comment]
@ThatLing meme? No this is deadly serious, we demand snail people

**Comment by ThatLing** [comment]
Just let this die

**Pull request closed without merging**
