### PR TITLE
PR template change

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Changes the changelog bit of the PR template to show which options you have for the changelog.

image

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
why do you need a changelog for this

**Comment by Amelia0010** [comment]
Because i've been told to always make a changelog, no matter what

I can just remove it, as it seems kinda dumb tho

**Comment by ShadowDeath6** [comment]
imo you should only make a changelog that players will actually experience

**Comment by ghost** [comment]
changelogs are shown ingame, noone ingame cares about a dumb changelog template.

**Comment by Amelia0010** [comment]
it's gone now 👍

**Pull request merged**
