### PR TITLE
Removes drone lights and gives them nightvision

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Lights can fuck over slings and help phytosians. This also allows them to see through walls which just improves their ability to help the station 👍 

#### Changelog

:cl:  
tweak: The new series of NanoTrasen drones have had their optical sensors upgraded, meaning they no longer need a light to see.
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
drones gonna wear hard hats with light on/glowshroom if they wanna fuck slings/heal plantmans

**Comment by Slinky5890** [comment]
>drones gonna wear hard hats with light on/glowshroom if they wanna fuck slings/heal plantmans

Except now if they do that we can call them out on it easier. Because it's obvious their intentions as opposed to a drone working on an area where a sling is with a light on

**Review by AshCorr — APPROVED** [review]

**Comment by Cruix** [comment]
This did not remove the light, it just removed the ability to toggle it.

**Comment by Amelia0010** [comment]
I'm not sure why that's a problem?

**Comment by Cruix** [comment]
Because it leaves around dead code that people will see and not understand why it is there.

**Pull request merged**
