### PR TITLE
Lavaland Overhaul: Part 4 - Resonators

### PR DESCRIPTION
**Pull request by Super3222**
https://github.com/yogstation13/yogstation/pull/1773

#### Intent of your Pull Request

Resonators now work with a quick chain effect.
Resonance fields spread when they're created next to other mineral tiles "connected" to theirs.

In return, hitting a rock turf adjacent to another one will create an extra resonance field on top of the 2nd one.

##### Changelog

:cl:
rscadd: Resonators work more proficiently now. Creating a resonance field ontop of a mineral turf will spread it to other adjacent mineral turfs creating a chain reaction.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
this just makes resonator fields automatically spread to other MINERAL tiles, right?

**Comment by Nickvr628** [comment]
So hitting one rock tile means it will spread to every rock tile on lavaland, revealing EVERY deposit of ore?

I love strip mining.

**Comment by Super3222** [comment]
Only works on mineral turfs. It's in the code

**Pull request merged**
