### PR TITLE
Adds Design and Technology disks that can hold more than one entry

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
rscadd: Space floppy-disk technology has advanced to the point that multiple #technologies or designs can be stored on a single disk.
/:cl:
Also made technology disks have the same materials as they cost to create.

Tier 1 tech disks hold 1 technology, require programming 1, and cost 300 metal and 100 glass
Tier 2 tech disks hold 5 technologies, require programming 3, and cost 300 metal, 100 glass, and 50 silver
Tier 3 tech disks hold 10 technologies, require programming 6, and cost 300 metal, 100 glass, 100 silver, and 100 gold

Tier 1 design disks hold 1 design, require programming 1, and cost 300 metal and 100 glass
Tier 2 design disks hold 5 designs, require programming 3, and cost 300 metal, 100 glass, and 50 silver

Added a debug design disk that has all technologies at level 8, because it's faster than deconstructing a research object seven times.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
people will not use these for the sole fact that they are tech disks, but this is cool

**Comment by X-TheDark** [comment]
I'm not even sure what exactly these are used for.

**Comment by killerx09** [comment]
How does this interact when exported to cargo?

**Comment by Cruix** [comment]
The same way it would if you just exported several disks.

**Comment by Super3222** [comment]
@X-TheDark Floppy Disks are used to basically save the research levels your RnD computer has gotten too. It can come in handy when moving it, having the R&D server room destroyed, or creating a whole new RnD computer that'll be off the z level.

I'd usually do it when saving high amounts of research levels, because antagonists like wizards, blebs, or slings no like science.

**Pull request merged**
