### PR TITLE
Ports Vorestation in its entirety

### PR DESCRIPTION
**Pull request by Kmc2000**
Refer to issue #all of them

### Intent of your Pull Request

Ports a bunch of vorestation sprites, AKA sprites from CEV Eris, a russian ss13 server (all credit to them)

And no Adam you can't roast this because they're not my sprites :^)

Sprites locally sourced from:
https://github.com/Repede/YawnWiderStation

Things to note:
None of these sprites are mine, I ported them and made some modifications so they'd work here

I need testers for this, like seriously. Please play this with the intent of breaking it so I can fix any naming errors in the DMIs.

Like favourite and subscribe, become my patron at: patreon.com/ssssss

#### Changelog

:cl: Kmc2000
rscadd: Ported vorestation's nice sprites, check them out now
tweak: Please note, to remove catwalks in maint use a welder or wirecutters. You can also alt click to get at the wires underneath
/:cl:

### CODE REVIEW

**Comment by Alek2ander** [comment]
I like half of them
I dislike the other half
Maybe do a poll?

**Comment by matskuman5** [comment]
Can you post pics of all the sprites you ported?

**Comment by Kmc2000** [comment]
>Can you post pics of all the sprites you ported?




HNGHHHHHH

**Comment by Oakboscage** [comment]
Those airlocks and vendors are disgusting.

**Comment by matskuman5** [comment]
I'm not going through the effort to downlaod your branch or whatever and screenshot it all

You're the one who made the PR. Post them or I won't support

**Comment by Partheo** [comment]
Eh, some are nice, others are kind of disgusting. Personally i believe the console screens should be pointing towards the player's view do that you can easily identify what kind of computer it is.

**Comment by Jc1469** [comment]
> I need testers for this, like seriously. Please play this with the intent of breaking it so I can fix any naming errors in the DMIs.

please play this after it gets merged having not been fixed at all as I present no way to test it aside from downloading a full branch

**Comment by Kmc2000** [comment]
>please play this after it gets merged having not been fixed at all as I present no way to test it aside from downloading a full branch

That is the plan..

No, but seriously if you can test this please do.

**Comment by Kmc2000** [comment]
http://www.strawpoll.me/13424933

**Comment by Jc1469** [comment]
Having wasted my time downloading an entire branch to see it, I can say that in my eyes it doesn't look fitting.  The contrast between the new icons and the old just don't mix well together.

image


image
And heres some curtains.

**Comment by ghost** [comment]
As usual, KMC is terrible at recognizing what good sprites are.

**Comment by ShadowDeath6** [comment]
all of these look bad

I especially dislike the machinery and console changes, but everything is a downgrade imo

**Comment by drderp3635** [comment]
*ahem* 

no.

disgusting.

get this out of here.

**Comment by Time-Green** [comment]
Port vore mechanics instead

**Comment by Chuggachar** [comment]
These are all awful.

**Comment by LarissaMayrink** [comment]
The airlocks are nice but they look VERY out of place near everything else. Same goes for the vendors, but incredibly not the airtanks, /tg/ uses them and it doesn't looks much out of place.

**Comment by Partheo** [comment]
For the airtanks: I am personally against diagonal sprites for a few reasons; while the TG ones do look better and ours are shit, it really wouldn't be difficult to sprite a new set.

**Comment by ghost** [comment]
i would literally prefer actual vore to these sprites. in fact, i think i know why they have vore-it's so they always have something to throw up after looking at these sprites.

**Comment by Kmc2000** [comment]
Wish granted @AdamElTablawy

**Comment by ghost** [comment]
I love the airlocks, APCs, and seats. everything else sucks

**Comment by Cruix** [comment]
Try making PRs with a few related sprites at a time.

**Pull request closed without merging**
