### PR TITLE
i'll settle for a 90% chance of fire and death

### PR DESCRIPTION
**Pull request by ghost**
cruix don't stealthnerf my stuff

### CODE REVIEW

**Comment by Time-Green** [comment]
There are multiple sparks, so this is pretty much a 100%

**Comment by ShadowDeath6** [comment]
put it at a 33%

**Comment by monster860** [comment]
I can't find a PR for the prob()

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1490/commits/841da946dd318dc45dfd10851b170d493c4ed6c4

**Comment by oisin100** [comment]
> electric storm
> all the fuel tanks in the affected area blow up from light sparks

> revenant blows up fueltanks

> RPD blows up fueltanks

Just remove this.

The best part about all this is that griefers can fueltank grief without it ever being logged.

**Comment by ShadowDeath6** [comment]
More like adam el badfeatures

**Comment by ghost** [comment]
@oisin100 that's the fuckin point

revenant can welderbomb

ai can welderbomb

etc

**Comment by oisin100** [comment]
> @oisin100 that's the fuckin point

So the point in this is to allow people to welderbomb grief without being caught?

**Comment by Cruix** [comment]
2% is fine and there are other problems as well, like being unable to log who made the sparks and sparks that spawn on the same tile as the fuel tank not setting it off.

**Pull request closed without merging**
