### PR TITLE
Adds painting mechs with spray cans

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
image

:cl:  
rscadd: Mechs can now be spray painted!
/:cl:

### CODE REVIEW

**Comment by ToGWtF** [comment]
Go Voltron Force! Form Voltron!

**Comment by Altoids1** [comment]
Has this been tested with that one mime mech?

**Comment by Amelia0010** [comment]
image

**Comment by ShadowDeath6** [comment]
can you clean them

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
no, if you have commitment problems, too bad

**Comment by ShadowDeath6** [comment]
make it so using soap or space cleaner removes the paint

**Pull request merged**
