### PR TITLE
Removes Supermatter from CC

### PR DESCRIPTION
**Pull request by ghost**
This PR removes the supermatter sword from Centcomm because it was obnoxious and you couldn't end-round grief as well. Other items are added, minor.

:cl:
tweak: Research at Central Command has stopped experimenting on the supermatter sword.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
noice

**Comment by ghost** [comment]
fucking really groxic

**Comment by Time-Green** [comment]
I was going to do this at some point.
:+1: 

One thing tho, you didn't do the mapchanges right. 
Fix that first.

And who the hell is grubik?

**Comment by ShadowDeath6** [comment]
grubik is evil groxic

**Comment by ghost** [comment]
I ran prepare maps first, then I made the changes and ran map merge, I selected map #7 which it said was z level 2, and the one that I had changed.

**Comment by Time-Green** [comment]
You made over 80.000 changes. That's not good. 
Did you use tgm?

**Comment by ShadowDeath6** [comment]
can you also remove the fire foam nade from the armory since it kills almost everyone and breaches the fuck of the area

**Comment by Groxic** [comment]
I uses the DMM map merger. Was I supposed to use TGM?

**Pull request closed without merging**
