### PR TITLE
Updates many food, drink, and bureaucracy sprites

### PR DESCRIPTION
**Pull request by Partheo**
This PR updates a lot of old food, chef item, booze, bureaucracy, and janitor item sprites.
Griffeater Gin has also been renamed to Bomb-Bay 12 Gin to better reflect its new sprite.
The dmi files used in this are compatible with MenacingManatee's cinnamon PR- **use these dmi files, not his.** This PR contains his food sprites, but his don't contain mine.
This is part of a small project of mine to redo old sprites

I also added two unused sprites, TopKakes, which has a food sprite in food.dmi and its respective trash sprite in janitor.dmi. These can/will be added to vending machines later.

Attached is a .txt file that lists every change I made.
[Changelog 1.txt](https://github.com/yogstation13/yogstation/files/1156716/Changelog.1.txt)

containers
booze
bureaucracy

Note: a couple of sprites have been modified after receiving more feedback and aren't pictured here.

🆑
imageadd: Many food, chef item, booze, bureaucracy, and trash sprites have been changed.
tweak: Griffeater Gin has been renamed to Bomb-Bay 12 Gin to better reflect its new sprite.
bugfix: Dankpockets and Stuffed Legion have sprites now.
/🆑

### CODE REVIEW

**Comment by Time-Green** [comment]
Those are really good sprites, and the new flour is the most beautiful thing I've ever seen.

**Comment by Kmc2000** [comment]
OK merge

**Comment by ShadowDeath6** [comment]
not a big fan of the pens, everything else looks great though

**Comment by MenacingManatee** [comment]
The new flour and pepper mill are amazing, and i like how the space milk and soy milk have depth to them now. I'm not seeing the dank pocket sprite in your images though, do you have a picture of it by any chance?

**Comment by Partheo** [comment]
@menacingmanatee

There are actually a lot more sprites redone than what I showed here. I didn't picture any of the food sprites I changed. It would be a lot of sprites.

The dankpocket just looks like a donkpocket with a greenish tinge

**Comment by Zostroll** [comment]
Not a fan of the new salt shaker... also do the new gangster pens not have two states? Isn't that gonna be meta'ed as fuck.

**Comment by Partheo** [comment]
@zostroll

The gang pens flash between states. When not in use, they will just look like regular pens.

**Comment by Super3222** [comment]
I'm pretty sure the gang pen has 2 states IG.
Edit: Agreeing with Partheo here. Pens look fine in the picture

**Comment by Partheo** [comment]
Any info on how I could resolve the merge conflict? @cruix

**Comment by Cruix** [comment]
You will have to grab the icon file from the server's master branch and paste the new icons into it.

**Comment by Partheo** [comment]
There, added the missing sprite(Whoopee Cushion) so I'm pretty sure it can be merged now. Let me know if there's anything else I missed. @Cruix

**Comment by Cruix** [comment]
I cannot merge this because it has merge conflicts, I think there is a dmi conflict resolver somewhere in the tools folder.

**Comment by Partheo** [comment]
I'm a bit of a github noobie so I have no idea what the actual problem is. What does it mean that there is a merge conflict with this file?

**Comment by Cruix** [comment]
It means that since you made the commit, someone else has edited the file icons/obj/items.dmi, and git is not able to automatically merge your changes with theirs.

**Comment by Partheo** [comment]
Now that I've just made a commit a few hours ago though, wouldn't there no longer be a merge conflict? I've updated the file to something more recent.

**Comment by Cruix** [comment]
Just because your commit is more recent does not mean that Git will allow it to overwrite the dmi file. Because Git does not understand how dmi files are formatted, even if you went in and manually added all the icons that exist in the current master branch, it thinks that there are still missing changes, and it will not be convinced that there are not until you pull the current yogstation master branch into your branch and tell it that the conflicts are resolved by committing that merge.

**Comment by Partheo** [comment]
Okay, I'll try figuring that out. In the meantime, if I don't get it, can I send the file to you or something to have it merged?

**Comment by Partheo** [comment]
YAY

**Comment by Partheo** [comment]
Would it be possible to merge this @Cruix ? I have another PR ready that modifies items.dmi. Just waiting on this one to pass before make the request.

**Comment by Cruix** [comment]
I am not going to merge it until I can update the server. If you branch off of this branch for that PR, you will not get merge conflicts.

**Comment by Partheo** [comment]
Ah, cool. Thanks for your help.

**Comment by Partheo** [comment]
Holy shit I got roasted

**Comment by Super3222** [comment]
Their opinions don't matter. What matters is whether our community votes them in or not (probably want to make a document with side by side comparisons to make it easier). I've got to admit though, the spray bottle and filled donuts look weirder than the originals, but that's just my opinion.

**Comment by Partheo** [comment]
I'm really confused about the spray bottle. I barely changed it but I've gotten so much feedback on it, mostly bad. What's wrong with it?

A lot of these sprites were just minor improvements on my part. I'm not an artist and it really shows on the first few sprites I've made. I've been improving though and working on sprites for yogs is a way for me to both practice and contribute something. I don't mind the bad feedback, IMO it's totally justified.

**Comment by Super3222** [comment]
It looks... extra longer than the original. Which is off putting,because it's suppose to be a small spray bottle shorter than an arms length.

**Pull request merged**
