### PR TITLE
Portable Anti-Breach Capsules

### PR DESCRIPTION
**Pull request by Super3222**
Refer to issue https://github.com/yogstation13/yogstation/issues/485.

#### Intent of your Pull Request

- It's a capsule that summons breach shields around the spawn zone.
- Activate it. If it's already used it's nothing more than a dud. Else, it starts a timer for 10 seconds.
- 10 seconds are over. It checks for the atmosphere of the spawn zone. If it's not over a space tile, than it gets curious. It then checks for the pressure of the spawn zone. If it's lower than 60 than it will accept the spawn zone.
- If the spawn zone is accepted the capsule will create blast shields within a 1x1 range. These shields spawn with only 20 health (compared to actual anti breach shields that spawn shields with 100 health).

##### Changelog

:cl:
rscadd: Engineering now has portable anti breach capsules.
rscadd: Anti breach capsules will summon the same shields anti breach shields do.
rscadd: Anti breach capsules are good for temporarily patching up holes, and whatever they come across.
/:cl:

Read the branch name.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
can you not have it display for each shield, that's going to get spammy as fuck

**Comment by ghost** [comment]
make it qdel on use

**Comment by ShadowDeath6** [comment]
make it qdel the user

**Comment by Super3222** [comment]
current branch is taken up. i'll make the adjustments requested eventually o7

**Comment by ShadowDeath6** [comment]
Thank

**Pull request merged**
