### PR TITLE
Adds in mouse kebabs!

### PR DESCRIPTION
**Pull request by Kmc2000**
Ktl requested this.

https://i.gyazo.com/ac588c4acb8721240d84ea7cf36afdec.mp4

#### Changelog

:cl: Kmc2000 with Jamie Oliver
rscadd: Added mouse kebabs, craft them today! *NT's dietary association will not be held responsible for the consumption of this food item.
/:cl:

### CODE REVIEW

**Comment by Oakboscage** [comment]
Neat

**Comment by Nickvr628** [comment]
Ewwwwwwwww, it has the GROSS tag so humans cannot enjoy it...

**Comment by Kmc2000** [comment]
Thank you for stating the intentional, Nick

It is three dead, bleeding, squirming mice on a stick.
In what way is this not gross?

**Comment by AlpacaGoesCrazy** [comment]
This will be awesome addition to my lovely hell kitchen!

**Pull request merged**
