### PR TITLE
add skeksis race

### PR DESCRIPTION
**Pull request by Lilhagan**

### CODE REVIEW

**Comment by AlpacaGoesCrazy** [comment]
what is this?
buyable shuttles + new vent sprites = new race?

**Comment by Time-Green** [comment]
dude your PR ended up so messy you didnt even add skeksisses

**Comment by Amelia0010** [comment]
@AshCorr speedmerge

**Comment by ToGWtF** [comment]
assign every coder to this and it will get done 👍

**Comment by ShadowDeath6** [comment]
nice meme dude

**Pull request closed without merging**
