### PR TITLE
Added $sector variable to NTSL

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
rscadd: NTSL can now use the $sector variable to detect what z-level a transmission was made from.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
wouldn't this only apply to the listening post / DJ station since no other z level will transmit to station (without station bounced radios, which ignore ntsl anyway)

**Comment by Cruix** [comment]
It would apply to lavaland, and bounce radios do not ignore ntsl.

**Comment by ShadowDeath6** [comment]
true about lavaland
I'm pretty sure SB radios do ignore ntsl, unless that was changed recently.

**Comment by Cruix** [comment]
They have not ignored NTSL at least since the tg rebase, and probably longer.

**Comment by Jc1469** [comment]
that's pretty nice.  you could actually make it so source says something like "from Lavaland" now. So you know to never go there to help anyone.

**Comment by Amelia0010** [comment]
station bounced radios ignore NTSL trying to not broadcast it, afaik

**Comment by Notamaniac** [comment]
RIP syndie comms agent, people can now tell if he's impersonating someone while he's on lavaland

**Comment by Ratvar** [comment]
Allow voice changer to ignore parts of NTML through some sort of menu? Give lavaland agent his own console that works only on his radios? Make NTML scripter machine need R&D parts to include bigger texts and work on non-common channels?

Do not give NTML even more power cause you can print this shit roundstart with ctrl+v?

**Comment by Jc1469** [comment]
A lot of stuff that is never going to happen.

**Pull request merged**
