### PR TITLE
Administrative tool refactors.

### PR DESCRIPTION
**Pull request by Kmc2000**
Whenever you temp, or permaban someone, our man Tyrone wishes them well as they get banned.
https://www.youtube.com/watch?v=EBNZnNPnfUs

#### Changelog

:cl: Kmc2000 & Tyrone
rscadd: New sound effect for getting banned
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
They will get kicked before they even hear this.

**Comment by Kmc2000** [comment]
Fucc

**Comment by ShadowDeath6** [comment]
I think the connection closing will kill sounds playing

**Comment by Jc1469** [comment]
connection closed does infact kill all running sounds, including midis.

and I think we can do without delayed bans. even for memes.

**Pull request closed without merging**
