### PR TITLE
Re enables lone operative event

### PR DESCRIPTION
**Pull request by Amelia0010**
One nuke op with 25tc, a stetchkin, and a bulldog. Can't happen in nuke ops, blob, rev and wiz.

#### Changelog

:cl:  
rscadd: The syndicate is now sending lone operatives to blow up stations!
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
Why no in rev, but yes in cult?

**Comment by ghost** [comment]
Roundending random event. Are you sure?

**Comment by ghost** [comment]
More roundending than basically anything else, I mean. At least with blob or swarmers it tends to take a while to reach ‘FUCK’ porportions and it ends in a shuttle call which lets some people greentext.

As it stands, this guy spawns with no warning, like a ninja, except instead of an invisible speedhacker with an energy sword who, at least, has to manually kill everyone on the station, this guy spawns with the best shotgun in the game, access to the best ammo in the game, and access to stimpacks, and only needs to kill the Captain to kill the entire station, forcing everyone to redtext virtually out of the blue with no warning aside from ‘REDSUIT’ and then delta alert.

And honestly, you know well enough that one operative is more than enough to win a nuke round normally, and honestly, every time ops win it is usually BECAUSE of one robust guy and everyone else is just a distraction at best. And by robust, I mean ‘bought stimpack’. 

So yes, while you might say ‘well if someone robust gets blob/ninja/xeno the station is fucked’ and that is true, but you are effectively introducing another roundending random event antagonist into the game, but this time, rather than ending the round via shuttle call or personally killing everyone, this particular one can end the round within two minutes of spawning or less by virtue of killing one person before anyone can react.

*Are you sure?*

**Comment by AsV9** [comment]
@AdamElTablawy You get success on escaping the station if you're not on the station Z-level when the nuke blows up.

**Pull request merged**
