### PR TITLE
Ports Changelingrain's celestial gateway bomb weakness PR

### PR DESCRIPTION
**Pull request by ghost**
i'm not mad i swear

#### Changelog

:cl: Changelingrain
rscadd: The celestial gateway can now take damage, but not be immediately deleted by, bombs.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I took out all of cargo without damaging the gateway once, that was fun.

**Comment by Mrcreepssss** [comment]
what is this even?

**Comment by ghost** [comment]
maybe if you could read code @Mrcreepssss

**Comment by matskuman5** [comment]
@AdamElTablawy please credit the original coder in the changelog if you port something, otherwise people will think you're competent

**Comment by AshCorr** [comment]
```
🆑
rscadd: The celestial gateway can now take damage, but not be immediately deleted by, bombs. Made by Changelingrain
/🆑
```

Better to use

```
🆑 Changelingrain
rscadd: The celestial gateway can now take damage, but not be immediately deleted by, bombs. 
/🆑
```
As it will then make them the author of the changelog.

**Pull request merged**
