### PR TITLE
adds modified brig

### PR DESCRIPTION
**Pull request by utahclock**
Per request of Super, updating/reloading a brig rework.

:cl:
rscadd: Nanotrasen engineers have made renovations to the the brig.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
no windows to execution from space is a pretty big nerf to people trying to get into sec

**Comment by Dagdammit** [comment]
Interesting vulnerabilites are a vital part of ss13 map design, and this would make perma a LOT less interesting. I don't think I can see a single change I'd consider positive.

**Comment by Lightning38088** [comment]
why was the secure cell removed?

**Comment by Jc1469** [comment]
Glass airlock on the execution room is a bad thing, if silicons are good and know how to follow laws.
Removal of the seperate room in permabrig makes it harder to slip people in that 1x1 gap they have to walk through, making escape harder, which is bad because it's already not easy.
As said above, isolation and the transfer chamber window are both gone, both being ways in.
Windows in the execution room or whatever it's called in this _update_ aren't electrified, as far as I can tell.

**Comment by Nickvr628** [comment]
Ehh I don't like it. While the new execution room layout is nice, I don't like the changes to perma, and losing the isolation cell. Also, the lack of windows is a large nerf to antags trying to break in, as others have said.

**Comment by ghost** [comment]
No iso cell. Perma is okay I guess. Why is there a metal sheet in the execution room? Also, needs iso window.

**Comment by Ephemeralis** [comment]
Why?

**Comment by Rafael450** [comment]
I think a plant bag at perma would be amazing

**Comment by Rafael450** [comment]
The good plant trails are also amazing

**Comment by Super3222** [comment]
Utah doesn't care about this anymore as a matter of fact. There WAS a map that she made with better modifications, so I'll probably go digging for it.

**Pull request closed without merging**
