### PR TITLE
PORTS THE MOST IMPORTANT ROOM

### PR DESCRIPTION
**Pull request by Time-Green**
Yes, I ported abuse room. I couldn't copy it but I remade it, probably missing a few weapons, but I have added more aswell, enough to keep everyone busy.

image

 :cl: Time-Green
   rscadd: Central Command has decided to put their strongest weapons back in one tiny room so assistants can play with it and blow their college's heads off. (Adds back abuse room)
   /:cl:
https://github.com/yogstation13/yogstation/issues/145

### CODE REVIEW

**Comment by oisin100** [comment]
Screenshot?

**Comment by oisin100** [comment]
> WAIT FOR PICTURE

Give meh teh picture.

**Comment by Super3222** [comment]
There needs to be a [Mapping With No Pictures] tag

**Comment by Time-Green** [comment]
There is a problem with my dream maker. I will also add a landmarker for ez admin teleport.

**Comment by FluffySurvivor** [comment]
> WAIT FOR PICTURE 

give the damn picture or i'll have your pr closed pls

**Comment by Time-Green** [comment]
I am not home, but at school. So I simply can't. 

AND NO ONE CAN TELL ME EHAT TO DO

**Comment by Time-Green** [comment]
schermopname 257
I will be making some final changes, like adding a land-mark and removing the nuclear core, it kills you quick. Aswell as removing those pepe faces. I was drunk
And smoothing the windows

**Comment by Time-Green** [comment]
image
This is now merge ready, in 5 seconds when I fix the lighting

**Comment by timkoster1** [comment]
We need a "fucking merge me" tag

**Comment by oisin100** [comment]
ERT Raiding abuse room for gear?

**Comment by Time-Green** [comment]
I have no idea where they spawn, good call tho, I'll check it out and see if it's safe

**Comment by timkoster1** [comment]
I actually can't check it out, due there being something wrong with the DM that holds the map. Do you know where they spawn?

**Comment by Time-Green** [comment]
Fixed

**Comment by Time-Green** [comment]
schermopname 273
Also added 4 cyborg recharging stations.

**Pull request merged**
