### PR TITLE
Adds a new line to brain damage

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**

### CODE REVIEW

**Comment by Alexandria404** [comment]
Good PR, great addition.
 






pls no

**Comment by Amelia0010** [comment]
I love and hate you at the same time

**Comment by AlpacaGoesCrazy** [comment]
at least its not wgw

**Comment by Xantam-13** [comment]
No...

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
oi, we got a headcoder for a reason

**Pull request closed without merging**
