### PR TITLE
fixes saw from messing up

### PR DESCRIPTION
**Pull request by ShadowDeath6**
#1119

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
thanks I couldn't compile because my dme is being shit

**Comment by Super3222** [comment]
Can you explain how your DME was messing up

**Comment by ShadowDeath6** [comment]
When I merged from master the new datums like the pAI stuff and the mouse event go onto my dme file and when they compile they error because they're calling on files that don't exist in my dme

**Comment by ShadowDeath6** [comment]
merg pls @X-TheDark

**Comment by X-TheDark** [comment]
I'll merge this in a few hours.

**Pull request merged**
