### PR TITLE
Updates the PALADIN lawset to reference what it really includes

### PR DESCRIPTION
**Pull request by ghost**
cough
#### Changelog

:cl:
rscadd: The PALADIN lawset has been changed to reflect what it really represents.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
:triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: :triumph: 

no

**Comment by ShadowDeath6** [comment]
padladin more like padamdin

**Comment by Kmc2000** [comment]
Agree

**Comment by RoboticVodka** [comment]
Sounds like a salt PR, but I agree. :^)

**Comment by Super3222** [comment]
har har

**Pull request closed without merging**
