### PR TITLE
Rapid Terraforming Device

### PR DESCRIPTION
**Pull request by silicons**
CURRENTLY A DIRECT PORT OF https://github.com/tgstation/tgstation/pull/21724

#### Intent of your Pull Request
Adds the **Rapid Terraforming Device** as requested by @dagdammit
A device specifically for terraforming the hostile wastes of lavaland that ONLY works on its zlevel.
Currently not available in-game.
Membrane walls sprites from BAYSTATION.
Other sprites + idea from Dagdammit.

RAPID TERRAFORMING DEVICE.
A specialized bulky item that uses RCD technology to terraform hostile environments
It is limited to the mining zlevel, unless it is hacked.
It has several functions:
All of them use matter in the form of metal, glass, plasteel, RCD cartridges, or IRON ORE.
The pressurize function uses gas that is internally regenerated.
Using it has a chance to shock you unless you are wearing insulated gloves.
Use a mining satchel on it to load iron ore if there is any in the satchel.

1. Make catwalks on lava/chasms to allow people to cross. These catwalks can not be destroyed by normal welders.
2. Turn asteroid floor into plating, and rock walls into normal walls
3. Fabricate airlocks.
4. Fabricate membranes which are airtight but are destroyed in one hit from just about anything.
5. Remove catwalks made by this
6. Blow out compressed air to pressurize areas.

##### Changelog

:cl: kevinz000
rscadd: Adds the Rapid Terraforming Device. It is a bulky piece of equipment that uses RCD technology to terraform foreign lands and create man-made structures on them. It can be loaded with standard RCD compressed matter cartridges, sheets of metal and plasteel, and iron ore directly from the wastes. Careful though, you'll need insulated gloves to use them safely!

/:cl:

### CODE REVIEW

**Comment by Dagdammit** [comment]
Yasssssssss

For the record, if we can get this working I'm 100% fine with it being merged purely as an admin-spawn item for the time being. That way I can test it out and we can leave the question of when/if/how to add it to game for later.

**Comment by ShadowDeath6** [comment]
Cool

**Comment by silicons** [comment]
Items work fine, however, action button sprites ar eborked and I can't get github to work with yogstation repo...

**Comment by silicons** [comment]
Ok, Im' pretty sure I fixed them and the sprites are a client-side issue, as they worked fine when I tested today but when I reconnected they disappeared again and I'm sure my code isn't to blame.

**Comment by ShadowDeath6** [comment]
_shrug_

**Pull request merged**
