### PR TITLE
Every miner now has access to the mother jaunter

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

- Every miner now has access to the mother jaunter beacon.
- Jaunter beacons come with descriptions that will hopefully help people understand how to use them.
- Remodeled the mining medics office
- Added a new computer that will allow you to see through cameras installed inside of jaunter beacons.

#### Changelog

:cl:
rscadd: Miners can now access the mother jaunter beacon.
tweak: Jaunter beacons now come with helpful descriptions.
tweak: Remodeled the mining medics office.
rscadd: Added a jaunter beacon camera computer.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
TODO: Make it so the cameras only work while on lava land (or maybe simply on any z level that isn’t the station or centcom).

**Comment by ShadowDeath6** [comment]
kind of obstructive right in the middle of the hallway, why not put it in the under-used ore refinery room

**Comment by Super3222** [comment]
Nobody would use it if I put it in there.

**Comment by ShadowDeath6** [comment]
putting it as a random object in the middle of the hallway is stupid, though
if it's useful it'll be used, if they don't walk the 10 tiles from the mining EVA wing to the refinery area then that's on them

**Comment by Super3222** [comment]
I want it in the hallway.

**Comment by ShadowDeath6** [comment]
:thinking:

**Comment by Super3222** [comment]
1v1 me on traitor deathmatch

**Comment by Ratvar** [comment]
Put it onto wall, newcaster style

**Comment by Dagdammit** [comment]
Maybe the mining medic should get the ore refinery room.

Or maybe the lavand mining base needs to suck less idk.

**Comment by ghost** [comment]
why not make the miners start with a wrench so they can wrench their fucking beacons in the first place

**Comment by ShadowDeath6** [comment]
>toolbox in mining eva room

**Comment by Dagdammit** [comment]
Religious reasons, they would never forsake their crowbar god for a heathen
tool.

**Pull request merged**
