### PR TITLE
Makes shaft miners unable to become rev heads

### LINKED ISSUE #1405: Make Miners ineligible for rev head
reasons why: 
https://gyazo.com/a11d753436e74509dd87e72d41eb4527

Goddamnit this keeps happening make it stop

### PR DESCRIPTION
**Pull request by matskuman5**
Fixes #1405

:cl:
tweak: Shaft miners can't be head revolutionaries anymore.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Seems good. Did you test it?

**Comment by matskuman5** [comment]
Uh... no

The change seemed pretty simple so I thought there would be no need for that

**Comment by Super3222** [comment]
You don't need to test it.
Also new meta for security. It makes my life easier

**Comment by matskuman5** [comment]
keep in mind they can still be flashed to become revs :^)

**Comment by AsV9** [comment]
but it's funny when all the revs leave the station to go mine

**Comment by utahclock** [comment]
You sure that doesnt blacklist them from being flashed?

**Comment by Super3222** [comment]
> You sure that doesnt blacklist them from being flashed?

It doesn't. That specific list is only used when the round is compiling together.

**Pull request merged**
