### PR TITLE
The nuke disk is now dropped when its holder is gibbed or dusted

### PR DESCRIPTION
**Pull request by Cruix**
Kill nukeop

He explodes

Disk nowhere to be found

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
He Explode

**Comment by Jc1469** [comment]
kill nukeop

he explodes

disk is now in one of 70 different places.   as it should be.  :-1:

**Comment by Cruix** [comment]
Put nukeop in disk

Disk explodes

Nukeop is now in one of 70 different places as he should be

**Comment by drderp3635** [comment]
Kill explodes

Put 70 places on nukeops

Should be is now where disk as he

**Comment by Super3222** [comment]
you're not allowed to comment on bugfix prs

**Pull request merged**
