### PR TITLE
adds the anti bear circle, thanks goofball

### PR DESCRIPTION
**Pull request by ghost**
i saw this masterpiece deep in /tg/'s rejected PRs and i'm angry that this was denied so here, have it

goofball came up with this

if you draw a circle around you, bears won't attack you. anti bear circle. 

yes this is a reference.
#### Changelog

:cl:
rscadd: SolGov environmental advisors have issued a PSA reminding space travelers to have anti-bear circles ready in the event of a space bear attack.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
This is amazing

**Comment by Super3222** [comment]
we HAVE to merge this

**Comment by Time-Green** [comment]
How can /tg/ have ever denied this?
Also add bear proof underwear.

**Comment by Ephemeralis** [comment]
Yes.

**Pull request merged**
