### PR TITLE
holorays!

### PR DESCRIPTION
**Pull request by Amelia0010**
stolen from https://github.com/tgstation/tgstation/pull/35020/files
https://gyazo.com/19cae4bfdac28bfccfdb542a94aa9e03

:cl: MRTY
rscadd: HOLORAYS!
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
I don't like the look of that

**Comment by Alexandria404** [comment]
muh immersion is happy.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Might look less awful if you make it move with the hologram and not jump from tile to tile

**Comment by Kmc2000** [comment]
Would it not look less trash if you had the pad fastprocess instead of on movehologram? and just move the beam to the holoman?

**Comment by simonset55** [comment]
Looks like a graphical error, not sure if i like that, but it makes sense since it's the AI

**Pull request closed without merging**
