### PR TITLE
You can now draw crayons ANYWHERE

### PR DESCRIPTION
**Pull request by Time-Green**
Ported from https://github.com/tgstation/tgstation/pull/34034 by @deathride
image

🆑 
add: Crayons will now draw at the position you click. Ported from deathride58
/🆑

It's current year, crayon decals shouldn't be bound to mere tiles.

### CODE REVIEW

**Comment by Time-Green** [comment]
delethis

**Comment by Kmc2000** [comment]
What a fucking hero. Yes

**Comment by Super3222** [comment]
This NEEDS to happen. The best revenge for being brigged for slipping the HoS is drawing a penis in his office.

**Comment by AlpacaGoesCrazy** [comment]
no penis drawing rule incomming

**Comment by Ratvar** [comment]
Title says ANYWHERE
can't draw with crayons on walls
                                         on space
                                            on lava
                                               b u l l s h i t

**Comment by Time-Green** [comment]
Did you try?

**Pull request merged**
