### PR TITLE
buffs blob a large amount like, wow 

### PR DESCRIPTION
**Pull request by Jc1469**
no more afk blobs pls

### CODE REVIEW

**Comment by Partheo** [comment]
Game breaking

👍👍👍

**Comment by drderp3635** [comment]
Blob powercreep

**Comment by Cruix** [comment]
Make it do a poll instead

**Comment by Jc1469** [comment]
Making it do a poll makes there be a wasted 30 second period of a blob spending the points to split, so I'm not doing that. And a lower timer risks the window not loading and half the dead ghosts outright not having a chance to begin with.

**Pull request merged**
