### PR TITLE
Implements differently stocked YouTool vendor variant for public use

### PR DESCRIPTION
**Pull request by Tenryumi**
I've noticed many rounds now that Primary Tool Storage becomes completely empty very often nowadays. Since we started becoming more cool and hip to play on more people have been participating in rounds. 
That makes for less tools available (if any at all!) for late joiners or people whom don't make a mad dash for the room less than 5 minutes into the round.

So, I've moved around some tables to make way for the solution to that problem!
new tool
The premium coin items appear below "Engineering Gear."
_not pictured: the hacked items are an industrial welder (no cool upgraded welder here, sorry) and budget insulated gloves._
#### Changelog

:cl:
adds Public YouTool, stocked with the lame, mostly non-engineering tier tools
moves some tables around in Primary Tool Storage to make way for its placement
/:cl:

### CODE REVIEW

**Comment by Tenryumi** [comment]
HOLY SHIT
sdfdsgdgdg
HOW DID I NOT NOTICE THIS

**Comment by Time-Green** [comment]
Is that milk?
Oh wait that's a light

**Comment by Tenryumi** [comment]
OOOO COMMITS
OOOOOOOO CLOSED PR COMMITS
OOOOOOOOO THAT'S NOT A THING

**Comment by Super3222** [comment]
LOL

**Pull request closed without merging**
