### PR TITLE
Reflector Helmet

### PR DESCRIPTION
**Pull request by Super3222**
https://forums.yogstation.net/index.php?threads/reflector-helmet.13633/#post-126291 for pictures + details.

I added one to the armory. I could add one to cargos supply list.

#### Changelog

:cl: Larissa Mayrink
rscadd: Adds a reflector helmet to the game. It comes with the same abilities as the reflector vest - but for your head.
/:cl:

### CODE REVIEW

**Comment by LarissaMayrink** [comment]
Ay ay ay, thats lovable.

**Comment by ShadowDeath6** [comment]
This is a precursor to ablative riot armor, right?

**Comment by fonedsky** [comment]
> ablative riot armor

Is it bad that I can see someone unironically suggesting this in the future?

**Comment by LarissaMayrink** [comment]
>abalative riot armor
Its called SWAT and its already ingame, but they are expensive af at 3k points each(6k a crate with two sets), they got 80 bullet and 80 melee resistance.

**Comment by LarissaMayrink** [comment]
@fonedsky SWAT has 80bullet, 80 melee

**Comment by Cruix** [comment]
You will have to add a head check to /mob/living/carbon/human/proc/check_reflect() for this to work

**Pull request merged**
