### PR TITLE
removes the description of megafauna from the admin log popup of megafauna being lead to places. because why.. why would it be there?

### PR DESCRIPTION
**Pull request by Jc1469**
why the fuck

### CODE REVIEW

**Comment by Stealthkibbler** [comment]
GUARDIANS OF NECROPOLIS

**Comment by Jc1469** [comment]
I want to know every time a monstrous creature protected by heavy shielding is lured to nowhere.
I definitely do.  Every single fucking time.

**Comment by Time-Green** [comment]
John, use correct commit names dammit.
"why was this a thing" is a bad name
If someone were to look in the code and see the last changes, they'd see that.

**Comment by Jc1469** [comment]
and they'll see something that should not have been a thing. and not bother checking it.  it's the perfect name.

**Comment by ShadowDeath6** [comment]
The only reason I can think is if the creature was named something else, such as the renamed ash drake in one of the ruins.

**Comment by Jc1469** [comment]
im sure the admins know about that one ash drake by now.  if not I can re-add desc, add type, add health, god.  is fin.

**Pull request merged**
