### PR TITLE
Nerfs telebaton

### PR DESCRIPTION
**Pull request by ghost**
telebatons can no longer stunlock

:cl:
tweak: Telebatons no longer stunlock
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
Can we get an explanation? Because the way I see it this is not happening.

**Comment by Notamaniac** [comment]
I have a feeling this is going to make the telebaton completely useless.

You do know the telebaton was added to replace the nerfed flash heads got right?

**Comment by Amelia0010** [comment]
Isn't the stuntime already so short that you have to begin cuffing immediately to do it before they get up?

**Comment by Jc1469** [comment]
:policeman: b a l a n c e   p o l i c e :police_car: 


no. this is a bad pr. The ability to stunlock is already unreliable.

There's no gain to this other than "weh i break in to science and rd beat me up every time, nerf because unfun i want greytide easy"

**Comment by X-TheDark** [comment]
Yeah, an explanation for this is definitely needed.
Why do you think permastun from this is bad, considering that's sort of the point of this baton, for heads to be able to defend themselves without needing to call sec.

Also, numbers:
* This is a 3 BYOND tick stun (6 seconds, as it calls the `stun = stun-1` thing once every 2 seconds), with a cooldown of 4 seconds...usually. Weird stuff can happen if you hit the target just as a tick is about to be called...

**Comment by Chuggachar** [comment]
Yeah I don't see a problem with the telebaton, the stunlock is already unreliable as john said.

**Comment by ToGWtF** [comment]
:salt: PR

**Comment by ShadowDeath6** [comment]
the stun is really unreliable since there's a 1 second window where you can actually hit them with the baton rather than the 6 seconds you get with sec's stunbaton

**Comment by Cruix** [comment]
The whole point of telebatons is to stunlock

**Pull request closed without merging**
