### PR TITLE
weavers are more toxic

### PR DESCRIPTION
**Pull request by ghost**
why did i make them do food poisoning again
##### Changelog

:cl:
rscadd: Marrow weavers are more toxic than they were before.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
ALMOST AS TOXIC AS @AdamElTablawy GET IT I MADE A JOKE FOR THIS PR

**Comment by ghost** [comment]
# wow

**Comment by Super3222** [comment]
Absolutely unacceptable. This will completely fuck blobs even more than they already are, screw over revheads early and late game, contribute to the growing holoparasite problem, reinforce the emag-revolver meta, and destroy the viability of shadowlings. I don't know how you could even consider this change.

Did it ever occur to you how much this would affect traitors, abductors, changelings, nukeops, deathsquads, and megafauna? This game is a complex balancing act of interwoven checks and balances, maintained by some of the most highly trained and educated spaceman experts in the world, and this PR shows complete disregard for that haphazard yet workable tapestry which we have spent five years holding together with duct tape and bubblegum.

If by some miracle this is merged we may as well set the probability of all gamemodes to zero except extended so that the playerbase can at least eke out some meager entertainment from roleplay, since any semblance of balance will be utterly and completely destroyed.

**Comment by Kmc2000** [comment]
FUCK MARROW WIENERS 11111!!!!!

**Pull request merged**
