### PR TITLE
Refactored gangtool code

### PR DESCRIPTION
**Pull request by Cruix**
Everything should appear to be exactly the same in-game, except that the sleeping carp gang can now buy dope necklaces and dope necklaces are under equipment instead of weapons.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
important

**Comment by Super3222** [comment]
> important

Framework for

T H E M E D
G A N G S

**Comment by Cruix** [comment]
shhhh don't give it away

**Comment by ShadowDeath6** [comment]
don't forget, it's cruix's monthly refactor pr!

**Pull request merged**
