### PR TITLE
blobbernauts have less max health and lose health faster when off blob

### PR DESCRIPTION
**Pull request by ShadowDeath6**
makes blobbernauts slightly more defensive
also this fixes an "oversight" I forgot to fix when I made blobbernauts heal twice as fast since they can actually outheal the damage from losing their factory which is really dumb
also makes sorium not stun you by slamming you into walls fuck you

:cl: ShadowDeath6
tweak: Blobbernauts now die more quickly upon losing their factory.
tweak: Blobbernauts die more quickly off of the blow.
tweak: Sorium blob doesn't stun you anymore.
tweak: Lowers blobbernaut max health from 200 to 160.
/:cl:

### CODE REVIEW

**Comment by LarissaMayrink** [comment]
But blobs are already so weak that i haven't seen a single blob win through this entire month

**Comment by ghost** [comment]
if you have half a brain cell you can win as a blob

proof: won blob by spawning in incinerator

blob still has like a 60% winrate

**Comment by ShadowDeath6** [comment]
it was an oversight that they could outheal having their factory destroyed, that should be a guaranteed death

**Comment by Super3222** [comment]
i realllyy wish we had statistics to prove reasons for or against balance changes. yogstats where are you?

**Comment by Super3222** [comment]
Holy shit, my mistake. I accidentally closed this

**Comment by ShadowDeath6** [comment]
Accidentally

**Comment by Jc1469** [comment]
Reducing max health and also increasing degen rate :thinking: 
Seems a bit overkill to m- 
**THE BALANCE POLICE DO NOT APPROVE OF THIS CHANGE.**
**LESS HEALTH AND DIE FASTER? WHAT.   JUST DO ONE OR THE OTHER.** 

>makes blobbernauts slightly more defensive

**MAKES BLOBBERNAUT FUCKING DIE IF IT LEAVES BLOB TILES**

**Comment by ShadowDeath6** [comment]
@Jc1469 they can just run at people and facetank 5 lasers off blob tiles then run back and heal 10 health per blob movement, which is actually more than per blob pulse since they get healed by the overmind creating tiles near them

**Pull request merged**
