### PR TITLE
MATSKUMAN, YOU DUN FUKED UP

### PR DESCRIPTION
**Pull request by monster860**
This is not supposed to be included @matskuman5 

@X-TheDark @Cruix SPEEDMERGE SPEEDMERGE SPEEDMERGE

### CODE REVIEW

**Comment by ghost** [comment]
FUCK tag

**Comment by Jc1469** [comment]
more like matsuckman :100:

**Comment by Mrcreepssss** [comment]
so what exactly happened?

**Comment by Cruix** [comment]
Six tiny, unreachable z-levels were being generated every round.

**Comment by Mrcreepssss** [comment]
seems not so much problematic as useless waste of time and resources.

**Pull request merged**
