### PR TITLE
Allows for the TEG to be wrench/unwrenched and adds it to cargo

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

First off: Adds the Thermo-Electric Generator to cargo. It costs 10.000 credits, just like a supermatter shard.

Second: Allows the Thermo-Electric Generator to be moved around, by wrenching/unwrenching it.

#### Changelog

:cl:  
rscadd: Nanotrasen has begun selling Thermo-Electrig Generators through their supply vendors! Buy yours today!
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
does this actually work

**Comment by Partheo** [comment]
Let the autism commence

**Review by AshCorr — APPROVED** [review]
We can rebalance it later.

It shouldnt be able to generate power just by using a heater and a cooler.

**Comment by Amelia0010** [comment]
image

I got 2MW out of a heater and cooler.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
that is 2 million watts

**Comment by Amelia0010** [comment]
I can't do numbers

**Comment by Alexandria404** [comment]
Sounds like way too much power.

**Comment by Amelia0010** [comment]
Well, the singularity and the tesla both make more than enough power to power the whole station several times over, with no cost, whereas this would power the station several times over, with some cost.

Not to mention that having a lot of power doesn't really matter. Either you have enough, or not. Excess really doesn't matter. You don't gain anything from having extra power, other than the fact that you have extra power.

**Comment by Partheo** [comment]
Thinking that this would break balance is ridiculous. SS13 has next to no balance and lives off of its features and complexity. Excess power generation really doesn't matter.

**Comment by grubstank** [comment]
It doesn't matter in the current meta, but it is a good idea to maintain balance for future features - for instance, if we were to one day port over the power export laser from goon

If you actually want to add complexity to the game, at least the core features need some semblance of balance - for instance there really is no meaningful strategic difference between the tesla and singulo

**Pull request closed without merging**
