### PR TITLE
Adam CC

### PR DESCRIPTION
**Pull request by Cruix**
untitled

### CODE REVIEW

**Comment by Super3222** [comment]
I somehow saw this coming.
Please re-add https://github.com/yogstation13/yogstation/pull/1961 somewhere near the entrance if you can.

**Comment by ShadowDeath6** [comment]
some things
1. where's the adminbus room
2. where does the shuttle land and does it have openings for the 3 doors on the right side of the shuttle
3. add doors and windows to the AI upload area pls

**Comment by Jc1469** [comment]
adam cc. more like boring cc amiright

**Comment by ghost** [comment]
1. adminbus room-gone,  because that shit is irritating and it never used to be available before either

2. shuttle lands in the middle and it has 3 openings

3. no

**Comment by ShadowDeath6** [comment]
Adminbus area is fun for people to dick around in at the end of the round, and it's been available for a very long time before ans after the rebase

I also don't see where the three doors for the right are, in the screenshot it just has 6 blast doors to the left and everything else is closed off

Also the AI upload room looks exceptionally ugly if it doesn't have windows and doors

**Comment by ghost** [comment]
I don't like the adminbus room.

Doors are there.

Fine.

**Comment by ghost** [comment]
Remember that eshuttle has blast doors that open when shuttle docks.

**Comment by matskuman5** [comment]
I liked the bus room

Fun to let off some steam when round ends

**Comment by ghost** [comment]
it's irritating in general to me. I can add weapons to CC/a bus room, but getting to it will be an achievement as it used to be.

**Comment by ShadowDeath6** [comment]
Achievement as in you need to run through the doors while getting shot at or achievement like hacking into the mech room and stealing the phazon so you can cheese to the bus room

**Comment by ghost** [comment]
mech room phazon bus room

**Comment by Kmc2000** [comment]
What about what hippie has, have gun dispensers all around CC and leave the real bus room sealed so the mods can bus and smart people get the rewards?

I do still want something like that, but i do agree in that it looks cluttered

**Comment by Cruix** [comment]
Gotta add flags to CTF

**Comment by tvcc-larsencm** [comment]
Security camera consoles on the station are borked. Certain cameras like "toxins storage room" are pointed at Central Command.

**Comment by Dagdammit** [comment]
I love this because the halls make it feel like arriving at an airport. Current central command really does suck; it's a tiny cardboard cutout of a disembarkation area with a bunch of impassable 'doors' hiding meta rooms or empty space. 

This centcomm's like 50% believable place and that's great. It gives the players stepping off the escape shuttle a faint chance of something, ANYTHING happening that isn't 60 seconds of meta deathmatch.

**Comment by 00aquir** [comment]
would be cool to have spell books at different points of the map, people are beating each other to death at the end anyways and it's more interesting and fun to revive and polymorph them

**Comment by Paragonid** [comment]
The adminbus room is the only way for people who don't play much to try some items or at least to see how they work when someone else uses it. Keep it in the game somewhere, let people spawn in or access it after round end, even if not puting it on CC.
On CC it gives a motivation to actually stay alive until the end though.

UPD: I would like to work on PR for letting players to spawn in separated from CC adminbus room after-death-lavaland-style. It would be even better. Should I make a separate issue for that?

**Comment by ghost** [comment]
i can't believe you guys merged this

**Pull request merged**
