### PR TITLE
Makes summoning nar-sie or ratvar end the round

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

No more five minutes of harvester/scarab spam.

#### Changelog

:cl:  
tweak: Ratvar and Nar-sie now have the power to end the round!
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Gud

**Comment by ghost** [comment]
Give it 90 seconds or so at the least so there's some time for the harvesters and cogscarabs to fuck around.

**Comment by Amelia0010** [comment]
it ends the round as per normal, so if there's no tickets they get 90 seconds, otherwise they get tickettime + 10 seconds

**Comment by ghost** [comment]
90 seconds of actual fucking time at to play the game. IE make the shuttle arrive immediately  and then depart in 30 seconds. The funnest part of nar'sie hell is managing to escape safely.

**Comment by AshCorr** [comment]
Seems kinda lame.

Let them dick about a bit.

**Comment by Amelia0010** [comment]
it is 3 minutes of killing everyone, followed by 2 minutes of sitting on the shuttle doing nothing. They get to dick around during the time it takes to do tickets regardless

**Pull request merged**
