### PR TITLE
buffs the (currently harmless) radbow

### PR DESCRIPTION
**Pull request by ghost**
due to tg fucking up how radbow worked it was bad

now it's good again

irradiates more, hands out nasty mutations, does more damage

is now worth as much tc as compared to the 2shot instakill revolver
#### Changelog

:cl:
rscadd: The radbow is now not assbow.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
jesus fuck this is op no
1. bad mutation like blindness or deafness or mute almost guaranteed on hit
2. without rads this crits in 4 hits and mutes for 6 per hit
3. with rads this crits in 2 hits

HA

**Comment by Dragonforcefive** [comment]
Well... it's a weapon. It's worth as much TC as the revolver. Maybe should be worth a tad bit more for the status effects.

**Comment by ghost** [comment]
>crits in  4 hits

oh a bad revolver

>crits in 2 hits 

oh the revolver

**Comment by ShadowDeath6** [comment]
Oh the infinite silent revolver that mutes anyone and leaves no blood

Bad pr

**Comment by Super3222** [comment]
we've balanced this fine in the past

**Comment by ghost** [comment]
Tbh it's useless at the moment but radiation code is so finicky I can't get it to do what I want it to do as I'm bad

**Pull request closed without merging**
