### PR TITLE
[WIP] Makes all the maps playable, and non-runtimey

### PR DESCRIPTION
**Pull request by Amelia0010**
1st commit: Added a clerk room, sig-tech and outdated plasma tank to asteroid station, and added the asteroid and ministation map to the config.

### CODE REVIEW

**Comment by Time-Green** [comment]
What about we delete those maps instead?

**Comment by Amelia0010** [comment]
go die

**Comment by Amelia0010** [comment]
Unless you have a suitable replacement for maprotation

**Comment by Time-Green** [comment]
I understand metastation for highpop, but all those other maps are only here to cause fucking conflicts

**Comment by Amelia0010** [comment]
hmm, maybe just deleting the maps and fixing metastation is actually a better solution than manually fixing so many fucking shitty issues

**Pull request closed without merging**
