### PR TITLE
Fire Axe Cabinet Improvements

### PR DESCRIPTION
**Pull request by Firewolf34**
### Fire Axe Cabinet Improvements

fireaxe

The Fire Axe is a truly robust and powerful weapon, and as such the Cabinet that holds it should be equally as robust and well-built. 

As is only reasonable, I have made some slight modifications to improve the Fire Axe Cabinet:

- Cabinet can now be deconstructed, using a wrench. But only if it's open or broken, and the axe is removed. Useful for those who are rebuilding areas where the axe cabinet is.
- Cabinet can now be unlocked/locked using an ID card with Atmospherics access (includes CE & Cap obviously, and the Engineer, strangely enough)
- Old mechanic of "resetting the locking mechanism" has been moved into a separate action: it can still be performed with the multitool, but it takes longer than swiping an ID. Instead of the AI and borg performing the reset action, they now just simply unlock it with no wait time.
- Cabinet has been made marginally stronger to incentivize using an ID or hacking it with the multitool, and the hack time has been increased to incentivize using an ID to open it.
- Fingerprints are added to the metal when deconstructing, to the cabinet when the axe is removed, and to the cabinet when it's hacked or broken into.
- Log entry created when someone removes the fireaxe, to help track down those pesky griefers.
- Other minor bugfixes, such as removing the ability to lock/unlock it when it's already open with the multitool.

#### Testing

All of this has been tested fairly extensively. I tried every access permutation, and being a Borg, and an AI, along with trying to deconstruct it in various edge cases. It seems to perform correctly. The only thing I would like to add, possibly, in the future, is the ability for the emag to trigger the lock reset action, maybe throw a few sparks. But I won't be adding that to this Pull, most likely.

Thanks for reading, and happy axing!

#### Changelog

:cl:  
bugfix: Fire Axe Cabinet cannot be locked/unlocked when already open
bugfix: Fire Axe Cabinet use will result in fingerprints
tweak: Fire Axe Cabinet can be deconstructed with a wrench!
tweak: Fire Axe Cabinet made more robust: health increased, hack time increased
tweak: Fire Axe Cabinet can be unlocked/locked with an ID with Atmospherics access
soundadd: Fire Axe Cabinet will make locker open/close sound when opened/closed respectively
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
this is perhaps the most pointless PR i've ever seen

**Comment by Cruix** [comment]
#79

**Comment by Moja10** [comment]
High effort PR, I like

**Comment by KrabSpider** [comment]
I like it. Changes the gameplay dynamics

**Comment by Partheo** [comment]
The hero we need

**Comment by Firewolf34** [comment]
Pull me! :100: More pointless PRs to come, I promise. :)

**Pull request closed without merging**
