### PR TITLE
cogscarabs can use slabs but can't pick anything non cult related up

### PR DESCRIPTION
**Pull request by ShadowDeath6**
yes
#1860 

uhh tl;dr cogscarabs can't pick anything up, including guns and stunprods and other cancer items
BUT
they can use slabs now
they also get PASSMOB so they can't try and cheese people onto the stun sigil things

:cl: ShadowDeath6
rscadd: Cogscarabs can now use clockwork slabs.
rscdel: Cogscarabs can no longer pick up anything that isn't cult-related or a tool.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
It has some interesting potential. It's worth a try.

**Comment by Dagdammit** [comment]
Woah, hang on, they get full access to scripture?

...I guess that's not as bug as it sounds, since they can't wear alot of clock cult items. Still- can they guvax? Can they get clockwork guardians and impale people on Function Call spears?

**Comment by ShadowDeath6** [comment]
they can't get marauders, they can guvax, and they can get spears.

**Comment by Dagdammit** [comment]
Can they then use the spears for stabbing? Can they pull people & thus do
the powerful spear impale move? Can they throw things?

**Comment by ShadowDeath6** [comment]
they can't pull, they can attack with spears (they should be able to defend themselves a little bit) and they can't throw things.

**Comment by Dagdammit** [comment]
That balances itself nicely then.

**Comment by ghost** [comment]
taunting tirade on a cogscarab sounds awful

**Comment by ShadowDeath6** [comment]
I've never even seen a regular cultist use taunting tirade

**Comment by Super3222** [comment]
Can you disable judgement and revenant for these guys. Those are the powerhouse abilities, and cogs aren't meant to "take over the show" during this mode.

**Comment by ShadowDeath6** [comment]
Sounds good

**Comment by ghost** [comment]
i can't wait for cogscarabs casting geis when it's ported

that'll be fun

**Comment by ShadowDeath6** [comment]
Ngl geis is an awful name, guvax is infinitely better

**Comment by ghost** [comment]
Guvax = aoe convert that's obvious as fuck and can't be reliably used to convert

Geis = single person stun convert

Idk i like geis more

Also taunting tirade plus cogscarab is going to suuuuuuuuck

**Comment by ShadowDeath6** [comment]
I know what their differences are, I'm just saying that geis is an awful name for a magic word

**Comment by ghost** [comment]
For the unaware taunting tirade is an aoe confuse + brief knockdown for anyone in visual range with a fast invoke speed and lets you move a bit after casting and casts repeatedly

It also stacks

Ie 3 cogscarabs constantly casting taunting tirade will keep people stunlocked in aoe

**Comment by ShadowDeath6** [comment]
yeeb!!!!!!!!!!!!!

**Comment by Super3222** [comment]
Are you going to disable revenant and judgement for cogs?

**Comment by ShadowDeath6** [comment]
shit urite

**Comment by Super3222** [comment]
:+1:

**Comment by ShadowDeath6** [comment]
this is available for testmerge or whatever

**Comment by ShadowDeath6** [comment]
:zzz:

**Comment by Mrcreepssss** [comment]
maybe they should also be able to always use the hierophant network (especially if this doesn't go through)? i remember once being a scarab and not being able to use it standardly. only option slab, but thats all i could use for the slab... fuck.

**Comment by ShadowDeath6** [comment]
They use :b to talk on it

**Comment by Mrcreepssss** [comment]
ah, nice but ehh could you add a prompt that tells that?

**Comment by ShadowDeath6** [comment]
`as a cogscarab, you have low health, an inbuilt proselytizer that can convert rods, \
	metal, and plasteel to alloy, a set of relatively fast tools, can communicate over the Hierophant Network with </b><span class='heavy_brass'>:b</span><b>`

**Comment by ShadowDeath6** [comment]
latest commit makes them less aggressive again, less movespeed and a limit on number of active scarabs
also gives more health to compensate for slower speed, they can take 4 laser shots rather than 3 now

**Comment by Cruix** [comment]
I really don't like this, but it has been testmerged on and off for two weeks now and no one has complained.

**Pull request merged**
