### PR TITLE
Adds a failsafe, just in case

### PR DESCRIPTION
**Pull request by Amelia0010**
This might be usefull in the future, just in case someone manages to break this

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
A failsafe for what? How hard is it to describe your prs, damn it!

**Comment by Amelia0010** [comment]
just in case someone manages to runtime the release characters proc, meaning the proc stops running and doesn't release anyone, meaning everyone is locked in place unless an admin fixes it which most admins won't be able to do, since they don't know how.

**Comment by Amelia0010** [comment]
A failsafe for that

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Thanks babe

**Comment by Amelia0010** [comment]
@AsV9 please, this is quite urgent.

**Pull request merged**
