### PR TITLE
Changeling Revive now regenerates limbs

### PR DESCRIPTION
**Pull request by Super3222**
#### Intent of your Pull Request

It was kind of stupid to regenerate everything, but these.

##### Changelog

:cl:
rscadd: Changeling revive regenerates limbs.
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
query. How is a ninja supposed to steal a ling's brain when cutting their head off and taking their brain isn't actually _their_ brain.  I cut the same ling's head off 4 times and had 4 brains; objective failed.  Do you have to surgically remove their brains for it to be a real brain or what?

**Comment by Super3222** [comment]
> query. How is a ninja supposed to steal a ling's brain when cutting their head off and taking their brain isn't actually their brain. I cut the same ling's head off 4 times and had 4 brains; objective failed. Do you have to surgically remove their brains for it to be a real brain or what?

~~I can buff the objective. Currently it checks for whether the target in brain form or not.~~

Scratch that. You need the very last brain the changeling was using.

**Comment by Jc1469** [comment]
I cut their head off 4 times and they were actually dead still when the round ended, without their head. None of the brains were labelled as "X's brain".Just "brain"

**Comment by Super3222** [comment]
> I cut their head off 4 times and they were actually dead still when the round ended, without their head. None of the brains were labelled as "X's brain".Just "brain"

I've got it. 

https://github.com/yogstation13/yogstation/blob/f589a9ca72e7273ba8d85d7d115da0ad4de6ce75/code/modules/surgery/bodyparts/dismemberment.dm#L113

Changelings drop a decoy whenever you try to spoon out their brain. You'll need to keep their head in your hands to complete the objective.

**Comment by Cruix** [comment]
Fleshmend is intended to be the only changeling ability that regrows limbs.

**Comment by ShadowDeath6** [comment]
That is true but it's dumb when a ling runs (floats) around at max speed as a torso

**Comment by ghost** [comment]
@Cruix on /tg/ fleshmend doesn't regen limbs at all and a limb has a custom ability to do it

that being said i feel like regen stasis should be the only limb-regen ability

**Comment by ShadowDeath6** [comment]
Goon speed regen AND stasis regenerates limbs so both should have it >:^)

**Comment by Cruix** [comment]
0/10 no more headless lings running through the halls chased by all of security

**Pull request merged**
