### PR TITLE
allows you to attach seclite to KA

### PR DESCRIPTION
**Pull request by ghost**
QoL (quality of light)

what do you mean that's not what the acronym means
##### Changelog

:cl:
rscadd: You can now attach seclites to kinetic accelerators.
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
makes mining easier. 
no reason for it. 
no.

playerbase has expressed that mining is too easy.  make it so flashlights only work when held in your hand instead.

**Comment by Time-Green** [comment]
can you add unique sprites?

**Comment by RoboticVodka** [comment]
TG already has this, and with sprites can we just port that instead?

ALSO how the fuck does this make it easier? Wow now you don't have to hold the light in your pocket. What a fucking buff. Plz nerf. OP.

**Comment by Dagdammit** [comment]
Neat. I can make the sprites if you like. There's no easy way to make something in SS13 emit light in a 90 or 180-degree arc, is there?

**Comment by drderp3635** [comment]
Lights are already fucked up enough as is, giving them directional lighting would probably only add to that cancer

**Comment by Dagdammit** [comment]
Yeah I'd be pretty surprised if the answer was yes.

**Comment by Super3222** [comment]
port the sprites

**Pull request merged**
