### PR TITLE
Adds a coffee machine to the break room in mining

### PR DESCRIPTION
**Pull request by matskuman5**
Implements #1115 

:cl:
rscadd: There is now a coffee machine in the break room at mining.
/:cl:

### CODE REVIEW

**Comment by utahclock** [comment]
You need to map merge... Should be 1 line change not 60k

**Comment by Time-Green** [comment]
Beware with this comment names, or you'll summon the rare Super

**Comment by Time-Green** [comment]
I'd like to point out, that the next person that looks for changes through commits, will see matsk screaming about italian diarhea.

**Comment by matskuman5** [comment]
that was supposed to be temporary, crap

**Comment by ShadowDeath6** [comment]
Absolutely unacceptable. This will completely fuck blobs even more than they already are, screw over revheads early and late game, contribute to the growing holoparasite problem, reinforce the emag-revolver meta, and destroy the viability of shadowlings. I don't know how you could even consider this change.

Did it ever occur to you how much this would affect traitors, abductors, changelings, nukeops, deathsquads, and megafauna? This game is a complex balancing act of interwoven checks and balances, maintained by some of the most highly trained and educated spaceman experts in the world, and this PR shows complete disregard for that haphazard yet workable tapestry which we have spent five years holding together with duct tape and bubblegum.

If by some miracle this is merged we may as well set the probability of all gamemodes to zero except extended so that the playerbase can at least eke out some meager entertainment from roleplay, since any semblance of balance will be utterly and completely destroyed.

**Comment by ghost** [comment]
Absolutely unacceptable. This will completely fuck blobs even more than they already are, screw over revheads early and late game, contribute to the growing holoparasite problem, reinforce the emag-revolver meta, and destroy the viability of shadowlings. I don't know how you could even consider this change.

Did it ever occur to you how much this would affect traitors, abductors, changelings, nukeops, deathsquads, and megafauna? This game is a complex balancing act of interwoven checks and balances, maintained by some of the most highly trained and educated spaceman experts in the world, and this PR shows complete disregard for that haphazard yet workable tapestry which we have spent five years holding together with duct tape and bubblegum.

If by some miracle this is merged we may as well set the probability of all gamemodes to zero except extended so that the playerbase can at least eke out some meager entertainment from roleplay, since any semblance of balance will be utterly and completely destroyed.

**Comment by ghost** [comment]
YOU SON OF A BITCH I WAS GOING TO COMMENT THAT 

DELETE YOUR COMMENT I THOUGHT OF IT FIRST SHADOW

**Comment by Time-Green** [comment]
This will come in handy, since coffie blocks freezing and some poisons including morphine.

**Pull request merged**
