### PR TITLE
You can now light cigars on burning people

### PR DESCRIPTION
**Pull request by ActualRory**
Ports https://github.com/tgstation/tgstation/pull/31081

:cl: RandomMarine
add: You can now light your cigs with people that are on fire. The surgeon general is spinning in their grave.
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Important change 👍

**Comment by Ratvar** [comment]
Can you lit papers on burnt people?

**Comment by Alexandria404** [comment]
Do you get a fancy text saying how cool you are similar to lighting cigs with a welding tool?

**Comment by Partheo** [comment]
@alexandria404 [user] lights [src] with [M]'s burning body. What a cold-blooded badass.

**Pull request merged**
