### PR TITLE
Slavemaster fix

### PR DESCRIPTION
**Pull request by Cruix**
Fixed the slavemaster cartridge not working

### CODE REVIEW

**Comment by Time-Green** [comment]
Should probably remove slavemaster from value-pac

**Comment by Cruix** [comment]
Value-pak does not have it.

**Comment by Time-Green** [comment]
Yesterday it did. Unless it got stealth merged, pretty sure value-pak has it.

**Comment by Cruix** [comment]
It had it for the same reason the HoP cartridge had it, and this PR fixes it.

**Pull request merged**
