### PR TITLE
Ported antagonist datums from tg

### PR DESCRIPTION
**Pull request by Cruix**
Ported https://github.com/tgstation/tgstation/pull/20591 and related fixes

I might have accidentally broken some cult and clockcult stuff so I'll testmerge this before merging it.

### CODE REVIEW

**Comment by enailz** [comment]
Wtf is a datum antag

**Comment by matskuman5** [comment]
Wtf is a datum antag

**Comment by Time-Green** [comment]
Currently: a round type picks antags and stuff, giving other antags does weird.
Datum antags: You can have changeling malf blob AI cult

**Comment by oisin100** [comment]
Oh.. /TG/ Finally did this? Crap, Now i have to fulfil my promise of an update from /TG/..

**Comment by matskuman5** [comment]
Time, what the fuck are you saying

**Comment by ShadowDeath6** [comment]
Still not entirely sure how datum antags will change anything outside of future gamemodes. Hopefully this doesn't cause cult and clockwork to happen in the same round without intervention.

**Comment by Rafael450** [comment]
Would be funny to happend in some rounds a bunch of gamemodes together, but every round would make yog from Low RP to NO RP

**Pull request merged**
