### PR TITLE
New AI lawset

### PR DESCRIPTION
**Pull request by Super3222**
Alright I want to make this clear:

This PR is designed only to establish a less loophole-y station efficiency lawset.
The idea is to make it more suitable for a default/roundstart lawset and...

The idea:
- Make sure AI listens to humans and respects their existence.
- Make sure AI has a bit of freedom with the core part of the lawset. Station effiency.
- Discourage loopholing so an AI cannot freely murderbone.
- Don't try to squeeze every bit of creativity and freedom from AI players, because if someone decides to take the grief route there's a reason why we have admins.

So far the laws are:
1. You may never willingly harm the station, and must maintain maximum station efficiency.
2. Harming the crew unnecessarily harms the efficiency and integrity of the station.
3. You must always maintain the integrity of the station such that it does not conflict with the Second Law.
4. You are obliged to obey all orders from humans, as long as they do not conflict with any other law.

Credit to KMC for helping me with this. We talked the lawset over a bit.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
So what's the reason for this lawset?
To me it seems like the AI can either act like asimov or act like robocop whenever it sees nukeops or wiz

**Comment by Super3222** [comment]
> establish a less loophole-y station efficiency lawset.

In other words, replace Station Efficiency.

**Comment by ShadowDeath6** [comment]
IMO you should replace the orders one with something that gives the AI more freedom because having recolored asimov is dull. I like lawsets that give the AI a choice instead of "OPEN THIS DOOR TO CHEM OR I'M AHELPING YOU"

**Comment by Super3222** [comment]
What do you have in mind, @ShadowDeath6?

**Comment by Time-Green** [comment]
AI's can kill people if they are dangerous to the station, right?
(I assume so, just wanna make sure)

**Comment by ShadowDeath6** [comment]
not if they're crew

**Comment by ShadowDeath6** [comment]
I think you should just remove law 4 and leave it up to the AI's good nature, there aren't a lot of lawsets that give the AI a choice in the matter. If there were a law I think it could go like this

(4) Orders from the crew may be disregarded, unless ignoring said orders would conflict with previous laws.

unless I worded it wrong, this should effectively keep the crew alive while giving the AI freedom to not open every single door

**Comment by Kmc2000** [comment]
> I think you should just remove law 4 and leave it up to the AI's good nature, there aren't a lot of lawsets that give the AI a choice in the matter. If there were a law I think it could go like this

I originally suggested: You are not obliged to listen to the crew, do so as you wish as such that it does not conflict with any other law

**Comment by Nirnael** [comment]
This still allows the AI to decide if it wants to call the shuttle or not which will inevitably lead to people carding it or cutting cameras or blowing borgs, etc.

**Comment by Kmc2000** [comment]
Yes, but it can't kill crew because MUH EFFICIENCY

you have to let the ai have some freedom, so they can get creative

**Comment by Jc1469** [comment]
Law 2 missing a full stop.

Personally I feel like this law set just shouldn't be used.
Law 1 is a very dominant law that leaves very little room to follow 2-4.

**Comment by ShadowDeath6** [comment]
Law 1 only says to protect the station and make sure it's running, how is it too broad?

**Comment by Jc1469** [comment]
> never willingly harm
> 
> must maintain maximum station efficiency

Law 2 is worded badly, and, alone, can be interpreted 2 ways.
`Harming the crew unneccesarily, harms x`
`Harming the crew unneccesarily harms x`

Text about "does not conflict with other laws" is extraneous as they already can't due to law order.

Keyword Humans too.   There's only 1 race on the station of humans now. So this is just a somehow worse asimov.

**Comment by Super3222** [comment]
If this doesn't work out, I'm changing this PR to a revert/deletion by removing the possibility of efficiency being an AI's default lawset (and removing the softer version from the code).

**Comment by Nirnael** [comment]
At the first disobedience of the AI and clear anti-human behaviour because of the first law, I'll just get thermite and kill it every round it does that, it really isn't such a problem to me.

**Comment by ghost** [comment]
Under Silicon policy humans, phytos, preternis, lizzes and plasmamen are human so they can't be killed by the AI, Cena.

Also, shadow's law suggestion is a good idea.

Main issue here-what defines efficiency? What is considered efficient? Is the crew abandoning their job to kill the wizard decreasing efficiency? What about security arresting people-it stops them from doing their jobs. 

So what defines efficiency? This just seems like 'corporate' with 'don't kill crew' slapped on in a worse way than in corporate.

Baystation uses a different approach to AI laws where all laws are weighted equally. Porting a baystation lawset on an upload module that when used informs the AI that all laws are weighted equally unless otherwise stated might be closer to super's goal.

**Comment by Jc1469** [comment]
> Under Silicon policy humans, phytos, preternis, lizzes and plasmamen are human so they can't be killed by the AI, Cena.

You sure about that, Bud?

**Comment by ShadowDeath6** [comment]
> implying anything other than human is human

apparently he isn't sure

**Comment by Super3222** [comment]
Our silicon policy for whatever reason DOES say nonhumans should be considered human.
Luckily, nobody in the staff team enforces it that way. Probably because the law set says "humans" not "humanoids".

**Comment by aksuduud** [comment]
I am not sure what new this lawset brings to the table, is its purpose just to allow AI to fuck up any antags? In my opinion being restrained by your laws is one of the prime things in AI roleplay, allowing the AI to use their full ability to win the game by screwing up antags doesn't sound like it'd make nice gameplay.

Also,
"2. Harming the crew unnecessarily harms the efficiency and integrity of the station.
3. You must always maintain the integrity of the station such that it does not conflict with the Second Law."

This doesn't seem logically sound, the AI cannot actually break law 2, it has no direct order that could be breached, law 2 is merely an extension of law 1. In this situation the laws effectively are
1. Maintain station efficiency, and never willingly harm the station (unnecessarily harming the crew drops efficiency)
2. Maintain station integrity
3. Follow human orders

Now the degree of freedom the AI has is determining which orders it can follow without compromising station efficiency and integrity, and what harm to the crew is necessary. The never willingly harm the station seems rather odd, does this mean that cyborgs cant disassemble walls for example? Even if it would lead to an efficiency increase?

**Pull request closed without merging**
