### PR TITLE
does the things

### PR DESCRIPTION
**Pull request by Amelia0010**
@yogstation13/council 

#### Changelog

:cl:  
rscdel: The drone dispenser has been removed from the testing lab. Print drones from robotics from now on.
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
salt pr

**Comment by Ratvar** [comment]
drones still being able to print more respawnes from robo/R&D, duh, what will change

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
image

**Comment by Amelia0010** [comment]
image

**Comment by Super3222** [comment]
the drone wars have begun

**Pull request merged**
