### PR TITLE
[s]Fixes lavaland waste APC's

### PR DESCRIPTION
**Pull request by Time-Green**
closes https://github.com/yogstation13/yogstation/issues/2215
:cl:
fix: Fixes being able to place an APC in lavaland and lag the server/powe whole lavaland
/:cl:

### CODE REVIEW

**Comment by McDonald072** [comment]
fun removal

**Comment by Alek2ander** [comment]
#2222 wasted on a bugfix

**Comment by Super3222** [comment]
As long as it's not #3222 it's okay

**Comment by Cruix** [comment]
Why not just use always_unpowered?

**Comment by Time-Green** [comment]
That would still allow people to place APC's in the lavaland wastes

**Comment by Time-Green** [comment]
That would still allow people to place APC's in the lavaland wastes
They wouldn't do anything, but reasons

**Comment by Cruix** [comment]
That's how it works with space, why are the lavaland wastes magically immune to having a useless machine placed in them?

**Comment by Time-Green** [comment]
Because placing an APC on a rock wall on a strange planet is stupid?

**Comment by Cruix** [comment]
But you can still place air alarms, newscasters, computers, air pipes, wires, and machines there.

**Comment by Time-Green** [comment]
Want me to change it?
EDIT: I think I can quess the answer

**Comment by Time-Green** [comment]
Done, sorry for commit spam, didn't feel like doing it properly and just used the web version

**Comment by drderp3635** [comment]
outlet

**Pull request merged**
