### PR TITLE
New brig

### PR DESCRIPTION
**Pull request by Amelia0010**
My redesign of the brig. Heavily inspired off of this: https://github.com/HippieStation/HippieStation/pull/6008

scrnshot1
scrnshot2
scrnshot4
scrnshot5

#### Changelog

:cl:  
experimental: Re-designed brig
/:cl:

### CODE REVIEW

**Comment by Alexandria404** [comment]
Also  FIRST!!!11
Nice, like it.

**Comment by Kmc2000** [comment]
This is just hippie's brig

**Comment by Amelia0010** [comment]
You see the bit where it says "heavily inspired off of this:" and then links to a hippiestation PR?

**Comment by ghost** [comment]
Atleast copy the brig of a good server

**Comment by utahclock** [comment]
Gross

**Comment by ghost** [comment]
wow!

it's bad

**Comment by Jc1469** [comment]
I like how easy the armory is to break into.

**Comment by Moja10** [comment]
What is the purpose of reshuffling the locations of so many different things for seemingly little reason at all? Why remove the paths commonly used to break into brig and replace them with nonsense (like the left maint that led to gulag dock now being replaced with airlock to det's office.) Why the hell is the detective's office so big? Why is the lawyer's office so big? This is a high effort PR but why why why

**Comment by Zostroll** [comment]
This makes perma escapes much more do-able as the arrivals airlock is closer.

**Comment by matskuman5** [comment]
Why is interrogation in the perma / labor wing

Why are the detective's AND the lawyer's offices doubled strangely like that

Many of the rooms are empty, weirdly shaped, too big or just designed weirdly. For example the detective "storage" room is huge

Why are all the medical equipment near isolation, instead of the warden's office or the sec equipment room

Double airlocks to the sec office look kinda weird

**Comment by grubstank** [comment]
I have concerns similar to Zostroll's and Matskuman's. 

I feel that the detective has been given way too much space, and that the medical facilities have been cut back too much - at least put them behind their own door.

Why is the interrogation room sequestered deep down the perma hallway? It's one of the few 'roleplay' sec rooms that actually sees use - putting it back there makes it much more of an inconvenience. 

I think you should add wall mounted flashers to the perma cells. Sec shouldn't have to play yakety sax every time they want to move around a perma prisoner.

I like the new armoury design (though I feel that front-facing airlock is inconveniently placed)

Also, what's up with the HoS' disposals in those screenshots?

Anyways - My suggestion would be to put the first aid stuff where the interrogation room is, and cut back the detective's space to make an interrogation room that's connected to the main brig area. I could imagine a couple ways you can make that current interrogation space into a combined sanitarium/morgue/first aid room, though putting that much in there might make it too crowded. (and also add those wall flashes to perma)

**Comment by Amelia0010** [comment]
meh, it's bad

**Pull request closed without merging**
