### PR TITLE
nerfs stuntalismans

### PR DESCRIPTION
**Pull request by Amelia0010**
requested by @ratvar 

:cl:
tweak: Nanotrasen has begun shielding their crewmembers from the mute capabilities of blood cultists' stuntalismans (READ: stuntalismans don't mute)
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
Now we can watch together as the cult win rate plummets to near zero!

**Comment by simonset55** [comment]
Just close this, don't remove stun papers

**Comment by ghost** [comment]
Without stun talisman the cult will always lose. Retvar is an idiot please never listen to them.

**Comment by Time-Green** [comment]
Stun talismans are disgustingly OP. But, they are also the cults only way of stealthy conversion.

**Comment by Amelia0010** [comment]
they now don't mute, and don't stun for 30 fucking seconds, cause jesus fuck

**Comment by Moja10** [comment]
So what you are saying is that the cult will be immediately revealed because the person who is stun talisman'd will immediately begin screaming gibberish about narsie and send the entire station on a validhunt that ends with the 3 - 4 roundstart cultists getting gangbanged by the entire crew + sec because one dude started screaming gibberish? Shit PR, stun talisman muted for a good reason

**Comment by Time-Green** [comment]
@Moja10 emp talismans exist

**Comment by ma44** [comment]
Probably be better to just separate the functions into their own two talismans, or help the cult out by saying that EMP is a good alternative to muting a target.

**Comment by ghost** [comment]
No.

Look, just no. The cult needs hard stuns to convert because they can't immediately convert like revs or gangs can. That's the issue with conversion gamemodes. They need hard stuns to do shit.

Clock cult has a terrible time converting because we have guvax, not geis, which does not stun, and so unless you get some willing converts early on you'll never progress to conversion sigils which let you do the work for you. 

blood cult NEEDS a hard stun and mute to convert anyone, and forcing the cult to pop an EMP talisman is an immediate sign to literally everyone that there is a cult because an EMP just went off and EMPs keep going off and obviously that's not an EMP kit. And since cult isn't metashielded that means everyone worth a fuck will know about it.

Aside from that I don't know how you expect yogstation players to actually be intelligent enough to stun and then use an EMP talisman when the majority of them barely know how to bang two rocks together. 

Watch cult winrate plummet to zero for no reason, today on completely fucking unneeded nerfs. One use, obvious melee inhand that stuns and mutes someone. That also hurts the cultist.

THAT'S not the problem. That's actually fairly reasonable because anyone with a fucking stunprod can do just about the same, but they get killed because it's loud so whatever. The point remains it's a melee stun that's one use and that's fine.

If you want something retardedly strong, then look at how absurdly more efficient it is for the cult to kill and sacrifice people rather than make constructs. You get shells for practically free, the cult archives and forges and so forth are indestructible because you don't have object damage, you can make soulstones out of fucking reinforced glass and fill them with manifest ghost runes because balance, and the cult can get shielded hardsuits they can recharge at pylons within minutes of roundstart. There's your fucking imbalance. The stun talismans aren't the problem.

**Comment by Ikoden** [comment]
The reduction of stun time is okay for me, but don't remove silence and stuttering. Leave them like they are or if you really want to nerf them - leave silence at 5 and lower stuttering from 15 to 10.

**Comment by ShadowDeath6** [comment]
can you explain why an item that immediately reveals the user as cult if anyone sees it being used needs a nerf to immediately reveal the user as cult to the entire station

I don't care that much about the mute but removing any restriction on speaking through stutter or cult slur is a stupid idea and a horrible restriction to place on players becsuse carrying an emp talisman can fuck over a ton of stuff, including shorting out the apcs to the cult base which renders all doors inoperable outside of a crowbar for the next 3 minutes or however long it takes to recharge

**Comment by Ratvar** [comment]
" renders all doors inoperable" - Teleport runes/hit cultwall with tome when?
"reveals the user as cult if anyone sees it being used" - Aka, when some idiot uses stunpaper near 2 people? That's problem of someone braindamaged who does so right now.

**Comment by ma44** [comment]
>changelog says crew members are immune to the mutes
>Halfs the stun duration, removes stuttering, cult stuttering and jittering 
🤔

**Comment by ghost** [comment]
No @ratvar

None of what you said applies.

Completely fucking over your cult base, damaging any cultist preternis nearby, alerting the Ai to where the emp went off nigh immediately and making it difficult to even leave the fucking area unless you have a teleport rune every ten feet because airlocks are everywhere is a bad idea. Don’t force cultists to use emp talismans just to get one convert.

The lack of mute means everyone stunned will instantly shout ‘help cult’ and that’s the end of the cult.

**Comment by ShadowDeath6** [comment]
>cultwalls

the things you need constructs or runed metal to make and instantly reveal the cult?

>teleport runes

teleport runes generally aren't that useful from getting from one room to another room unless you really want to go that route which is a waste of time

**Pull request closed without merging**
