### PR TITLE
woopsie

### PR DESCRIPTION
**Pull request by Amelia0010**
less snowflakey, now it's basically just the AI check

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
your pr names are almost as bad as people who say "x is broken, fix it" then refuse to elaborate

**Comment by ThatLing** [comment]
you broke travis 👏

**Comment by Time-Green** [comment]
You’re the reason viewing commit history is a pain

**Comment by Partheo** [comment]
This is legitimately worse than a MRTY pr

**Pull request closed without merging**
