### PR TITLE
Abandoned Asteroid

### PR DESCRIPTION
**Pull request by Time-Green**
:cl:
rscadd: Reports of malfunctioning mining shuttles have been... reported?
/:cl:
Re-adds the good ol' asteroid. It's now all abandoned looking. It can only be reached by space exploration and a rogue mining shuttle event.

Also adds rogue shuttle events. Not really an event, but it sounds cool. Like, there's a 1% chance it'll happen.

I made sure the escape shuttle doesnt land at the asteroid

### CODE REVIEW

**Comment by Time-Green** [comment]
For testers, change error_chance on the mining shuttle console to 100

**Comment by Time-Green** [comment]
Transistion is still broken, hold on

**Comment by Ratvar** [comment]
Make escape pods have random chance to land here instead of lavaland when jumpstarted?

**Comment by Time-Green** [comment]
Eh, I’d need to setup special escape pod spots, maybe later

**Comment by Time-Green** [comment]
Oh yeah and looping does work I forgot to sync my changes

**Comment by AsV9** [comment]
Screenshots please ;^)

**Comment by Time-Green** [comment]
schermopname 12
schermopname 13
schermopname 11

**Comment by AsV9** [comment]
Add hacking the shuttle console to make error_chance 100 when?

**Comment by ghost** [comment]
@Time-Green Honestly, I don't see a reason why this isn't an option for the mining shuttle to go there normally as a kind of safer lavaland, lavaland having the good shit and this being mostly safe but lacking most items since it's already been stripped bare.

**Comment by AsV9** [comment]
That can be done in a second pull request, @AdamElTablawy

**Pull request merged**
