### PR TITLE
nerfs dual esword

### PR DESCRIPTION
**Pull request by ShadowDeath6**
flip on your own time

:cl: ShadowDeath6
rscadd: Alt+click a dual esword to toggle flipping while attacking.
/:cl:

### CODE REVIEW

**Comment by oisin100** [comment]
Ffs. Now Dual esword is shit.

**Comment by Time-Green** [comment]
unplayable 👎

**Comment by Super3222** [comment]
> removes flipping, now you only spin

nah

> reason being I liked the spin more than the flip and the flip kind of concealed it

shit reason

> flip on your own time

DNM

**Comment by Super3222** [comment]
No, really. The flipping was awesome and a parody of Darth Maul. In fact, the entire weapon was a parody from Darth Maul & the SW prequels. So let it be.

**Comment by X-TheDark** [comment]
Absolutely 0 reason for doing this. Dual Esword is not exactly what you'd call "stealthy equipment". I'll close this soon enough if there are no arguments for this being merged.

**Comment by ghost** [comment]
@x-TheDark

Use your eyes he said nothing about stealth at all

@Shadowdeath6 make it a toggle on the dropdown menu/prefs to flip or spin

**Comment by ShadowDeath6** [comment]
removing the flip just makes the thematic spin affect more prominent, I don't think it needs a config option.

**Comment by ShadowDeath6** [comment]
don't close it just yet kiddo

**Comment by ShadowDeath6** [comment]
merg dis

**Comment by Super3222** [comment]
> making NO FLIP default

That's pretty lame. At least it's included in the examine though.

**Comment by ShadowDeath6** [comment]
I'm making the default mode active by default. Sue me.

**Comment by Super3222** [comment]
> @x-TheDark
> 
> Use your eyes he said nothing about stealth at all

@AdamElTablawy Pretty Sure X was joking...

**Pull request merged**
