### PR TITLE
Gives some lavaland ruins more stuff

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

I felt like some of the ruins were lacking a bit.

Added 50 blocks of mythril near the sand pile for obvious reasons. I feel like the Hermit should be able to scavenge around the lavaland, and bring resources back to him. Given that the sinew tent is pretty much a survivor pod with open doors I think it's pretty approrptiate to give him some.

I added an empty APC frame, APC circuits, and a crew monitor board. I was intending on adding some more boards, but I didn't really see anything else fitting in. Nevertheless, the NT surveyor is now more than a crashed pod with ERT armor. My intention was for players to find a way to restore power to the pod, and to make the pod into some sort of control center.

The red arrow will direct you to where the crew monitor board is "hidden".

#### Changelog

:cl:
rscadd: The Hermit now has 50 blocks of mythril avaliable to him - intended so he can get out more and create sinew tents.
rscadd: The NT surveyor now comes with a few circuitboards.
/:cl:

### CODE REVIEW

**Comment by MayhemSailor** [comment]
I think this is a good start to these two. B.Z!

**Comment by Slinky5890** [comment]
Really liking this work on extra/tweaked lavaland ruins, keep it up.

**Comment by Time-Green** [comment]
Could you give the hermit a portable seed extractor?

**Comment by Super3222** [comment]
> hermit a portable seed extractor?

That's probably something to consider, but I want to see how well they do with the mythril first.

**Pull request merged**
