### PR TITLE
Adds buyable shuttles

### PR DESCRIPTION
**Pull request by Amelia0010**
Ports this PR: https://github.com/tgstation/tgstation/pull/21398, as well as the flatten_list() proc from /TG/, and a bunch of shuttles from TG, Para, Bay, & Tau Ceti.

### Intent of your Pull Request

Lets the captain buy a shuttle each round, using Cargo's budget. I didn't add a price to things like the STV5, as they would just be used as an armoury on revrounds.

The prices are as follows:
Mini shuttle: 6000
Goon shuttle: 7500
Meta shuttle: 7500
Pubby shuttle: 7500
Department shuttle: 7500
Asteroid shuttle: 10000
Delta shuttle: 12500
Tau Ceti shuttle: 12500
Bar shuttle: 15000

Some shuttles can only be bough if the communications console is emagged. Those shuttles, and their prices, are as follows:
Scrapheap shuttle: 2500
Oh, hi daniel: 5000
Wabbajack shuttle: 7500
Snappop shuttle: 15000
Nuke-ops shuttle: 20000

An emagged comms console can override the shuttle purchase that the captain has already made, but can only do so once, as with normal consoles

Also adds the flatten_list() proc, as the shuttles needed it.

Added the plastitanium wall from TG, except you can only get it via either mapping or admin spawn. When destroyed it doesnt drop anything.

Also ports the asteroid shuttle, delta station shuttle, the scrapheap shuttle, and the pubby station shuttle from TG. And the department shuttle from Paradise  We had the asteroid shuttle as a datum, but not the map file itself. 
#### Changelog

:cl: Kor
rscadd: The Captain can now purchase alternate escape shuttles from the communications console. This drains from the station supply of cargo points, and you can only do so once per round, so spend wisely.
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Could this be moved so that the QM does it instead of the captain?

**Comment by Moja10** [comment]
One of my favorite features on /tg/. I think it's only for the Captain because there are some quite griefy shuttles that can be bought and the Captain should bear the responsibility of buying a stupid unfitting shuttle, like the tiny Daniel one during high pop.

**Comment by Amelia0010** [comment]
> Could this be moved so that the QM does it instead of the captain?

The captain is ultimately in charge of the entire station, and its potential evacuation, and as such he bears the responsibility of not choosing the ministation shuttle on highpop, not the QM.

**Comment by Partheo** [comment]
Yeah, Moja's point makes sense. I just think QM would be a good fit since he oversees cargo points and logistics(transport), which purchasing a shuttle would fall under.

**Comment by ShadowDeath6** [comment]
some of these shuttles are really griefy and awful, not a fan :-1:

**Comment by Amelia0010** [comment]
And the really griefy and awful shuttles, such as the armoury shuttle or the supermatter shuttle aren't available to buy.

**Comment by ShadowDeath6** [comment]
ah yes the chasm shuttle and the wabbajack shuttle are not griefy or round changing in any way

**Comment by AsV9** [comment]
they`re insanely cheap though.
idk. getting 25k credits is easy, just ship a stack of plasma to CentComm.

**Comment by Amelia0010** [comment]
well, got any suggestions for the prices?

Right now the prices are exactly the same as they are on TG

**Comment by Ratvar** [comment]
Remove easy money shit like moneytrees, before you do all shuttles cost literally nothing untill moneytrees

**Comment by ghost** [comment]
remove money trees or this is aids

**Comment by fonedsky** [comment]
Here's what's gonna happen
'hehe i'm a funny guy' captain buys the HONK shuttle 10 rounds in a row when this is implemented
everyone gets sick of it and it stops OR the feature gets reverted
Unless every captain in yogstation needs psychiatric evaluation, I've seen this feature in /tg/ and the times where it was used badly usually either only resulted in hilarity or a very small amount of death. The HONK shuttle in particular needs you to TRY to die, or push people around - which is a fair concern if they're standing on the edge, but if you're tryna push someone to the chasm for no reason, that's grounds for a ban (and easily escapable, too).
I don't know what the wabbajack shuttle is.
It would be very easy to fliptwist into the supermatters in the SM shuttle and kill everyone, so I'm okay with that. Never seen STV5.

**Comment by Amelia0010** [comment]
> 'hehe i'm a funny guy' captain buys the HONK shuttle 10 rounds in a row when this is implemented
everyone gets sick of it and it stops OR the feature gets reverted

Honk shuttle isn't buyable.

The only buyable shuttles now are: 

1. Metastation shuttle: Slightly bigger than normal, has a command area, brig, medical, and storage, like the normal shuttle
2. Ministation shuttle: Slightly smaller than normal, has medical, brig and command as far as I remember.
3. Goon shuttle: about the same size, I think, and has brig, command and medical, I think.
4. Bar shuttle: Same size as current one, has a brig and command area

**Comment by fonedsky** [comment]
damnit, long gone are the days of watching ascended slings fall into chasms and laughing your fucking ass off as a ghost

**Comment by killerx09** [comment]
To be honest Armoury Shuttle on Rev rounds is a pretty good idea.

Because by that point, Security must have lost control of Cargo and Revs are probably in control and hunting for the last head of staff hiding in a locker. It'll stop admuns having to call the ERT/Deathsquad on the off chance the round drags on for 2< hours.

Just make it expensive.

**Comment by Amelia0010** [comment]
> Just make it expensive.

And here we run into the money fruit problem. While all the current shuttles provide no gameplay benefit, but a mostly aesthetic one, adding something like that would be a balance change.

**Comment by Amelia0010** [comment]
Also, if anyone has any suggestion for any price edits, i'm up for changing them to whatever, as long as it isn't "money trees are unbalanced, so we're gonna need you to use money trees to get these, as it would be too easy otherwise"

**Comment by Partheo** [comment]
Well, it's not only money trees that generate absurd amounts of points.

I would increase the prices a fair amount and leave them at a point where this feature wouldn't be used every round. Make it difficult to get things like a luxury shuttle, for example.

**Comment by Xantam-13** [comment]
Is there an admin undo button?

**Comment by Partheo** [comment]
Admins can pick what shuttle is being sent, so they can always just change it.

**Comment by Xantam-13** [comment]
I was thinking more to refund points spent on stupid things for cargo.

**Comment by Amelia0010** [comment]
> Is there an admin undo button?

You can change the shuttle manually. You can't refund the points, but you can't refund the points spend on 40 toy crates either, so eh.

> I would increase the prices a fair amount and leave them at a point where this feature wouldn't be used every round.

If you had to put a number on "fair amount", what would it be?

**Comment by Partheo** [comment]
I don't really know how many points are a lot, because I haven't played cargo since shit like data disks and money trees that gave you 20k points were added.

**Comment by Partheo** [comment]
Let me reiterate: I don't want to see a new shuttle every round. Make it expensive enough that it won't happen every round.

**Comment by ghost** [comment]
you can refund the points if you var-edit the shuttle subsystem @nichlas0010 

also, regular shuttles don't need high prices, just memey ones. Honestly I don't see the issue with different types of shuttles and if anything it's funny.

Heck, if it was up to me I'd make the default shuttle a piece of shit garbage bin and force you to buy a luxury ride home :^)

**Comment by ghost** [comment]
emagging the console should let you purchase the scrapheap challenge or a syndie shuttle

**Comment by CrazyDrakkon** [comment]
> To be honest Armoury Shuttle on Rev rounds is a pretty good idea.

> Just make it expensive.

And make ones like these only available during code red or delta?

**Comment by CrazyDrakkon** [comment]
Waiting to see how the not-yet-added shuttles look so I can map more.

**Comment by Amelia0010** [comment]
I'll get pictures of the shuttles I added when I get home in a couple of hours

**Comment by Amelia0010** [comment]
Asteroid shuttle:
image

Department shuttle:
image

Pubby Station:
image

Delta Station:
image

Scrapheap (emag only):
image

**Comment by CrazyDrakkon** [comment]
Holy crap I hope 18x29 is as big as it gets.

On a side note I'd like to make some gimmicky/memey ones for ya.

**Comment by CrazyDrakkon** [comment]
Take this and do whatever ya want with it~

[emergency_festivecabin.zip](https://github.com/yogstation13/yogstation/files/1436453/emergency_festivecabin.zip)

**Comment by Amelia0010** [comment]
Tau Ceti escape shuttle: 
image


Their chair sprite has been inserted into chairs.dmi, but isnt used anywhere except for on this shuttle

**Comment by Amelia0010** [comment]
Modified nuke-ops shuttle:
image

**Comment by ghost** [comment]
lol what show pics

**Comment by ghost** [comment]
oh wow you posted it as i commented fuck u

**Comment by ghost** [comment]
>>no turrets

what is this

**Comment by Amelia0010** [comment]
> what is this

A hugbox?

**Comment by CrazyDrakkon** [comment]
50k or something absurd for fully armed syndie shuttle?
Also non-wrecked wizard shuttle?

**Comment by ghost** [comment]
>hugbox

>it comes with 2 syndibombs

>hugbox

**Comment by Amelia0010** [comment]
;^)

**Comment by Amelia0010** [comment]
The difference between turrets and syndiebombs is that turrets have a 100% chance of killing, whereas the bombs have a 99% chance of killing.

**Comment by ghost** [comment]
>dodgeable, breakable turrets that are blocked off by windows have a 100% percent chance of killing

>bomb that can be immediately triggered at max size via bombcore removal has only a 99% chance of killing 

lmao

**Comment by Amelia0010** [comment]
What I meant is that the turrets will fire constantly, and most definitely kill someone, whereas bombing takes a person to choose to do it

**Pull request merged**
