### PR TITLE
Abductor Headsets

### PR DESCRIPTION
**Pull request by Super3222**
- Gives abductors their own headset.
  Abductors should have first hand had their own headset, considering they are not aligned with the syndicate and operate on their own terms.

#### Super3222

:cl:
rscadd: Abductors now have their own emp-proof headsets.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
Make it EMP proof so they don't have to worry about giving people the EMP implant and shorting their headsets.

**Comment by oisin100** [comment]
You might want to change the channel, so people who steal the headsets cant speak on the syndicate frequency.

**Comment by FluffySurvivor** [comment]
> You might want to change the channel, so people who steal the headsets cant speak on the syndicate frequency.

feature

**Comment by oisin100** [comment]
> feature
> 
> considering they are not aligned with the syndicate and operate on their own terms.

**Pull request merged**
