### PR TITLE
ID fluff

### PR DESCRIPTION
**Pull request by Time-Green**
Been a little inactive lately, school has been consuming me. I hope this makes up for it.

Gives every single job a completely unique ID card. 

The colors do mean something, the big lines in the middle give away the department, and the smaller ones the job in that department.

For example, Janitor has a green line, because he is civilian, and the other thing purple, because janitors are purple. I tried to make this as convenient as possible, but there's a limit.

Some examples: (Not all jobs included)
id s and stuff
Oh yeah and this uses ovelays and stuff. And I know QM isn't a head, but it looks cool.
Custom job names will look like the classic ID's

:cl: 
rscadd: Gives every job a unique ID. It's very pretty and the clowns ID will probably give you an epileptic attack.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Err? It's supposed to work...

**Comment by Alek2ander** [comment]
Why not use background and middle band instead of middle band and tiiiny rectangle?

**Comment by Time-Green** [comment]
Uhh, I just did. I didn't think it meant anything
And I used all three, background, middel band and rectangle.

Rectangle and middle band share the same color.

I thought about making rectangle represent the gender, but discarded it.

EDIT: I understand what you mean now, but I think this looks better

**Comment by Dragonforcefive** [comment]
Cool stuff. I mean it's fluff, but cool.

**Comment by Time-Green** [comment]
kill meeeeeeee
Optimized some of the colors, they were to bright IMO

**Comment by matskuman5** [comment]
My god it's beautiful

MERGE NOW

**Pull request merged**
