### PR TITLE
Fixes Marrow Weaver Speed

### PR DESCRIPTION
**Pull request by ghost**
I made the marrow weavers slow down :)
#### Changelog

:cl:
rscadd: Marrow weavers no longer rival F-16's in speed.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
just completely remove the fuckers, nobody likes them.
VIVA LA REVOLUTION!!

**Comment by ShadowDeath6** [comment]
me when I get assmad

**Comment by Kmc2000** [comment]
Upboat

**Review by Kmc2000 — APPROVED** [review]
Yes, do this

**Pull request merged**
