### PR TITLE
adds channels to in-game say logs

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Adds channels for the in-game say logs.
image

#### Changelog

:cl:  
tweak: the national security ADMINistration can now see where you say stuff.
/:cl:

### CODE REVIEW

**Comment by X-TheDark** [comment]
This is a weird one. What administrative purpose does this serve? I can't quite think as to what you'd be enforcing that requires knowledge of which channel someone said anything.

**Comment by matskuman5** [comment]
>This is a weird one. What administrative purpose does this serve? I can't quite think as to what you'd be enforcing that requires knowledge of which channel someone said anything.

"why did you kill that guy?"

"cap said to execute him"

"but you're an engineer and he said it in security channel"

"*disconnect*"

**Comment by Amelia0010** [comment]
> This is a weird one. What administrative purpose does this serve? I can't quite think as to what you'd be enforcing that requires knowledge of which channel someone said anything.

Slov asked for this, so I assume it must serve some purpose or another.

**Comment by X-TheDark** [comment]
Gotcha.

**Pull request merged**
