### PR TITLE
Adds new ambience by Kayozz11

### PR DESCRIPTION
**Pull request by ghost**
:cl: Audio by Kayozz11 and implementation by Floyd
rsadd: New ambience for areas
soundadd: Ambience by Kayozz11
sounddel: Sounds that super implemented because >wtf is rsc size management. seriously 4mb by like 3 audio files stop the madness
/:cl:

copy pasto below which talks about the sounds. Not all ambience is used because I was either lazy or couldn't find a cool place, feel free to suggest ones I haven't added below.
https://www.youtube.com/watch?v=JZ5KzZvae7M&feature=youtu.be

//ambiatmos – Fit factory, atmos and ruin settings
Ambiatmos
ambiatmos2

///ambidanger – Fit syndie, dangerous, ominious and ruin settings
Ambidanger
Ambidanger2
Ambidanger3

///ambigen – fit anywhere inside a structure
Ambigen

///ambiholy – Fit anywhere in somewhere tranquil like the chapel or botany. Or something mysterious/odd
Ambiholy
Ambiholy2
Ambiholy3

///ambicave  - Ominious, fits caves, ruins, abandoned places or lavaland.
Ambicave

//ambimaint – Maint, factory, engineering or ruin settings (caves too because theres dripping)
Ambimaint

///ambimystery -  Ominious, mysterious . fits ruins, engineering and dangerous places
Ambimystery

///ambinice – Dreamy, nice, tranquil. Not holy enough to be holy but still nice. Fits a planet or dreamscape.
Ambinice
///ambiodd – wacky and nice, also creepy – fit wacky or psychotic places. Abductor ship or maybe when you’re on drugs.

///ambiruin – ominious, slow, creepy, tense fit ruins and dangerous places. Mix of mysterious and creepy in this section
Ambiruin
Ambiruin2
Ambiruin3
Ambiruin4
Ambiruin5
Ambiruin6
Ambiruin7

///ambispace – Spacey sounds.
Ambispace

///ambitech – Tech sounds, fit things like tcomms, ruins engineering AI and robotics. 3 sounds particularly creepy and fits ruins/malfAI better
Ambitech
Ambitech2
Ambitech3

///Ambitesla – Particularly aggressive electrical sounds, fits tesla well.
ambitesla

### CODE REVIEW

**Comment by ghost** [comment]
my commit ment to say "im such a dickhead" not "im suck a dickhead"

**Comment by ghost** [comment]
please dont ban me from this christian repo @Super3222

**Comment by ShadowDeath6** [comment]
two problems I have with `ambitesla.ogg`
1. I don't see a place it's used
2. there's more than one engine and it doesn't really fit singlo

**Comment by ghost** [comment]
read "Not all ambience is used because I was either lazy or couldn't find a cool place, feel free to suggest ones I haven't added below."

you can easily attach it to the tesla to randomly play from that instead of the area.

**Comment by Ratvar** [comment]
add new ambulance sound

**Comment by ShadowDeath6** [comment]
something something don't add unused files since they take up space

**Comment by ghost** [comment]
something something the way yog handles audio actually means I downsized the rsc pack 👌

**Comment by ghost** [comment]
https://i.gyazo.com/6565074e24adc151f9797950c66751a1.png

literaly unplayable without that 55kb of extra space on everyones computer

**Comment by ShadowDeath6** [comment]
the problem I have is that you're adding a file that nobody will ever work with besides you who will either delete the file or put it into the engine ambience, either use the file or don't add it

**Comment by ghost** [comment]
k

**Comment by ghost** [comment]
@Cruix this should be ready, by the way.

**Pull request merged**
