### PR TITLE
New vending machine sprites and minor tweaks

### PR DESCRIPTION
**Pull request by Partheo**
So, continuing what I did in #2578, here are my updated vending machine sprites. This took way too long to do.

Yog currently:
vending 2

What TG has and I tried to port:
vendingtg

The edits I made:
vending

TG's vending machines were boring and uninspired, but cleaner and more consistent than ours. I've gone through all of them and added detail, made them all unique, updated a lot of boring animations, added proper-perspective knock-over sprites, updated the panel icons for each one and also organized the .dmi file into something that wasn't shit. You wouldn't believe how long that took.

Also some of them glow a bit. It looks cool.

Open panels:
capture

Liberation Station (This is my favorite, whoever made this is great):
afb2cdfae4698add4b4cfc7c8a8835b1

Knocking over the VendoMat:
3085d86ac9fbc033786227e809cd8419

SecVend denying:
34066e39dfcb07864b31a0e2a4659f46

Cola and Snack machines:
88979c7d629e2fe09f5b2cbe6201a491
## Other tweaks:
I added a PTech vendor to the HoP office, and moved the ClothesMate into the head's meeting room, replacing a slot machine that was there. The PTech also now requires HoP access to use.
cart
clot

I deleted some unused sprites, such as the Nutri-vend's deny animation.
Cleaned up icon names in the .dmi and in the code. Cola_Machine-off is now just cola-off.
The Liberation Station at centcomm is now open for everyone to use.

:cl:  
imageadd: All vending machines now have new sprites.
tweak: The Liberation Station no longer requires access. FREEDOM!
rscadd: A PTech vendor has been added to the HoP office.
rscadd: A ClothesMate has been added to the Heads of Staff meeting room.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
SEXY SEXY SEXY YES YES YES

**Comment by Cyberboss** [comment]
PR UPSTREAM REEE

**Comment by ghost** [comment]
cyber you are drunk go home

**Comment by Alek2ander** [comment]
Very :+1: , except the knocked over sprites. Why are they so squished?

**Comment by Partheo** [comment]
They just look squished. The size of the front panel is the same in all cases.
They look short because the bit at the top that's extended for perspective is removed and instead added to the side when they fall over. It's odd at first and would take some getting used to (I agree it's different) but I think it's the better way to go.

**Comment by ShadowDeath6** [comment]
knocked over sprites look weird imo, I would make it thinner but I don't have an eye for design

**Comment by Partheo** [comment]
I know the feeling, they looked weird at first but they grow on you. I toyed around with them in-game and it looks fine after you get used to it.

**Comment by ghost** [comment]
@Partheo port this upstream to /tg/

**Pull request merged**
