### PR TITLE
[s] Made bluespace shelter capsules not work on the station.

### PR DESCRIPTION
**Pull request by Cruix**
Requested by GreatBigBen

Shelter capsules no longer work on the station z-level, because 90% of the time they are used to block hallways for no reason.

### CODE REVIEW

**Comment by Stealthkibbler** [comment]
You may want to do the same with Ashwalker sinew tents as they are basically copy/paste code of the capsules.

**Comment by Super3222** [comment]
Good change, but I feel like they should at least work in space.

**Comment by EMT321** [comment]
I believe there are some limited uses to them on the station. Could you make them only trigger in the absence of oxygen, so they can be used in space and Lavaland?

**Comment by Dagdammit** [comment]
From an in-game logistics standpoint, bluespace shelters in space don't make alot of sense; they're inflatable shelters that are supplying air by pumping in the atmosphere outside and refining it, or at least that's what I figured.

But that would be a shame from a meta standpoint, because there isn't much of an alternative. EMT's approach seems like a good solution.

Another could be if you were able to open a maintenance hatch on one of the machines in the back, & trigger a "repackage" option which caused the shelter to pack itself back up.

**Comment by Dragonforcefive** [comment]
I applaud the person who fixed the capsule spawning on station crap. I always get annoyed when some random jackass spawns a shelter in the middle of Central Hallway when I'm Captain or HoS.

**Comment by Cruix** [comment]
Now they always work in space.

**Pull request merged**
