### PR TITLE
Removes Gang Mode

### PR DESCRIPTION
**Pull request by Super3222**
Happy april fools!
and no this pr only makes it worse.

# NOW EVERY APRIL FOOLS DAY THE GANGS DONK AND ZERO-G REVEAL THEIR TRUE IDENTITIES

Donk becomes the CLOWN GANG!

Clown Gang
- Banana's. - 15 cost
- Clown Masks. - 5 cost
- Golden Airhorn - 10 cost
- Bananaium Esword - 30 cost
- Bananaium Eshield - 60 cost
- Tearstache - 10 cost
- Clownbug Delivery (only spawns 3 this time) - 30 cost
- Dark HONK! - 200 cost

Zero-G becomes the MIME GANG!

Mime Gang
- Bottle of Nothing - 10 cost
- Mime masks - 5 cost
- Spellbook that teaches you mimery - 10 cost
- Spellbook that teaches you invisible wall - 10 cost
- Bottle of Mutetoxin - 20 cost
- Spellbook that teaches you the invisible touch (does not come with limits) - 50 cost
- Reactive Stealth Armor  - 30 cost.
- RETICENCE! - 200 cost

Unlike sleeping carp, these gangs can still buy pistols.

like i mentioned before this only happens on april fools so pls merge into master branch

#### Changelog

:cl:
rscadd: On April Fools the Donk gang turns into the clown gang and the Zero-G gang turns into the mime gang!
rscadd: On April Fools the station gets a rare case of clown bugs...
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
!

**Comment by Jc1469** [comment]
how about when its not april 1st gang cant trigger.

**Comment by Super3222** [comment]
IT'S HAPPENING

**Comment by Mrcreepssss** [comment]
OI I WANT TO TRY THESE MORE THAN ONE DAY PER YEAR!

**Pull request merged**
