### PR TITLE
Addes 2 new lavaland ruins

### PR DESCRIPTION
**Pull request by utahclock**
:cl:
rscadd:  Adds 2 new lavaland ruins for your exploration!
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
can we have some elaboration or

**Comment by Super3222** [comment]
Lore behind them?

**Comment by Cruix** [comment]
The second one is just a bigger version of the automated trade outpost

**Comment by utahclock** [comment]
ok i can scrape the second one. didnt know something similar exsisted

**Comment by ghost** [comment]
wtf is the first one

it's a random rusted metal wall with no loot and an empty ai core?

no lore?

no logic?

**Comment by ghost** [comment]
it has rooms to space

in lavaland

**Comment by ShadowDeath6** [comment]
it's burrowed through the entire asteroid to get that spess view

**Comment by utahclock** [comment]
i can fix those tiles tomorrow.

**Comment by Super3222** [comment]
the first one was pretty cool at sight. it just needed some lore, actual maintainable loot, and maybe a challenge.

**Comment by utahclock** [comment]
Ok I can work on adding more spice to it. but for now PR is closed

**Pull request closed without merging**
