### PR TITLE
Steal the Rapid Engineering Device

### PR DESCRIPTION
**Pull request by Super3222**
#### Changelog

:cl:
rscadd: New Traitor Objective: Steal the Rapid Engineering Device!
rscdel: The Syndicate are no longer interested in stealing the CE's magboots.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
CE already has two things to steal

**Comment by Super3222** [comment]
[I'm making the CE's life harder on purpose!](https://github.com/yogstation13/yogstation-old/pull/776#issuecomment-205475396)

**Comment by Mrcreepssss** [comment]
could i be reminded what those two are? hardsuit(boots i think) and...?

**Comment by Super3222** [comment]
It's a fusion between the RCD, RPD, and an airlock painter.

**Comment by Super3222** [comment]
And Cruix, I can't really say much to convince you. The RED is just an interesting tool, unique to our server, which would make it even more interesting for traitors to attempt to steal.

**Comment by ShadowDeath6** [comment]
Remove magboot objective for this

**Comment by Super3222** [comment]
canonically if the syndicate have stolen enough of the ce's magboots that means syndi magboots should be the same speed as the ce's

**Comment by Amelia0010** [comment]
But if every shift is the first shift, then they haven't stolen any 🤔

**Pull request merged**
