### PR TITLE
Zombie Mode, but its simpler and can be merged

### PR DESCRIPTION
**Pull request by Super3222**
#### Changelog

:cl:
rscadd: ZOMBIE MODE!
rscadd: Zombies, attack the crew.
rscadd: Crew, attack the zombies.
rscadd: Whoever makes it to centcom alive wins.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
Zombie Mode
0 classes
0 special mechanics
At the start of the round 7 people = 1 infected person

**Comment by matskuman5** [comment]
Imagine Gang. Take that image, make it 10 times worse. Now think of a gamemode that is literally antags vs. validhunters. Merge that image with the old one. Now make it 10 times worse. Try to picture the WORST possible gamemode you can think of. Think of a station where the gamemode is announced at roundstart, security is blown up at roundstart, and validhunters are given syndicate uplinks. Think of a system where validhunters are rewarded for killing antags, and get more good boy points to buy things like rocket launchers and centcomm adminspawn-only mechs that are stronger than durands. Take that image, and make it 10 times worse. Think of gangs, but with infinite free revives, asspulled reinforcement portals that spew out gangsters. Think of a station where everyone is encouraged to validhunt, people are rewarded for validhunting, and it's literally the basis of the whole gamemode. Take that thought, merge it with TDM, and make it 10 times worse. It's becoming a shit singularity, exponentially and infinitely growing beyond what anyone previously thought to be possible.

If you have never seen this gamemode in action, consider yourself lucky. I wish I had never witnessed this literal garbage fire of a roundtype. I would rather gouge my fucking eyes out with a homeless person's rusty fork than ever have to endure another minute of this absolute disaster. Super, I don't know what was going through your fucking head when you thought THIS would be a good idea, but it should have been a bullet. If I ever have to play through this call of duty bootleg again, I'm going to promptly overdose on amphetamines and hang myself in a hotel bathroom.

I like it

**Comment by Frostben** [comment]
@matskuman5 Im getting the fuck back on ss13 to witness what the actual fuck it is you are talking about.

**Comment by Mrcreepssss** [comment]
zambles!

**Pull request merged**
