### PR TITLE
Adds asay and dsay hotkeys

### PR DESCRIPTION
**Pull request by Time-Green**
**Requested by Slinky**
Hotkey , = asay
Hotkey . = dsay
asay and dsay hotkeys
:cl:
add: Adds asay and dsay hoteys, "," and "."respectively.
/:cl:

### CODE REVIEW

**Comment by Groudonmaster** [comment]
:+1:

**Comment by Alek2ander** [comment]
Please change from "." to something else, "." is radio channel select in normal speech and will be constantly pressed by mistake

**Comment by Time-Green** [comment]
Tell me wich keys to change it to, and I'll do it

**Comment by Cruix** [comment]
Why do we need these hotkeys for admin-only commands? I have never had a problem typing asay or dsay into the command line even when sending multiple messages.

**Comment by Time-Green** [comment]
I don't know either, but it was like no 1. requested by staff members

**Comment by Groudonmaster** [comment]
QoL cruix. Qol.

**Comment by Jc1469** [comment]
staff are just bad at typing and only know how to type ooc and accidentally type in ooc, so they want a hotkey to fail to press and hit the ooc hotkey instead.

qol and all that crap sure, a bit pointless though in my eyes, and will probably end up being more trouble than you'd think

**Pull request merged**
