### PR TITLE
Added ghetto surgery maint room

### PR DESCRIPTION
**Pull request by Cruix**
untitled

Comes free with all the ghetto tools required for surgery

### CODE REVIEW

**Comment by LarissaMayrink** [comment]
Where is it? also *nice*

**Comment by Cruix** [comment]
To the left of tool storage

**Comment by LarissaMayrink** [comment]
isnt that the place where the maint garden is at?

**Comment by Cruix** [comment]
Yes, the maint garden is currently the only maint ruin, which is why it is always chosen for that spot.

**Comment by Mrcreepssss** [comment]
sweet

**Pull request merged**
