### PR TITLE
Bolts the emergency shuttle airlocks during flight

### PR DESCRIPTION
**Pull request by matskuman5**
I spent like 5 hours figuring this out and it's probably shitcode but it works, so whatever

This can MAYBE be applied to mining shuttles as well, but it would require some tinkering

Hopefully we'll see less "oops i spaced 5 people by accident" tickets

:cl:
tweak: The emergency shuttle airlocks are now bolted during flight.
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
> Hopefully we'll see less "oops i spaced 5 people by accident" tickets

I doubt anyone has ever managed to _accidentally_ space 5 people.
Overall this fucks over antags more than anything, as most, including me, don't bother with objectives until round-end because I actually enjoy jobs.  The inability to space people without blowing something up, eh.  I don't see that as a good change.

**Comment by ShadowDeath6** [comment]
just kill them

**Comment by Zostroll** [comment]
While you are at it do you want to remove the three airlocks on the right of the shuttle?

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/issues/1607

**Comment by matskuman5** [comment]
You can still break the windows if youre tator.

**Comment by Cruix** [comment]
This will also bolt the doors open

**Comment by matskuman5** [comment]
Hm? what? I tested it out with the doors open, they closed then bolted themselves

**Comment by Cruix** [comment]
My mistake, apparently shuttle code closes all the doors right when the shuttle takes off, which is why the spawn is needed. However, this does bolt every door on the shuttle, including the shuttle brig doors, the medical door, the bridge door, and the door to the little closet.

**Comment by matskuman5** [comment]
Oh, damn....

I'll try to figure out a way to prevent that

**Comment by matskuman5** [comment]
OH MY FUCKING GOD REEEEEEEEEEEEE

WHY CAN'T I HAVE ONE FUCKING PR WITHOUT MERGE CONFLICTS AAHHHHHH!!!!!!!!!!!!!!!

**Pull request closed without merging**
