### PR TITLE
You can now theme your bar as a chef or bartender!

### PR DESCRIPTION
**Pull request by Kmc2000**
### Intent of your Pull Request

As the title says, you're now able to use different styles of bars!

This only works for chefs and bartenders, who have an equal chance to get their pick (this can be modified with a flag in datum/job)

You select a bar via player preferences, if you roll one of those two rolls and have this preference set, your choice will be weighted twice in a list, this list contains all the maps. The more players that have the same preference, the better the chance of rolling the map you want!

I'd like some more bars! if you're a mapper, feel free to contribute to this. It's all documented

Some examples of the new bars on offer:

Conveyor belt bar
https://i.gyazo.com/6135f5fc5cbb4fc2499b06196c00d0a6.mp4

Casino bar

Rage cage bar

Spacious bar

Space ship bar (Bar trek)

American diner

Hear me out on the pref part,
I tested it, it loads completely smoothly and in-sync with job spawns. It is unnoticeable.
Yes, ghosts will see a big thing saying BAR!, but I'd rather have players choosing what theme they get rather than having some bullshit RNG (Aka. Always rolling RAGECAGE bar)

If you make a bar, please send me a message on discord and I'll handle the rest.

If you have bar suggestions, leave them below!

P.S The lighting issue in some screenshots is due to my local branch being fucky. This should not happen on the actual server (citation needed)

Obligatory bad PR ruins immersion for the spacebar.

#### Changelog

:cl: Kmc2000
rscadd: You can now theme your bar automatically as a chef/bartender, look in your preferences (This doesnt guarantee you'll get the bar you want, but you'll get a chance!)
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
-1
Removes tasks for engineers or the bartender to do. Rage cage one especially.

**Comment by Super3222** [comment]
I like this. Really changes the game. The bartender can still make the tweaks and edits, JC.

**Comment by MegaEmpirical** [comment]
Fucking love it.

**Comment by ghost** [comment]
Cloning your repository, this may take a while...

**Comment by Kmc2000** [comment]
@Jc1469

**Review by Amelia0010 — DISMISSED** [review]
I'd love it if you could change it so it's RNG and not a preference, thank you very much.

**Comment by MegaEmpirical** [comment]
He's mad with power, don't listen to him. Maybe random if no cook or bartender at start or if no preference set (so set random as base preference).

**Comment by Super3222** [comment]
If nobody picks either chef or bartender it should be randomized.

**Comment by Super3222** [comment]
If nobody picks either chef or bartender it should be randomized. But make sure the empty version can't be picked from the randomization.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
We don't let anyone else choose how the station looks or acts, not to mention that everything is loaded in on initialization, not later. If the bartender prefers a specific layout, then they are more than welcome to modify the bar to support that, but it should not be as simple as changing a preference. This should be consistent with everything else in those regards, and if you dismiss this review then I will have your git powers removed :blobupsidedown:

**Comment by Kmc2000** [comment]
"We don't let anyone else choose how the station looks or acts"
Engineering
Mapswitching/Map changing (map voting)

Comprimise:
Maybe i can add their suggestion to a random pool? so they get a say in it. If enough people choose the same, that bar is weighted more heavily against the random bar?

**Comment by Amelia0010** [comment]
>"We don't let anyone else choose how the station looks or acts"
>Engineering
>Mapswitching/Map changing (map voting)

Engineering is doing it IC, not by a preference to finish all their autism forts in an instance, and replace the construction office with a bar or w/e. Almost like what I said in my message about the bartender tweaking it if he doesn't get what he want

And map switching is different than a change in one department, since it doesn't change the way your specific workstation acts/looks, but the whole dynamic of both antags and nonantags, and the crew as a whole. 

That said, as much as I'd personally much prefer if it loaded with the rest of the ruins loading during initialization, I can live with it just being a weighted preference, so it's not "hey, lemme make rage cage evry rund". But idk what @AsV9 thinks 🤷‍♂️

**Comment by MegaEmpirical** [comment]
So if it is technically annoying to select the theme as maps are done before players are even picked, I get it. However, if it's reasonably viable, then I think the benefit of being to select the theme for the bar is such a minor bonus to two largely uneventful jobs.

**Comment by utahclock** [comment]
I agree with travis

**Comment by Kmc2000** [comment]
I'm alright with the comprimise. But I'd rather not turn it into RAW RNG.

**Comment by Nickvr628** [comment]
I think it SHOULD be a preference. I also think that this could be expanded to other jobs/departments too. Imagine if the CE could choose between the singlo/tesla or a TEG layout in engineering, or botany can start with either bees or planters. It could lead to a "unique" station every round.

**Comment by Kmc2000** [comment]
>Nick
Yeah the framework is there. I can add that in future PRs

**Comment by Smudged** [comment]
I agree with the others, especially rage cage bar, deconstructing that if you want to do anything else would be a massive pain. Even randomly some of the bar designs like casino would be a pain in the ass. I like the premise, but the problem is it's taking work away, instead of building your own, it's just a thing now, which I don't really like myself

**Comment by Kmc2000** [comment]
To be fair, most players don't even touch the bar. Those that want to can just opt for the DIY bar which comes pre-disassembled

**Comment by ghost** [comment]
Nobody goes to the fucking bar anyway, what's the harm.

**Comment by matskuman5** [comment]
Rage cage is stupid

**Review by Amelia0010 — APPROVED** [review]

**Comment by kooarbiter** [comment]
what about a xenomorph bar with alien toys for when your diet consists of alium wing wang? they could even have chairs designed to look like xeno nests

**Pull request closed without merging**
