### PR TITLE
Fixes Paramedic Lockers

### PR DESCRIPTION
**Pull request by SKR6DarkVoid**
Fixed the Paramedic Locker Icons, along with them not spawning in.

### CODE REVIEW

**Comment by SKR6DarkVoid** [comment]
This is referring to issue #127 

I had to re-import the paramedic icons, along with some minor mapping.

**Comment by oisin100** [comment]
Did you use DreamMaker's inbuilt Import/Export feature to update the icons?

**Comment by SKR6DarkVoid** [comment]
Yes

**Comment by oisin100** [comment]
Right'o

**Pull request merged**
