### PR TITLE
Adds emoji to Asay

### PR DESCRIPTION
**Pull request by Amelia0010**
**Asay is ostensibly only for professional and mature communication between admins and does not need emojis.**

New headcoder, new opinions, let's try again.

previous PR: https://github.com/yogstation13/yogstation/pull/2638

### CODE REVIEW

**Comment by Alek2ander** [comment]
🤡

**Comment by Koffheatalt** [comment]
> Asay is ostensibly only for professional and mature communication between admins and does not need emojis.

If you use emoji's as a administrator I doubt you're mature enough to be a administrator

**Comment by Amelia0010** [comment]
>If you use emoji's as a administrator I doubt you're mature enough to be a administrator

🤔

**Comment by simonset55** [comment]
Just dab on them haters :thinking::thinking::thinking::thinking::clown_face::clown_face::joy: :joy: :joy: :joy:

**Comment by Koffheatalt** [comment]
0.0:🔩 Don’t👴🏾 be a👮🏼✴️ dick. Don't🎡 behave💛 in a manner🎃 that🐤🏪📁 goes🍋 out🎨 of🍃 its👲🏿 way💈👳🚴 to🙌🏽 deprive the enjoyment💳 of👎🔐✳️ others.🐢 These rules are not🚑 an exhaustive💷🙆🏼 list. Rules-lawyering👮🏾 is👋🏼🏇🏿 strongly🙅🏼 discouraged.📑 If🔶 an admin↩️🏈 asks you👆 to🏧 knock🎅🏿💉 something🔑 off, 'well it's not in🍞🆒👏🏽📖 the👨‍👩‍👦‍👦👈🏿 rules'🙏🏽🐕 is not really an🈹 argument. 0.1:😳😧🆖 Do🐡 not⛽️ be🈵🛀🏽👼 a bigot.🐭 We expect🙌🏿 our players🕛 to be tolerant💂🏻 to people who🚍 are♥️😑⛲️ different♈️ from🙋🏻 them👶🏾 in👳🏿 some🎱 way, and🎡💐🐗🈹 respect their🙎🏽 choices. Do not use🏦 terminology🍪 that is🌝📫🔌 considered😢 bigoted😁 or racist,👜 or📊 is🎶 offensive☝🍬👩🏼 to🐞 a large group of🏃 people.👲🏽 Usage of🏂 the💺 words “nigger”, “faggot”,🈁 and🐟 derivatives🚶🏻 of🔇 those🐎🆎🆙 are completely banned🙏🏼 from💨 the💃🏿👊🏽 server. 0.2:🍸👆🏻 Erotic content is📣🌻 forbidden.🆙 As👚🐭👦🏿🐰 a⏳ general rule,😾 anything🈯️ more sexualized🚡🔰🔫 than🔊🏃🏿 kissing➖ and🔜 hugging😐 is considered erotic. Do not🔷 roleplay🎵🌿 acts😉🚣🏊🏿🏄🏽 of an➰ erotic💌🎱🚶🏻🏭 nature.🙅🏻 Insulting😇🔤 people with😖🎻🆘📥 erotic or🍄 intercourse🚣🏿 related😃 terms🙋🏻🍚👌🏿 is fine🐕💆🏽😊 as🐋😅🆖 long as the🔏 insults🙇🏽 are not💏 graphic or explained🔃😤💇🏼⛵️ in👨‍👨‍👦‍👦✊🏿 detail. Do🐧 not write,☁️ upload,🗾👊🏿 or👍🏾 distribute pornographic🎀 literature. 0.3: Do👾🔻 not💧 mix IC👮 (in character)😛 and OOC📵 (out of character)🚿🌐 knowledge.🌆 Do😨 not🔛🐁🍺 post information related👴🏽 to a⛺️ round✊🏻🏬😽 in🎱 progress in the OOC chat.👑 A person reading🎵 the OOC🚻 chat should💅🏽 not be🔤 able👨🙉⚠️ to know🐝 what's👨🏽 happening in a🚙🌵 round, whether🍹 anyone is dead, etc. Do😴 not use🎷🛄 information✊🏻 your📜 character➖ would have💾 no way of🎲💪🏾 knowing🌾💙 in👨🏾📜 game. We◽️ have🚤🌾👵8⃣ a zero-tolerance👇 policy on this,⚡️🏇🏾✊🏼🎆 it🍅👮🏻❗️ doesn’t🎏💲 matter how🚜 small🚓 or🎇 insignificant you think📔👊🏼 it is. Avoid using🐻 OOC▪️💅🏽👱🏿 terminology in character,🎵📋🐙 but if👼 it is necessary, use double♣️➰ parentheses😅 ((like⭕️ this)). 0.4: Do not😩 metacommunicate or💺 multikey. You👌🏼 are🚴🏼 only⚫️ allowed to😜😋👋🏿 participate on this server on⛵️♊️⛳️🎺 a👩‍❤️‍💋‍👩 single BYOND account.🍗 Do🌞👊🏿👱🏻 not try to join👮 with👣 a different😾 account to continue💢 playing.🙌🏽 Only🍵🌍 use👈🏽 in-game👅 means🈂 of communication👦🏿☎️ to🏊🏿👐🏼 discuss in-game events. 0.5:👌🏿 Do♻️🕐📷🙈 not🌟 spam😉 or👮🏽 advertise.🍋 Do🎀 not🎧 post🆕 links without💆🏾 prior approval💁🏽 by🙌🏾 an🍎💨 admin. 0.6:🔥🙍🏾 Use👅 proper🚴🏽 IC🍣 language. We🈹 are👴🏽 an🏧 English〽️ speaking community. Using🆕 any💅🏻 language👶🏼 other💝 than👧🏿 English♓️🚩0⃣🐉 in🐙 either IC🈳 or🚼 OOC🍉 will be treated6⃣ as🐂🚥🚄 metacommunications,😦 as🉑 our🎢🏄🏽👨‍👩‍👦‍👦🐝 admins▫️ cannot translate👮🏾🏉 all🛂🎴🏊🏿 languages.👰🏽🚡📏 Do not👇🏿👐🏼🐣 use netspeak,👠👳🏼 emoticons,🙇🏼👊🏾👧🏿✔️ or🙆🏽 internet memes👞👊🏽👧🏼 in💪🏾 vocal👦🏼 IC😤 communication. 0.7: Listen🚠 to📟 admins.👱🏽 All👨‍👩‍👧‍👦 cases🐟👨🏃🏾🐬 are👣🔵 subject👌🏻 to🕒 admin discretion.🏢😂🔍 If✌🏽🙇🏼👨‍👨‍👧‍👦 you cannot🌖 be contacted, you may👷🏻🚖 be😂 banned to have🏭 you explain🌵🍏📪 your😶 part📫 of the🏇🏾 story💂🏼🏄🏼 on📄 the🐎 forums.📟 Ignoring admin🐷 PMs, lying, insulting👩‍👩‍👧‍👦🅾🙋🏼 admins or other players, or showing a🐬 general🏦 bad attitude👆🏠😯 will🉐 be counted against👛📴 you and🔡 could lead🙇🏿 to a👷🏼 ban. 0.8: Do not💫 abuse macros or autoclickers🐨💅🏿 to🐋🚝 gain👨🏿 an👍🏿 unfair advantage.👏 Do not🚍👂🏼 abuse👱🏽 bugs. In-game rules: 1.1: Do not grief. IfⓂ️ you are💆🏾🌂Ⓜ️🙅🏿 not👶🏼🍤👵🏾 a⚡️ round🃏 antagonist,📗🏧😆 do🙌🏻 not👷🏿 cause🔆🔟 major🐙 station🏣🍥💋 damage, cause🚜 major chaos,🐥✋🏼🆒 create🙎🏼 fires💆 or😢👰🏿 hull breaches, release harmful♓️🌾 gasses, spread↘️ harmful🕖 diseases,👸🏿👈🏿 severely🍫🚹 harm,👩‍👩‍👦👅👘🚯 decapitate, or🐧📏🆓 murder🙏🏼 people, trap🕘🈚️ people🌉 in places from which👲🏿👽🕞 they🎺 cannot🙍🏻 escape, or🌄 any🍬👇🏻⛅️ other👟🚴🏾🎅🏻💅🏾 action㊗️😧🎠 that would👍🏼💧🐦 be considering😡 agonizing↘️🌻✂️ for🙍🏼😇 other players.⚪️ As a🔬👐🏾🈲🏊🏻 cyborg👺 with⏪ an🚱 Asimov㊗️ lawset, following this👨‍👨‍👦 rule👊🏼 is👵🏾 mandatory👐🏻 towards non-human🆑 players.💶 As a rule🌇⏪ of🔸 thumb,📏 don’t🎂 commit crimes😈 worthy⛳️ of capital💃🏼🔀🌕 punishment☑️📱 as🐢 a non-antagonist. 1.2:👿🚴🏿 Do🌹🕟 not📒 greytide.🙎🏿 Do😧🙍🏾👂🏿😬 not break windows💴 to🛀🏻 space,👃🏽 electrify👃🏾 doors,🏄🏼☝🏻👲🏼 steal important🐄9⃣🚪 items or🚒 attack🚴🏿 or🌃 rob✋🏻 random🍢👲🏻🐠😰 people, especially those👂🏿 that👂😁 are⬛️ AFK🎄🔐👨‍❤️‍💋‍👨 or💜 braindead.㊗️ Do🔑 not😪 vandalize👻👷🏻♓️👬 areas🎦⛅️🏥 or👓 break lights excessively.👌🏻 Do😐 not🕟 block🍧 public📯🙆 hallways.🌞 Do👷🏿 not▫️ deconstruct🙊 shuttle💈 chairs.🐘 Do not disrupt security🌎 for♣️🕛🏇🏻 your own enjoyment. For🎣 antagonists, the👈🏼💃🏻 murderboning rule applies😏 instead. 1.3:🚴👨‍👨‍👦‍👦👮🙆🏼 If👂🏼 you acquire♦️ guns or☺️ magical🆎👮🏽👦 items🐕 as🙍 a crewmember during👰🏽 a🔳 wizard🐕 round🍊 and🙋🏼 you are not given🔻 any🌜🏬♨️ objectives📷 by the👧🏻😔 game,🀄️ do🌀 not🏤 use the👓🎒👵🏼 given items👛 for👦🚫👋🏼🔀 killing, griefing or greytiding.🚜 For people🌉🌘 who🚴🏽 are given objectives,⛵️ the🗿 murderbone👮🏻 rule applies💵🅱👂🏿 instead. 1.4: Do not powergame. As a🏃😢🔽 regular📰 crew member, you're🎅🏼 not👃🏾🍙🉑 an🚅 experienced👧 soldier,🌁🍚 nor🗻🐝😭 do you📭 know all🔋👊🏽🏇🏾 the jobs5⃣ of the👡🔭🐑 station.💪 Do🕤👨🏿🌴 not📻 hunt📃💂🏽💍 down🙇🏾👊🏻 criminals🎡 as👨🏿 a📓🐋 regular🏀🍊👋🏻👍🏾 crew👧🏽 member,❕ that’s👌🏽 security’s🙎🏼 job. Do⏫ not rush into🔽😋 danger without👀 a🚣🏽 good🌐 reason🔈 to😮 do so.🌘 Do💬💓😰 not collect🎈 dangerous items,👊🏿🌲🍚👈🏿 weapons,🚴🏾 rare tools "just in👐🏿👋🏼😛 case".🐫 Use🈲🚎🔏 reasonable💏 self-defense; do📃🏇🏿👱🏿🐱 not try to🉑 kill your😖 attacker in🔈🐺 revenge, especially📪 after conflict🌊🎬 has👩🏾🍳 already🔻👱🏽 ended. Do🐫🚵🏼👮🏽 not🙅 call💹💊 the💛 escape shuttle🚔👊🏼💇🏽 without🍳 a🚣🏾 proper👰🏽 reason, and❄️🚣🏿 do not recall🌀 it🎣🔪🍂🌗 or👩‍👩‍👦 early-launch👶🏽 it needlessly.🚼 This rule does not🚌 apply🚉 to antagonists. 1.5:🔇 Do not0⃣ metagame. Your📞🙋🏽🔝 character✌🏿👍🏽🎀🎬 does👑🆕😛 not👏🏼🚾🔃 know〽️🐤➡️ everything👌🏾 you do.👼🏻 You should➿💧👈 not🎱 know the💅🏻 nature of🐬 traitor🎬 items (see🗼 the💇🏼 metashield🍔 guide below).👋🏿 This💟 rule does not👌🏼 apply to🕓 antagonists.⛳️

**Comment by Amelia0010** [comment]
>that long emoji post

What did he mean by this

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Impressive

**Comment by Moja10** [comment]
honestly impressive

**Comment by ghost** [comment]
*Magnificent.*

**Comment by ThatLing** [comment]
Amazing

**Comment by Koffheatalt** [comment]
I warn you people if we allow this he's just gonna add emojis to everything

**Comment by Amelia0010** [comment]
we already have emoji in ooc, I don't understand why this is any worse, especially not when the vast majority of the playerbase not only won't see it, but can't see it.

**Pull request merged**
