### PR TITLE
Ports a buttload of TG sprites [Not ready]

### PR DESCRIPTION
**Pull request by Partheo**
# SCROLL DOWN FOR PICTURES

Here it is...

Don't merge this yet, I still have to test some of it and I'm sure I've missed a lot of stuff.
I've gone through the TG sprites by hand and picked what worked for us, given our code differences.

Look at the commit names to see what has changed.
The biggest change? Most machines no longer have an isometric perspective and are instead 3:4.

Isometric perspective:
image

3:4 perspective:
image

Since I went through these by hand, I have done my best to adjust what I got from TG to work with our code. For example: We have knocked-over vending machines, TG doesn't. So I made sprites for the knocked-over TG vending machines that I ported. I'm not going to link any PRs because of this.

I've also adjusted quite a few TG sprites that I found were an improvement, but lacked something, or to add Yog flair to it.

:cl: Partheo
imageadd: Many machines and objects around the station have been updated with new sprites from TGStation and Endless Horizon!
imageadd: Nanotrasen has finally shipped updated hardware for the station's outdated APCs. They will look different but work in the same fashion.
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
these are cev eris sprites, not tg sprites.

**Comment by Partheo** [comment]
I know. Look at the changelog.

**Comment by matskuman5** [comment]
Please screenshot all the sprites you updated. Shouldn't be hard, just take an image of the .dmi file open in DM

This is so we can see if there are any sprites that we don't want

**Comment by GrayRachnid** [comment]
Matsku go over to code changes and look at how many files he changed. "it shouldn't be hard" then you should do it yourself. You can open the files yourself from the code changes button.

**Comment by Partheo** [comment]
As I said in the OP, I'll post pictures later. I finished this at 3AM last night, so I wasn't about to go and take 50+ screenshots. Expect pictures tonight or tomorrow.

**Comment by ShadowDeath6** [comment]
3/4ths perspective looks bad

**Comment by ghost** [comment]
@ShadowDeath6 so does your sense of art

**Comment by ShadowDeath6** [comment]
what are the fourth sprites from the bottom supposed to be? do they replace the transmitters?

**Comment by Partheo** [comment]
@ShadowDeath6 Fourth sprites from the bottom? What?

**Comment by Partheo** [comment]
# PICTURES
No, this is not everything. However, these are the main differences. Everything else is fairly minor or not a big change.

Pipe dispensers
pipedisp

Tanks
holdtanks

APCs **(THESE ARE NOW CHANGED)**
apcs

Pen, filing cabinet, recharger, **paper bin**(Looked gross, this isn't included in the PR)
secoffice

RnD machines, machine frames
rnd

Tcomms
tcomms

Vending machines
vending

Racks and autodrobe
racks

Robotics machines
robo

Basketball
basketball

Pen, cabinet, rack, photocopier, stamp
law

Body bags, blood bags
med

Gas tanks and tank dispenser
tanks

Microwaves, whetstones, canned drinks, wanted poster
microwave

Biogenerator and big water tank
hydrop

Autolathe, ammo, stamps.
cargo

Candles, washing machines
wash

**Comment by MenacingManatee** [comment]
APCs are cool, the pen is OK, I like the exo fab and the basketball stuff, blood bags are cool but I could go either way on the body bags (also are you updating the bluespace bodybag with it?) I love the biogenerator, rnd machines, and the autolathe. Everything else though I'm kinda iffy on. The stuff where you just made it no longer isometric I could go either way, but the wanted poster specifically looks too wide and cartoony. I like the shape and size of the new whetstone but I prefer the palette of the old one, and I'm not sure what it is about the racks but I really dont like them.

**Comment by Partheo** [comment]
@menacingmanatee
Bluespace body bag is changed too, yes.
I'm not too much of a fan of the new wanted poster too, but the current one looks abysmal, and this new one is very eye-catching. I could edit it.
I can do some color changes on the whetstone and tweaks for the racks, might be good.

Thanks for your feedback! If anyone else has stuff to say like this, please do.

**Comment by ghost** [comment]
the vending machines suck ass because they're 1-dir

**Comment by Amelia0010** [comment]
I'm fine with mostly everything, but those pipe dispensers don't look that well

**Comment by ShadowDeath6** [comment]
this

I meant this, my bad.

apcs look really fucking awful also :-1:

**Comment by Partheo** [comment]
@shadowdeath6 that machine is in the signal technician's room. I think it's the arrival message broadcaster.

What don't you like about the APCs? I'll make a gif of their complete operation on Monday so people can get a better idea.

**Comment by ghost** [comment]
@Partheo ignore ShadowDeath6 he doesn't seem to like new things

**Comment by GrayRachnid** [comment]
THE PAPER HOLDING THING SUCKS

**Comment by Partheo** [comment]
@grayrachnid yeah it's garbage, don't expect to ever see that on the server. I'm gonna revert it.

**Comment by Super3222** [comment]
I think one of the main problems with some of these sprites is that they clash with the simplistic design of ss13 which makes up 90% of the other sprites in the game. Also, am I the only one that hates those tank sprites?

**Comment by Partheo** [comment]
@super3222 I'm not happy with the tanks either. Will revert or edit them.

**Comment by ghost** [comment]
you want our ugly tank sprites, rather than /tg/'s beautiful sprites, @Partheo? eughhh

**Comment by Partheo** [comment]
@morerobustthanyou the tank sprites are good sprites, but they are in no way cohesive with anything else on the server. They stand out like a sore thumb. The art style is way off.

As for the machines, most of them look soft enough to fit in with what we have.

**Comment by matskuman5** [comment]
Machines, vending machines, candles and basketball look good

Everything else I don't think fits

**Comment by AshCorr** [comment]
The only thing I like is the tanks and the tcomms machines.

Everything else looks like absolute garbage and out of place compared to the rest of ss13 sprites.

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Time-Green** [comment]
I dont really like the sprites. But holy shit, the APC looks absolutely fucking disgusting. I'm sorry, but please dont port the APC, its the worst of all.
Just make your own sprites, I liked those way more

**Comment by Partheo** [comment]
# EDIT: Ignore, I've made my own sprites(Next comment)

**These are the current TG APCs.**

Constructing an APC:
ezgif-1-876f0103fb

APC standby:
ezgif com-video-to-gif 2

Emag:
ezgif com-video-to-gif

Broken APC:
ezgif com-video-to-gif 1


The thing with APCs is that making them are a lot of work. I'm not going to make my own version of an APC until I have a lot of time, which I don't. What do people think of these?

**Comment by Partheo** [comment]
Alright pals. I made my own APC sprites by editing the TG ones.
Before you scream at me, they are direct upgrades of the CURRENT sprites we have. No redesign.
The only difference is a bit of shading, new screen animations, and a new deconstructed-APC look. Terminals are also redone.
unknown

Gifs:
Fully charged standby https://gyazo.com/383d5a5c2c39a356703e2b57d2e797b3

No charge standby https://gyazo.com/94fc7219f0ddfc86954fee195eab93bf

Charging standby and opening https://gyazo.com/a2344ea99a2ffbd6a5c9820b21d5531c

Essentially, this is what the old open APC sprites looked like:
unknown

And these are the new ones:
unknown

Don't tell me this isn't an improvement or that the open panel is "iconic". The front panel is barely changed, and looks the same at a glance.

Thoughts?

image

**Comment by ghost** [comment]
could you maybe STOP USING JPEGS FOR THE APC PICS

**Comment by Partheo** [comment]
I'm using the sniping tool at 3 am. Not gonna bother.

**Comment by Partheo** [comment]
So, update on this. I'm currently redoing some of the worst offenders from the sprites I ported.
For example, I'm currently doing a pass over the vending machines, because honestly the TG ones look uninspired and fucking generic. They will still be the 3/4 sprites from TG, but I am editing all of them to add a tiny bit of detail, and also to make them fit in better with our(my) art style. Example:

TG Vendomat VS my Vendomat
image
image 

TG Nanomed VS my Nanomed
image
image

(Like honestly, these look like they were made in the DMI editor)
image

Expect the worse things in this PR to be edited in this fashion. I'm looking at you, air tanks.

**Comment by Partheo** [comment]
## Closing this PR while I update the sprites. Not gonna be done for another little while, but I'll probably atomize it a bit as I go along updating new sprites. Thanks for all the feedback folks, I'm listening.

**Pull request closed without merging**
