### PR TITLE
Removes the ARG rifle from ERT commander on non-red alert

### PR DESCRIPTION
**Pull request by matskuman5**
#1407 

:cl:
tweak: The ERT commander now only gets the ARG rifle on red alert.
tweak. Red alert ERT security members no longer spawn with a useless ARG along with their plasma rifles.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Why?

Red alert already comes with pulse rifles.

The entire reason I buffed blue ERT to have this is because it was either 'send blue ERT, helplessly outgunned, and watch them die, or send RED ERT with pulse clips and they kill everything'.

There's a reason why blue ERT comes with superior gear to put themselves on par with station crew.

**Comment by Stealthkibbler** [comment]
Did you remove it for red alert security officer? He already gets the pulse rifle, he shouldnt need an ARG.

**Comment by Stealthkibbler** [comment]
Also the red alert security officer still spawns with auto rifle ammo but doesnt spawn with an autorifle.

**Comment by matskuman5** [comment]
I would have put it in the armoury, but #1389

**Comment by ghost** [comment]
Stop removing/nerfing ERT's. 

The entire reason I made that PR was to make blue/amber ERT's viable because otherwise they're fucking helpless against whatever threat is up there unless it's a red alert ERT and that's a miniature deathsquad.

**Comment by matskuman5** [comment]
Blue ERT = no weapons needed (fixing a major breach, etc.)

Amber ERT = anything with weapons needed but no heavy weaponry (early / medium revolution, gangs, etc.)

Red ERT = anything with heavy weaponry needed (wizard, rev / gang / cult with major control of station)

Deathsquad = literally kill everything on the station (xenos)

That's my view on it

**Comment by ghost** [comment]
Blue ERT = Useless, die instantly

Amber ERT = Never called unless the situation is absolutely fucked. An admin who sends an eRT for anything less is liable to have a complaint forced on them, the same as sending a deathsquad or red ERT. Also, less well armed than the average security member.

Red ERT = Miniature deathsquad.

Deathsquad = Deathsquad.

That's the truth of it.

Amber ERT is fucking useless, and nobody sends it because it dies instantly. Red ERT is overpowered with pulse lasers, so nobody sends it because it kills everything.

There needs to be a middle ground, and amber and blue having the abiltiy to fucking fight back is that middle ground.

**Comment by Stealthkibbler** [comment]
Blue ERT is a scouting team/diplomacy, regardless they still get 2 eguns and sec members still get an autorifle and tazer as-well as flashbangs. If anything it should be used if an admin wants to test the waters just to see how deadly the situation is, if blue ert gets wiped then no doubt the situation is fucked.

Amber ERT gets access to a good amount of stuff in the armory, 2 medibots, emp grenades for taking out rogue silicons and electronics more munitions, riot shields, combat defibs and plenty of construction tools. They are effectively the cleanup crew if blue ert fails to accomplish their goals. 

Red ERT is the BOIS, when everything is fucked beyond belief they get sent in to contain the situation with extreme prejudice. ONLY the sec officers get pulse rifles, the medics and engineers are still support for the team, engineers should be assisting with busting down walls/doors etc for easier access if shit is bolted while the medics should be focused on making sure their team doesnt die.


In hindsight it is very team orientated, a bad commander can be the be all end all of an ert. But the fact that staff rarely ever deploy erts is part of the reason people just dont know how to play them accordingly.

**Comment by ghost** [comment]
there's no s uch thing as scouting/diplomacy stealthkibbler

blue = cannon fodder

amber = garbage

red = overpowered

at least now it's balanced

**Comment by Stealthkibbler** [comment]
ERT isn't meant to b 100% combat orientated, its a mix of support, combat and leadership bundled into a group of slighty retarded manchildren. If people cant work together to achieve their goals then they deserve to fail, if they dont learn from their mistakes then its their own fault. 80% of ss13 is learning how everything works anywho; as long as someone learns what they did wrong and how to get better at a job I honestly dont give any less of a fuck.

**Comment by Stealthkibbler** [comment]
also 

If red was the only viable threat then the problem is the players not understanding how to be robust as ert. as I stated on the forums I've sent plenty of erts back when I was admin, none of which procurred a single complaint against me. Admins just need to stop being retarded and learn to evaluate when is the right time to send an ERT. There's also the escalation factor. You dont want to send red ert immediately unless you absolutely need to, ert should for the most part be sent to spice up the round while offering a challenge to the antagonists.

You can create a nice buildup of suspense and make the round more intense by the use of central command announcements, centcomm inspectors and proper timing of ert deployment. Whether the ert falls flat on their face or not is just a factor of how good they operated as a team, when you have 5 geared people working together, you CAN beat just about anything, they don't need ARGs outside of red alert to overcome an obstacle.

**Comment by ghost** [comment]
>ADMINS NEED TO STOP BEING RETARDED

# LIVIN' THE DREAM

**Comment by matskuman5** [comment]
I've sent plenty of amber ERT's during my time as admin and they seem to get the job done

Amber ERT vs. Wiz, ERT usually wins

Of course it all depends on how robust the team members are

**Comment by ghost** [comment]
SINCE WHEN DOES A FUCKING WIZ LOSE TO ANYTHING BUT A DEATHSQUAD

**Comment by ghost** [comment]
oh right this is yog nvm

**Comment by enailz** [comment]
> Of course it all depends on how robust the team members are

It depends on how robust the wiz is, rather.

**Comment by ShadowDeath6** [comment]
Ert is dumb, they're literally never used why do we need multiple levels if they do jack anyway

**Comment by Nickvr628** [comment]
Blue ERTs get slaughtered and amber is never called, keep it the same as it is now, and least they can fight back.

**Comment by Stealthkibbler** [comment]
Ert does not need semi-automatic rifles with 30 ammo that 2 hit crit anything not wearing armor. Not even Nukeops M90s and C20rs are not that deadly, even the L6 SAW has a slightly slower firing rate than an ARG.

**Comment by ShadowDeath6** [comment]
I just realized this is an ARG, which is a ballistic pulse rifle with less ammo and a faster firing rate. No bueno pls no keep

**Pull request merged**
