### PR TITLE
Crit cult, more like fuck cult.

### PR DESCRIPTION
**Pull request by Jc1469**
:cl:
tweak: Offer runes no longer heal people that get converted.
/:cl:

AKA fuck you crit cult meta

### CODE REVIEW

**Comment by simonset55** [comment]
Nice change

**Comment by ghost** [comment]
do i smell a grudge

**Comment by Jc1469** [comment]
How is it a grudge when I play and enjoy it? I just find it overpowered. Having managed to roflstomp twice while doing relatively little aside from beating the shit out of people unable to defend themselves and dragging them onto a rune adjacent to a person that went braindead as soon as I beat the shit out of them and converted them prior.

**Comment by X-TheDark** [comment]
Think you could at least inject some epi into them so they don't die on the spot?

**Review by X-TheDark — APPROVED** [review]
I don't mind converts not getting healed after being critted. It's a lot more fair, considering how much stun/crit blood cult has.

**Comment by ShadowDeath6** [comment]
Have pylons restore lost blood if you're going this route

**Comment by Jc1469** [comment]
Alternatively the cult can just not be set on critting people because it turns out fine.

**Comment by ShadowDeath6** [comment]
the problem that the original pr solved was that cults were just killing people and soulstoning them because it's less work than restraining someone and converting them, because stun papers are finite (unless you make like 20 but that's still inventory space and time spent)
making pylons heal blood loss means that cults can actually have functioning members but if they damage them before conversion they need to wait out the pylon healing them

**Comment by Super3222** [comment]
this is more balance than tweak

**Comment by Jc1469** [comment]
balance wasn't an option so it gets tweak. I also can't set tags

**Comment by ToGWtF** [comment]
The ONLY difficult part about bloodcult is getting a LIVING target back to the base to be converted without them screaming over radio. Stun papers already got a buff in that it makes people unable to scream a location but if they talk over radio it still reveals cult. New meta is just to send a jugg to stomp its way down the hallway and crit the first person it sees because they get healed anyway.

**Comment by Partheo** [comment]
@togwtf I've never had a problem with converting people using stun talismans, if you're quick you can remove their headset and restrain them before they are able to speak. Alternatively, work with a friend or use EMP talismans. They're are lots of ways to work around this

**Comment by Ratvar** [comment]
So they just WILL spam pylons and nothing will change? Maybe, uh, make converting actually damage target? Use sacrifice+raise dead charge to bring them back or heal them beforehand.

**Comment by Jc1469** [comment]
Atleast spamming pylons requires something.

What you're asking for is just stupid.

**Comment by Ratvar** [comment]
Requires some plasteel/roundstart talisman uses to...wait, critcult is still here. Just with wait time.

**Comment by ShadowDeath6** [comment]
maybe this pr doesn't completely remove the cult's ability to heal people, it just makes it so they're not encouraged to use lethal tactics to recruit people.

**Comment by Ratvar** [comment]
Stunpaper/manifested ghost+stunpaper still is superior to critcult. And you just need to plop pylons for critcult to work.

**Comment by ShadowDeath6** [comment]
if they use pylons to heal then fine, it takes a very long time to heal people and it encourages players to not bash other players' heads in since they need to wait for the pylon to heal

**Pull request merged**
