### PR TITLE
Ports over several /tg/ performance PRs

### PR DESCRIPTION
**Pull request by X-TheDark**
Ports:
https://github.com/tgstation/tgstation/pull/18567 - improves living mod deletion (for singularity, mainly)
https://github.com/tgstation/tgstation/pull/18703 - ports over improved processing queue management
https://github.com/tgstation/tgstation/pull/19093 - faster get_turf() from /vg/
https://github.com/tgstation/tgstation/pull/19498 - lag removal from character creation screen
https://github.com/tgstation/tgstation/pull/19667 - fixes tapecorder being a bastard in lava
https://github.com/tgstation/tgstation/pull/19899 - removes approximately 50ms of input lag

### CODE REVIEW

**Comment by Cruix** [comment]
Crap I should have merged this one first.

**Comment by X-TheDark** [comment]
Merge conflicts fixed

**Comment by X-TheDark** [comment]
Note to self: Stop sucking at resolving merge conflicts. This should be good to go once it compiles.

**Comment by X-TheDark** [comment]
Speaking of merge conflicts. I wonder how many this PR will cause once merged.

When this is merged, go ahead and squash it so it's not fucking awful.

**Pull request merged**
