### PR TITLE
Mining Medics can now freely leave the mining station.

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

In the future I will be making the mother jaunter PUBLIC, giving every miner a wrench, give mining medics a bluespace futon to launch corpses back to the mining station, and eventually add in a camera console that will allow you to monitor the activity of those jaunter beacons.

#### Changelog

:cl:
tweak: Mining Medics can now freely leave the mining station.
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
Make jaunters deconstructable? Cameras you can pull everywhere on station and cannot throw away without access to space or bombs, but also can see roundstart from other zlevel. Or they are?

**Comment by Super3222** [comment]
Oh... I meant jaunter _beacons_, not jaunters!

**Comment by Super3222** [comment]
Oh... I meant jaunter _beacons_, not jaunters! And I can make it so the camera console can only detect jaunters on the mining z level, or something like that. So jaunter beacons don't become the powercreep for normal cameras.

**Comment by Super3222** [comment]
Oh... I meant jaunter beacons, not jaunters! And I can make it so the camera console can only detect jaunter beacons on the mining z level, or something like that. So jaunter beacons don't become the powercreep for normal cameras.

**Comment by Time-Green** [comment]
Oh... I meant jaunter beacons, not jaunters! And I can make it so the camera console can only detect jaunter beacons on the mining z level, or something like that. So jaunter beacons don't become the powercreep for normal cameras.

**Comment by Partheo** [comment]
Good change

**Pull request merged**
