### PR TITLE
Shuttle Notifications

### PR DESCRIPTION
**Pull request by Super3222**
Refer to issue https://github.com/yogstation13/yogstation/issues/1176.

### Intent of your Pull Request

Shuttles now send notifications everytime they're sent.
These notifications will go to their assigned division's radio channel (ex: labor camp goes to sec, mining goes to supply).

Currently the only shuttles that send messages are:
- Mining Shuttle
- Labor Camp Shuttle

#### Changelog

:cl:
rscadd: Every time the labor camp or mining shuttle is launched a notification is sent over the radio.
/:cl:

### CODE REVIEW

**Comment by AndySok** [comment]
The torture is finally over
Now you cannot die because of some chucklefuck who sended shuttle

**Comment by Trojanplunder** [comment]
I cannot +1/like/upvote/whatever this enough. Thanks Super.

**Comment by Cruix** [comment]
People will still get sucked out, since the message is sent at the exact same time as the shuttle moves.

**Comment by Super3222** [comment]
Yes, what Cruix said. When a message is sent the shuttle will leave a second after.

Additionally, we could add a delay every time someone uses the console or maybe the computer could message their channel every time someone touches the computer (emagging and multitooling disables this).

**Comment by Paragonid** [comment]
3-5 seconds delay for shuttle to move after console used would be great

**Pull request merged**
