### PR TITLE
Space Station 13 (Guardians of the Galaxy 2 Opening Style)

### PR DESCRIPTION
**Pull request by Super3222**
#### Changelog

:cl:
rscadd: Space Station 13
rscadd: Starring...
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
THE MESSIAH RETURNS

**Comment by Zostroll** [comment]
A audio PR where you don't let us see any audio...

**Comment by Alek2ander** [comment]
The audio file is in the diff, sounds pretty :1st_place_medal:

**Comment by Iamgoofball** [comment]
:cop: 📧 ➡️

**Comment by Super3222** [comment]
👮 📧 ➡️every ss13 server

**Comment by Cruix** [comment]
Sorry this PR will be held up for six months due to dubious filesize concerns before I give up worrying and merge it anyway.

**Comment by Cruix** [comment]
Whoops I skipped a step.

**Pull request merged**
