### PR TITLE
Removes the stun from vortex

### PR DESCRIPTION
**Pull request by Time-Green**
This might be too powerful considering most wizards fill it with plasma, slimes and animated objects
:cl:
tweak: Hell is now a little less bad
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
No this is a bad change. First they came for Ei Nath, now they are here for vortex!

**Comment by Ratvar** [comment]
now remove vortex processing gases and it will be better

**Comment by ghost** [comment]
It hardly matters time. The wizard can throw a bomb in and the crew will immediately die via breach. Or just unleash a grenade.

**Comment by Time-Green** [comment]
Walls and floors are indestructible

**Comment by ghost** [comment]
wasn't the case last time i threw a clf3 grenade in there unless you changed it @Time-Green

**Comment by Time-Green** [comment]
Only stunned non-vortex casters

**Comment by Time-Green** [comment]
I see how that might happen

**Pull request merged**
