### PR TITLE
Revert "Made the syndicate base ruins inescapable"

### PR DESCRIPTION
**Pull request by ghost**
The vast majority of people are against this and there are other solutions that do not involve making the base entirely worthless and also boring for the xenos who win and 'and then what'.

Hardy himself offered proposed solutions

I'd rather this not be closed until the matter is properly adressed and other solutions are found.

Some proposed solutions are to simply, I dunno,

Ban the syndies who leave because they're explicitly not supposed to? Then, the xenos cannot get to station.

If the xenomorphs do make it to station it is on the fault of the miners explicitly and they can get in trouble for it. 

As for poor miners getting killed by xenos-Eh, who the fuck cares.

Honestly, the main solutions are either-

Remove the ruin entirely, because without being able to leave it is complete garbage (not to mention the syndies can jsut open up the ruin and make a wall across the lava to leave) 

Or 

Fix the issue with xenos assaulting the station by having admins do their damn jobs

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
good luck getting this merged, should I just close it now and save us the pain?

**Comment by ghost** [comment]
yes i know that this is just numbers and would have no effect on anything

It's the principle of the matter

**Comment by BOBsHERE** [comment]
Dont close this shadow. Most players are against the PR you made earlier anyways. We want xeno's to be a threat to the station. It was fine as long as the syndicate didnt directly bring them on (AKA leaving the base).

**Comment by Super3222** [comment]
> As for poor miners getting killed by xenos-Eh, who the fuck cares.

No

**Comment by ShadowDeath6** [comment]
@puremanbird I don't make prs, you might be talking about @Cruix's pr

**Comment by X-TheDark** [comment]
So, if I understand correctly, people want Aliums on Lavaland to be a ghost role, but not the syndies (since they don't want those to leave the base)?

**Comment by ShadowDeath6** [comment]
@X-TheDark the original pr created a ruin so that ghost roles (xeno scientists) could spawn and work with actual xenos as a sort of tutorial ruin to learn how to deal with and play as a xeno. There was an exit added, so people started breaking out and working with the xenos via mindslave implants they get roundstart so they raid the station with infinite xenos since they have about 70 monkey cubes total which ends up ruining the round

**Comment by X-TheDark** [comment]
I see, and which parts of this people (aka, the community that apparently didn't like the ruin becoming inescapable) want to stay and which parts people want to remove?

**Comment by ShadowDeath6** [comment]
_shrug_

**Comment by ghost** [comment]
we might as well just add back the old xeno ruin with better rewards since that caused xeno rounds as well but less syndies with guns sniping xenos and infinite respawns, yeah?

**Comment by GrayRachnid** [comment]
I still don't understand why this even still exists when the issue of not being able to have Two queens exists.

Assuming a random xeno event happens on the station, the station xenos can't evolve into a queen because a queen exists on lavaland.

**Comment by X-TheDark** [comment]
@GrayRachnid 

Now that's just top kek, if I do say so myself.

**Comment by Super3222** [comment]
For whatever reason the facility is still open right now.

**Pull request closed without merging**
