### PR TITLE
Revokes minerals withdrawal access from miners.

### PR DESCRIPTION
**Pull request by Super3222**
https://github.com/yogstation13/yogstation/issues/2055

this pr does 3 things.

1. it takes away minings access to the ore redemption machine. stop bringing back ores.
2. i add a new access level which is named 'slave owner'. chemists, qm, and engineers get it. this gives them access to the ore redemption machine.
3. miners have a more appropriate name. slaves.

### CODE REVIEW

**Comment by LlamaObama** [comment]
This really isnt - Oh. oh I see.

**Comment by GrayRachnid** [comment]
6e68cc646a38df3059480b8582207732

**Comment by RoboticVodka** [comment]
https://www.youtube.com/watch?v=dj9NJZUomjQ

Might I add; A man chooses, a slave obeys.

**Comment by ShadowDeath6** [comment]
Doesn't compile smh :smh:

**Pull request closed without merging**
