### PR TITLE
pop up

### PR DESCRIPTION
**Pull request by utahclock**
reenables admin popup

:cl:
rscadd: Admin popups are enabled again so they are no longer easily missed.
/:cl:

re enable admin pop up

### CODE REVIEW

**Comment by Zostroll** [comment]
Admin pop up has killed me like 5 times. They boink is enough.

**Comment by Super3222** [comment]
Don't. If someone's ignoring admin messages and claiming "ME NO SEE IT", than that's on that person. Not the admin.

In any case this should stay disabled. I'm 100% sure someone else tried enabling this before, and it got turned down.

At the VERY LEAST to integrate this into Tickets you could add a BUTTON for ADMINS to "force popup" on someone.

In all cases, I'd be common sense to be careful with it. So using it, and getting someone fucked over like in zostrolls case would be the admins fault. However, in almost every scenario a player should be able to hear that unique BWOINK sound and KNOW that an admin has PM'ed them. So really, it's going to be the players fault without the force popup.

So anyway :-1:

**Comment by ghost** [comment]
People keep whining when I ban them because 'ME NO SEE MESSAGES WHAAAAAAA'

If you fuck up and get a message, that's on you. If the admin tickets you mid combat so you die, that's on them.

**Comment by Nickvr628** [comment]
The issue becomes when someone is in the heat of the moment and does not hear the sound and see the chat message, or they walk away for a moment and when they sit back down the message is already buried in the logs.

I like the idea of a force popup though.

**Comment by utahclock** [comment]
what nick said and the bwoink doesnt always fire if other sounds are.
On Oct 11, 2016 10:06 AM, "Nickvr628" notifications@github.com wrote:

The issue becomes when someone is in the heat of the moment and does not
hear the sound and see the chat message, or they walk away for a moment and
when they sit back down the message is already buried in the logs.

I like the idea of a force popup though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/yogstation13/yogstation/pull/977#issuecomment-252944560,
or mute the thread

**Comment by Zostroll** [comment]
Adam a lot of tickets are made for no rule breaking reasons. If you are saying a miner deserves to die to a Goliath cause he has asked a question then you are a bit of a cunt.

**Comment by utahclock** [comment]
if someone asks a question admins can just a ghost to em before replying if
its a miner

**Comment by Super3222** [comment]
Like I said earlier. You shouldn't force anything on the players or force the admins to popup players.

Simply make it a toggable option, where in a ticket you can click a button that makes every comment that YOU (the admin) send pop up on the player / ticketee.

Therefore, it's the admins decision whether they want to pop up or not. And ticket-based situations become more easy and flexible to deal with. There'd literally be no reason not have this system over pop ups unless you believe that every comment within a ticket is 100% important and NEEDS to be sent to a player immediately. Which is untrue.

**Comment by BOBsHERE** [comment]
I liked when the admin chat popped op. Make it pop up to the side, so it doesnt cover your character or his immediate move space. Also make sure that it doesnt auto select, so we can still move around until we actually click on it.

**Comment by Ephemeralis** [comment]
This is a configuration issue and lies within the scope of the Council, not the coders.

Closing.

**Pull request closed without merging**
