### PR TITLE
Revert "Added the criminal management console"

### PR DESCRIPTION
**Pull request by ghost**
Reverts yogstation13/yogstation#1809

WHAT THE HEL CRUIX

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
kneejerk

**Comment by Bittern12** [comment]
This a dumb feature. So dumb that it forces me to agree with Adam! What have you done Cruix?!!

**Comment by ShadowDeath6** [comment]
fixed in https://github.com/yogstation13/yogstation/pull/1809/commits/9b3d85bd074af52f67a4c3122339f7b2ede38e86

**Comment by X-TheDark** [comment]
You magnificent bastard, Cruix. I love it.

Just for that:
**"I think this feature should stay for a week or two so people can get used to it to, so they can provide feedback on how to improve it."** 👌

**Comment by AdamElTablawy** [comment]
oh its' not on the map

**Pull request closed without merging**
