### PR TITLE
Makes the box of beakers hold large beakers

### PR DESCRIPTION
**Pull request by ghost**
fucking this is really needed already 
##### Changelog

:cl:
rscadd: The box of beakers now holds large instead of normal beakers.
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
H U G B O X

**Comment by matskuman5** [comment]
No but seriously what will normal beakers ever be used for again?

**Comment by Super3222** [comment]
This is a pretty hugboxy PR. IMO this doesn't need to happen given that the games not set up so you can access every little feature so easily. 50/50 beakers are fine, and chemists start with enough beakers to sustain themselves as long as they aren't going into grenades.

Cargo can also massprint large beakers with enough glass (which isn't hard to get).

**Comment by matskuman5** [comment]
Exactly what Super said ^^^^

**Comment by Cruix** [comment]
Leave a comment

**Pull request closed without merging**
