### PR TITLE
Adds new White Ship variant

### PR DESCRIPTION
**Pull request by Tenryumi**
# Meet the S.S.S.

shitbucket
### Screenshot updated as of 642dbd7f73be6c72e0bda94e9ad48e5f535b2a7a

It was very fun making this thing.
# wtf is this, an escape shuttle?

No. This is a variant of the White Ship, Built to accommodate much more people staying there for a much longer time.
### S.S.S.? What do those initials mean?

The name derives from the same event that inspired me to make this: A failed admin event staged so that the entire crew of 30+ people could go on a space adventure on the original White Ship. It was claustrophobic and very ill-equipped to handle what was to come, and the event bombed. 
The aforementioned disastrous ship's name? _The S.S. Shitbucket._

Some things to note regarding the ship:
- All cameras start off deactivated.
- It holds an inactive AI core, so you can card an AI and install it onboard with no hassle.
- Has 10 EVA suit units, and 10 oxygen tanks (More will have to be attained elsewhere.)
- <strike>Has oxygen tanks and vents to keep the airlocks pressurized (so everything doesn't get spaced quite so easily midround)</strike>
## <strike>And wait, what's this about BoxStation being widened?

I've widened BoxStation's outer space by exactly 14 tiles and made some adjustments to the Arrivals docking bay so that the S.S.S. may fit properly in the map if it is deployed.
dreammaker_2016-10-12_20-06-00
_And no, it doesn't actually look like this on the .dmm! I've just temporarily made this space empty for the sake of this screenshot._</strike>
**NVM THE SHIP FITS JUST FINE ON THE MAP WITHOUT MODIFICATIONS**

:cl:
rscadd: Nanotrasen has built a substantially improved version of the White Ship based on its ancient blueprints that they now hold at Centcomm, waiting to be deployed in the White Ship's place to send the crew on proper space adventures.
/:cl:

### CODE REVIEW

**Comment by utahclock** [comment]
actual screenshot please of widened area

**Comment by utahclock** [comment]
also dont ever merge from your master branch. master should be clean code.
make a new branch for every project. push from that.

**Comment by utahclock** [comment]
and it looks like you didnt use map merge tool.

**Comment by Tenryumi** [comment]
Triple oops. I'll get to that in just a minute!

**Comment by Tenryumi** [comment]
dreammaker_2016-10-12_21-03-50
Map of areas after widening

**Comment by Super3222** [comment]
The ship looks amazing. The only flaws I can see are the unreachable suit storage's. Otherwise, it's really great.

**Comment by Tenryumi** [comment]
The 2 obscured suit units are accessible once the units adjacent to them are open.
I had to choose between either those 2 units being temporarily inaccessible, or ruining the symmetry of the room and redoing it entirely. I chose the former.

**Comment by Zostroll** [comment]
Add a mass driver remove the morgue and replace it with botany.

**Comment by utahclock** [comment]
you still havent properly used map merger on tgstation. please fix this.
other wise it looks good. if you need help on how to run the map merger pm
me on discord.

**Comment by Zostroll** [comment]
Your chemistry medbay combo also needs a heater for making some chemicals I suggest you replace the chair with it.

**Comment by Tenryumi** [comment]
@Zostroll There is a heater.
image
- Of course, I could place a chem heater beneath the ChemMaster (not the chair because with this setup the chemist doesn't have to move to do their job,) but that would make the medbay even more claustrophobic than it already is. There are exactly **16** open tiles in the medbay (18 if you count the opened sleepers.) 16/18 tiles of maneuverable area is only barely enough to fit a chemist, 2 doctors, 4 patients and _maybe_ the CMO, all except the chemist constantly moving around inside.
  This would give the medical staff even less room than they already have. I'm trying to leave as much room as possible so as to allow a crew of up to 30 people to board the ship and not get trapped in the crowds, and the best way to do that is to make the stations more compact.
- The chef's gotta get his meat to feed the crew from somewhere. Removing the morgue entirely would put all the meat-producion pressure on the Botanists (meatstalks) and Chemists (synthmeat). 
  However indeed, the chef needs more ingredients than just meat to make their variety of foods. That, and the versatility of Botany is unparalleled. I'll cut the Morgue in half to make way for a Hydro area. 

However I'll have to make more room in order for these additions to actually work without trapping the crew in, and this will involve snipping away some of the inner walls of the ship.

Sure, I'll try to fit a mass driver in.

---

@utahclock Yeah, I need some help understanding how this merger works. I'll PM you.

**Comment by Zostroll** [comment]
Put the heater next to the smart fridge? If not the lighter works its just rather inelegant.

**Comment by X-TheDark** [comment]
Have you tested this?

I'm worried about whether or not you configured the docking points properly, as they carry such things like **maximum width/height** of the ship that can dock to it, as well as the docking point on the ship itself (that tells the game how high/wide it is).

**Comment by Kmc2000** [comment]
I came

Im gonna take inspiration from this and make voyager a white ship

**Comment by utahclock** [comment]
map still not merged properly. hint is it adds a line of text to map when done properly.

**Comment by Tenryumi** [comment]
@X-TheDark Welp... I've now configured the docking port to what it should be. Oops...

@utahclock _still?_ I'm really clueless on how to use this map merger it seems...

**Comment by utahclock** [comment]
yes still. it adds a very specific line of text to top of map file when
done correctly.

**Comment by Tenryumi** [comment]
@X-TheDark I have now tested the map. I'm experiencing some very odd issues where some air pipes don't spawn, and the vents don't connect. Even odder is some objects are duplicated on top of each other (?????)

**Comment by X-TheDark** [comment]
Is it just the pipes that aren't spawning or are parts of the ship "cut off", like it's a rectangle or something?

**Comment by Tenryumi** [comment]
Everything was working just fine but the pipes and doors. Realized the problem was the pipe types I was using were incorrect. Removed the pipes because it seems the vents don't work on shuttles anyway.
In addition the doors were duplicating themselves (specifically the doors I modified to fit the shuttle.)

**Comment by Tenryumi** [comment]
And now the only issues I face when testing are: 
- some doors duplicate themselves on top of each other when previewing the shuttle.
- Attempting to load the ship itself to replace the old Whiteship gives no feedback and does not work. However I can preview the ship with no issues asside from the above.

**Comment by utahclock** [comment]
You have your ship movement area layer as big as your ship right ?

**Comment by Tenryumi** [comment]
You mean the variables on the docking port that tells the length+width of the ship? Yes, I'd changed that after reading @X-TheDark 's comment on it.

**Pull request merged**
