### PR TITLE
Ports BayStation12 Sound

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Ports BayStation12 Sounds
- Sounds are environmental. Yay!
  - In some places sounds will flatten or sounds will become more echo-y (hallways).
  - Lavaland sounds amazing.
- Being in space, dizzy, drugged, sleeping, or hallucinating will all have effects on how sound is perceived.
- They generally sound great.

Credit to:
https://github.com/Baystation12/Baystation12/pull/8855
https://github.com/Baystation12/Baystation12/pull/9942

#### Changelog

:cl: Super3222, Baystation
rscadd: Ports Baystation12's sound system. Depending on your location and body condition you will hear sounds at different pitches, volumes, and possibly in an echo.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
example please

**Comment by matskuman5** [comment]
^

**Comment by Lightning38088** [comment]
Will it play music in someplaces like major tom in space and noir music in detectives office, or will it just play sounds like the weird ambiance?

**Comment by Super3222** [comment]
No, this PR isn't involved with lobby music in anyway. It changes the way sounds work in the game. Now it will be more environmental base, and on top of that manipulated by the state of your mob.

**Comment by matskuman5** [comment]
I just tried it out on Bay, it's super fucking loud compared to other sounds

**Comment by Super3222** [comment]
It sounded completely normal on my private server.

**Comment by Nirnael** [comment]
It's cool but way too echoy imo, it sounds like a huge empty hangar in small hallways.

**Comment by ShadowDeath6** [comment]
the ping of announcements and vox just sound so awful with this, it gives me headaches

**Comment by Slinky5890** [comment]
The echo bwoinks are pain

**Comment by Super3222** [comment]
I'll attempt to remedy vox, announcements, admin noises by making them ignore the area you're in.

**Comment by McDonald072** [comment]
It's waaaay too echoy. Sounds like you are in a huge hangar or cathedral no matter where you are.

**Comment by Super3222** [comment]
I'm looking into it. @McDonald072 it's the reason I opened up a topic on the forums for players who want to inform me of rooms that are too echo-y.

**Comment by stikenir** [comment]
While this is very cool, echo makes me uncomfortable... It would be great to have an option in the preferences tab to change the echo, if you want more or less, somewhat like other sound options in the game.

**Comment by Super3222** [comment]
I can definitely work with a preference option to cancel out all echos. However the default would be with echoes so new players can try it out before quitting :P

**Pull request merged**
