### PR TITLE
more cult balancing

### PR DESCRIPTION
**Pull request by ShadowDeath6**
who would have guessed, cult spamming manifests is a bit unbalanced.

:cl: ShadowDeath6
tweak: Manifest runes now hurt you when you bring a ghost into a soulstone.
tweak: Lesser supply talismans now have one use, down from 2.
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
If you want to _really_ balance blood cult, make their runes cost blood ASWELL as brute.  Blood is a lot harder to fix, and can really fuck someones day over.

**Comment by matskuman5** [comment]
It'd be cool if cults needed blood packs or bodies to make runes

**Comment by ShadowDeath6** [comment]
Blood is too hard to get a lot of, considering the only way you can only get it from cargo or the two O- bloodpacks in medical.

**Comment by Jc1469** [comment]
I mean blood from the people using it. Not blood packs. It's a cult about blood for a reason.  >you cut your wrists, oh no, brute damage raaagh.

**Comment by ShadowDeath6** [comment]
Yeah, but getting blood is still extremely irritating when you lose blood when you try and play the antag.

**Comment by YogsMcree** [comment]
Blood exists inside Viro, Mining and Medical. I think it wouldnt be hard to make a Virology trait that restores the blood of the user at a cost of metabolism (increased food drain). This would make Virology EXCEEDINGLY important for cult rounds, both fighting and bolstering. You could lie and distribute a weight loss blood gain virus labeled as Weight Even blood gain, or be converted and forced to make a weight even blood gain virus.

**Comment by ShadowDeath6** [comment]
I'm not making multiple new features and a new viro symptom for nerfing unbalanced cult features

**Comment by Super3222** [comment]
It's still going to be unbalanced after this given that pylons and bruise kits exist in the game.

> blood packs or bodies to make runes
> I mean blood from the people using it. Not blood packs. It's a cult about blood for a reason. >you cut your wrists, oh no, brute damage raaagh.

@matskuman5
@jc1469 
Honestly requiring blood and/or bodies would be a cool to see in a possible bloodcult remake / rework.

**Comment by ShadowDeath6** [comment]
Pylons heal slowly and brute kits are decently finite. The point is to slow it down, not to outright kill them for using a feature.

**Comment by Dagdammit** [comment]
Could give blood cultists high blood regen as baseline.

**Pull request merged**
