### PR TITLE
Adds new lobby songs

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
enjoy

### CODE REVIEW

**Comment by Time-Green** [comment]
Good PR. 
This reminds me tho, we really need to change the way the title music gets played. It takes alot of memory, and this quadrupples it, if not more.
Pheraps we could use soundcloud and have that play on the background.

**Comment by Super3222** [comment]
Give examples of the actual songs.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
All of the songs listed here: https://forums.yogstation.net/index.php?threads/add-more-lobby-songs.12527/#post-119263

**Comment by Super3222** [comment]
There's 18 songs on that poll. You've chosen about 11 of them. Can you please list them out specifically.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
[Carmen Miranda's Ghost title song](https://www.youtube.com/watch?v=D5p8YhhaVlA)
[Space Station 13 - Musique d'intro](https://www.youtube.com/watch?v=pInBXkt3jvQ)
[robocop.mp3](https://www.youtube.com/watch?v=vHo7npmGcHU)
[clown.wmv](https://www.youtube.com/watch?v=d2xkpz-26jM)
[Get Lucky - 8 bit remix](https://www.youtube.com/watch?v=CfMMlT8Lyns)
[Seven Light Years](https://www.youtube.com/watch?v=SyhrlkObeJE)
[Kavinsky - Nightcall 8 bit remix](https://www.youtube.com/watch?v=0m5POcX2VSo)
[Yes - Roundabout](https://www.youtube.com/watch?v=-Tdu4uKSZ3M)
[FTL Soundtrack - Lanius Battle](https://www.youtube.com/watch?v=mG6Ys2opFD0)
[ME3 Sountrack - Mars Ambient](https://www.youtube.com/watch?v=4hpy49M6QnU)
[HL Soundtrack - Nuclear Mission Jam](https://www.youtube.com/watch?v=0iXfWWrwrlQ)

Some are extended to be longer than 3 minutes

**Comment by GrayRachnid** [comment]
Won't this add a huge strain on the server bandwidth?

**Comment by utahclock** [comment]
Yes it will thats why we have limited songs that we do have. Ask cruix. Ive
suggested adding 1 to 2 songs too pool and was told because of resources
 No.

**Comment by Alek2ander** [comment]
Maybe embed a youtube video or something? So everything is clientside?

**Comment by Time-Green** [comment]
Already suggested that to Oisin and he told me it was fine to have alot of songs

**Comment by oisin100** [comment]
> Already suggested that to Oisin and he told me it was fine to have alot of songs

*she

I believe it should be fine, it will use a little bit more resources when downloading assets, but not a great deal(Im told all the songs in total are 7MB?)

**Comment by Time-Green** [comment]
That was the current songs. 
This brings it to about 35 mb

**Comment by Dagdammit** [comment]
If you wanted to trim the list a bit the ones that barely made the cut were "Seven Light Years", "Nightcall 8bit" and "Roundabout". Could also use the non-extended versions of other songs, especially those lasting 2-3 minutes; I know I'd be fine with some songs finishing a bit before roundstart if it meant more variety.

**Comment by Gintoki1** [comment]
In my opinion I think the Clown.nmv should stay on and surprise no doom music was listed (for miners)

**Comment by McDonald072** [comment]
Won't this only be a one time download? So the server will only be strained once after this is merged, when people are downloading the songs, then it won't be too big of an issue.

**Comment by doerakpoes** [comment]
> *she

Wait are you telling me I have been misgendering you all this time?

Also : [Yes - Roundabout](https://www.youtube.com/watch?v=-Tdu4uKSZ3M) good choice

**Comment by ShadowDeath6** [comment]
Feel free to work this into a mergeable state, I look forward to new songs.

**Comment by GrayRachnid** [comment]
This shouldn't be merged because of how much space it would take 👎

**Comment by Super3222** [comment]
@Cruix @oisin100 Can we get a final decision between the two of you? One says that it won't work, and the other says it does. Can we have a confirmation?

**Comment by Dagdammit** [comment]
Or just try and it see who's wrong.

**Comment by oisin100** [comment]
If it was 7 MB i would have been fine with it, But 35MB's are too much, that almost doubles our download size, not good for new players.

**Comment by Dagdammit** [comment]
I'll try and cut it down some.

**Comment by Dagdammit** [comment]
I took a minute in audacity and carved the files down to 16 mb total. That drops to under 11 MB if we cut the three in current pool that polled lowest (7 Light Years, Nightcall and Roundabout), or under 9 MB if we also use just the clown version of Robocop theme rather than both that & original.

Not sure what the best way to upload the files would be in this circumstance. Could just make a .zip and post the link here I guess.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
sure, hand em over and I'll push them

**Comment by Dagdammit** [comment]
https://drive.google.com/open?id=0B3Q3BH2z4ExCNDFFaVBseGhGR3M

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
So which option are we going for? 16, 11 or 9 MB? @Cruix  @oisin100 
Right now it's about 10 MB

**Comment by Super3222** [comment]
@Cruix What is your take on this?

**Comment by Daman453** [comment]
@Cruix pls

**Comment by Dagdammit** [comment]
Asked him recently on discord, he said something about wanting to review the songs himself? Possibly to decide which amount to include? I don't think I fully grasped his intent.

@Cruix can we just merge the version with 9 songs and accept that you might want some changes in the near future? I think it'll be a really nice change.

**Pull request merged**
