### PR TITLE
Buffs the space bartender via space bar map changes

### PR DESCRIPTION
**Pull request by Tenryumi**
I've always wondered... Why is it that the space bar has LESS things in it than the actual bar itself does?
So I thought, "Let's set it apart and add further to the surprise of discovering the space bar! And maybe also give the space bartender SOMETHING TO ACTUALLY DO."

dreammaker_2016-10-14_20-38-24
# WHAT WAS ADDED:
### \- An autolathe, with 2 full stacks of both metal and glass next to it.

_Purpose: to enable the bartender to build all sorts of tools and devices to customize the bar. Also to create ammo for the shotgun._
### \- A double-barreled shotgun and bandoiler

_Purpose: If all bartenders start with this, why shouldn't the space bartender?_
### \- A crate with an RCD and 4 RCD cartriges

_Purpose: to allow the bartender to customize the bar a little bit to their own preferences. Help them feel more at-home by making their permanent home their own._
### \- A Dinnerware Vendor

_Purpose: kitchenware to accommodate the fridges and microwave._
# WHAT WAS CHANGED:
### \- Soda and Booze dispensers start off emagged

_Purpose: To give the bartender more chemicals to play around with, and to help further set their bar apart from the station's bar. They have had their name slightly changed to reflect this._
# "But isn't this overpowering the space bartender?"

Consider the fact that the space bartender is one of the most isolated ghost spawn roles in the entire game, spawning in a tiny asteroid in space with no internals access. The chance of somebody actually visiting the space bar is even lower than somebody finding a Lifebringer vault in Lavaland, where one can create 100 potency deathnettles with substantially less effort than a standard Botanist. This buff is intended to not only give a space bartender something to do, but also allows them to truly make the bar their own and add to the surprise of its discovery when it's been set up with whatever wacky spin the player wants to put on the bar.

:cl:
rscadd: The Space Bar now has much more to do in it for those lonely nights on an isolated asteroid.
/:cl:

### CODE REVIEW

**Comment by Ephemeralis** [comment]
I'm actually very impressed with your thought process for the improvements I've seen you do so far. Are you on our development discord at all? I'd like to run a few things through you to get some feedback.

**Comment by Time-Green** [comment]
Looks good.
Could you also add in an arcade?

**Comment by Tenryumi** [comment]
@Ephemeralis Oh, uhm, thank you. I am on your discord as _Yumi (Aka Gowst)#1153,_ But I never knew you guys had a separate development discord. Sure, feel free to invite me.

@Time-Green Hahah, sure!

**Comment by ghost** [comment]
Put a bluespace gigabeacon and a teleporter and GPS there, so people can warp to the space bar and visit

**Comment by Tenryumi** [comment]
Closing this so I can re-do it; merged incorrectly, and the branch it was on has been since deleted.

**Pull request closed without merging**
