### PR TITLE
makes rice useable

### PR DESCRIPTION
**Pull request by ToGWtF**
### Intent of your Pull Request

grown rice couldn't be cooked in any way

#### Changelog

🆑 

bugfix: rice actually works now hey

/🆑

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I think you broke Travis

**Comment by ActualRory** [comment]
Poor Travis, we barely knew thee.

**Comment by ToGWtF** [comment]
I don't honestly know how I could have possibly done this..

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
close and reopen, should knock some sense into him

**Review by AshCorr — APPROVED** [review]

**Pull request merged**
