### PR TITLE
Reverts a part of #1397

### PR DESCRIPTION
**Pull request by Super3222**

### CODE REVIEW

**Comment by Time-Green** [comment]
Didn't my bugfix work? I mean, power works, wires might be jerky tho.

**Comment by Super3222** [comment]
Oisin told me that the APCs wouldn't charge.

**Comment by Time-Green** [comment]
The hell? I tested my bugfix PR and they did.

**Comment by Time-Green** [comment]
schermopname 375
This is from my private branch I made the bugfix on

**Comment by Cruix** [comment]
The server has been finicky lately, the last two times I have updated I have had to do it twice to make the changes go through. If the fix did not have a changelog the server might be running the pre-fix version and nobody would know.

**Comment by Time-Green** [comment]
Shit. So it did work! Muhahaha!
I still fucked up tho, let's just wait for the next time the server gets updated, and then it'll probably go in effect.

**Comment by Time-Green** [comment]
DNM, the bugfix indeed worked, simply didn't update.

**Comment by Super3222** [comment]
Nice work

**Pull request closed without merging**
