### PR TITLE
Ports: Juicy ss13

### PR DESCRIPTION
**Pull request by Time-Green**
Ports: https://github.com/tgstation/tgstation/pull/23885 by @Iamgoofball 
Ports: https://github.com/tgstation/tgstation/pull/23516 by @Cyberboss

- [X] Make progress bars look sexy

- [X] Make foam look sexy

- [X] Make the singularity look sexy

- [x] Make beams sexy

:cl:  Iamgoofball and Cyberboss
experimental: Makes most visual effects juicy as fuck with animations.
rscadd: Makes progressbars stack
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
By beams do you mean the laser variety?

**Comment by Time-Green** [comment]
No, I mean the ones like lightning, the BSRPD, ninja net etc

**Comment by oisin100** [comment]
This changelog wont work, Yogbot will only count the first one.

**Comment by X-TheDark** [comment]
Damn, great work!

**Comment by Zostroll** [comment]
Can we get some gifs/photos?

**Comment by Time-Green** [comment]
I'm on my phone, so I can't. Hit the link to goofs PR for pictures

**Pull request merged**
