### PR TITLE
Improves centcom!

### PR DESCRIPTION
**Pull request by Kmc2000**
Tired of our old, boring centcom, filled with bland colours and no fun?

Well, say no more friend. This makes Centcom much more interesting, with 10x the lebensraum!

This new centcom better befits the tyrannical Nanotrasen of lore than a weird hotel lobby style centcom, as well as boasting a wider range of facilities, this one also has actual staff that walk around the place!

Before:

Pics:

The shuttle is now much more Kriegsmarine oriented too:

What's actually different?

The admin abuse room has been assigned the correct area
The thunderdome has been re-added, players can access it too.
The ninja holding facility is also themed
Along with the restyling, alternative centcom outfits have also been added to suit the mood.

#### Changelog

:cl: Kmc2000
rscadd: Added alternative centcom uniforms
rscadd: Remodelled centcom to fit NT's personality more, check it out! 
rscadd: The default emergency shuttle has been modified to fit the new Centcom theme, it's now more kriegsmarine oriented in design.
/:cl:

### CODE REVIEW

**Comment by Zostroll** [comment]
Did this unfuck krampus'es bag?

**Comment by Ratvar** [comment]
only need mecha hitler now

**Comment by Nickvr628** [comment]
Breaks the lore and style of everything... ehhh.

It looks really cool, but I am not sold on the red and black color scheme.

**Comment by Super3222** [comment]
Nanotrasen is composed of rich, power-hungry, money-loving capitalists. They're not klingons. Centcom isn't meant to strike fear into anyone.

> also not mapping star bases

**Comment by Geikkamir** [comment]
Would say that the biggest problem is the colors. Red and black is the Syndicate color scheme. NT is usually blue and white.

**Comment by ghost** [comment]
>red

>your shitty syndi moon

can we just port /tg/'s centcomm

**Comment by drderp3635** [comment]
Ah yes the classic red and black color scheme only assosiated with nanotrasen. Im so glad that there isn't an entire syndicate of rival groups who have set out to take down nanotrasen and very much so flaunt their love of the red and black color scheme pretty much everywhere they can. nope don't see any mismatching bits here. no sir-ee. what a error proofed concept.

**Comment by Kmc2000** [comment]
>Drderp
There are other ways to get back into good favour with people other than joining a bandwagon with a pitifully sarcastic roast, leave that to Adam or people who know what they're talking about, please.

**Comment by matskuman5** [comment]
What even is that red V logo meant to represent and why is it placed literally everywhere

**Comment by Notamaniac** [comment]
V for vendetta

**Comment by Kmc2000** [comment]
>matskuman

Oaksoc, the real party controlling the Yogs universe

**Comment by Moja10** [comment]
You spent way too much energy on this PR and I fundamentally disagree with it purely based on the colors alone, stop with the fucking Nazi themes

**Comment by Amelia0010** [comment]
r i p c o n f l i c t s

**Pull request closed without merging**
