### PR TITLE
Remove secborgs

### PR DESCRIPTION
**Pull request by ghost**
these things literally ruin the lives of antags. they got removed on /tg/ for a reason. Also, we need more borgs playing Peacekeeper.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
every antag has a counter to it, please git gud 

do we really need a label for "we aren't tg"

**Comment by Time-Green** [comment]
The sec borgs are hardly a problem here on yogs, the only problem may be their disabler charge, wich can easily be changed

**Comment by Kmc2000** [comment]
No

**Comment by ghost** [comment]
I hate being dunked by a freaking robot as a clockwork cultist.

**Comment by Mrcreepssss** [comment]
pal
use flashes. and convert them, also git gud

**Comment by ghost** [comment]
Too bad loser.

**Comment by Super3222** [comment]
The majority of antagonists already have ways to beat borgs + provided that our disablers drain battery and we have an open PR that limits the number of cuffs they have.
Hell, as a clockwork cultist I managed to kill a secborg on accident by building a bunch of random defense-eye thingies.
And with the loss of secborgs, people will move to clwonborgs at best.

**Comment by doerakpoes** [comment]
Sec Borgs should live if you can't defeat sec borgs then git gud

**Comment by Jc1469** [comment]
:thinking:

**Comment by Mrcreepssss** [comment]
"The majority of antagonists already have ways to beat borgs + provided that our disablers drain battery and we have an open PR that limits the number of cuffs they have."

with that cuff limit, how can it be refilled? i mean otherwise we have an issue.

**Comment by Super3222** [comment]
> with that cuff limit, how can it be refilled? i mean otherwise we have an issue.

With cyborg recharge stations. It's all mentioned here: https://github.com/yogstation13/yogstation/pull/1992

**Comment by Mrcreepssss** [comment]
"borgs playing Peacekeeper."
peacekeeper has no redeeming value, it's just as useless as the clown. well except cookies, cookies are great!

**Comment by Time-Green** [comment]
It's not happening, the only one that liked it, is gt33

**Pull request closed without merging**
