### PR TITLE
removes multiplying dragons

### PR DESCRIPTION
**Pull request by ghost**
Removes ash drake multiplication

#### Changelog
Ash drake attack chance of creating more dragons is now based off how pissed they are. The lower health, the more often they spawn dragons.

#### Changelog

:cl:
rscadd: Ash drakes no longer undergo mitosis
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
fix lesser drakes spawning other drakes as well that wasn't intended

**Comment by Jc1469** [comment]
of course it was intended.  it was also intended to _walk away_ from the lesser drakes and kill them later, but some people.  
but sure, make it even rarer.  It's already an rng shitfest anyways.  I had many fights where they didn't call in 
lesser drakes at all :thinking:

**Comment by ShadowDeath6** [comment]
As much as I like the idea of megafauna being challenging, there comes a point when having what's essentially a meatshield for the original drake having a chance of duplicating itself whenever it takes a hit is unfun. This also makes fighting drakes on-station much more difficult because the megafauna take way more hits from conventional station weaponry, thus rolling the chance of duplication much more often, and having random dragons that can destroy literally every structure and spam an instacrit swoop move against unarmed crew is really annoying.

**Comment by Nirnael** [comment]
Who even made ash drakes spawn other ash drakes? In 1 minute I got 3 ash drakes on me, and you cant even tell which one you were fighting at the start, its so idiotic

**Comment by Super3222** [comment]
@fizzle7 Megafuana scaling made megafuana randomly spawn on a scale from strongest to weakest. I'm guessing you were fighting a strong one.

**Comment by Nirnael** [comment]
Its not even that, we were fighting a kindling thats like the second weakest or something and from 1 drake spawned like 7. I managed to kill them tbh, its not like THAT hard, its fun but still, it as a weak drake. 7 stronger drakes is retarded.

**Comment by Jc1469** [comment]
>removes attack that makes drakes harder, doesn't mention removal of entire attack.

k

**Pull request merged**
