### PR TITLE
Gives engis access tot he ORM

### PR DESCRIPTION
**Pull request by Amelia0010**
🆑 
tweak: Engis can now use the ORM
/:cl:

### CODE REVIEW

**Comment by Enkaaa** [comment]
at last i will have bottomless supplies of metal to fix hull breaches and make walls

**Comment by Nickvr628** [comment]
*heavy breathing*

**Comment by Jc1469** [comment]
signal tech needs it to make plasma floors to kill themselves

**Comment by Nickvr628** [comment]
Do not forget installing uranium doors everywhere to increase reliance on medbay, and then start charging for antitoxins!

**Comment by MegaEmpirical** [comment]
Is this for the engineering department or engineers? Atmos techs could use access too.

**Comment by MegaEmpirical** [comment]
So no love for atmos, sad. Still nice that engis can now.

**Comment by kooarbiter** [comment]
if we're gonna give engineers mat storage we should also give it to CE, or maybe give CE access alone and have all requests for mats from engineers go through them, although nothing stopping anyone from asking hop for access if there isn't a ce or they are being a comdomy mc comdomface

**Comment by Amelia0010** [comment]
the CE already has access...

**Pull request closed without merging**
