### PR TITLE
Yogmap2

### PR DESCRIPTION
**Pull request by utahclock**
Gray's permabrig changes

### CODE REVIEW

**Comment by TheSadFox** [comment]
Pictures.

**Comment by ShadowDeath6** [comment]
where's iso

**Comment by GrayRachnid** [comment]
gone

**Comment by ShadowDeath6** [comment]
replace rwall room with iso

**Comment by GrayRachnid** [comment]
You know my request was remove iso and put the r-wall room in instead.

**Comment by ShadowDeath6** [comment]
ok well my request is to remove that because the rwall room will be spammed by le powergaming HOSes and is akin to locking them in the 2x3 permabrig room but it has rwalls instead of regular walls

**Comment by Super3222** [comment]
In that tiny space above the insane asylum's exterior & interior, mind putting an alien nest & random misc. item spawner? There's no harm in those items.

**Comment by Super3222** [comment]
In that tiny space above the insane asylum's exterior & interior, mind putting an alien nest & random misc. item spawner? There's no harm in it at all. We also had it in the execution room.

**Comment by GrayRachnid** [comment]
> ok well my request is to remove that because the rwall room will be spammed by le powergaming HOSes and is akin to locking them in the 2x3 permabrig room but it has rwalls instead of regular walls

I'm going to be adding a rule specifically for that room so it doesn't get abused like isolation.

**Comment by utahclock** [comment]
yea i can add it tomorrow. :)

**Comment by ShadowDeath6** [comment]
or just don't have it exist to be abused

**Comment by Alek2ander** [comment]
You could quickly escape the old isolation if you had tools and space protection, even if the shutters were closed.
This is much more op

**Comment by EMT321** [comment]
I see you have an igniter in the execution chamber, and gas pumps. Please add a plasma tank to the available gas storage so prisoners can be caramelized. Might require blast doors to be able to fall, much like the testing lab.

While you are at it, can you change the walls at Sec Storage and HoS office (specifically the space-facing ones) to be R-Walls? Always bugged me that the rest of brig was reinforced, but not the room with all the sec gear, or the HoS private office.

**Comment by Alek2ander** [comment]
You reinforce walls between less secure and more secure areas, not between sections of one area with the same level of security. So separating armory from brig office with rwalls is reasonable, and separating brig office from maint, but not separating brig office and brig storage or HoS office.

**Comment by killerx09** [comment]
Make sure the cameras don't cover the execution doors if possible.

**Comment by ParagonPrime** [comment]
Also, change the bed in the execution room to be a chair so you can still make electric chairs.

**Comment by GrayRachnid** [comment]
> Also, change the bed in the execution room to be a chair so you can still make electric chairs.

There's a wrench right there, just change the bed to a chair and do it.

**Comment by ShadowDeath6** [comment]
why not have it start as chair tho

**Comment by GrayRachnid** [comment]
because beds are cooler

**Comment by ShadowDeath6** [comment]
no

**Comment by Super3222** [comment]
There shouldn't even be a bed there, to be honest... aren't psychopaths suppose to walk around inside of a inescapable room with a straight jacket on?

Edit: 

> Please add a plasma tank to the available gas storage so prisoners can be caramelized.

This'd be good.

**Comment by GrayRachnid** [comment]
We already have cases of people accidentally flooding permabrig with N2O when they try to use it. Plasma is worse, and if you want to incinerate someone then do it in the crematorium or science.

**Comment by ParagonPrime** [comment]
> because beds are cooler

what

what fucking purpose would there be for a bed in an execution room

have you ever heard of execution rooms with beds in them

it should just be a chair at the start for a million fucking reasons

> We already have cases of people accidentally flooding permabrig with N2O when they try to use it. Plasma is worse, and if you want to incinerate someone then do it in the crematorium or science.

Nobody uses those canisters anyway and Gray's now applying his "no fun allowed" approach, so I'd recommend removing them and the gas port. The usual methods of execution are egun, syringe, or just opening the blast doors, and occasionally electric chair if the HoS is entreprising

**Comment by GrayRachnid** [comment]
I wouldn't call it no fun allowed when i'm stating a fact, N2O leaks are already a thing, why would you want a plasma leak?

**Comment by Alek2ander** [comment]
For science. If you add a chair make sure there are wires under it.

**Comment by Super3222** [comment]
Why'd you revert the insanity ward? That was literally one of the best things I've seen on the map, right next to the floorsafe.

> powergaming HOSes and is akin to locking them in the 2x3 permabrig room but it has rwalls instead of regular walls

That's an admins problem, not the maps problem.
The room is meant to hold AWFULLY LETHAL ANTAGONISTS which can't be locked up in permabrig, because maybe it's not safe or there's other prisoners, or for prisoners that are fucking nuts. Please re-add it Utahclock.

And Shadow is right about the execution stuff, there should be a chair in the execution room. For obvious electric chair memes, lets not complicate things for 4noraisens. If you want a bed, wrench the chair, and make it yourself. A chair serves more purpose than a bed.

**Comment by ShadowDeath6** [comment]
> shadow is right

I was the one complaining about the insanity ward

it needs a window so antags can break into it tho

**Comment by Super3222** [comment]
@utahclock Can we get an update on the map, please?

**Pull request closed without merging**
