### PR TITLE
Adds nice engines

### PR DESCRIPTION
**Pull request by Kmc2000**
Our current engines are old and outdated, this makes them look prettier. MOST of the ships have been optimized for them, but there is one straggler (the shitbucket) that doesn't play well

Sprite PR with no pictures:

(The sprites in action)

##### Changelog

:cl:
rscadd:  Nanotrasen scientists have developed a new kind of thruster, said to exceed its predecessor in carbon neutrality, as part of the "keep the space lanes clean" initiative, NT has kindly made these new thrusters mandatory and incurring heavy charges for using them. Aren't they nice.
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
i don like it.
corners look clunky.
ugly
805cc2d8fb 1

doesn't blend in with the shuttle scheme at all imo

NO / 10

**Comment by Kmc2000** [comment]
>johncena meme

Fixed the shuttle at least

**Comment by Jc1469** [comment]
I accept that you're trying to fix it, but it looks like someone cut a sleeper in half and glued parts of the PA to it and decided to use that as a thruster.
The singular ones for the pods also look a lot like airlocks.

The phrase I'm looking for is probably "if it ain't broke, don't fix it"
Some things are meant to look clunky and horrible. It adds to the feel that you're on a space station full of retards.

**Comment by Kmc2000** [comment]
Meh, i just hate the clunky thrusters so personal opinion i guess

**Comment by george99g** [comment]
image
Obligatory "SQUASH YOUR FUCKING COMMITS ALREADY" post.

**Comment by Kmc2000** [comment]
😆🔫

**Comment by Kmc2000** [comment]
Alright if there's much more negative feedback then i'll comprimise:


I'll keep the stock ones, but add subtypes of each for these ones for mapping space ships and such, as on stuff like the white ship they do work well.


So yeh would that be acceptable?

**Comment by ShadowDeath6** [comment]
Stop bitching about no smoothig, half the sprites in this game don't fit together and look worse than this. It's not noticeable unless you actually care enough to look for a problem in game and these look nicer than the old ones

**Comment by ShadowDeath6** [comment]
no I like the new ones

smoothing complaints is NOT grounds for not implementing new cool sprites

shutl
also this is good keep this

**Comment by GrayRachnid** [comment]
They don't fit in.

**Comment by Jc1469** [comment]
sprites not fitting in == grounds for not implementing.  See: ponies walking around as pAIs and admins getting strikes for it.

They look fine, sure, 

>  but it looks like someone cut a sleeper in half and glued parts of the PA to it and decided to use that as a thruster.
The singular ones for the pods also look a lot like airlocks.

**Comment by ShadowDeath6** [comment]
sprites from a tv show as mob sprites != making engines that don't look like microwaves

**Comment by enailz** [comment]
well at least it doesn't look like a clown
_**HONK!!!**_

**Comment by Super3222** [comment]
> smile seeing that somebody got a lot of emojis on their post indicating that multiple people reacted to it
> frown when every last emoji was sadly made by the poster himself.

**Comment by ghost** [comment]
>read pr name saying 'adds nice engines'
>smile
>realize it was a sprite PR created by KMC and therefore includes KMC sprites
>frown

**Comment by Kmc2000** [comment]
>adam


Ouch..that hurts

**Comment by matskuman5** [comment]
Clashes with the rest of the shuttle. Old engines are better IMO.

**Comment by Notamaniac** [comment]
The engines are sprited in such a way that they don't connect to the shuttle walls properly, either with misaligned shading or greyspace. The plates on the engine are also very plain, and need some texture, either metal or just some extra shading.

**Comment by Rafael450** [comment]
i prefer the old ones

**Comment by Cruix** [comment]
Add it to the white ship and leave all the ones on the station. It will avoid merge conflicts and people might start getting used to them.

**Comment by Kmc2000** [comment]
k i will add a subtype when i get around to it

**Comment by Super3222** [comment]
20 days later...
@Kmc2000 Consider making it blend with the rest of the shuttle. Right now it contrasts with it, which is a BIG weakness and not something players would enjoy looking at. Imagine being a player and seeing two pieces of a puzzle not going together, but for whatever reason they're jammed stuck. That's what's happening here. You've got to find the right pieces.

**Pull request closed without merging**
