### PR TITLE
Does what was necessary to Pun Pun

### PR DESCRIPTION
**Pull request by ghost**
I'm so sorry, but it had to be done. 

The meme never dies.

:cl:
rscadd: Pun Pun name list has been updated
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I don't even think punpun's name can change ever

this is a good change though

**Comment by ghost** [comment]
it does change if he dies

**Comment by ShadowDeath6** [comment]
I've seen pun pun die a lot and I don't see it changing

**Comment by timkoster1** [comment]
tru

**Comment by george99g** [comment]
I don't think that functionality is enabled, Adam.

**Comment by Time-Green** [comment]
Doesn't matter george, if it ever gets enabled, or spawned in, harambe has a 1/8 chance to be there.

Worth it.

**Comment by Super3222** [comment]
goddamnit adam

**Comment by ShadowDeath6** [comment]
custom desc for different names when

**Comment by george99g** [comment]
_why was this merged_ :frowning:

**Pull request merged**
