### PR TITLE
More xeno facility fixes

### PR DESCRIPTION
**Pull request by Stealthkibbler**
reeeee

:cl: Stealthkibbler
fix: Xeno Facility nano-med and Booz-o-mate are no longer ID restricted, the eswords can now be combined to make double eswords.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
the monkey pen is dark in there y'know

**Comment by ShadowDeath6** [comment]
>dual eswords

gooooooood.

**Comment by Stealthkibbler** [comment]
Its fixed in this pr

**Comment by Stealthkibbler** [comment]
merge ready

**Pull request merged**
