### PR TITLE
Refactored chameleon items.

### LINKED ISSUE #1199: Can we get a better UI for chameleon gear?
Right now finding a specific torso or helmet is extremely annoying. Scrolling through that huge ass list is ridiculous, and looking for the first letter takes just as long. If we could CTRL F search the list it wouldnt be so bad. Can we get a better UI that lets us search like the syndicate PDA or sec records?

### PR DESCRIPTION
**Pull request by Cruix**
Fixes #1199

Chameleon items no longer each give you an action to change them, having any chameleon items gives you a single action that brings up a UI to change all the items you are wearing individually, or all at once into a default job outfit.

Also fixed some items not appearing on the chameleon item selection list.

cham2

:cl:
experiment: Chameleon items now have a UI that allows you to quickly select default outfits for all jobs.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
oh boy more tgui

**Comment by Cruix** [comment]
If tgui can handle byond icons I don't know how to do it.

**Comment by Super3222** [comment]
my first reaction was "fucking sweet" :ok_hand: nice work.

but yeah tgui has a tendency to lag.

**Comment by Cruix** [comment]
It's not tgui, it's regular browse and Topic

**Comment by Dagdammit** [comment]
Does this still show to any non-traitor who picks a chameleon item up, despite them being not supposed to have any in-game ability to see the item is unusual?

**Pull request merged**
