### PR TITLE
Adds emoji to Asay

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Adds the use of emoji to Asay.

#### Changelog

:cl:
tweak: Emoji now work in asay
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Give this man head coder

**Comment by drderp3635** [comment]
Absolutely revolutionary a real notch above the rest

**Comment by Ratvar** [comment]
add emoji to dsay, start with nichmoji

**Comment by Cruix** [comment]
Asay is ostensibly only for professional and mature communication between admins and does not need emojis.

**Pull request closed without merging**
