### PR TITLE
Borer Control Panel

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Introduces the ~~extremely rough~~ Borer Control Panel

- Tracks borers unattached to humans
- Tracks borers inside of humans, linking to PP and universal vars of both the borer and the human.
- Tracks borers that are controlling humans, and gives where each others minds are located.
- When you open the panel you get sent numerical values containing: 
  - the amount of borers alive inside of a human
  - the amount of hosts alive with a borer inside of them
  - the amount of roaming borers with no human
  - how many humans are being mind controlled by borers.

Also some side things.
- Panacea force ejects borers.
- Borers can no longer infect shadow people. **Requires https://github.com/yogstation13/yogstation/pull/1148 to be merged intentionally**. I was making 2 checks in the same place.
- Borers on-leave will delete the borer HUD from their victims.
- Created species is_helper's for shadowpeople and shadowlings.

#### Changelog

:cl:
rscadd: Borer Control Panel installed to help admins control the flow of borers.
tweak: Changeling Panacea now ejects borers out of your body.
tweak: Shadowpeople are resistant to borer infections.
fix: Borers on-leave now properly delete the borer HUD from their victims.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
In the future, it could use a little more decoration.

**Comment by ShadowDeath6** [comment]
does black recuperation transformation remove borers

**Comment by Cruix** [comment]
:+1: very nice

**Comment by ShadowDeath6** [comment]
also why does this check for dead borers inside humans

**Comment by Super3222** [comment]
So admins don't have to dive into variables to help people with borers stuck in their heads. If borers pop out of their hosts brains when the borer dies, than I'll remove it because at that point it'd be useless.

**Comment by ShadowDeath6** [comment]
I don't think borers can die inside people

**Comment by Super3222** [comment]
Alright, give me a sec.

**Pull request merged**
