### PR TITLE
Removes useless items from the necropolis chests

### PR DESCRIPTION
**Pull request by Super3222**
#### Intent of your Pull Request

I was wrong about the alien brain being useful, so I'm removing it. However I have improved the overall reward of it in a PR that I'm pushing, but that is going to come out in a looong while.
Likewise, the freedom suit is being removed, despite having the best joke ever created in this codebase.
The talking scythe reward spawns with a flask holding 15u of godblood (lore omnizine, slightly buffed OD). Because I don't want miners being stuck with a stupid 18 damage melee weapon when they have a 40 damage ranged gun in the other.

##### Changelog

:cl:
rscdel: Stupid items like the freedom suit and alien brain are removed from necropolis chests
rscadd: 15u of godblood spawn with the talking scythe.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
It's not a joke

**Comment by ghost** [comment]
I WAS THE ONE WHO MADE THE JOKE I'm HAPPY

**Comment by ShadowDeath6** [comment]
Godblood is bad considering that you can already roll infinite bicaridine bottle

**Comment by Super3222** [comment]
Godblood heals all forms of damage, Shadow. Just like omnizine.

**Comment by ShadowDeath6** [comment]
So you get 15u of of and then you run out of it forever. Imo it doesn't seem like theckind of thing miners would like unless it would heal massively. Could be cool if it healed a ton, like 10 damage per tick, but ODed at like 5u

**Comment by Super3222** [comment]
That sounds interesting! I'll try to make it do that, and than give the miners a little "warning" in the description.

**Comment by Zostroll** [comment]
Isn't the alien brain good for r&d bio levels?

**Comment by ShadowDeath6** [comment]
nobody ever uses it and you can get better bio levels by sticking a deathnettle in

**Pull request merged**
