### PR TITLE
FUCK ROMAN SHIELD

### PR DESCRIPTION
**Pull request by enailz**
why shadow had council rank

### CODE REVIEW

**Comment by enailz** [comment]
what the fuck is Travis CI
fuck off

**Comment by Cruix** [comment]
The config only works for localhost, the real ranks are in the database.

**Comment by enailz** [comment]
oh
FUCK

**Comment by ShadowDeath6** [comment]
It doesn't actually do anything, I accidentally committed that and couldn't revert it because my master branch had fucked up

Coincedentally it also makes me not have to change my rank on my local test server so

**Comment by Time-Green** [comment]
You don't remove memes dammit!

**Comment by ShadowDeath6** [comment]
why did you :tada: your own post you fuk

**Comment by Cruix** [comment]
Now you don't need that, because localhost automatically gets full privileges.

**Comment by enailz** [comment]
succ baby is a meme!

**Comment by Cruix** [comment]
Please make your commit messages make sense for future generations who have to look through commit history.

**Comment by ShadowDeath6** [comment]
Idk I think that's a pretty valid commit name

**Comment by ShadowDeath6** [comment]
@Cruix dream daemon makes my computer choppy, ctrl+r runs faster but doesn't give host

**Pull request merged**
