### PR TITLE
Fixes cult walls of all kinds

### PR DESCRIPTION
**Pull request by MacHac**
This PR tweaks the functionality of both blood and clockwork cult walls, because constructs spamming unremovable walls was getting annoying.
# NEW (and old) SHIT:
### Blood Cult

Blood Cult walls can now be removed with a standard welder.  Cultists do this twice as fast as a normal wall.  Girders can be sliced apart with a welder to drop runed metal.  As usual, cult walls can be hit with a tome to make them see-through and walk-through.
### Clock Cult

Clock Cult walls can be removed with a standard welder.  Clock cultists do this in half the time of a regular metal wall.  Non cultists take twice as much time.  Clockwork cultist girders can be unsecured and moved around, or smashed until they yield alloy fragments to remove them.
## WHAT THIS MEANS

You can now get rid of cult walls without blowing them up.  Without this, culties can just have the artyfacers wall off their summoning position and kill toxins, and you're forced to welderbomb in.  Also, flavortext.

:cl:
tweak: Cultists now remove cult walls faster.
tweak: Clockwork cultists now remove clockwork cult walls faster.
tweak: Non-cultists now take noticeably longer removing clockwork cult walls.
bugfix: Cult walls of all types can now be destroyed by anyone with a welder, although effectiveness varies based on cult membership.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
This is an awful lot of copypasted code. Could you maybe have a proc in turf/closed/wall that takes the user and the tool and returns the time it takes to slice the wall apart, and another that gives the text for the visible_message, then only override those in the cult and clockwork versions?

**Comment by ShadowDeath6** [comment]
make sure turf/closed/cult/artificer walls or whatever they are don't drop metal so artificers can't mass produce metal

**Comment by Super3222** [comment]
> make sure turf/closed/cult/artificer walls or whatever they are don't drop metal so artificers can't mass produce metal

Artificer walls don't drop rune metal.
However, the feature you earlier made where Artificers could "corrupt" normal walls into cult walls isn't pathed for artificer walls. It's pathed for cult walls. Which in turn, can be broken down for cult metal.

Which is a bad idea... even if it's only popping out one or two rune walls. Mac'd need to add a few lines under `attack_animal` or something.

**Comment by Super3222** [comment]
@MacHac Seems like you've gone inactive. If you're still working on this PR, than please answer. Otherwise, I'll be closing this PR **very shortly.**

**Pull request closed without merging**
