### PR TITLE
Redoes centcomm

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Redoes centcomm, now consists of a terminal, a bathroom and a murderroom.
image

#### Changelog

:cl:  
rscadd: Nanotrasen has built a new space station, and moved Central Command to it.
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
IS THAT A GREENTEXT

**Comment by Amelia0010** [comment]
yes, it is

**Comment by Time-Green** [comment]
Thank god. Current centcom is blant, ugly and boring

**Comment by drderp3635** [comment]
Greentext after the round ends 2 op

**Comment by Partheo** [comment]
Please lock up the greentext somehow, I feel like it should be unattainable

**Comment by ghost** [comment]
why? the round ended so nobody cares anymore.

**Comment by Partheo** [comment]
It's sacred

**Comment by ShadowDeath6** [comment]
I like it, adminbus room and the statue. Does ERT spawn where it normally does?

**Comment by Amelia0010** [comment]
ERT is entirely unchanged

**Comment by Super3222** [comment]
You added the statue back. Bless 🙏

**Comment by ghost** [comment]
you made it look even worse lmao

**Comment by Super3222** [comment]
Ass

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Blast

**Comment by Amelia0010** [comment]
USSR

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
y tho

**Comment by Amelia0010** [comment]
Because I found another thing that would look better, but would be horrible in practice and take way too long to actually make.

**Review by AshCorr — APPROVED** [review]
The statue alone makes this PR worth it.

**Pull request merged**
