### PR TITLE
Refacter ragin' mages code

### PR DESCRIPTION
**Pull request by ThatLing**
Here I was, peacefully minding my own business when all of the sudden the game spawns me as a mage and forces me to actually play this game. I have created this PR after getting robusted 5 minutes into my adventures

This basically just cleans up the code. It also asks you if you want to be a ragin' mage now and disables malf ai because this gamemode is already chaotic enough.

:cl:  
tweak: The game will now ask you if you want to be a ragin' mage diplomat  
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
To be clear, this only disables malf AI in ragin mages, not in regular wizard gamemode?

**Comment by ThatLing** [comment]
Yes, this only disables for ragin' mages.

**Comment by Kmc2000** [comment]
bad Pr, nerfs administration because now we have to feel guilty after hitting YES and leaving a newmin on alone Xd

**Comment by Amelia0010** [comment]
>bad Pr, nerfs administration because now we have to feel guilty after hitting YES and leaving a newmin on alone Xd

Admins didn't get ragin mage before :^)

**Comment by AsV9** [comment]
@nichlas0010 you do if you de-admin before every roll :^))))))))

**Comment by Amelia0010** [comment]
Yep, I once left halu to handle tickets as the captain while I waited for magin 👌

**Pull request closed without merging**
