### PR TITLE
Removes chameleon kit from DA

### PR DESCRIPTION
**Pull request by ShadowDeath6**
> being able to infinitely change your appearance as well as name for 6 TC during a round where you have to kill one person 

Call it salty all you want but I've seen multiple DAs spend entire rounds looking for their target and never finding them because they became random grayshirt mcgee 5 minutes into the round, and you very well can't randomly kill people on the off chance they're your target.

:cl: ShadowDeath6
rscdel: Removes the chameleon kit from Double Agents.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
I really hate how DA is EMAG PISTOL RUN TO YOUR TARGETS WORKPLACE AND MURDER THEM QUICK then hide in a locker the rest of the round for greentext.

**Comment by ShadowDeath6** [comment]
if people want further clarification on why this was necessary, in DA rounds at least one person would have their assassinate objective completely impossible to complete because one other agent would buy the chameleon kit and become completely impossible to pin down as they could look like any job, and with an agent card could look like any person.

**Comment by Ephemeralis** [comment]
There are holes in any chameleon disguise and it requires more than just waltzing around the station looking for people.

Start looking for duplicates of people, or active people wearing masks whose names are not on the manifest.

Let's not nerf strong mechanics when the counter to them is a bit of investigative work and general intelligence.

**Comment by ShadowDeath6** [comment]
You'd need to be supremely lucky to one- find out that your target has a chameleon kit, two- you actually find them and see their ID/name, three- you realize that specific person is wearing the cham kit so you confirm it with checking the manifest.

**Comment by Super3222** [comment]
Confirmed salt PR and unreasonable change. So :-1:

**Comment by ShadowDeath6** [comment]
> unreasonable

I think I've explained the reason enough. Provide a counterpoint and I'll change my position.

**Comment by Super3222** [comment]
Go with Eph's explanation. Use your head and stop relying on shift+click spamming. DA will always be a shit mode to me but, removing a game mechanic from the mode out of salt makes it any better. It just sounds like someone one-upped you.

To be honest you don't even need a chameleon suit to hide. I could get an RCD, find myself a 1x1 room in maint, wall myself in there, and click out of the tabs to do something else. Constantly switching back in until the shuttle is called and, then leave to a pod to get my greentext.

If you can't find your target then you're either doing something or wrong or they're doing something right.

Do you not realize that I could do the same thing with an agent ID card and traitor gas mask about 3-4 months ago? It's only a problem now because they're getting a full set of clothes, isn't it?

**Comment by Super3222** [comment]
Go with Eph's explanation. Use your head and stop relying on shift+click spamming. DA will always be a shit mode to me but, removing a game mechanic from the mode out of salt doesn't make it any better. It just sounds like someone one-upped you.

To be honest a DA don't even need a chameleon suit to hide. They could get an RCD, find themself a 1x1 room in maint, wall themself in there, and click out of the tabs to do something else. Constantly switch back until the shuttle is called and, then leave to a pod to get their greentext.

If you can't find your target then you're either doing something or wrong or they're doing something right.

Do you not realize that people could do the same thing with an agent ID card and traitor gas mask about 3-4 months ago? It's only a problem now because they're getting a full set of clothes, isn't it?

**Comment by ShadowDeath6** [comment]
Yes, it is, because it requires absolutely no effort, where before if you managed to get a full department's clothes and blended in you couldn't change it whenever you wanted, you actually needed to get the access and get the clothes, which put you in danger of being found out. It's like having a ling as your target except the ling has the identity of every real and fake person that's ever existed in the game.

**Comment by Super3222** [comment]
*cough go up to people with an emp flashlight and blink them.
If you don't want them changing their clothes instantly, than try creating a cooldown for the weapons.
This type of thinking is what gives into the  `REMOVE, DON'T IMPROVE` ©️ meme.

And no, you never needed to get access. All you needed was to either kill someone for their clothes (which was allowed) or hack in yourself.

If you're in the situation where you can't tell who's real and who's fake, than start narrowing down your suspects and memorizing names. The game's not going to get magically easier for you just because someone was able to hide in plain sight with their own TC. That's stupid.

And if effort is your problem, than this entire PR is stupid. Because a part of the things you can buy with TC, you can easily find on the station. Buying it only gives you more powerful and easier to use tools/weapons. Poison Kit -> Anything good in chemistry, Guns -> Cargo, Bombs -> Literally fucking science or chemistry, Emag -> Toolbox and Multitool, No slip shoes -> galoshes, Syndicate Soap -> do i need to go on, Spacesuits -> ... Come on now

**Comment by ShadowDeath6** [comment]
cham items ignore EMP.

Next time you see/take part in a DA round, look at the end-round results. Someone will almost always have a chameleon kit, and the person with them as their target will not have greentexted, because it's impossible to keep track of an infinite array of names and compare it to a crew manifest every time you see someone. There is no tell for a chameleon kit. There is no way to FIND your target if they are using a 6 TC combination of items. You can be the most robust person in the game in DA, but you can't track down someone who changes their entire appearance and name any time they're put in a threatening situation.

Not to mention that you have no idea what the person has bought. You can't tell if the person is alive or dead, you can't tell if they've welded themselves into a wall for the entirety of the round, and you certainly can't tell if they're a random atmos tech lurking around in maint.

**Comment by Super3222** [comment]
> cham items ignore EMP.

ok you found a reasonable counter. :+1:

> you can't track down someone who changes their entire appearance and name any time

cooldown

edit: and make it obvious to the people around you when you switch from one appearance to another with cham objects

> Not to mention that you have no idea what the person has bought. You can't tell if the person is alive or dead, you can't tell if they've welded themselves into a wall for the entirety of the round, and you certainly can't tell if they're a random atmos tech lurking around in maint.

So basically everything that a player can experience after playing 1-2 DA rounds?

**Comment by ShadowDeath6** [comment]
cooldown isn't going to change anything unless it's a 10 minute cooldown.

Not to mention "kill someone / hack in" will still draw suspicion onto you, cham kit will give it to you with no obvious tells whatsoever.

**Comment by Super3222** [comment]
No shit it draws suspicion to you. The uplink exists so that suspicion gets drawn away and the outcome seems more random & unpredictable. No one can draw clues from an unknown in a syndicate hardsuit out in space. But they CAN draw clues seeing the unknown in the atmospherics hardsuit.

Balance out cham gear or don't touch it at all.

Edit: Hence why a smart Detective is the greatest counter to a sneaky traitor.

**Comment by ShadowDeath6** [comment]
It's just a bad idea, and advocates lazyness. Just like the shit tier mulligan implant in the traitor uplink.

If you want to spam swap disguises on a round where knowing who your target is is the core focus, then spend the time gathering multiple disguises, no "vanish at roundstart" bullshit.

**Comment by Super3222** [comment]
> comparing chameleon box to mulligan

Come up with a better analogy or direct me towards where I can get the /SAME EXACT FEATURE/ which does the /SAME EXACT THING/ and I'll retract my statement. And I don't go 'oh super you can just go to the locker room'. No, I mean clothes that can switch into other clothes (even ones not on the station / might be destroyed) in an instant because that's the prowess of the item. My entire ordeal with mulligans and SE injectors is that there's no special ability to them at all which makes them any different from their conceivable pair, making them a bland and boring thing to use. Obviously, you have no understanding of that.

And once again, because the points going over your head I'll have to repeat myself. People could literally do the same thing a few months ago. Just because there's a box full of it, you're shitting all over it being used strategically in DA. Not everyone buys a chameleon box. I've already given you enough solutions to try to counter chameleon clothing for the good of DA, but if you're ulterior motive is to only see it gone than I doubt this PR is going to be merged. Removing content that could easily be rebalanced is a toxic way to move forward and, I'm growing sick and tired of letting it fly by. If it was an actual item that we couldn't figure out how to nerf than I'd understand but, it's not. In fact, you're quite literally ignoring every chance to keep it within DA. I think you're honestly over exaggerating, antags shouldn't be cuddled like this, they should be challenged. You weren't in any situation like that to begin with. Eph's right in the sense that it just takes a bit of investigation work to find someone. You can easily narrow down your target by their position.

Hell, you're lucky enough to have them running around in a cham suit. They'd be better off somewhere random in a locker.

Because it makes perfect sense to remove the one thing that lets you hide in plain sight from the mode which you actually need to do some hiding in.

**Comment by ShadowDeath6** [comment]
The chameleon kit was designed for traitor, as the people you're hiding from is sec, and by some extension, the AI. They've all got roundstart access to the crew manifest, nonlethal, inconspicuous weaponry and reason to search people who look suspicious.

Traitors don't get that kind of access without stretching themselves. Imagine that you're DA, and at the beginning of the round, the clown, your target, used a chameleon kit. Keep in mind that you don't know what the clown's bought, and he never appears again because he looks like a medical doctor and you don't know what he looked like before he became a doctor. He silently kills his target because he could actually identify and kill them, and then escapes on the shuttle after hiding in escape lockers for the majority of the round. Even if you came across him, you didn't have time to cross-reference him to the crew manifest, or didn't think about it at the time, because you were busy looking for him or busy avoiding your target. No amount of vulnerability is going to change that, because people are immediately going to yell traitor when you try to look for the person, and then you get fucked.

Rebalancing it to fit DA would severely gimp its effectiveness in its intended round, which is traitor.

**Comment by Super3222** [comment]
There are holes in that entire statement.

Choosing to buy a cham kit.
And then hiding in a fucking locker? For the majority of the round? For what? That kit is made to be able to infiltrate areas and blend in with crowds.

I could do the same thing without a cham kit and without changing my clothes, and I probably have. Which is why I've always been saying DA is shit.

Like Ive been saying, investigate. Narrow down suspects, look at the people who are out of place, it'll be real easy. I shouldn't have to type up an entire guide on doing it. Play Detective as a DA and get it done.

And whoever said that you don't need to hide from sec or the AI in DA can, using Adams words, choke on a dick and die.

**Comment by ShadowDeath6** [comment]
> narrow down suspects

How? How would you find any suspects in a round where someone with a chameleon suit can be anyone, or any job, or any made up thing? Maybe the problem is DA, but it's guaranteed redtext for the assassin.

**Comment by Ephemeralis** [comment]
There's a few holes in constant chameleon disguise shifting:
1. Total ID concealment requires a mask to be worn at all times, be it any face hiding mask or a voice changer. If there's no reason for a person to be wearing a mask so early on in a round, they're probably highly likely to be one of your targets.
2. Medical records contain images of your targets at roundstart. Hair colour can't be changed in-round outside of genetic alteration (as far as I know), so you can isolate your targets down by checking things against their hair colour, or lack of hair colour.
3. Attempts at altering hair colour will leave a trail either through access to genetics or requests made to people manning genetics.
4. Agent card users speaking over standard radio are immediately noticeable to any station AI with appropriately loaded telecomms scripts.

The issues you're raising in here are more issues with DA as a gamemode rather than chameleon being responsible for them. Of all the traitor items and paradigms, the disguise gear in general is probably the best thought out and most interesting over all the umpteen dozen ways of killing people that you can get out of an uplink.

If you want to make code changes, make EMP disable or scramble the current disguise of chameleon clothing. I swear that was actual functionality at one point.

**Comment by ghost** [comment]
@Ephemeralis 

The chameleon kit includes a chameleon gas mask with voice changer capability.

You can disguise it as something completely invisible or ordinary-such as say, a cigarette-and have your face counted as 'concealed' because it's a chameleon gasmask, and thus have voice changer activated.

This allows you to run around naked with an agent ID and a voice changing cig/eye of god/distorted mouth or whatever you disguise as and be completely undetectable.

Altering hair color is easily done with a mirror, or using the mulligan traitor item, or even just spritzing yourself with shit you can find on the station.

Medical records can be altered with ease.

Chameleon kit also has the hat, which allows you to disguise as, yes, any bit of headwear, meaning you can conceal your head with ease with something unsuspicious like a black cap or EMT hat or even completely fake out and look like you're wearing a hardsuit altogether.

@Super3222 You can't narrow down suspects. They can look like anyone, anywhere, at any time, or make up completely imaginary identities. Unless you're willing to start murderboning (and get banned) you won't find your target if he disguises as a non-existent medical doctor in medbay, and it'd take far, far too long for people to realize in succession-

A. Their target is disguised and not just fucking around somewhere
B. Where their target is 
C. Who their target is disguised as

Because after they complete their objectives they can look like a completely unsuspicious med doctor and do normal med doctor duties for the rest of the round and not get killed or suspected by anything suspicious whatsoever because _there's no way to draw attention to yourself._

DA is a cancer gamemode for numerous reasons-But the chameleon kit deserves to be disabled in DA for the same reason the detomatrix cartridge is disabled-for the sake of logic and sanity (so you don't blow up your target's PDA at roundstart). 

There's no reason whatsoever to have it as a possibility in DA simply because agent card + cham kit lets you disguise at will as anything you want and be completely undetectable, and you can't go around killing random people that look nothing like your target because 'i thought he looked suspicious and might have been my target in disguise.'

Chameleon kit is completely overpowered for DA and doesn't fit at all. Super, you've provided no points whatsoever as to why it should be a possible item.

Let's go over the facts again.

A. You can look like anyone, at any time, and thus be 100% free of suspicion. Nobody can find you out.
B. You're free from the risk of being killed because 'I thought he was suspicious and is thus my target in disguise.' because that's considered murderbone if you go around killing mildly suspicious people. And if you're NOT, then that's just a shitty excuse to murderbone, and ALSO needs to be removed.
C. Nobody is likely to assume a random med doctor walking around in maint is their target disguised as a med doctor. If they're even in maint-after they complete their objective they're liable to just fuck around in medbay or something.
D. All of eph's points are incorrect and based on false information which was disproven above.
E. The chameleon kit is perfect as is and does not deserve to be touched since it works perfectly as intended in normal traitor. But it's not fair for DA. Read below to understand why.
F.You CANNOT narrow down your target by their position or detective work. What part of 'they can look like any job and thus can be anywhere without suspicion' is not understood here? They can look like an ordinary greyshirt assistant and wander the halls. They can look like a chef and fuck around in the kitchen, or in botany. They can look like the chaplain, or a roboticist, or a paramedic, or a geneticist, or an engineer, a cargo tech-anything. If they want to go in somewhere, they just swap their disguise.
G. Modifying the chameleon kit makes it bad for normal traitor-assume you did something drastic like make it only able to change once. Then it's shit altogether. IT's fine altogether as an item for traitor, but not for DA. 
H. A cooldown wouldn't work either. There's no instance where you'll be swapping clothes THAT FAST. You generally only need to change once or twice in the whole round unless you're running a gimmick.
I. They can add their own security record and med record, so don't even try that. (Like anyone would actually start checking the database for a random cargo tech hanging around in the front of cargo. That's time consuming and hard to do-IE a waste of time.)
J. It IS only a problem now that they're getting a full set of clothes because you can't even use a forensic scanner to check for prints on missing clothes or people with gasmasks anymore. They can look like anyone at will and have completely unsuspicious gear like sterile masks on an EMT.

@Ephemeralis I'd like to stress, AGAIN, that there's no 'duplicates of people' or  'active people in masks.' You can't kill someone wearing a mask just in case, not to mention they don't even have to look like they're wearing a mask-they could just be smoking a cig or wearing a breath mask since it's a chameleon voice changer. And no, tcomms scripts won't figure out voice changer agent ID anymore.

**Comment by ghost** [comment]
So yes, the above completely negates all points made prior, especially those by eph.

Merge this.

**Comment by Cruix** [comment]
For the record, the chameleon clothes do respect the cover flags of the item they are disguised as, so you could not hide your face with a chameleon cigarette.

**Comment by Super3222** [comment]
I'd respond to Adam's post but, I don't have the time. You, @ShadowDeath6 and @AdamElTablawy are really looking too deep into the chameleon kit. You're trying to figure out what must happen 100% of the time and how undeniable it is. (almost) Nothing happens 100% of the time in SS13. That's all I can say for now. Neither of you have even been in the situation to begin with, I'll start with that.

**Comment by ShadowDeath6** [comment]
They don't, @Cruix, at least in the case I've used the exosuit disguised as a hardsuit, as it showed all items under the hardsuit, like glasses, mask, and jumpsuit.

**Comment by Cruix** [comment]
Dammit goof

**Comment by Ephemeralis** [comment]
I vehemently oppose this being merged as is. If you're going to "fix" these items, then do so by giving them vulnerabilities rather than outright removing them from an entire gamemode. Either you fix it for DA, or you fix the item in general. You don't just remove shit.

I'm serious. I'd rather we added in-game accessible logs to medical record altering to leave trails for people to follow, innate EMP weaknesses to chameleon gear, or a limited number of charges to change outfits/skin for chameleon equipment over. Basically anything is better than taking the hail mary **WELL FUCK BOYS IT WORKS TOO WELL LIKE THIS LETS FUKKEN DELETE IT** approach.

**Comment by ShadowDeath6** [comment]
Nerfing it won't help, because it's balanced to be used in traitor mode, and making an entirely new subtype for DA takes far too much effort for balance memes. Cham kit is not fit for DA.

**Comment by ghost** [comment]
# R E M O V E

# D O N ' T

# I M P R O V E

**Comment by Super3222** [comment]
⏰

**Comment by ShadowDeath6** [comment]
I'm not going to nerf this item because it'll be shit when used in traitor. 
It's the exact reason that the maxcap syndiebomb was removed, it was intended for traitor and was too stupidly powerful / unfit for DA. 
Adam restated my points very well, I have nothing more to add.

Also, before you continue pushing the autistic "LE REMOVAL DON'T IMPROVAL" meme, this is not removing the item in any way. I'm removing its use in a mode where it has no balanced place in being. This in itself is an improvement to the mode.

**Comment by ghost** [comment]
Remove don't improve is literally saying trying to improve it would be a waste of time and effort so removing it is good

**Comment by Super3222** [comment]
Going over a lot of the points made on this PR, admittedly I can say that I was wrong about a few things. In fact, going over some of my earlier posts makes me cringe.

It would be painstakingly hard to find your target utilizing a chameleon kit in DA, but what I was looking at was the demanding effort that traitors had to put in during DA.

I'm use to the terrible anxiety rush of crunching in time to find wherever the hell my target is but, when they have a chameleon kit on it's nearly fucking impossible unless they're using it wrong.

My main point was that finding out whether someones imaginary or not is not hard at all. You have an entire PDA that can help you find that and manifests which can be printed out. Not to mention the lawyer's drawer that gets filled up with papers of everyone on the station. When it comes to more than one person, it's hard.

Second point was that if the chameleon kit was impossibly hard to counter than, it would have never been merged in the first place by /tg/. Given that it doesn't take a foresnic scanner to discover someone w/ a chameleon kit on than, I didn't expect a DA agent to have any trouble either. But DA's are not security and they don't have the authority to search someone.

My third point was quiet literally everything that Adam pointed out was exaggerated. You account for a lot of things that a traitor "might" do that gives them leverage. What's not put into factor is how the kits going to be actually used in the game. But like I already pointed out, it'd be too hard to figure out where or even who your target will be.

And remove, don't improve is exactly what you're doing. It's not always bad but, it's quite literally a meme on Yogs now like I pointed out. If you look at the last few pages of PR's, we've taken out a lot of things aside from improving them. So yes, for instances like balance via, this PR, it's necessary. But there are some cases which actually need to be reversed and our efforts should come towards fixing things, not destroying them.

I see what you're trying to do Eph but, Shadow has a point. The item was never intended for traitor v traitor so it's better off not within the mode.

**Comment by ShadowDeath6** [comment]
As much as I'd like to rework the item to fit the mode, the problem is that it's balanced toward traitor. 

If we make it so that non-sec can see through disguises more easily, so DAs can find their targets, it would make validhunting civs during REGULAR traitor even more likely to go after people using the cham kit as a stealth item.

**Pull request merged**
