### PR TITLE
Toy mechs

### PR DESCRIPTION
**Pull request by Cruix**
#### Changelog

:cl:
fix: Toy mechs no longer hide under the hand icon when you reset them
fix: The toy mech controller menu no longer pops up in your face after you have closed it.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
hink mech can't actually damage other mechs, is this intendo?

**Comment by Cruix** [comment]
Honk, firefighter, and Odysseus can't do damage because they have other, real-world uses.

**Comment by ShadowDeath6** [comment]
what does the honk do then

**Comment by Cruix** [comment]
It honks

**Pull request merged**
