### PR TITLE
Clash of clowns: Mobile Port

### PR DESCRIPTION
**Pull request by Kmc2000**
Clash of clowns! everyone's favourite game has now been ported onto a game child, which is found in the clerk's office, if at any time you think you're shit and need some """""help""""" you can insert any kind of mineral (Including wood) into the slot in this satanic machine to give you a leg up.

"That's not a slot for games, that's a slot for your valuables."

In the spirit of:

https://github.com/yogstation13/yogstation/pull/620
### Pictures

BEFORE:

AFTER!

Now with emag functions, as CLEARLY requested by @ShadowDeath6 

Notes:

You do have to click it every time you do an action, that's a thing i can't really fix
#### Changelog

:cl:
rscadd: Satan: Ports your favourite game onto a micropurchase laden gaming console, god help you all
/:cl:

### CODE REVIEW

**Comment by george99g** [comment]
screenshot from 2016-09-06 18 29 53

**Sqash
your
fucking
commits
for
flying
fuck's
sake.**

**Comment by X-TheDark** [comment]
Ladies and gentlemen. **This** is how you suck the life out of a very clever joke PR...

But no, seriously. Your repo needs fixing. Please don't code until you do so.

**Comment by Alek2ander** [comment]
Game-changing meta shift :point_left: :point_right: Shitty arcade game

**Comment by Kmc2000** [comment]
Alek

You fail to see the point

_the whole idea behind these phone games is that they all rip each other off completely@

**Comment by Super3222** [comment]
Let it pass but, without the gibbing part. Maybe make it drain your life like the lottery of greed, inflicting brain however instead if it's emagged.

It's a fun little game and, perfect for the clerk. Could you include 3 inside of the gift vendor? Code could use some sprucing, like removing `src.` when it's not necessary. Unless it's in `[src]` or you're using it for a proc, you don't need to apply it.

**Comment by Kmc2000** [comment]
Well it gibs because the arcade one gibs,  but alright

If people seriously want this as a non joke thing i'll add interchamgeable games cartridges

**Comment by Super3222** [comment]
Considering Cruix's toy mech PR, I'd suggest making these shit out a variety of different mechs.
((Also still putting 3 of these inside of the clerks gift vendor))
@Kmc2000 Trouble with merge conflicts?

**Comment by Super3222** [comment]
@Kmc2000 Are you going to fix the merge conflicts within this PR, or do you need help with that?

**Comment by Kmc2000** [comment]
Uhh people.universally hated it so its a bust

**Pull request closed without merging**
