### PR TITLE
Ion law fix

### PR DESCRIPTION
**Pull request by SKR6DarkVoid**
Title States it all.

:cl: 
bugfix: Fixes Ion Laws!  We can now enjoy the humorous laws! 
/:cl:

..
....

`purge the ai...`
#547

### CODE REVIEW

**Comment by george99g** [comment]
Uhh.

Why are you doing all of this?

**Comment by george99g** [comment]
I mean, the define is there and it seems to work right. Why are you stripping it out and hardcoding a string in?

Does this code even compile?

**Comment by SKR6DarkVoid** [comment]
Yes

**Comment by SKR6DarkVoid** [comment]
The string was not properly defined, so it would only show half of the law.

**Comment by george99g** [comment]
You've literally broken a define and hardcoded the same string in.

**Comment by SKR6DarkVoid** [comment]
Well, Ill close this, I mean it worked on my private server so. Ill find another way around it then.

**Pull request closed without merging**
