### PR TITLE
Implements a new traitor objective, stealing the outdated plasma tank!

### PR DESCRIPTION
**Pull request by Super3222**
### Intent of your Pull Request

Adds a new traitor objective for fun, as well as a new display case in the bridge.
Also uses a, presumably old, icon that I dug up from the pit of the never-used.

#### Changelog

:cl:
rscadd: An antique has been shipped off to Space Station 13 and placed in the Heads Meeting Room
rscadd: The Syndicate off the bat are interested in stealing the new antique.
/:cl:

Old Places:

New Place:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
that is not a good spot for a movement-restricting display case, please put it literally anywhere else

**Comment by Super3222** [comment]
I see what you mean, and I have another spot in mind. literally right in front of the ai core because you said "literally anywhere else"

**Comment by Zostroll** [comment]
You shouldn't put something that block's your movement in the middle of the bridge. Why not have it next to the caps gun or in the staff meeting room next to the vender's?

**Comment by ShadowDeath6** [comment]
fix your changelog maen

> rscadd: A new antique to Space Station 13 and installed it square-flat inside of the _bridge_. Be careful, ruthless syndicate _spies_ may attempt to steal it only to mock Nanotrasen.

**Comment by Time-Green** [comment]
Actually, I like the spot.

**Comment by Alek2ander** [comment]
The location sucks. Bridge is a common place for firefights, having more stuff blocking the way is a bad idea.

Put it in cargo, maybe, somewhere in view of the security office? Science and engineering both have enough steal objectives already.

**Comment by Super3222** [comment]
In the last commit:
- Moved the display case to the RD's room.

**Comment by Super3222** [comment]
In the last (few) commit(s):
- Moved the display case to the RD's room.
- Removed the display case from the bridge.

**Comment by killerx09** [comment]
This is good.

**Comment by Alek2ander** [comment]
That's 2 steal items in RD's office. Seems a bit much.

**Comment by Time-Green** [comment]
Give it to the HoP, that guy has nothing to be stolen!

**Comment by Super3222** [comment]
I was considering the HoP's room but, there's not a lot of space...

Edit: I could put it in toxins and, restrict the objective from all science roles w/ a security system. Any objections?

**Comment by ShadowDeath6** [comment]
fuck your changelog nerd

**Comment by Groudonmaster** [comment]
Why not put it in the library? It's a piece of history isn't it?

**Comment by Alek2ander** [comment]
Put it in cargo. Literally the only department without unique stealables and you're ignoring it.

**Comment by Super3222** [comment]
Where exactly in cargo should it be where people can see it and the average greytider can't rush in and break it open?

**Comment by Alek2ander** [comment]
QM office. Let average greytiders steal it, so sec can fukken murder them for grand theft.

**Comment by Time-Green** [comment]
Inb4 it gets directly sold

**Comment by ShadowDeath6** [comment]
make sure it doesn't cost anything and can't be sold so QM doesn't fuck with traitors

**Comment by Super3222** [comment]
I'm bringing this back & moving it to the head's meeting room.

**Comment by Dagdammit** [comment]
Stealable item in head's meeting room is a good idea.

**Comment by Mrcreepssss** [comment]
i agree, it put's some purpose to it, besides a filler room.

**Pull request merged**
