### PR TITLE
Toilet improvement

### PR DESCRIPTION
**Pull request by Time-Green**
Toilets used to open a disposal bin UI, now the toilet just peacefully flushes like a good ol' toilet.
:cl:
tweak: NT has removed their advanced toiletitating intarface in favor of <strike>money</strike> peace.
Thanks to @simonset55 for sounds
/:cl:
For testing: Dont. Trust me, it's as tested as it could be and works completely fine

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
add a water rushing sound

**Comment by Time-Green** [comment]
I feared someone would say that. And honestly I have no idea how I do that. I'll try

**Comment by Time-Green** [comment]
Ugh, they're all a minute long and in the wrong format. If someone could pass me an ogg of a nice short flushing sound, that'd be great

**Comment by Tummywumbes** [comment]
does this mean we cant hide in toilets anymore?

**Comment by Time-Green** [comment]
You still can hide in toilets. Just not turn off flushing and hide there indefinitely

**Pull request merged**
