### PR TITLE
Gives clock prolyterelizer research levels.

### PR DESCRIPTION
**Pull request by ghost**
# ephermalis doesn't know how to ask for things and not close prs
#### Changelog

:cl:
rscadd: The clockwork prolyterelizer now has research levels.
/:cl:

### CODE REVIEW

**Comment by Zostroll** [comment]
What this PR name is wrong aren't you changing medbay to more like baymed?

**Comment by Ephemeralis** [comment]
Fix the changelog.

**Comment by X-TheDark** [comment]
Fixed.

**Comment by Zostroll** [comment]
Adam I can't seem to find any designs that use the arcane tech tree. Are there any?

**Comment by Super3222** [comment]
There is an arcane tech tree in research.dm

**Comment by Zostroll** [comment]
I understand there is a arcane tech tree I just couldn't find any design's that used it and I was wondering if there were any.

**Comment by Super3222** [comment]
No, there isn't.

**Comment by ghost** [comment]
none atm

**Comment by Cruix** [comment]
Are scientist cultists just going to make tons of these to max out magnet research?

**Comment by ghost** [comment]
if there is a clock cult in fucking science you have more to worry about than goddamn fridge magnets

**Comment by ShadowDeath6** [comment]
mag 7 is way too good for an item that can be spammed with 2 rep alloy

**Comment by ghost** [comment]
it's clock cult either they have infinite components and will produce a shitton of anything regardless of component cost or have zero components and will die within minutes

also if there's a clock cult in science you have more to worry about than goddamn fridge magnets

**Comment by Super3222** [comment]
Mags is absurdly high, and considering that there's nothing you can really get out of going beyond 5-6 it's pointless. When the time comes, and more powerful things(if ever) are added to R&D, than I'd advise them to decrease these levels to 4 or 5.

Spawning an infinite amount of tools that'll grant you high research levels is just bad in my opinion.

**Comment by ghost** [comment]
You are a fickig clock cult if you are in science you can jsut shove your dick into the deconner for bio 5 and get a little gold and shit out infinite seas of cult borgs via posibrains 

Mag 7 wont do anything at that point and if you can actually take down a competent clock cultist (which they are if they have a prolyterelizer) you deserve ufking emp 4000

**Comment by Super3222** [comment]
I'm well aware that being a scientist servant will help out greatly. That's just an aspect of the game.

But even at that moment, we can't throw around freebies and say, "Yeah, well you would've already been there by now anyway". 

The Ion Carbine only needs 4 magnets anyway.

**Pull request closed without merging**
