### PR TITLE
gives juggernauts the ability to phase again

### PR DESCRIPTION
**Pull request by ShadowDeath6**
https://github.com/yogstation13/yogstation/commit/f690fee11621cd6ae3d327eb4ec459a67e1e672f
@Cruix 
removed without pr or discussion as far as I can tell
????????? why

:cl:
bugfix: Juggernauts once again have the ability to phase through walls.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
and before we go down the shithole of "balancing", both juggernauts being able to phase through walls and wraiths being able to dismember were removed without pr.

Regardless of what people think about it, this pr was already merged in https://github.com/yogstation13/yogstation/pull/1927 and then removed without github discussion(unless I'm missing something), which is really shitty and abusive.

edit: https://github.com/yogstation13/yogstation/pull/2338 it was removed in this along with a bunch of other unnamed changes

**Comment by Slinky5890** [comment]
Na it needs phase jaunt

**Comment by Partheo** [comment]
touch

**Comment by Cruix** [comment]
As I explained to you in discord, #1927 was merged and altered as part two large PRs by me in #2333 and #2338 that were done to merge a large number of PRs at once while fixing merge conflicts and unresolved issues. The ability for juggernauts to phase through walls has never been live on the server. I still argue that this is a bad change to for an already horribly overpowered antagonist.

It is regrettable that your PR being merged made you think that all your changes had been added unaltered, and that I did not update the changelog in the PR to reflect my changes, and I am sorry. At the time, I was very busy and tired of waiting for people to fix their PRs, and I used the opportunity to add your changes to the mix and "fix" them. Fortunately, this will probably never happen again, because I am no longer willing to take the time to resolve other peoples merge conflicts for them.

**Comment by ShadowDeath6** [comment]
I was never informed on discord, though, and by checking the history when I first made this pr I found out that you had changed it. It's horrible form as the person who maintains the code to not comment on the balance of prs and just not merge it rather than fooling the playerbase into thinking that a change went live and giving no comment on github outside of a single commit in a pr called "stuff" that you merged the same day you opened it.

**Comment by ShadowDeath6** [comment]
it isn't up to you to "fix" fully functioning balance changes, it's up to the coder to either close the pr or accept criticism. 

I also don't accept https://github.com/yogstation13/yogstation/pull/1927#issuecomment-284284420
as criticism, because you merged the pr regardless. Being busy isn't an excuse to remove other coders' changes, it's just as easy to not click the merge button as it is to click it.

**Comment by Cruix** [comment]
I told you about this on discord one week ago, after which you added
>edit: #2338 it was removed in this along with a bunch of other unnamed changes

to your previous post.

I do not think you understand how this works. I did not rub my hands together, twirl my moustache, and say "Aha! I will just merge shadowdeath's change and then remove half of it, he will be none the wiser!". Although this may shock you, I am not a criminal mastermind with a personal vendetta against you, I am quite literally a guy who walked in off the street one day and decided to start coding in BYOND. I make mistakes quite regularly, particularly because there is no one willing to check over my work, despite my constant requests to the contrary. It is not a stretch to believe that in the process of resolving merge conflicts between ten different PRs, I forgot about a one line change.

As I stated above, I was in a hurry to get things merged. Because you had two separate balance changes in a single PR, I had two options. I could pull from your branch and edit it myself, resulting in Github marking your PR as merged, or I could copy and pasted the changes and commit them myself. I chose the former option, because you would retain the credit for your work in the repository's commit history. I never clicked the merge button on your PR. If you do not want this to happen, then make sure your changes are all atomized.

It is, in fact, up to me to "fix" everything that goes on the repository, balance changes or otherwise. If you have a problem with this, start working harder than I do, and get Xantam to promote you to Headcoder and change things yourself. Making personal attacks against me will not change anything.

**Comment by ShadowDeath6** [comment]
I added that edit because I found out how to reverse search prs by their commits, I didn't hear anything from you.

I don't think you have a personal vendetta against me, but it's very easy to just say "atomize your prs" and I would change it.

**Pull request merged**
