### PR TITLE
Makes asteroid mining as an alternative to lavaland

### PR DESCRIPTION
**Pull request by AsV9**
Not fucking finished yet. 

- [x] Set up a separate mining shuttle that goes to the asteroid.
- [x] Fix shuttle animating the wrong direction. :rage: :rage:
- [x] Map the asteroid station in a way that actually makes it usable at round start.
- [x] Add screenshots to pull request.
- [ ] Make the new mining dock look not revolting.
- [ ] Maybe add some ruins or ghost roles. I have some ideas, but I'd love to hear more (once I get so far).
- [ ] Test and fix inevitable bugs.

New mining dock, not quite finished yet.
image

New asteroid bus:
image

The new lavaland shuttle has been made slightly smaller, just to feel a bit more cramped. It's a lander, after all.
image

The new asteroid mining station:
image

Laborcamp is still as abandoned as always:
image

### CODE REVIEW

**Comment by drderp3635** [comment]
if you go through with this you should be sure to set the mining hardsuits on the asteroid base to EVA suits if you haven't already to stop miners from just flying to the asteroid base, stealing the suit, then going back to lavaland.

**Comment by Time-Green** [comment]
Make the suits just gib you if you use them on lavaland, something about ash getting in the circuits

**Comment by AsV9** [comment]
@Time-Green I was thinking EVA suits with the exact same armor stats as the default shaft miner kit gives you.
You /can/ after all buy a mining hardsuit for mining equipment points.

**Comment by Alexandria404** [comment]
Moon dust actually was an issue for spacesuits. Crawling into joints etc.
You could use that as an excuse to make them fail on lavaland, something about ashstorms.

**Comment by Amelia0010** [comment]
Will the labourcamp shuttle have an option to choose where to go? Will there be two labourcamp shuttles? Will it be random?

**Comment by Amelia0010** [comment]
image
please put stripey turfs here too thanks

**Comment by Time-Green** [comment]
@nichlas0010 
>Laborcamp is still as abandoned as always:

**Comment by Amelia0010** [comment]
>Laborcamp is still as abandoned as always:

Yet it has a shuttle dock 🤔

**Comment by AsV9** [comment]
maybe a rainy day

**Pull request closed without merging**
