### PR TITLE
Ported tg virology

### PR DESCRIPTION
**Pull request by Cruix**
Ported:
https://github.com/tgstation/tgstation/commit/2279d1f89ec480b94fd4f40850485281066acd5c
https://github.com/tgstation/tgstation/pull/15993
https://github.com/tgstation/tgstation/pull/20843
https://github.com/tgstation/tgstation/pull/19693
https://github.com/tgstation/tgstation/pull/20547
https://github.com/tgstation/tgstation/pull/11989
https://github.com/tgstation/tgstation/pull/15396
https://github.com/tgstation/tgstation/pull/9836
https://github.com/tgstation/tgstation/pull/19983
https://github.com/tgstation/tgstation/pull/16136
https://github.com/tgstation/tgstation/pull/17835
And probably more that I forgot about

Requested by Adam
:cl:
rscadd: virology has been updated to tg's version. Probably.
/:cl:

### CODE REVIEW

**Comment by SirCodey** [comment]
no pls

**Comment by Jc1469** [comment]
> removed stimulant

wow. big nerf to something that's been broken for years. I feel like the crappy genetics update that was just merged needs upping if we're completely removing virology symptoms.  Genetics>Virology, always has been.

**Comment by ghost** [comment]
@jc1469 

WRONG

it's completely possible-or WAS, up until just now-to make a triple-stacked healing virus that healed 39 of each damage type per tick and prevented getting stunned or slowdown'd.

up until this nerf comes in viro > genetics

aside from that stimulant has been nerfed for a while and thus didn't incur any stun resistance or speed up and was litrally a joke placebo symptom so removing it has no impact whatsoever

@SirCodey 
i'm not sure if you're joking or just completely braindead but the one thing that pisses me off is wordless 'no's' in response to a github with no fucking reason provided 

what the fuck do you mean 'no pls', did you just read the word virology and shit out your brain or something? like come the fuck on

what is the possible reasoning to saying 'no pls'. if the answer is 'but i like our viro' then suck it the fuck up buttercup our viro is shit and buggy as fuck and /tg/ viro is superior in every way, from it's available symptoms and scaling and interaction between virus stats and symptoms beyond symptoms being completely arbitrary and unrelated to stats at all and being able to minmax retarded stats etc

the /tg/ virology fixes almost all of those issues and allows interaction between virus stats and symptoms-something with higher stealth makes choking do more damage, faster stage speed and less stealth makes necrotizing fatalisis do more damage, etc. unlike at current where stats are -completely irrelevant- because if you're making a murder virus it doesn't matter what the cure is, just stick in disabilities, disorientation and necrotizing on one virus, combustion and the other 2 on the others, and slap hallucination and deafness on the third and watch people shit their eyes out and catch fire. 
/tg/ viro fixes all of that.

so again, what's the 'no pls'. too difficult to learn? suck it the fuck up. 'too much of a nerf'? it's actually stronger than current, just use your brain.

**Comment by Super3222** [comment]
SirCodey actually wanted /tg/viro.

**Comment by SirCodey** [comment]
We do infact have /tg/ viro, it's just outdated by three/four months.

**Pull request merged**
