### PR TITLE
fucking plasmaman speed

### PR DESCRIPTION
**Pull request by GuppyLaxx**
wow i made them faster probably

:cl:  
tweak: Made plasmamen not have this damn slow speed
/:cl:

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
travis machine 🅱️roke

**Comment by ToGWtF** [comment]
close and reopen to tell travis to get his shit together

**Comment by ShadowDeath6** [comment]
why?

**Comment by Alexandria404** [comment]
What speed are they going to be at with that PR?

**Comment by GuppyLaxx** [comment]
It'll be the speed of a human at full health with an EVA suit on

**Comment by Time-Green** [comment]
So you made them slower?

**Comment by Amelia0010** [comment]
no, faster.

**Comment by Time-Green** [comment]
They’re just as slow as they were, it’s just on the suit now

**Comment by GuppyLaxx** [comment]
put on an eva suit as a human, is that faster or slower than the average plasmaman
🤔

**Pull request merged**
