### PR TITLE
Adds powertools

### PR DESCRIPTION
**Pull request by Amelia0010**
ported from: https://github.com/tgstation/tgstation/pull/20923/files

:cl:
add: Added a new unique tool belt to the CE
add: Added new power tools, a hand drill that can be used as a screw driver or wrench and jaws of life which can be used as either a crowbar or wire cutters
soundadd: added new sounds for the power tools
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
is there a powersaw in this that can remove plating in 3 seconds

**Comment by Kmc2000** [comment]
Shoutout to that reference JC

**Comment by ghost** [comment]
this should be your changelog

add: Added a new unique tool belt to the CE
add: Added new power tools, a hand drill that can be used as a screw driver or wrench and jaws of life which can be used as either a crowbar or wire cutters
add: Power tools can also be made from the protolathe with engineering and electromagnet 6
tweak: slightly revamped how construction/deconstruction handle sound
soundadd: added new sounds for the power tools
soundadd: added a new sound for activating and deactivating welding tools, just because.

since just saying 'power tools' will clue nobody in

as an fYI the jaws of life can pry open airlocks

**Comment by Amelia0010** [comment]
>tweak: slightly revamped how construction/deconstruction handle sound
>soundadd: added a new sound for activating and deactivating welding tools, just because.
>add: Power tools can also be made from the protolathe with engineering and electromagnet 6

i'm 99% sure I didn't bring either of those changes along with the port 😕

**Comment by ghost** [comment]
@nichlas0010 oh, well then you should probably do that because it's cool

**Comment by Amelia0010** [comment]
i'm not adding them to science, cause science already has more than enough playthings. 

and as for adding special sounds for when you use the tools; I'm lazy, and can't be arsed to go through hundreds of playsound()s to find the needed ones

**Comment by Amelia0010** [comment]
Oh and you don't need to ping me, I have this repo on watch and github lets me know whenever anyone says anything here

**Pull request closed without merging**
