### PR TITLE
Gex will now occasionally eat trash.

### PR DESCRIPTION
**Pull request by Cruix**
:cl:
rscadd: The janitor's lizard will now occasionally eat trash, healing him and increasing his maximum health.
/:cl:

### CODE REVIEW

**Comment by Groudonmaster** [comment]
Nice. Let's give get a girlfriend so we can breed the hell out of gex

**Comment by ShadowDeath6** [comment]
gexplosion 2016

can we get PR of the year tag

**Comment by FluffySurvivor** [comment]
make him increase in size as well

**Comment by ParagonPrime** [comment]
GEXZILLA

after he reaches a certain critical mass he can become inhabited by a ghost

his objective is to eat trash by any means possible, and let no one interfere

**Comment by drderp3635** [comment]
^

**Comment by Cruix** [comment]
Maybe later.

**Comment by Groudonmaster** [comment]
Make sure to count the clown as trash

**Pull request merged**
