### PR TITLE
Maps out an engine bay instead of the memey space engine thing.

### PR DESCRIPTION
**Pull request by Kmc2000**
🆑 kmc
rscadd: Nanotrasen decided that having open space inside the engine bay was a pretty bad idea overall, a brilliant team of engineers managed to make it airtight.
/🆑

References: https://github.com/yogstation13/yogstation/issues/355

### CODE REVIEW

**Comment by Super3222** [comment]
Spaceless engine bay is bad imo.
And making it so you don't need a suit to set up the emitters changes up the game for engineers.

Also the color tiles..

**Comment by Kmc2000** [comment]
@Super3222  the light tiles are so the middle bit stays lit

As for the rest 

¯_(ツ)_/¯

**Comment by TheSadFox** [comment]
Don't see a reason for this change other than H U G B O X.

**Comment by Time-Green** [comment]
I love the idea.
It allows engineers to more easily set up the tesla and it also allows for easier variation of setups, they can even look at the tesla from REALLY close.

**Comment by Super3222** [comment]
I can do easier variations in the field with a hardsuit... All it takes is a bit of metal and rods.

**Comment by Kmc2000** [comment]
H U G B O X
U
G
B
O
X

**Comment by oisin100** [comment]
Nah, That just kills all the challenge.

I mean, Floating around in a vacuum playing laser tag with some heavy duty emitters is all part of the job.

**Pull request closed without merging**
