### PR TITLE
Revert "Adds animal respawn for donators"

### PR DESCRIPTION
**Pull request by ghost**
Bad PR. No reason to have it now, donators getting free donor-only ghost roles is dumb, and they can still talk and shit so basically it's a free license to spawn as a dog, follow someone around all the time watching for them being suspicious and scream TATOR while abusing passflags to get away

didn't make RP sense either for animals to randomly become sapient

negative feedback in general

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Let's just make animals not able to fucking speak instead.

**Comment by ghost** [comment]
or we could not give free ghost roles to donators

**Comment by ghost** [comment]
- that would make xenobio sentinence potioning ian way less fun and break xenobio sentinence altogether

**Comment by ghost** [comment]
and minebots too

and blobbernauts

**Comment by ShadowDeath6** [comment]
easy fix, no need to remove it

**Comment by ShadowDeath6** [comment]
how to fix: use the already existing simple_animal saycode to make animals not sentience potioned talk in animal voices, and make a check for donator_sentience rather than regular sentience so we can't have donator blobbernauts

**Comment by Ephemeralis** [comment]
Correct response! Get right on that, Adam.

**Comment by ghost** [comment]
Still the other 500,000 issues I pointed out @Ephermalis

**Comment by ghost** [comment]
@Ephermeralis or whatever

**Comment by ghost** [comment]
@Ephemeralis GOD DAMN

**Comment by ShadowDeath6** [comment]
The mobile meme master @adem-ek-tablaway

**Comment by Super3222** [comment]
> how to fix: use the already existing simple_animal saycode to make animals not sentience potioned talk in animal voices, and make a check for donator_sentience rather than regular sentience so we can't have donator blobbernauts

**Pull request merged**
