### PR TITLE
Revert "Merge pull request #2190 from AdamElTablawy/patch-90" aka the one that touched my baby

### PR DESCRIPTION
**Pull request by Jc1469**
This reverts commit a986ca52fb4cebe1934b223d23825da1db8dbedd, reversing
changes made to 888a8808d3599b224f0f1de9bad3fb6c59fbd6f5.

Let's just say Adam didn't fix the problem, he ignored it.

#### Changelog

:cl:
tweak: Ash drake duplication is back, but lessened...  because lesser drakes.. you get it? No?  Aight.  Anyways, incase you didn't know, lesser drakes are essentially 1/5th of an actual ash drake.  And now the lesser drakes themselves can't duplicate anymore.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
meh, never really liked the idea of having to fight two megafauna, the lesser ones just serve as an obstacle rather than an extra fight to the real drake

**Comment by Jc1469** [comment]
perhaps, but it also drops a fifth of what a normal drake drops.  It's not something for nothing, and it also isn't aggroed to you when it spawns.  That and they're now also going to spawn a lot less.

**Comment by Cruix** [comment]
But can a normal dragon split more than once?

Also don't use istype() on src, override the lesser drake's xoxo_and_friends() proc to do nothing.

**Comment by Jc1469** [comment]
Drakes don't split, they call in reinforcements, and if I do that, admins can't even proc call a lesser drake to use the ability.

**Comment by ShadowDeath6** [comment]
If an admin wants to spawn another lesser drake they can just spawn one in, they don't need to call a proc on an existing lesser drake, that would be really inefficient and annoying to do.

**Comment by Cruix** [comment]
A subtype overriding its own procs instead of the base type checking its own type when it tries to do something is part of object-oriented design, which is the codebase standard.

**Comment by Jc1469** [comment]
Lesser drakes attack slower.
Lesser drakes will still have that attack in their possible moves, doing nothing.
That's a chunk of time where a drake will just not be doing anything.

**Comment by Cruix** [comment]
Then make the proc return it's success or failure and have it do something else on failure, make the moves it could take and their probabilities into a list and set the lesser drake's probability of calling reinforcements zero, or override the OpenFire() proc on lesser drakes instead so that the reinforcement proc is never called.

**Comment by X-TheDark** [comment]
Why would you need to be able to call the xoxo proc manually via admin commands on a lesser drake, when as Shadow pointed out, you can just spawn the damn things?

**Comment by Cruix** [comment]
Do it with proc overrides

**Pull request closed without merging**
