### PR TITLE
One armed people can be cuffed all over again

### PR DESCRIPTION
**Pull request by Super3222**
Since Adam abandoned https://github.com/yogstation13/yogstation/pull/1015.

#### Changelog

:cl:
rscadd: One armed people can be cuffed again.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
what if no arms???

**Comment by Dragonforcefive** [comment]
Well... what reason do you have to cuff them? What are they gonna do? Run into you?

**Comment by Super3222** [comment]
> Well... what reason do you have to cuff them? What are they gonna do? Run into you?

Use one arm to robust you.

**Comment by Time-Green** [comment]
"Well... what reason do you have to cuff them? What are they gonna do? Run into you?"
I think it was a reply to the above comment

**Pull request closed without merging**
