### PR TITLE
Special snowflake husks

### PR DESCRIPTION
**Pull request by Kmc2000**
:cl: Kmc2000 
rscadd: Plant nerds and robofreaks now have their own special husks..wow!
/:cl:

Fixed it this time, wew lad

For:

https://github.com/yogstation13/yogstation/issues/346

### CODE REVIEW

**Comment by Kmc2000** [comment]
NOTE

There is no code for this, the icons are just there and usable for you

**Comment by FluffySurvivor** [comment]
> There is no code

wow

meme zone tag pls

**Comment by ShadowDeath6** [comment]
> there is no code

better than 90% of PRs tbh

**Comment by Stealthkibbler** [comment]
@FluffySurvivor what even is an icon change??????????? :^)

@Kmc2000 
also you should present the sprites on a 100% view ratio so they dont look all oversized and blurred, I've found that sprites tend to look a hell of a lot different when scaled to size in the game.

**Comment by Kmc2000** [comment]
Meh, good to give a close up alternative sometimes

**Comment by Time-Green** [comment]
Kmc, both preternis and phytosian use limbs, you should make the husks limbs aswell.

**Pull request merged**
