### PR TITLE
Honkcans2

### PR DESCRIPTION
**Pull request by utahclock**
:cl:
rscadd: Honk! Industries has obtained financing to supply the clown and mime with a spraycan.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
What we really need is to give the clown colourful reagent grenades at roundstart.

**Comment by Cruix** [comment]
The clown already starts with so much crap in his backpack, why does he need more?

**Comment by Super3222** [comment]
Just make attacking a spraycan with a rainbow crayon, makes the crayon get "installed somewhere" resulting in a honk can.

And then attacking a spraycan with a silent crayon, does the same thing.

**Comment by Super3222** [comment]
@utahclock 

Seems like clown already spawns with enough gear, and won't be getting anymore. I've already suggested an alternative route. Do you still want this PR up? If not, than I'm closing it.

**Pull request closed without merging**
