### PR TITLE
Smes1

### PR DESCRIPTION
**Pull request by matskuman5**
At round start AI SMES had an output level of 50k, making the APC not charged and killing the AI quickly.

So I changed the output to 53k.

### CODE REVIEW

**Comment by matskuman5** [comment]
WHAT IN THE EVERLOVING FUCK IS GOING ON

WHY IS THERE THE MAMA MIA CHANGE THAT WAS THE LAVALAND THING

WHILE I ONLY PUSHED THE NEW BRANCH THAT HAD SMES

# **_FUCK GIT_**

**Comment by RoboticVodka** [comment]
I'M NOT CREDITED REEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by matskuman5** [comment]
Closing this until I figure out what the fuck is wrong

**Comment by Cruix** [comment]
Git is wonderful.

**Pull request closed without merging**
