### PR TITLE
Adds Medgun and Tirizine syringe gun to Syndicate Medborgs

### PR DESCRIPTION
**Pull request by ShadowDeath6**
> > > > > > > > spending 80 tc on a medborg with fuckin ephedrine when you could spend 15 on a medgun

:cl: ShadowDeath6
rscadd: The Syndicate has realized that their medical cyborg was a very advanced piece of machinery, and added a medical beamgun to its arsenal of healing.
rscadd: They've also added a knockout syringe gun to their arsenal for self-defense.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Inb4 it blows up

**Comment by ShadowDeath6** [comment]
If you get 2 med borgs and they're dumb enough to cross the beams they deserve to get blammed

**Comment by ShadowDeath6** [comment]
Thanks x

**Comment by ghost** [comment]
Or a medgun and a medborg

**Pull request merged**
