### PR TITLE
updates ling stings, makes DNA extract sting cost points, nerfs mutesting, unnerfs transformsting and adds PARASTING

### PR DESCRIPTION
**Pull request by ghost**
# I WAS BORED

So first off DNA extract sting is now a buyable ability instead of a default ability, so that you know, FUCKING EAT PEOPLE AS A LING GOD DAMMIT

Transform sting is no longer nerfed into oblivion because what the fuck it was hilarious. It also no longer kills  you because wtf.

Armblade sting no longer causes genetic dmg cause it did for some reason

Mutesting now DOES cause genetic damage because lolop

Mutesting now injects you with mute toxin instead of lol xd silent

Hallucination sting now uh what was it oh yeah isn't _annoying and spammy as fuck edgy ling virus that stunlocks you and is cured by going to sleep and being eaten by a ling_ that you also constantly get reinfected with. now it's just LSD sting. Get stung trip balls. Uses mindbreaker. Shamelessly steals TGcode for it.

Shamelessly steals hippiestation's parasting with some bare-ass modifications. Parasting isn't what you think-you're not muted and there's an obvious and immediate delay before the effects kick in. It also costs a lot of chem and genetic damage. It takes more time based on human's health, the person is not muted, and it lasts about as long as a stunbaton. Essentially, it's good but not anywhere near the abomination it was before.
#### Changelog

:cl:
rscadd: Changelings have modified a wide variety of their abilities.
rscadd: DNA sting has been modified for some reason to cost DNA points to purchase, no longer a default ability.
rscadd: Transform sting's efficiency has been vastly increased.
rscadd: The hallucinogenic pathogen sting has been deactivated by the hivemind, replaced with a single-target hallucination sting that utilizes mindbreaker toxin.
rscadd: NT scanners now detect that changeling mutestings now use mute toxin. Efficiency of mutesting allover has been decreased.
rscadd: The changeling hivemind has once again developed the fearsome 'paralysis sting' ability.  (credit to Chronitonity) However, it's efficiency has been vastly decreased. When a captured changeling was questioned by an NT official as to why this was, the official was promptly absorbed by the changeling.
rscadd: He was delicious, by the way.
rscadd: 
/:cl:

### CODE REVIEW

**Comment by X-TheDark** [comment]
You can't be reinfected by a ling virus, once it's cured, you get the antibodies, at least that's how it supposed to work (and worked during me testing it when I buffed it out the ass).

**Comment by Nickvr628** [comment]
BOOOOOOOOOOOOOOOO I like the hallucination sting. It either needs to be buffed heavily and turned into a one target attack, or remain the way it is and infect everyone.

It is the Ling's best weapon for causing panic and chaos, and it needs to stay that way.

**Comment by ghost** [comment]
nick it literally is a one target attack

**Comment by ShadowDeath6** [comment]
6 absorbs for stronger stunprod is worse than it continuing to be commented out

**Comment by ghost** [comment]
stronger stunprod what

this is actually a way weaker stunprod

**Comment by ShadowDeath6** [comment]
Longer stun + silent activation says otherwise

**Comment by ghost** [comment]
there is no silent activation and it's a stunbaton stun while it takes between 8 to 20 seconds to kick in depending on mob health AND costs a high amount of chems and genetic damage so you can't pair mutesting with it

**Comment by ShadowDeath6** [comment]
Still hardstuns for longer and doesn't have an obvious meme zap

**Comment by ghost** [comment]
hardstun yes but you can avoid with anything and it's also a stun with no mute and no ability to mute the guy and 20 seconds to kick in and genetic damage blocks absorbing until it finishes, remember

so you'd stun a guy with it, have no chems or abilities while somehow keeping them from screaming for 20 seconds in all l ikelyhood and then keep them until genetic damage wears off to eat

**Comment by ShadowDeath6** [comment]
why even have it then

**Comment by AsV9** [comment]
fix & reopen please

**Pull request closed without merging**
