### PR TITLE
Yogs-specific job departments in Metastation

### PR DESCRIPTION
**Pull request by Ephemeralis**
Gift Shop:
http://puu.sh/rJX0d/957a2bed97.png

Paramedic Staging Area:
http://puu.sh/rJX1p/1ffa23d2c1.png

Psychiatrist's Office:
http://puu.sh/rJX2p/bea89310c3.png

Gift shop is pretty small but barely anyone plays Clerk anyway. If it's too small, we'll find out during the balance test and I can make another pass on it. I honestly just want to get us testing at this point.
#### Changelog

:cl:
rscadd: The "meta" model of Space Station 13 now accommodates the Paramedic, Clerk and Psychiatrist job roles.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
no meta allowed

**Comment by utahclock** [comment]
clerk shop needs random gifts... and needs to be a tile or two bigger. Plus no on META.

**Comment by utahclock** [comment]
also why is there a random cigarette butt on top of gift vendor ?

**Comment by ghost** [comment]
metastation is as good as shitty boring boxstation, fuc u

**Comment by Karinrine** [comment]
I was also making up an idea of an altered variant of Metastation for Yogstation, glad that I'm not alone.

**Comment by Ephemeralis** [comment]
Because the gift vendor is about as useful as an ashtray anyway.

Also metashield for Ratvar clerks is probably the funniest thing to come out of my completely-intentional-and-not-at-all-accidental-use-of-brass equipment. Maybe the role could be useful again.

**Pull request merged**
