### PR TITLE
Makes syndie base unescapable, adds some flavour

### PR DESCRIPTION
**Pull request by matskuman5**
Replaces r-walls with riveted walls, blocks the airlocks

Also adds some dank flavour, you know I like to make paper scraps

:cl:
tweak: The Syndicate have reinforced the walls in the chemistry and virology lavaland base! Unfortunately some concrete was spilled onto the escape airlocks...
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
Uh, this is the syndie base with science and the self-destruct if you're confused

**Comment by matskuman5** [comment]
Uh ,what? @Cruix why was this closed?

**Comment by X-TheDark** [comment]
Probably because #1662 was merged.

**Comment by matskuman5** [comment]
B-But my flavor... :^(

**Pull request closed without merging**
