### PR TITLE
Rebase's rogue sticky ban detection, planetary atoms, fixes to food crafting, cake cat, AND CANNABIS  from /tg/ 

### PR DESCRIPTION
**Pull request by Super3222**
This PR relies on https://github.com/yogstation13/yogstation/pull/279 getting merged.

Thanks go out to @MrStonedOne and @Iamgoofball for working on these PR's.
https://github.com/tgstation/tgstation/pull/19201 - Sticky Ban Detection
https://github.com/tgstation/tgstation/pull/19189 - Planetary Atoms
https://github.com/tgstation/tgstation/pull/19325 - Fixes Food Crafting lag

Also special thanks to @X-TheDark for showing me how to get this done.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
im da bes

**Comment by Super3222** [comment]
Give me a second to fix the conflicts

**Comment by X-TheDark** [comment]
Some of the conflicts are unfixable, since we don't have StonedMC (merged yet), unless you want to adapt it to the current MC.

**Comment by TheSadFox** [comment]
> tgstation/tgstation#19325 - Fixes Food Crafting lag

Yesssssssssssssssssssssssssssssss

**Comment by Super3222** [comment]
You see that? Travis only liked my PR when I included cannabis.

**Pull request merged**
