### PR TITLE
Replaces alien brain in necropolis drop table with greentext

### PR DESCRIPTION
**Pull request by Tenryumi**
# WHAT WAS CHANGED:
- In the tendril drop crates' drop table, the alien brain's position has been replaced by that of the the greentext

_Purpose: Antags and powergamers alike love to dig into tendril crates anyway. One may as well add an on-the-nose reference to this fact._
#### Changelog

:cl:
tweak: Necropolis chests have had one of their lamer loot options replaced with something more... desirable.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
barnyard is a grief spell please have anything else

**Comment by ghost** [comment]
NO

**Comment by Tenryumi** [comment]
What different item would you suggest then?

**Comment by Tenryumi** [comment]
WAIT
I GOT IT

**Comment by Zostroll** [comment]
The alien brain is useful for r&d replace something else(honk implant) or just add it as another item that drops.

**Comment by Tenryumi** [comment]
@Zostroll I already have something replacing the sad trombone implant in #1069. That, and xeno nests spawn pretty regularly. On top of that, tendrils aren't a reliable source of X item since there's a 1/25 chance of getting it.

**Comment by Super3222** [comment]
Greentext is as useless as a SORD. Alien brain had some purpose. Swapping the two would be a goof

**Comment by Tenryumi** [comment]
tHiS sHiT iS mOtHeRfUcKiN uSeLeSs HoLy FuCk

**Pull request closed without merging**
