### PR TITLE
Adds more ambient sounds

### PR DESCRIPTION
**Pull request by Time-Green**
All the sounds are from Kayozz11
Lavaland: http://vocaroo.com/i/s1Ub9yDLr1H6
Space: http://vocaroo.com/i/s0vvJdpPxOh7
Syndicate: http://vocaroo.com/i/s1oGZZEgbG4w
:cl: Kayozz11
soundadd: Adds 3 new ambient sounds, for space, mining and syndicate
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Can we add the "revenant" sound he posted as an ambient sound in Atmospherics?

**Comment by matskuman5** [comment]
use soundadd, not rscadd REEEEEEEEEEEEEE

**Comment by Time-Green** [comment]
That's actually a thing?

**Comment by matskuman5** [comment]
yeah

**Pull request merged**
