### PR TITLE
buffs assassin holos again

### PR DESCRIPTION
**Pull request by ShadowDeath6**
fuck yourself chaos holo

Assassin holos now have a vastly increased range to encourage actual usage of their stealth other than killing people

They also have full darkvision and thermals for sneaking purposes

they also have passmob while stealthed so they don't bump people while invisible

also they have passtable as a direct buff, it'd be a nice feature and I doubt it would really change much
# big shit

assassin holos also do a fuckton of stamina after stealth hitting, which slows their targets a lot

:cl: ShadowDeath6
rscadd: Assassin holoparasites now deal stamina damage upon stealth attacking, so they better secure kills.
rscadd: Assassin holoparasites now have thermal vision.
rscadd: Assassin holoparasites now pass through people while under stealth.
tweak: Increased Assassin holoparasite range has been increased.
/:cl:

### CODE REVIEW

**Comment by X-TheDark** [comment]
I'd like to hear thoughts on this.

What about replacing this with confusion/stamina damage instead to make it harder to run away without it being "gg no re" territory?

**Comment by ghost** [comment]
Assassin holos need no stealth range increase. Ranged holos have scout mode for that exact reason

Thermals is stupid, NV only

Give scout holos in scout mode NV as well and passmob/passtable same as assassin

Stunning holos is fucking retarded and overpowered. No stuns for holoparasites period that's their entire balancing factor

The master stuns you and the holo kills you, it's teamwork. Holos cannot do all the work by themselves. No stuns. None. Absolutely none. 

No fucking stuns for holoparasites. They're deadly enough as is. These guys in particular can dismember-IE target the leg for a stun. That's good enough. No fucking stuns. No.

**Comment by ShadowDeath6** [comment]
These are ASSASSIN holos. They have situationally the best damage but they also can't secure kills if they get unlucky and hit an arm or chest, which is retarded considering that they're intended to be ggnore and they can't do jack shit against a group or even one person somce their damage resist is literally none. 

As for "oh that's for ranged holos to have", every holo should have utility, locking it behind some bullshit where one holo has all the functionality and the others are used for niche memes is bad gameplay. Ranged holos have infinite range and free motion alarms as well as every single passflag available. They have a much broader utility, so they don't need nightvision or thermals. 

I'll add stamina damage for a slow, that sounds like a much better idea than a hard stun.

**Comment by ShadowDeath6** [comment]
Also before you quote me on "all holos need utility" I mean like each one should have its own supporty-type capability as well as combat. Healing holo is obvious, standard can break walls, explosive is kind of niche but its bombs are effective, protector holos suck ass, lightning and chaos are good CC but chaos does it better since it uses fire, and assassin will have the ability to stalk targets while the host doesn't look suspicious by having to lurk too close.

**Comment by ghost** [comment]
THE BLOOD SPRAYS FROM X is not subtle even if you're 10  feet away

**Comment by ShadowDeath6** [comment]
was planning on reworking that in a different PR

**Comment by Super3222** [comment]
Uh... shadow.

50 brute damage + 100% armor pen + 35 stamina damage + 50% chance to dismember.
Literally a meme. Slowdown should come from the fact their melee tears people apart like paper. And the fact that it's not hard to click more than once on someones mob.

**Comment by Super3222** [comment]
This is too much for one holo.

**Comment by ShadowDeath6** [comment]
gonna implement this PR differently since people are getting assmad about it being op

**Pull request closed without merging**
