### PR TITLE
you can now report clown sightings

### PR DESCRIPTION
**Pull request by Super3222**

### CODE REVIEW

**Comment by Tenryumi** [comment]
Merge it on the day of Halloween for maximum spooky pranks.

**Comment by ShadowDeath6** [comment]
why is PR not named after the commit?

**Comment by Time-Green** [comment]
The irony of his commit name.
Super, please don't make joke commit names, jeez.

**Comment by ShadowDeath6** [comment]
super confirmed for shit ass commits, please never make code ever again because your commits suck so much ass >:^(

**Pull request closed without merging**
