### PR TITLE
Makes space a bit more colorful [Ready]

### PR DESCRIPTION
**Pull request by Partheo**
# Updated!
I've listened to you guys and found a good compromise. I have reduced the amount of cyan visible in space, but instead of replacing it with white/gray, I've replaced a lot of stars with orange and purple ones!

output_lgfdnj
(Click the gif to see a higher resolution)

I have also moved around some stars so that the whole pattern looks more randomized, have corrected some weird looking stars, and have cleared up the near layer of the parallax so there is more color to it and so that it's less dense.

Overall, space is more colorful and has less obnoxious colors. Should look a bit more natural, while also looking more sci-fi.

:cl: Partheo
imageadd: The station has floated into a new sector of space. Look out the window to see the new, colorful starscape!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
i dont like it

**Comment by drderp3635** [comment]
Third times the charm?

**Comment by Partheo** [comment]
Lmao

**Comment by ShadowDeath6** [comment]
see the original PR for my suggestion since I can't post pictures on mobile

**Comment by Partheo** [comment]
I'll take a look tonight.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Cyan looked better

**Comment by simonset55** [comment]
What's wrong with having cyan stars?

**Comment by Partheo** [comment]
screenshot_20170915-135438
More opinions ^

Personally I made this change because I found that that space looked too colorful and saturated.
To clarify what I did: I only changed the large cyan stars. There are still the + shaped cyan stars, and little cyan stars so I didn't completely remove that color. I just found that there was too much of it in comparison to other colors. It also looks slightly more realistic.

**Comment by simonset55** [comment]
I don't really care much about it, but tbh wouldn't large stars usually be really shiny instead of grey? It does seem a bit weird to me, completely removing them would make space more empty though which, in my opinion would be more fitting

**Comment by Partheo** [comment]
I'll get back to this next week with more improvements.

**Comment by Partheo** [comment]
I've got a juicy change coming.

image

**Comment by Partheo** [comment]
Main post has been updated! What do people think?

**Comment by ShadowDeath6** [comment]
a palette swap is a nice change, :+1:

**Comment by ShadowDeath6** [comment]
looks good :+1:

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Not bad

**Comment by simonset55** [comment]
Looks mighty fine

**Comment by matskuman5** [comment]
MM juicy stars :+1:

**Comment by fonedsky** [comment]
There you go. That's how real stars would look like.

**Pull request merged**
