### PR TITLE
Lavaland! More Ruins, more budget, more loot!

### PR DESCRIPTION
**Pull request by Stealthkibbler**
Makes all ghost role ruins cost 10, prisoner shuttle now costs 20.

Stops seed vaults from duplicating to prevent them from chewing up budget.

Only the abductor crash site and survival pod tomb will duplicate.

Adds 7 new ruins.
Three 10 cost ruins
Three 5 cost ruins
One 20 cost ruin

I wont spoil any of them with pictures but heres some flavour text to show you what you're in for.

**Cuggans Cove**
_"Word has it that the infamous pirate Captain Cuggan made off with a Centcomm officials precious valuables and that he's crash landed on this forsaken wasteland to hide his fortune. Will you be the first to find the treasure in Cuggans Cove?"_
**Nanotrasen Surveyor**
_"They say not everyone is cut out for security work, that's why NT administration makes sure to send its most incompetent pilots and officers off to patrol borderworld hellscapes assigned with the all improved Snackcraft 1000, donuts not included"_
**Clown Facility & Miming Drill**
_"It seems NT isn't the only ones interested in Lavalands vast riches and minerals, farfetched reports of clown and mime encrypted crafts have been detected landing on the surface...only for their signals to go dark."_
**Syndicate Pod**
_"A signal was received by a jettisoned escape craft, the good news is that it was owned by a Syndicate mercenary group and it probably has some goodies in it. The Bad news is that whatever killed the crew may still be on it."_
**Research Outpost**
_"Who knows what interesting experiments and field tests were condu- Holy shit! Is that a carp hardsuit!?"_

raises lavaland budget from 60 to 125

Tested on 3 startups on my local host and it improves the ruin variation a good amount, this being said its only 6 additional ruins. In the future its expected we add more, however this will also heighten the chance at ghost roles spawning.

New Ghost Role
**The Hermit**
The Hermit is purely for solo play, to test you on if you can survive in the ashen wasteland, you really have free reign to do what you want but you start with basically nothing but bare minimum farming tools, a survival knife and an emergency toolbox, you will have to forage, hunt and survive off the land in general.
**Hermit Ruin**

I am contemplating making the Exile playable once @KorPhaeron or another coder from tg codes in the exile to actually have his inherited powers from his background lore (Assuming it happens anytime soon before this PR goes through and everything here is polished and ready for merging 100%) Otherwise if a coder here is comfortable with doing so then feel free, the lavaland code containing the Vars is in code/datums/ruins/lavaland.dm so everything should be there unless a Xui or Kor moved the files around again.

:cl: Stealthkibbler
rscadd: New Lavaland Ghost Role, Ports TGs Hermit along with their DMM for the Hermits hideout, only one hermit per round! Will you survive on your own and stand the test of time? Or will you crumble into the ashes and be forgotten by time itself?
rscadd: More ruins and crash sites are beginning to crop up on Lavalands surface.
tweak: lavaland budget should be getting doubled from 60 to 125.
rscadd: Due to recent legal problems regarding staff safety and wellbeing Nanotrasen has fitted their interplanetary prisoner shuttles with more survival gear in the event of an emergency.
tweak: Crashed Prisoner Shuttle has more gear to encourage group-work but not enough for everyone...
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
:+1: Looking forward to this.

**Comment by Stealthkibbler** [comment]
fuck i dont know why its failing, I only added in some basic objects

**Comment by GrayRachnid** [comment]
pics

**Comment by Super3222** [comment]
Can we get some screenshot of this new content? I know this must've already been in the code, but not used, yet it'd be preferred to see it on the PR bringing it in.

**Comment by Super3222** [comment]
Can we get some screenshot of the new content? I know this must've already been in the code, but not used, yet it'd be preferred to see it on the PR bringing it in.

**Comment by Stealthkibbler** [comment]
@Super3222 None of these were in the code, these were freshly made by both keek and me and we tested them for about 4 days to weed out any terrain issues/air problems that occurred. We'll definitely make more varying from small to large, we want to focus less on ruins that require you to fight an abyssmal amount of mobs but instead benefits exploring with loot that will in turn help you get more loot or can somehow be used to assist you in either more exploration or fighting fauna.

Cuggans cove gives a pretty hefty amount of treasure in the form of money, coins, weapons and valuables, however it requires you to have a boat, so there's already a requirement to even begin exploring it. It's arguably the most rewarding out of the lot but requires you to actually have a boat before you get to it, which should also increase the need for a boat if the cove spawns.

Edit: I recently added the Hermit DMM which was ported from tg.

**Comment by Stealthkibbler** [comment]
I will probably re-design the Hermits home to be more camouflaged into the rock using falsewalls, given the hermits current home he is very very open to attacks. His home should be his safe haven where he stores all his findings and his loot, it would be really shit if majority of rounds Hermit homes were ransacked with ease, there should be some amount of effort into unearthing a hermits home. even then Miners can still spot the obvious support beams and man made structures from outside.

**Comment by imtakingabreakdontatme** [comment]
Hermit could really use an oxy can to refuel

**Comment by Stealthkibbler** [comment]
@KorPhaeron I'll take that into consideration

**Comment by FluffySurvivor** [comment]
:+1: :+1: :+1: :+1:

**Comment by oisin100** [comment]
> Not giving the people responsible to checking on PR's pics

You only showed me the syndicate pod, PM me pics of the other ones, I shouldn't have to download your repo and compile it just to review the PR.

**Pull request merged**
