### PR TITLE
Order admin notes from new to old

### PR DESCRIPTION
**Pull request by ThatLing**
This makes new notes  appear above older ones.

### CODE REVIEW

**Comment by matskuman5** [comment]
[a quiet "ree" in the distance...]

**Comment by retrosquid64** [comment]
I'm not an admin, but isn't having the older ones at the top better? They could get buried in particularly busy rounds, right?

**Comment by Amelia0010** [comment]
Nope, notes are on a per-person-basis, so if they get buried in a single round then the person doing it probably deserves a ban at that point. 

Just to show what it looks like right now, here's my notes:
image

And making them show from new to old is better, since the newer notes are generally more relevant.

**Comment by retrosquid64** [comment]
Whoops, confused it with tickets.

**Comment by Amelia0010** [comment]
Tickets are currently shown from new to old, since some admins tend to forget to close their tickets, meaning that having 17 tickets open that are solved, would just bloat the ticket interface

**Comment by AsV9** [comment]
I mean this is going to get some admins confused and angrr but let's just have it and see what happens.

**Comment by Xantam-13** [comment]
Same thing I posted on the admin vote;
For people with small amounts of notes, the date order really doesn't matter at all. 

For people with lengthy notes, it's more efficient to see their most recent offences first, than their oldest, you tend to use recent notes against a player when issuing a punishment rather than age-old notes right? So why want to see oldest first?

**Pull request merged**
