### PR TITLE
Remodels the law office: Episode IV A New Hope

### PR DESCRIPTION
**Pull request by matskuman5**
#2516 

:cl:
tweak: Nanotrasen architects have remodeled the Law Office.
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Why have you remade this so many times???

**Comment by matskuman5** [comment]
Merge conflicts @Kmc2000

**Comment by Nickvr628** [comment]
Where are the briefcases and Space Law books, what else is missing?

**Comment by Amelia0010** [comment]
Space law books are in the bookshelves

**Comment by matskuman5** [comment]
Lawyers spawn with briefcases. The bookshelves are filled with Space Law.

**Comment by Partheo** [comment]
Hide an ace of spades somewhere in the office.

**Comment by Jc1469** [comment]
here's my new question.  

why.

Why is the law office where nothing will ever happen because yogs bigger than the detective's office.

**Comment by matskuman5** [comment]
Because it looks cooler and lawyer has two slots while detective has one. @Jc1469

**Comment by matskuman5** [comment]
Episode V coming soon to theaters worldwide

**Pull request closed without merging**
