### PR TITLE
Beepsky will attempt to arrest xenomorphs

### PR DESCRIPTION
**Pull request by ghost**
i'm not sure why i'm doing this but it'll be worth a laugh if he manages to cuff one

##### Changelog

:cl:
rscadd: Beepsky's targeting algorithms have been updated. As a result, he will attempt to arrest xenomorphs. This applies for all secbots, including ED209s.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
"You're under arrest for assisted facerape"

**Comment by enailz** [comment]
i ded

**Comment by Dagdammit** [comment]
They will learn to fear the true protector of ss13.

**Comment by Kyrigen** [comment]
"I AM THE LAW"

**Pull request merged**
