### PR TITLE
Allows AI cores to be dismantled if empty.

### PR DESCRIPTION
**Pull request by king5327**
AI cores couldn't be dismantled. Now, if there's no AI in a core (like for example after an intellicard is used), it can be screwdrivered open.

:cl:
fix: AI can now be deconstructed.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I'd have it drop a few sheets of plasteel or something since it does have materials needed to make it.

**Comment by king5327** [comment]
Strictly speaking the change only means that an empty core can be screwdrivered to the "glass inserted, need to screwdriver to complete" stage. Which is to say, if you crowbar it, it'll pop the glass as though you never finished it in the first place.

**Comment by ShadowDeath6** [comment]
oh, okay, cool then. :+1:

**Comment by Cruix** [comment]
In the future, do not commit things to your master branch. If this does not get accepted for any reason, you will have a dirty master branch, which is a pain to clean up.

**Comment by Cruix** [comment]
I took an AI out of an AI core, unscrewed the monitor, crowbarred out the glass, and was able to put the AI back into the core and repeat for infinite glass.

**Comment by king5327** [comment]
Noted. What's the adminbuse needed to make a dummy AI for this test?

**Comment by ShadowDeath6** [comment]
you can use game panel (in admin tab) to create a mob/living/silicon/AI or you can use the player panel to turn yourself into an AI then spawn a human in and posses that.

**Comment by Cruix** [comment]
I used the player panel to make myself an AI, turned off the turrets, aghosted, spawned a human, and put myself inside it by dragging my ghost onto it.

**Comment by AshCorr** [comment]
Fix the duplication glitch.

**Pull request closed without merging**
