### PR TITLE
Makes mobs get blown away by explosions

### PR DESCRIPTION
**Pull request by Time-Green**
Also adds pummeling. An easy to use proc to launch people

https://gyazo.com/5ba7d5ce072b2cf31589f8c4a79b2786

And another example of pummeling with the high force pummel hammer
https://gyazo.com/2cbafebb4fc19aa44c2510ac6c8de493
:cl:
rscadd: Due to a budget cut on the crews anti-bomb recoil implants, explosions may now fling you away
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Neat

**Comment by Partheo** [comment]
Could it fling you away from the explosion? In the gif or seemed like a random direction.

**Comment by Super3222** [comment]
This is a great idea! We just need to figure out how to fling them AWAY from the explosion.

**Comment by Time-Green** [comment]
It does fling away correctly with smaller explosions like welding fuel.
It was close enough IMO

**Comment by Ratvar** [comment]
Make CEmagboots/nukeboots remove recoil,normal magboots 1/4 recoil, noslips/galoshes 1/2 recoil?

**Comment by Ratvar** [comment]
Will it blow people/mobs on lavaland into chasms/lava? Thinking about gibtonite

**Comment by Partheo** [comment]
Getting blown into a chasm would be hilarious. I also like the magboot suggestion.

**Comment by Cruix** [comment]
Increase their throw speed so they can embed

**Comment by Tummywumbes** [comment]
would love to see this in game

**Comment by Time-Green** [comment]
Updated. Mag boots stop it and I made pummel proc
https://gyazo.com/2cbafebb4fc19aa44c2510ac6c8de493

**Comment by Ratvar** [comment]
wizard spell that flungs people the fuck out but leaves their shoes, YES

**Comment by AsV9** [comment]
fuk it let's merge this and see what happens

**Pull request merged**
