### PR TITLE
Lowers ninja spawn timer , minor HUD fixes

### PR DESCRIPTION
**Pull request by ToGWtF**
Refer to issue #1685 

#### Intent of your Pull Request

Ninjas are fun. Stop complaining and let people have fun

##### Changelog

:cl:
tweak: The Spider Clan has allocated more resources to its field agents, and their possibility of arriving on your station has increased
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Bad pr, I'm against this until ninjas are nerfed to be non round ending

**Comment by Jc1469** [comment]
[flashbacks to old ninja where I could press one button and gib 8 people with phase jaunt]

**Comment by ToGWtF** [comment]
I was going to change it so they only needed to abduct 2-5 people instead of 5-10 people, so its less "lol fucc shit up" and more "sneeky beeki cheeki breeki"

**Comment by ShadowDeath6** [comment]
fix them being fuckin dumb and cancerously op if you're making them spawn this early in the round because in their current state they're hitting wizard with bad build levels of unfair

see- https://github.com/yogstation13/yogstation/issues/1161

**Comment by ToGWtF** [comment]
what then make it its own god damn round type ?

**Comment by ShadowDeath6** [comment]
See #1161

**Comment by ToGWtF** [comment]
then why is it ive never seen a ninja greentext?

**Comment by Jc1469** [comment]
research objective is bugged, for one.
They also have to jump through a bunch of hoops to _actually_ debrain a changeling.

**Comment by ShadowDeath6** [comment]
you don't see a ninja greentext because they just go grief everyone 90% of the time rather than do their objectives

**Comment by Super3222** [comment]
This lets ninja's spawn in 30 minutes at a weight of 10. Hmmm, let people have fun and unleash one of the most easily playable murderbone antags or don't.

**Comment by ShadowDeath6** [comment]
Why the fuck are ninjas antag weight 10

**Comment by Super3222** [comment]
> Why the fuck are ninjas antag weight 10

@ShadowDeath6 It's the default weight. Also legacy code or however they say it.
@ToGWtF If you gave the ninja a considerable weakness, like 0 laser protection or some other balance thing, than lowering the spawn time wouldn't be so controversial. What you're practically saying is "fuck everybody in the round. letting the hardest-to-kill antagonist run around and murderbone is spicing up the round". The only problem with balancing it is the veteran players getting salty because we're """nerfing""" everything. So there'd have to be a reasonable divide or something.

**Comment by ShadowDeath6** [comment]
give ninjas negative melee resist and a weight lower than 10

**Comment by Jc1469** [comment]
:rareparrot:
on old code ninjas could spawn as early as 25 minutes
you're all just fucking babies

**Comment by Cruix** [comment]
I am not a huge fan of this because ninjas typically murder lots of people for no good reason. At least if it is late in the round those people actually get to play for a decent amount of time before being killed by something they have no chance of defeating.

**Comment by Super3222** [comment]
Reopen when you come back.

**Pull request closed without merging**
