### PR TITLE
Reduce The Speed of Swarmers

### PR DESCRIPTION
**Pull request by ArgyleSweatshop**
### Intent of your Pull Request

Swarmers are both small and fast, which makes even one of them able to stand up ridiculously well against the crew, even when the crew has a large numbers advantage. Making them a little slower makes it more realistic to hit them.

#### Changelog

:cl:
tweak: Swarmers now move slightly slower.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
no thanks I like swarmers

**Comment by ArgyleSweatshop** [comment]
swarmers are great, but it shouldn't be that a heavily armed security force struggles to deal with just one when they know where it is. This is because swarmers move so fast they are very difficult to fight with anything other than op shotguns

**Comment by ShadowDeath6** [comment]
the ion rifle / emps will kill them in one shot, the point is to use weaponry that they can't get away from, this change makes it so they can be caught up to and just melee'd to death which completely ruins their usability bar extremely good jukes

**Comment by Dagdammit** [comment]
I like swarmers and wholeheartedly support this change. Enemies with Speed 0 are a bad design practice; hunting them is terrible gameplay, frustrating and often downright pointless. When they die it's because they were bad or you just got lucky, not thanks to your wits or robust aim.

If speed 1 ends up nerfing swarmers too much, buff their HP by 1 laser rifle shot and cut replication costs by 25%.

Argyle, you should know: From what I'm told, speed 1 is healthy running human speed and Byond has no viable way to do anything in between. Sucks, huh?

**Comment by Dagdammit** [comment]
Alternately, have them turn invisible for 2 seconds upon being hit. Or give them a reactive teleport ability that drains 20 matter per use (and won't trigger if they don't have that much)

**Comment by Super3222** [comment]
Good change. Swarmer speed is bull.

**Comment by Time-Green** [comment]
Just make swarmers 10 times as big, and allow them to eat humans.
Problem solved.

**Comment by matskuman5** [comment]
WOW!!!!!!!!!

**Comment by Dagdammit** [comment]
For the record, this could definitely be a design change that clearly goes too far without follow-up adjustments. I suggest we do a test merge, have some admin-instigated swarmers every couple rounds, just quickly gauge if said adjustments are needed.

**Comment by Mrcreepssss** [comment]
YES. they are way too fast as it is RN.

"the ion rifle / emps will kill them in one shot, the point is to use weaponry that they can't get away from, this change makes it so they can be caught up to and just melee'd to death which completely ruins their usability bar extremely good jukes"
i thought their whole gig was overwhelming the crew with numbers?

**Comment by ShadowDeath6** [comment]
:angry:

**Pull request merged**
