### PR TITLE
Clothing additions

### PR DESCRIPTION
**Pull request by Kmc2000**
Adds in new clothes, you can get some of them via maintloot and gifts, but the majority need to be bought via cargo in packs, and boy do they NOT come cheap. There are also two undershirts that this adds, which can be selected with dressers or at character selection.

The clerk starts with two pairs of nice trainers for trading.

^sneakers in the wild (proof that maintloot works)

^ Ordering the shoes to show it works

UPDATE 1:
Scaled the shoes down massively, they're now all this size:

(kept the old icons because they're too sweet to delete)

#### Changelog

:cl:
rscadd: Added more clothes! find them under the miscellaneous tab in cargo, or in maintenance.
/:cl:

### CODE REVIEW

**Comment by Super3222** [comment]
Amazing :+1: only complaint is that the shoes look too big on their own. could you shrink em? and maybe make the icon appear with two shoes instead of one.

**Comment by Kmc2000** [comment]
@Super3222 

Ehhhh...

Aesthetics.

**Comment by Wilchenx** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Jc1469** [comment]
:thinking:

I don't think we need cruise ships on the station.

**Comment by Kmc2000** [comment]
@Jc1469  lol.

🤔

**Comment by Kmc2000** [comment]
Working with suggestions of succer and JC

**Comment by ShadowDeath6** [comment]
can you make them look anything similar to our current shoe sprites, they're so out of place

also again references to current era from 2557 is still aaaaaaaaaaarrrrrghhhh imo, don't refer to them as yeezies or whatever

**Comment by Kmc2000** [comment]
Can change the yeezy meme yeah.


Also they're meant to look out of place and flashy just like the real ones

**Comment by Kmc2000** [comment]
I'm leaving the type as yeezy because no one will see the type/care about it, k?

**Comment by Super3222** [comment]
Leaving a small reference, like a description referring to it as Yeezy's isn't bad, @ShadowDeath6 . There's tons of items and weapons that make those sort of references in the code already.

And yes, it's alright if it's in the type. Nobody's going to care.

**Comment by YogsMcree** [comment]
Can these be made to make you like, 1% faster for the luls? "I need the good shoes to go faster mom!"

**Comment by ShadowDeath6** [comment]
>giving cargo a flat speed increase for their powergaming stock memery

**Comment by Kmc2000** [comment]
Thought crossed my mind, but then again... nope

**Review by X-TheDark — COMMENTED** [review]
Code looks good, the icons seem to be weird, though. Specifically, ` icons/mob/suit.dmi`
untitled

**Comment by Kmc2000** [comment]
Right, yeah. I used a shading technique on gimp which may not agree with DM, didn't spot that. Will update asap

**Comment by X-TheDark** [comment]
Forgot to add this one as well to the previous thing.
untitled

That seems to be all for the weird icons, though. Other than that, great job!

**Comment by Kmc2000** [comment]
Issues resolved

**Review by X-TheDark — APPROVED** [review]
Since icon issues are fixed - seems good.

**Comment by Frostben** [comment]
All the other staff with their pumped up kecks better run better run, faster than my bola.
The hops got some sick kecks, he better watch out cuz I've got a stolen sec taser. 

Lel i can't wait for the mugging a to happen when these appear

**Comment by Kmc2000** [comment]
To come in my next PR:

Sneaker hunter antag/ traitor clown objective

**Comment by Time-Green** [comment]
Will we be able to make traps to capture the wild shoes

**Comment by Super3222** [comment]
Yeezy shoes that provide a speed boost should be a traitor item for clowns exclusively.
Or alternatively, a cannon that fires projectiles which force equips Yeezy's that slowdown.
Or even more, alternatively, a cannon that simply fires projectiles that equip's no drop Yeezy's with no drawbacks... only pros because of those stylish shoes.

**Comment by Kmc2000** [comment]
kappa

**Pull request merged**
