### PR TITLE
New air tanks and jetpack sprites

### PR DESCRIPTION
**Pull request by Partheo**
i need to stop

Again, these are modifications of the TG sprites I tried to port at #2578.

Current Yog sprites:
tankyog

TG sprites:
tanktg

My edits:
tank

The TG air tanks- while they are fantastic sprites themselves, they are extremely inconsistent with literally anything else in the game. I don't know what game the sprites were made for but it wasn't SS13.

I've modified them to fit our "softer" art style. It's also not 1996 so it's not crucial for there to only be four fucking colors on a sprite..

I've also redone the jetpack sprites, smoothed out their animations, and updated the plasmamen tanks to fit in a bit better.

## Closeups:
Old Yog
TG
New sprites
image

Old Yog
New sprites
image

:cl:  Partheo
imageadd: Air tanks now have new sprites
imageadd: Jetpacks now have new sprites
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
I also fixed a typo in the description of the outdated plasma tank

**Comment by Cruix** [comment]
Unacceptable, clearly this typo fix must be atomized, as it drastically affects the balance of traitor, rev, DA, blob, nukeops, etc. and will result in Yogstation becoming an extended-only server for obvious reasons.

**Comment by Partheo** [comment]
FUCK

thats it cruix

im done contributing
im drawing the line and its between us now

you

--------
me

im gonna go make my own server
my own codebase
its gonna have my typo fix AND tank sprites in one pr

and you wont be able to do anything about it

**Comment by ShadowDeath6** [comment]
do the same thing to the top of the large air tanks as you did to the small air tanks

I would prefer to have the "PL" on the plasma tank stay

**Comment by Partheo** [comment]
I must have been high when I picked those Captain's Jetpack colors because they're fucking terrible. I've gone and fixed them. Minor tweaks to other jetpacks.
New file:
tank

Also, new plasma tank sprite:
image

Finally, the Outdated Plasma Tank high-risk item will now use the old sprite:
image

**Pull request merged**
