### PR TITLE
Whoopee Cushions

### PR DESCRIPTION
**Pull request by Super3222**
https://github.com/yogstation13/yogstation/issues/1507

#### Intent of your Pull Request

This'll probably be my silliest PR, but hey it's a clown one. The item works exactly as it sounds.
- Attack a chair with it to place it on top
- The desc of the chair will change, and the cushion will be ontop of the chair (but not visiblly)
- The next person to buckle onto the chair will trigger the whoopee cushion, releasing a noise
- The whoopee cushion will come back up to the surface, on the turf of the chair.

If a spriter could please create a sprite for these that'd be great. It'd be an item icon, and than an icon that's visible on their mob.

https://github.com/yogstation13/yogstation/pull/1373 better be merged first or this is a clown-ruled codebase.

Someone remind me to spawn one of these on the map in the theater after I get a sprite for them...

##### Changelog

:cl:
rscadd: The Clown is now armed with a whoopee cushion. Beware!
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Could be a thing like bike horn so when you step on it it makes farts as well, buckling to chairs only makes ut a bit hard to annoy people with

**Comment by Hopekz** [comment]
I'll paste this here for reference and logging

"There could also maybe be a variant of the whoopie cushion for traitors. The sticky whoopie cushion. Works the same way as a whoopie cushion, but the person that buckled to the chair would be stuck in the chair for a certain amount of time (maybe like 20 seconds). It may or may not be a one time use depending on how good you deem this ability.(edited)
How you would make it one time use is you would make the syndie glue mixture come off the whoopie. (so just turn the syndie whoopie into a regular whoopie)(edited)
Also as a side fun idea, the struggling to get out of the chair when you can not should make the whoopie produce more fake farts whenever an unbuckle is attempted. This way you could convey to the victim that this is a syndie whoopie without even displaying text.(edited)"

**Comment by Kmc2000** [comment]
Add superglue for 3tc, apply to chair or buckleable object to stick someone and whopee cushion is a bonus.


10 uses

**Comment by Super3222** [comment]
Honestly, I like those ideas but for implementation they wouldn't work

> buy superglue
> rub hands together evilly
> glue chair
> buckle HoS
> chuck over minibomb
> HoS tries ridiculously hard to get out of the bomb range, but makes fart noises in his efforts.

**Comment by Cruix** [comment]
Every day we stray further.

**Pull request merged**
