### PR TITLE
Barrier

### PR DESCRIPTION
**Pull request by Time-Green**
Ports @Super3222  's barriers

### CODE REVIEW

**Comment by Time-Green** [comment]
I saw oisin was already doing the map changes with the barrier, so this is just the code

**Comment by Time-Green** [comment]
Something was merged that broke everything... 
I'll just close this again...

**Comment by oisin100** [comment]
you forgot to remove the barrier grenades from the other maps.

**Comment by Time-Green** [comment]
It's to much for me, I'll go knit some wool
And ehm, map changes aren't my greatest quality

**Pull request closed without merging**
