### PR TITLE
Completely redoes the atmospherics department, adds three random maint rooms, and modifies virology a bit

### PR DESCRIPTION
**Pull request by Partheo**
Why you say?
Our current atmospherics department looks, to me, like lazy mapping. I tried redoing it with actual thought going into it, balance considerations, and just general care. I like atmos a lot. Our current layout of atmospherics is also present in multiple different maps- mappers have habit of copying and pasting this layout (a "default") into theirs. This should make ours unique.
This is my first mapping project so there might be few things I have missed. More experienced mappers- please advise me.

I have been in contact with a handful of atmospheric technician "mains" to get their opinions. I've taken a lot of their requests and issues into consideration.

## Here is a picture(UP TO DATE):
atmos

## Here is a GIF, of old vs new(OUTDATED; REFER TO PICTURE ABOVE):
new
(Click for hi-res. Ignore sprite changes, those are a side-effect of my other PR)

# Main changes
- Atmos is mostly linear now, as opposed to spaghetti. Waste goes down into atmos from maint, then back up as air.
- Atmos has been split into two areas- Atmospherics, and Atmospherics Office.
- All tanks and filtering are in their own room.
- Atmos now has an actual room for their equipment.
- The incinerator room has been redone
- Virology has been tweaked to accommodate the new atmos
- Maintenance has been tweaked has a new room, which can accommodate a random room in a future PR.

# Case-by-case changes
I have swapped the location of the break room and the monkey pen. The monkey pen now is visible from the airlock, so the virologist can "show off" the effects of his diseases without having it spread or opening virology. The windows are electrified, and there is a new button which closes blast doors over them, in case they want it to act as a wall. I have also added a medical laptop to the break room because it has viral information on it, and the virologist should have it.
image
---
This is the Atmospherics Office. It contains a little atmos hallway which has the air canisters stored in it; the office itself; and the equipment room. Objects like the BZ canisters or fire axe are now behind two doors minimum from public access and therefore harder to steal. Everything is compartmentalized and not all over the place like in the previous map.
image
---
The mixed gas tank is no longer surrounded by space. It has a double-thickness R-wall layer instead. My reasoning for this is that it looks better, offers some antag potential, is about just as difficult to breach as a regular space-isolated tank, and that all areas surrounding it require either atmos or security access. It can now be breached into easily using X4. To balance this, the gas mix to incinerator pump **no longer requires plasma in the mix tank, so it should never be filled with plasma to begin with.** I'll expand on this later. I have also added a huge air scrubber to atmos which should curb any damage caused by this.
image
---
The air tanks now come in their own room. This should function essentially the same as the old one. The only difference is that the pump leading to the incinerator **bypasses the mix tank**. This is mentioned as a balancing factor earlier. Now I mention it as a convenience factor.
image
---
This room, plus the air tank room, is the "Atmospherics" area. The main pipe network is here. **The pipes operate identically to the old atmos.** All loops are the same, all pumps are the same. Yes, they are still logged. Now there are no kinks in the pipes, and everything is fairly straight. It also looks good from maintenance.
image
---
This is the new incinerator. Not much changed functionally- everything that was there prior is still there. The mix pipe now comes straight from atmos, no more huge loop around the whole department. Also, the pumps inside the incinerator itself have been replaced with manual valves, as the pumps were redundant given what was already on the pipe.
image
---

# Detailed case-by-case of small changes
I've added two flashlights, two analyzers, and two air alarm circuit boards to the equipment room. All other equipment is the same.
image
---
Atmos now has a huge air scrubber and an extra space heater. My reasoning for the scrubber is that it is at its core an atmospherics item, and atmos doesn't have one. They, of all people, should. Also, it should help curb any flooding within atmos due to tank breaches.
image
---
I've added two fire safety closets. Again, atmos should have some. There's an excess of fire extinguishers available, but it makes sense in this kind of department.
image
---
Transit tube has been moved down by 1 tile. No biggie.
image
---
I've opened up this part of maint so that a loop is present again.
image
---
The atmos department colors are now blue and yellow, instead of black and yellow.
image
---

**This PR is more or less ready. Feel free to add your suggestions and I'll look them over..**

:cl: Partheo
experiment: The Atmospherics subdepartment has been completely redone!
tweak: The Virology subdepartment has had some adjustments.
rcsadd: There are three new randomly appearing maintenance rooms. Try to find the Winter Storage, Fantasy Roleplay, and Cult Shrine rooms!
rcsadd: There is now a bookshelf with RPG manuals present in the library. Go play some tabletop D&D!
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
If this breaks #2616 I am not sorry

**Comment by Kmc2000** [comment]
Why the destroyed stuff up top? looks cool btw but really cluttered.

**Comment by Kmc2000** [comment]
P.S update the wiki for this so the pubbies arent confused about where the distro is

**Comment by Jc1469** [comment]
Did you log all the important pipes?

And by all I mean all, because there's a lot of new ones logged.

**Comment by Nickvr628** [comment]
I tested this on a server with him the other day, as an experienced atmos tech, it works great and feels good. The new incinerator is great, and while minor changes to viro were necessary to fit everything in, it still is fine.

Also, I think this version is easier to learn, since you can fit 90% of it on your screen at once, compared to having to do the walking tour in old atmos to teach newbies.

**Comment by Jc1469** [comment]
List of issues for me personally.
[This part of maint.](http://puu.sh/xLjnL/8b9dc29e1f.jpg) 
[This part of maint.](http://puu.sh/xLjp3/76acb0f0c6.jpg)
[The location of this fuel tank](http://puu.sh/xLjBQ/5c1b7486c9.png), mainly because anyone can smash that light and there's a chance of just blowing a hole straight into atmos then and there.. not to mention fuel tanks on either side of it already anyways.
[This circle of wires in viro, which I don't really see the purpose of.](http://puu.sh/xLjqi/d0e69876e7.png) 

The overall change to the mix chamber.  It now, to anyone not versed in atmos, has one use, putting things in distro.  And, as I've already been over, is an easy way to flood all of engineering and probably most of central primary if someone takes the time to dismantle the walls.

The manual valves in the incinerator; if people want them, they can just swap them out.  There's a reason to not have them though and just keep pumps, you want more going in than you're taking out, especially the way I do it.

**Comment by Partheo** [comment]
@Jc1469 
First part of maint- I don't really know how I can remedy this, unless I modify viro even more. I tried to leave it be as much as possible, but I would mind changing it if people are okay with it.
Second part of maint- I made this just to fill the hole there. It's messy. However, as mentioned this is a temporary maint room and I or someone else can/will replace it with a randomized maintenance room. I wanted to see what kind of reception the PR got before making a bunch of maint rooms. I'll see what I can do.
The first fuel tank- Didn't think of the lightbulb being a problem. It's been moved. I've also moved other fuel tanks into less dangerous positions.

**About the mix chamber, because this is a point of contention**- the mix tank begins empty at roundstart. This means that if you want to flood the station by breaching into the mix tank, you need to have set up atmos in a fashion that pumps plasma into the mix tank. **This means that any flooding caused from a breached mix tank is limited by how much can be pumped.** So, saying that it's equivalent to breaching an entire gas tank is incorrect. You could achieve the exact same amount of flooding by placing a vent somewhere and connecting it to the gas of your choice.

As for the manual valves in the incinerator, the way I see it- you can use the gas mix to incinerator pump to control pressure already, and the vent inside the incinerator to control how much you want to suck out. Adding more pumps doesn't change how it operates.
image

If you have any concerns with this, please let me know. I want to make this as great as it can be. Thanks for the feedback.

**Comment by Partheo** [comment]
Also if someone can counsel me about the failed CI check that would be great. I think it has to do with the other maps but I have no clue.

**Comment by Cruix** [comment]
Something has the step_x variable set, and Travis does not like that because that can break pixel gliding.

**Comment by matskuman5** [comment]
Looks gud :+1:

**Comment by Alek2ander** [comment]
30991946-542b55e6-a475-11e7-9e18-2777935b71d0

**Comment by Partheo** [comment]
@alek2ander
If I move the canisters, I wouldn't really know what to fill the current spot with. Besides, I quite like where they are now.

What do you mean by "easier to enter"? Do you mean that people will have an easier time getting into atmospherics from maint?

As for the corner walls in space, I could remove them. I added them mostly for aesthetics and because the dangerous air tanks and on the right already have windows nearby that allow you to get to them. What do others think?

**Comment by matskuman5** [comment]
I agree with Alek, remove the spess corner walls

**Comment by Partheo** [comment]
Spess corner walls have been removed, pipes have been logged, and I've replaced the mess in maint with two random maint rooms-

Tabletop RPG den:
image
Contains medieval gear, a dwarfism injector and lots of DnD manuals. That's why I modified books in my commit.

Winter storage:
image
A cold room with hot drinks and winter coats, as well as some snow.

Thoughts?

**Comment by tsit9** [comment]
I never realized how badly I wanted a secret D and D club before.

**Comment by Alexandria404** [comment]
A lot has been fixed that was addressed in coder chat since the start of this, some issues remain we talked about, mostly mentioned by John already.
Namely the location and change of usage of the mixing chamber and the issues that come from it as mentioned by John.

**Comment by Partheo** [comment]
I've changed that annoying part of maintenance by squishing viro a bit. Since it's just the monkey pen, I think it looks fine.
image

I don't want to sound hard-headed but I don't think the mix tank is as big of an issue as people are putting it out to be. Breaching it is not comparable to breaching a regular air tank because it starts as a vacuum at roundstart. Any dangerous gasses that could be present inside are limited by the flow rates of the pump system. Because of the way I set up the incinerator pipe, **plasma will only be present in the mix tank in antag or grief circumstances, rarely in regular crew operation.** It's all logged, so any admins noticing plasma in the tank already have a reason to start investigations. They don't have to hope it's there for a good reason.
I've also created a few balancing factors that I've mentioned earlier. I'm very willing to change this ASAP if problems do arise with it. As it is now though, I don't see it becoming much of an issue.

I've created a third maint room that can go in the corner: an abandoned cult base. The rune and tome are just for show and don't have any actual use. The whetstone is used. The floors are real cult floor, however. I think it could be interesting to have these in-game because they will break the meta a tiny bit. Seeing this tome won't be immediate grounds for confirmation of a cult on-board. Thoughts? I can tone it down if it's too extreme.
unknown

**Comment by Amelia0010** [comment]
>  plasma will only be present in the mix tank in antag or grief circumstances, rarely in regular crew operation

So malf AI's will have no way to cover up the fact that they're preparing to plasmaflood?

**Comment by Partheo** [comment]
@nichlas0010

It will look exactly the same as it does currently. If someone asks the AI why there's plasma in the tank, they'll have to lie about it. You can also lock atmospherics down, that's an option too.

This map will play differently, I'm fine with not every situation playing out the same. People will get used to it.

**Comment by Partheo** [comment]
Current cult room. I placed the candles at the tips of the star, for flavor, y'know.
image
The rune is cleanable like any other rune.

AFAIK this next commit fixes everything that needs covering so far. PR is now at a complete state and ready to merge. If there are any other fixes we need please let me know. Suggestions are welcome too.

**Comment by Amelia0010** [comment]
> If someone asks the AI why there's plasma in the tank, they'll have to lie about it. You can also lock atmospherics down, that's an option too.

> plasma will only be present in the mix tank in antag or grief circumstances, rarely in regular crew operation

There's literally no reason whatsoever that the AI could use. Before you could go with "hey, it's going to incin" but now there's literally no defense

**Comment by Partheo** [comment]
@nichlas0010 
I have never seen an AI pass it off as going to the incinerator, because only players bother setting it up anyway.

Also, "literally no defense":
>borgs
>lock the place down
>turn off lights so they don't see it
>mute tcomms
>get an engiborg to bypass the mix tank
>again, lie about it
>remove people who would have access to atmospherics
>CO2 flood instead
>get an engiborg to block it with walls(which is easier to do now!)
>zombo.com

By saying there's no defense, you're claiming that the only reason AIs can successfully plasma flood now is because they can say it's going to the incinerator. That's just not the case.

Plasma flooding is ridiculously powerful. I really, really don't think this loss of a minor excuse is going to unbalance the game or the feature. Even if it does make a change- which it will, but not in this regard - It's a map edit. Its expected to play out differently. If people don't want it to play different, then no change to the map can be made.

**Comment by Jc1469** [comment]
Actually I set it up to the incinerator when playing borg for a traitor AI.   It's easier and less suspicious.  

I do think the loss of a minor excuse is going to unbalance, at this point, an entire gamemode, considering malf is soon going to be its own thing again.

**Comment by ghost** [comment]
Maint rooms need to be added to main PR description.

Dwarf room is a bad idea, has dwarfism injector at roundstart.

**Comment by Partheo** [comment]
Speaking of atomization, since this recently came up: If this PR needs to be split into two to add the atmos and maint rooms separately, I'm fine with doing that. The reason I made these together is that it is one complete map change, and it's impossible to add the maint rooms without adding this PR first because that space is not available on the base map. Also, if only the atmos PR passes but not the maint rooms, then there will be a large 6x5 empty space in maint.

### Edit: That made no sense. Sorry. Here's a summary:
All the features of this PR are interdependent and thus you can't pass one feature without the others. That's why this isn't atomized.

**Comment by Oakboscage** [comment]
Geneticists with dwarfism running around fucking shit up is already annoying enough, I really don't need Assistant McShitler to have access to dwarfism at roundstart.

**Comment by Partheo** [comment]
After discussion in discord, the injector will be changed to be an "Expired Injector" with a 50/50 chance to either apply Dwarfism or turn you into a monkey. For balance,

**Comment by Xantam-13** [comment]
Remove the monkeys from viro, a room that small (which I'm fine with) doesn't need 4 monkeys over 6 tiles, put a box of monkey cubes in there instead, that removes the squished feeling. 

I will never claim to understand atmos, it's so foreign to me. But the map you have made looks good and once the kinks are ironed, I look forward to ghosting over it in game.

**Comment by Partheo** [comment]
@05rhardy Fair point, I'll lower it to two monkeys and add a cube box.

**Comment by Sharkeybtm** [comment]
I like this. Assmos was getting to be too bland.

**Comment by Partheo** [comment]
Forgot to mention this. Since I bothered coding a bookshelf that started full of DnD manuals, I've added one to the library here. It replaces a previously empty filing cabinet.
image

Also, unless anyone has anything else to add this seem mostly complete. I'll update the main post with an actual changelog.

**Comment by Dagdammit** [comment]
Looks fantastic, all the minor quibbles I could have had were brought up and resolved already.

**Comment by Partheo** [comment]
I've re-added the pumps in the incinerator. Me making it as bare bones as it needed to be was not necessary.
image

I've cleaned up this part of maint a bit. Cable and disposal pipe layout makes more sense now.
image

I've moved the transit tube dispenser here.
image

The huge scrubber is now in the equipment room.
image

Cleaned these pipes around to make better usage of the space.
image

And a bunch of other tiny little tweaks.

**Comment by Partheo** [comment]
Diff is much, much smaller now! I must have messed up map merging at some point earlier in the PR. Now it's been recopied and merged properly.

**Comment by Partheo** [comment]
Updated main post with an up-to-date picture of the map as it is currently. I'm pretty sure it's completely ready now.

**Comment by Partheo** [comment]
Can something please be done about this? This is the fourth time I've had to fix merge conflicts, and I will have to fix more if this is left open.
This PR is not dead or stale, it's complete and ready to be merged/testmerged.

**Comment by Jc1469** [comment]
:thinking: its a pretty major map change. not sure why it isnt being testmerged first

**Comment by Jc1469** [comment]
[also wheres this pipe going](http://puu.sh/yCGIM/00768996c5.jpg)

**Pull request merged**
