### PR TITLE
*flip 2.0

### PR DESCRIPTION
**Pull request by Amelia0010**
Adds failing flips!
Failing a flip stuns you for a short amount of time, and tells anyone near you that you failed. Currently you can fail if you're fat, a clown, wearing a bulky piece of suit or just by plain bad luck.
:cl:
rscadd: *flip
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
>clown can no longer fit = clown nerf = no
>Fat people cannot flip = fat shaming = no
>hardsuits and other outer wear make you unable to flip = fun killing = super no.

In short, no/10

**Comment by Amelia0010** [comment]
nick, it's a 6% chance, not a complete block...

**Comment by Silvaplex256** [comment]
And why, exactly, is this necessary?

**Comment by Alexandria404** [comment]
Nice, great PR.

**Comment by Jc1469** [comment]
:thinking: 
clown nerfs.

**Comment by Kmc2000** [comment]
no

**Comment by grubstank** [comment]
I like it. If you have a chance to fail, then it makes the flip more fun.

**Pull request closed without merging**
