### PR TITLE
Makes marrow weavers finally settle down

### LINKED ISSUE #611: Marrow weavers are unfun and unrewarding to fight
1. The chitin they drop is worthless on it's own, and relies on asswalkers spawning to get the other half of the crafting materials for the armour

2. Their venom is annoying as shit, two bites can last upwards of 10 minutes of blurry vision and over 20  brute damage from the histamine itching, even worse if you get hit more than twice.

3. Their web is also annoying as shit and provides no bonus to them as they charge at you out of their web. All they do is slow your progress forwards as you're forced to clear the web away (which takes forever) or take another path

4. They have no unique attack apart from their venom bite. All you do is kite, making them boring to fight.

5. Their death description is perhaps the most unnecessarily flowery thing I've ever read.

### PR DESCRIPTION
**Pull request by Cruix**
Possibly fixes #611
:cl:
tweak: marrow weavers are no longer found all over lavaland, only in massive spider nests. The weavers will not wander far from the nest unless they are chasing prey.
tweak: marrow weavers now inject toxin instead of venom.
/:cl:

Since no one likes fighting marrow weavers, they are now found only in a new ruin. The ruin contains a few scattered bones and more than enough mythril to make full sets of weaver chitin armor if you manage to kill all four weavers. The weavers will attempt to return to their nest unless they are chasing something.

<strike>The ash walkers no longer start with mythril since 90% of the time they will not be able to use it.</strike>

untitled

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
> 90% of the time they won't be able to use it

???

I think the point of giving them 100 sheets or however many of mythril is that they could make the armor and miners couldn't without going through a lot of work, like a lock. Now miners have a better chance of getting the armor than the ashwalkers do.

**Comment by Cruix** [comment]
If they do get chitin in order to be able to use the mythril they will already have mythril from the spider nest.

**Comment by ghost** [comment]
give ashwalkers mithril anyway, it's good miner loot

or of course you could add mithril as a mineable ore and give ashwalkers an ore reclaimer so they can smelt their bullshit and sell it so they aren't just UNGA BUNGA MURDER LIZARDS

after all bribing the miners to fuck off from lavaland is a good way to defend your home from well armed outsiders too

also finally >4 fucking weavers

can you nerf weaver damage and injection and health

because fullspeed mob that makes spider webs and does 25 damage a hit with 200 health and laser resistance while injecting histamine is just a tad awful compared to literally every other mining mob

**Comment by AdamElTablawy** [comment]
i mean seriously

**Comment by ShadowDeath6** [comment]
don't add mythril as an ore, it would have literally one function and adding an ore reclaimer function to smelt it would be completely useless

also just have weavers inject toxin rather than venom

**Comment by Super3222** [comment]
> The ash walkers no longer start with mythril since 90% of the time they will not be able to use it.

what.

Nerfing venom & weaves in general, moving mythril away from the ash walkers, and then re-adding mythril, the resource which has the potential of giving you the strongest armors in the game, all in the same place?????

My suggestion on that issue was designed to make weavers challenging, difficult, but fun & rewarding to beat. Exactly how Goliath's are right now, and herdes of legions.

> or of course you could add mithril as a mineable ore and give ashwalkers

Never, unless it's extremely rare (more rare than diamond), and only ever drops one-two pieces of ore. And that's IT.

I like the implementation of the den system but, weavers shouldn't run far away from their homes. I imagine them being territorial beasts that'll spare no expense to intruders but, they are not savages who'd flee their home for a fight. Sorta like Watchers but, they kill on sight & have a home to guard.

**Comment by ghost** [comment]
> strongest armor in the game

weaver armor is not that fucking strong and if it IS it needs a nerf

also cruix already added mythril back to asswalkers

**Comment by Super3222** [comment]
> weaver armor is not that fucking strong and if it IS it needs a nerf

I was able to tank 4-5 attacks from a goliath until it RNG penetrated me or something BUT EVEN THEN I WASN'T GOING TO DIE ANYTIME SOON, completely ignore attacks from legion heads and ignore watchers. Literally, NOTHING WAS SERIOUS up until I fought a weaver.

The reason it spawned within ash walker dens was because most of the mining mobs on lavaland will slap an ashwalker a few times and it's KO. They had almost nothing to back them up, even from crafting. Miners didn't have to deal with their situation, considering their long range abilities give them an upperhand. Ashwalkers on the otherhand, had to get close and personal, therefore no one (but me until I took a step back to see the results) opposed the idea of high stat values.
Letting them become a regular ore for miners is B A D. And yes, they might need a nerf. **But if anyone is planning on nerfing them, be sure to actually test it out and see how well the armor does in the game.**

https://github.com/yogstation13/yogstation/commit/add65b059bb88e562afb0952bf3e88ade1e40573#diff-1449b9cadfbf0b181a5640e4cf2a36f0R116
https://github.com/yogstation13/yogstation/commit/add65b059bb88e562afb0952bf3e88ade1e40573#diff-8f700b3dec8df4b3e668e0721951a60cR66
https://github.com/yogstation13/yogstation/commit/add65b059bb88e562afb0952bf3e88ade1e40573#diff-8b1997bcfb92062d44ebb89703560fc4R108

So even if someone considers making them an ore, it needs to be really rare. And yeah, armor does stack according to KorPhaeron.
Why would I bother with an ashdrake armor when I can just kill easier targets?
https://github.com/yogstation13/yogstation/blob/9ca634e7a20196faa263bda7fc5a35f687adab92/code/modules/clothing/suits/cloaks.dm#L81

**Comment by Cruix** [comment]
If the marrow weavers had a hard distance at which they would stop aggroing people would just kite them to the border, stand just outside it, and be untouchable. The only way to stop something like that would be to make the weavers heal when they return to the nest, which would be incredibly frustrating for both miners and ash walkers to deal with. As it is you at least have a chance of luring out one at a time for a somewhat fair fight.

**Comment by ShadowDeath6** [comment]
miners really don't need the armor, they already have upgradeable shit and they can actually kill megafauna for their loot.

**Comment by Super3222** [comment]
I had a pretty good suggestion on https://github.com/yogstation13/yogstation/issues/611 where Marrow Weavers are close-mid range opponents, rather than being stuck to close range.

It basically prompted miners to be careful as HELL, but not panic when facing weavers. This idea comes from how miners fight goliaths nowadays, considering you have to actually think and maybe plan an escape route (most likely the path you took to get to the goliath).

**Comment by ghost** [comment]
@Super3222 can you nerf weaver armor

**Comment by Stealthkibbler** [comment]
> Ash walkers not spawning with mythril

gooooooood fuuuuuckiiiiinnnnnng meeeeeemmeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

its not like walkers need mythril to make the advanced armor sets or anything, not at all, nope. fucking nice good one top kek top of the morning best decision clearly knew what mythril was for hehe xd.

**Comment by Stealthkibbler** [comment]
why do i even continue to look at these changes, every one i look at makes my soul die a little more on the inside.

what even is this stuff, i dont fucking know its not like it was the items that need mythril or anything.  

have you played ashwalker after my changes were merged? or along with balancing marrow weavers you were just like "lol wtf mythril" and just decided to change it without having any idea at all at why it was there in the first place.

/datum/crafting_recipe/sinew_tent
    name = "Sinew Tent"
    result = /obj/item/weapon/sinew_tent
    time = 30
    reqs = list(/obj/item/stack/sheet/bone = 3,
                 /obj/item/stack/sheet/sinew = 2,
                 /obj/item/stack/sheet/mineral/sandstone = 6,
                 /obj/item/stack/sheet/mineral/mythril = 1)
    category = CAT_PRIMAL

/datum/crafting_recipe/pathfindertreads
    name = "Pathfinder Treads"
    result = /obj/item/clothing/shoes/pathtreads
    time = 40
    reqs = list(/obj/item/stack/sheet/bone = 1,
                /obj/item/stack/sheet/sinew = 3,
                /obj/item/stack/sheet/mineral/mythril = 1)
    category = CAT_PRIMAL

/datum/crafting_recipe/pathfindercloak
    name = "Pathfinder Cloak"
    result = /obj/item/clothing/suit/armor/pathfinder
    time = 60
    reqs = list(/obj/item/stack/sheet/sinew = 6,
                /obj/item/stack/sheet/mineral/mythril = 1)
    category = CAT_PRIMAL

/datum/crafting_recipe/pathfinderkasa
    name = "Pathfinder Kasa"
    result = /obj/item/clothing/head/helmet/kasa
    time = 30
    reqs = list(/obj/item/stack/sheet/bone = 2,
                /obj/item/stack/sheet/sinew = 2,
                /obj/item/stack/sheet/mineral/mythril = 1)
    category = CAT_PRIMAL

/datum/crafting_recipe/chitintreads
    name = "Chitin Boots"
    result = /obj/item/clothing/shoes/chitintreads
    time = 40
    reqs = list(/obj/item/stack/sheet/bone = 1,
                /obj/item/stack/sheet/animalhide/weaver_chitin = 1,
                /obj/item/stack/sheet/sinew = 1,
                /obj/item/stack/sheet/mineral/mythril = 1)
    category = CAT_PRIMAL

/datum/crafting_recipe/chitinarmor
    name = "Chitin Plate Armor"
    result = /obj/item/clothing/suit/armor/chitinplate
    time = 100
    reqs = list (/obj/item/stack/sheet/bone = 5,
                 /obj/item/stack/sheet/animalhide/weaver_chitin = 2,
                 /obj/item/stack/sheet/sinew = 3,
                 /obj/item/stack/sheet/mineral/mythril = 1,
                 /obj/item/clothing/suit/armor/bone = 1)
    category = CAT_PRIMAL

/datum/crafting_recipe/chitinhands
    name = "Chitin Gauntlets"
    result = /obj/item/clothing/gloves/chitinhands
    time = 30
    reqs = list (/obj/item/stack/sheet/bone = 3,
                 /obj/item/stack/sheet/animalhide/weaver_chitin = 1,
                 /obj/item/stack/sheet/sinew = 1,
                 /obj/item/stack/sheet/mineral/mythril = 1,
                 /obj/item/clothing/gloves/bracer = 1)
    category = CAT_PRIMAL

/datum/crafting_recipe/heartprotector
    name = "Heart Protector"
    result = /obj/item/clothing/under/heartprot
    time = 20
    reqs = list(/obj/item/stack/sheet/bone = 1,
                /obj/item/stack/sheet/sinew = 1,
                /obj/item/stack/sheet/mineral/mythril = 1)
    category = CAT_PRIMAL

**Comment by Stealthkibbler** [comment]
and the ruin only has a chance to spawn along with the mythril, you just completely ignore the fact that its even a chance alone for ashwalkers to spawn.

whyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by Cruix** [comment]
Ashwalkers got their mythril back in this PR five days ago.

**Comment by Stealthkibbler** [comment]
fuck, sorry then, I had too much vodka last night and thought it would be the best time to browse yogs prs. good work on the weavers tho man :+1:

**Pull request closed without merging**
