### PR TITLE
OOC emojis

### PR DESCRIPTION
**Pull request by Kmc2000**
Got bored, decided to add some more emoji

Doge, gnome, sloth, illuminati and heart were adapted from existing emoji (the memey ones)

🆑 Kmc2000
rscadd: Added more emoji to the OOC channel.
 /🆑

### CODE REVIEW

**Comment by Kmc2000** [comment]
:Speedmerge:

**Comment by Super3222** [comment]
:+1: x :100:

**Comment by oisin100** [comment]
We need `:+1:`

Also you should probably change the `kmc` part of your changelog to `Kmc2000` so that it uses your ingame ckey.

**Comment by TheSadFox** [comment]
Do you take emoji requests? :yiff:

**Comment by Kmc2000** [comment]
Sure do @seikotheseal

I would add a few animememe emotes if it wouldnt get my pr shot down and burnt at the stake

**Comment by ShadowDeath6** [comment]
where is :ok_hand: ?

**Comment by Stealthkibbler** [comment]
@Kmc2000 

Yes we need :ok_hand: :cocochan2: and :yiff:

these are essential KMC dont fuck it up.

**Comment by Kmc2000** [comment]
:cocochan2:

**Comment by Nirnael** [comment]
> cocochan

**Comment by ParagonPrime** [comment]
we need :GERTY: and :pAI: (pAI's smile)

**Comment by Kmc2000** [comment]
> pai emoji

We already have those

:happy: :reallyhappy: :cat: 

Gerty, we don't though

**Comment by ShadowDeath6** [comment]
good PR now that you added swarmers and :ok_hand: ;^)

**Comment by Kmc2000** [comment]
Someone merge dis shit

**Comment by Zostroll** [comment]
I was merged but :validsalad: doesn't work.

**Pull request merged**
