### PR TITLE
Disable antag tokens

### PR DESCRIPTION
**Pull request by george99g**
https://forums.yogstation.net/index.php?threads/antag-tokens.11208/

This will probably need some more work in order to be gone from the admin interface as well, but I'll leave that for later.

### CODE REVIEW

**Comment by Bekons** [comment]
BUt why though.

**Comment by GrayRachnid** [comment]
This is a lazy fix, atleast put some effort in or ask a coder to do it. Geez.

**Comment by george99g** [comment]
> This is a lazy fix, atleast put some effort in or ask a coder to do it. Geez.

GitHub won't let me edit more than 1 file online. Thought I'd leave the better fixing for a coder and just get this done as soon as possible.

**Comment by george99g** [comment]
Actually, never mind.
I'll get this fixed proper.

**Comment by george99g** [comment]
@GrayRachnid Happy?

**Comment by GrayRachnid** [comment]
i'm never happy

**Comment by FluffySurvivor** [comment]
rip my 4 tokens

**Pull request merged**
