### PR TITLE
Remodels the Paramedic / Morgue / Sec Post area.

### PR DESCRIPTION
**Pull request by matskuman5**
List of things this does:

1. Move the Morgue nearer to Robotics.

2. Move the Paramedic room nearer to Medbay.

3. Give the Sec Post better access to Medbay.

4. Adds a sick flavor guide to the Morgue :3

:cl:
tweak: NanoTrasen architects have remodeled the Morgue and surroundings.
/:cl:

### CODE REVIEW

**Comment by matskuman5** [comment]
You fucking cunts AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

how the fuck do i fix this merge conflict

**Comment by ShadowDeath6** [comment]
no access to maint from the paramed office?

**Comment by Super3222** [comment]
The security post could use a button to open medbays doors.

**Comment by Lightning38088** [comment]
reeeee i gave him this idea finally it's getting merged

**Comment by Alek2ander** [comment]
Put an operating table in the new morgue area for ~lings~ autopsies

**Comment by matskuman5** [comment]
>Put an operating table in the new morgue area for lings autopsies

I'm planning to do that if I ever get around to creating an autopsy system or just porting bay's

**Comment by Lightning38088** [comment]
MATS i forgot to ask, can you add a entry button to the doors in the security area? be nice so if there is a guard there for once they can open the door.

**Comment by ShadowDeath6** [comment]
Security has no windows facing medbay itself smh

**Comment by Frostben** [comment]
Where is the front desk for medbay? You didn't remove it did you?

**Comment by Super3222** [comment]
> Where is the front desk for medbay? You didn't remove it did you?

This design removes the front desk.

**Comment by ShadowDeath6** [comment]
>removes front desk
>moves parameds to front of medbay like they're doctors

I changed my mind :-1:

**Comment by Dagdammit** [comment]
I'm with Shadow- it's good except for the removal of front desk, that thing serves multiple important functions (like giving arrivals medicine without having to let them in) and it's a real kick in the RP balls if doctors have to holler through a door to ask why you need in. It can be manned by sec too, so that option's already covered.

And yeah, sec office should have a view of the medbay interior as well as lobby.

**Comment by matskuman5** [comment]
>no access to maint from the paramed office?

Uh, is this a problem?

>moves parameds to front of medbay like they're doctors

They're first responders. Their job is to go out and transport injured people to Medbay. It makes sense for their office to be in the entrance of Medbay.

>like giving arrivals medicine without having to let them in

Chemistry tables still exist.

I'll add a button to the sec office and add some more windows, as well as try to figure out what's causing these merge conflicts

**Comment by ShadowDeath6** [comment]
If you enter a hospital do you see the first responder office before you see a single regular doctor

**Comment by matskuman5** [comment]
>If you enter a hospital do you see the first responder office before you see a single regular doctor

That's why I didn't add windows to the front entrance

Makes it clear that they're not for public access

**Comment by Frostben** [comment]
Suggestion, make the security post both a front desk and security checkpoint.  That way we can have both cuz the only thing I really don't like about this is that the front desk is missing and it triggers me every time i see that.

**Comment by Dagdammit** [comment]
How would you change the current front desk to make it more of a security
checkpoint? The medbay sec guard can already sit at the front desk.

**Comment by Frostben** [comment]
Aw wait i just thought about it and planned it out in my head and it would just look stupid or would be pretty annoying to deal with.

**Comment by Mrcreepssss** [comment]
what is wrong with old paramed office? it was in a spot that made alot of sense to me a bit out of the way too, i do like the new morgue though

**Comment by ArgyleSweatshop** [comment]
We can't not have a front desk.

**Comment by ArgyleSweatshop** [comment]
I suggest moving the paramedic door up and to the right one tile. Then set up a front desk area in front of the security post.

**Comment by matskuman5** [comment]
@Cruix how does this look

**Comment by Cruix** [comment]
I don't understand why it is not fine the way it is

**Comment by matskuman5** [comment]
>I don't understand why it is not fine the way it is

As I said in the opening post

Move the Morgue nearer to Robotics, so they can fetch corpses easier.

Move the Paramedic room nearer to Medbay, so they can access it easier and don't have to take the awkward route through the Morgue

Give the Sec Post better access to the Medbay. They can also access the front entrance area quicker.

Adds a sick flavor guide to the Morgue :3

**Comment by Paragonid** [comment]
1 movable tile wide security post? The worst security post on the station, please no

**Comment by ShadowDeath6** [comment]
Still don't like the front desk being replaced with sec
Also does sec even have lockers for their equipment

**Comment by ShadowDeath6** [comment]
people have suggested stuff, feel free to work on this some more so it's merge-ready

**Comment by Super3222** [comment]
Sorry Mat. Coming back to this PR the design looks fairly ugly, and reviewing the responses Cruix gave it seems like he's not interested in merging it.

Despite it's ugliness it would be pretty useful considering that medics nowadays don't bother using the front desk. Having a security officer stationed there would be great.

**Comment by matskuman5** [comment]
Ah well, I'll try something else

**Pull request closed without merging**
