### PR TITLE
Newcc

### PR DESCRIPTION
**Pull request by utahclock**
This is Adam's PR for new CC layout.

:cl: Adam El-Tablawy
rscadd: Nanotrasen Engineers have made some changes to Centcom.
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
Please remove the config change and add pictures

**Comment by utahclock** [comment]
Ah sorry didnt see config change get added. and ya ill take a pic in a bit

**Comment by utahclock** [comment]
,

**Comment by Cruix** [comment]
Can you access that teleporter station from a teleporter on a different z-level?

**Comment by Cruix** [comment]
Also that is an insane amount of tcomms machinery

**Comment by utahclock** [comment]
Tell adam :P its his map

**Comment by utahclock** [comment]
Dunno about the teleporter. I would assume so. in which case it might need to be removed.

**Comment by ShadowDeath6** [comment]
where's adminbus room

**Comment by ghost** [comment]
does not exist

**Comment by ghost** [comment]
it's not supposed to be accessible

**Comment by ShadowDeath6** [comment]
it's fun for endround memes, add it back

**Comment by Super3222** [comment]
At the end of the round, sleepers  harvesting commandos (IN GREEN SUIT THST BARELY ANYONE GETS TO SEE) and normal centxomm officers should spawn on centcom.

**Comment by Tenryumi** [comment]
You should tone down the size of the whole map area by about 40%. SO much wide open, empty space. It makes Centcomm look and feel extremely bare.

**Comment by Time-Green** [comment]
Why is this needed exactly? It also removes the greatest feature: The abuse room

**Comment by Super3222** [comment]
Shut up Time, it's fucking fun. And we could always make a teleporter room with a machine that takes you "beyond the fourth wall" aka to an abuse room.

**Comment by ShadowDeath6** [comment]
Abuse room is the only room players care about and they will bitch no matter how good centcomm looks if it's removed. If it fits, you should make a completely new abuse room, probably bigger to fit the bigger centcomm with weapons that actually fire and without the orion trail ship grenade because of tg's space wind.

**Comment by Super3222** [comment]
@utahclock you need to map walls around the shuttle.

**Comment by utahclock** [comment]
Tell adam it his map i prd it for him

**Comment by ghost** [comment]
@utahclock why

**Comment by utahclock** [comment]
Stale plus recloned repo.

**Comment by ghost** [comment]
well open it again then  or make a new one i want my new CC

**Comment by utahclock** [comment]
Youll have to send me file again

**Pull request closed without merging**
