### PR TITLE
Tomb of the Unknown Employee

### PR DESCRIPTION
**Pull request by Super3222**
I didn't know ArcLumin, neither do I recall ever interacting with them. But I do respect who they were as a coder for their dedication of time and effort into contributing for their community, and I will respect all of those who have contributed to this great big game as a whole.

In fact, here on Yogstation we have experienced a similar fate where one of our newest council members, EMT321, got in a car crash and was never heard of since. But to be fair, no one has officially come out with a statement on his health so no one really knows. However in this memorial we can respect what he's done for us on Yogstation.

Rest in peace, ArcLumin, EMT321, and every other perished member of SS13.

For better quality - [Full Image Here](https://cloud.githubusercontent.com/assets/8345184/23827801/58ee224a-0671-11e7-9a12-bba73a3b6963.png)

Sprite work done by Wjohn.
Concept Art done by Kor's Girlfriend.

#### Changelog

:cl: Every coder, player, and admin in Space Station 13
rscadd: Adds the Tomb Of The Unknown Employee to Central Command,
rscadd: Rest in peace, those who died after contributing to Space Station 13.
/:cl:

Relevant Links:
http://abc30.com/traffic/3-killed-in-hwy-99-crash-in-merced-chp-says/1790559/
https://github.com/HippieStation/HippieStation13/pull/450
https://hippiestation.com/threads/rest-in-peace-arclumin.6233/#post-51038
https://github.com/tgstation/tgstation/pull/25003

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
f

I'd change the file name to memorial.dm rather than arclumin.dm

**Comment by Iamgoofball** [comment]
that's a good idea

**Comment by matskuman5** [comment]
EMT's not dead. He talked with Xantam after the accident, though dont know what it was about

**Comment by imtakingabreakdontatme** [comment]
>Concept Art done by LanCartwright.

Minor nitpick but he was the one who paid for the art, not the one that drew it

**Pull request merged**
