### PR TITLE
Remove charter.

### PR DESCRIPTION
**Pull request by george99g**

### CODE REVIEW

**Comment by Nirnael** [comment]
Alert admins, don't remove.

**Comment by george99g** [comment]
I don't care. I'm removing it right now. If anyone wants to fix it, uncomment it and be my guest.

**Comment by Nirnael** [comment]
Absolute power corrupts absolutely.

**Comment by george99g** [comment]
I will not leave a broken feature that can be abused in until it gets fixed.
If you want to fix it so it works as you said you want it to, you're all fine to do it. I won't object to it.

**Comment by FluffySurvivor** [comment]
Merging your own PR? Ahem.

**Comment by george99g** [comment]
> Merging your own PR? Ahem.

How many times do I have to say this?
The station was literally named names against the rules while this PR was pending and nobody did anything about it.

**Pull request merged**
