### PR TITLE
Makes flashes stun borgs

### PR DESCRIPTION
**Pull request by Amelia0010**
Makes using the flash in_hand stun borgs. It's less than half of the normal click-stun, but hey, it's something

#### Changelog

:cl:  
tweak: borgs get stunned by in_hand flashes now
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
does this have a 2 tile AOE range? This can make flash versus borg fights really onesided since you can stun much more easily, then follow up with a direct flash to get the extended stun (given your flash RNG doesn't suck). Then again, borgs opie opie nerf now

**Comment by Amelia0010** [comment]
I'mma change it to one so you still have to be directly next to them

**Comment by ShadowDeath6** [comment]
:-1: no, this just makes fighting borgs braindead easy since it's basically impossible to avoid a 3x3 aoe centered on the person. Regardless of how long it can stun, it still lets the person click them again to stun them for the full 10 seconds or whatever. If you want to fight a borg and kill it risk free, use an emp or something, it's not that hard.

**Comment by Amelia0010** [comment]
Okay, would you be fine with me at least blinding the borgs like humans, since currently borgs aren't affected by the in_hand flash at all?

**Comment by Ratvar** [comment]
Make it dizzle borgs, so they walk in random pattern?

**Comment by Time-Green** [comment]
blinding or dizzle seems good

**Comment by ShadowDeath6** [comment]
I don't think it should do anything considering how easy it is to just spam at them

**Comment by Amelia0010** [comment]
I'll come up with something better the next time a borg makes me salty

**Comment by Jc1469** [comment]
if a borg is chasing you just run into the toilets and make it hit a sink with its baton

**Pull request closed without merging**
