### PR TITLE
Insignificant Brig Tweaks.

### PR DESCRIPTION
**Pull request by ActualRory**
Makes various insignificant tweaks to the brig.

Truly the greatest changes ever made and not just my modest first incursion into the wonderful world of Pull Requests.

:cl:  

rscadd: imageadd: Adds a new Wrench, the Security Wrench. It has a unique sprite and is largely identical to its default counterpart. If Medical gets one, why can't security?

tweak: Security Wrench added to both the execution chamber and Armoury, replacing the default wrenches in both locations. As such the Mechanical Toolbox in the Brig has been replaced with a "Security Toolbox." Functionally identical.

tweak: Adds a pocket fire extinguisher to the Warden's Locker.

tweak: Adds a fire extinguisher to the wall outside the execution chamber.

/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
sprites please xd

**Comment by Jc1469** [comment]
I've got bad news for you. 

Mapping isn't as easy as just editing the map and uploading it.  As you can see from the +7,380 −135,045 file changes.

I'd suggest giving this a read. https://tgstation13.org/wiki/Map_Merger

**Comment by ActualRory** [comment]
Alright, apologies, will give the mapping a deeper look into.

Cheers @Jc1469

**Comment by Partheo** [comment]
The first changelog entry of your PR:
>rscadd: imageadd: Adds a new Wrench, the Security Wrench. It has a unique sprite and is largely identical to its default counterpart. If Medical gets one, why can't security?

You put two prefixes, imageadd and rcsadd. As far as I know, you can only put one. The last line is also unnecessary. This is what the players are seeing- no need for discussion in the changelog. Be brief.

Also, your first and second entries could be merged. It could be as easy as:
"The wrenches in the brig have been replaced by Security Wrenches, functionally identical to regular wrenches but with a unique sprite."

**Pull request closed without merging**
