### PR TITLE
Changes "faggot" to "meatball" 

### PR DESCRIPTION
**Pull request by Time-Green**
Replaces all the instances of "the F word" being used. I replaced everyone single one of them with "Meatball".

:cl:
rscadd: Time-Green : 
fix: Cleanses the meatballs
/:cl:

### CODE REVIEW

**Comment by Cruix** [comment]
I see .dmi files changed but I do not see any icon_state vars changed

**Comment by Super3222** [comment]
And here we go with the commit messages again.
Sigh. You should have committed, "Reverts the use of faggot".

**Comment by ShadowDeath6** [comment]
k

**Comment by FluffySurvivor** [comment]
> k

k

**Comment by Time-Green** [comment]
Fine, but I love the title.

And @Cruix , that's with emojis, you don't need to, it automaticly does it. To add a new emoji, simply put one in the dmi. , no icon_state stuff.

**Comment by ShadowDeath6** [comment]
also

what kind of CL is that

**Comment by Time-Green** [comment]
Idunno, it probably works, maybe, I was told the rsc was optional

**Comment by ShadowDeath6** [comment]
:cl: **_PUT YOUR NAME HERE_** <----------------------
fix: fixes gross looking changelog
/:cl:

also remember to name your initial commit to something legible so people know what they see because that's what shows up when you look at the files

**Comment by Time-Green** [comment]
Oh, that's why that's needed. 
I never really understood the meaning behind it

**Comment by Kmc2000** [comment]
....

Why

**Comment by Cruix** [comment]
Merging this in a few hours.

The food.dmi file was also changed, are you sure meatballs are not invisible now?

Also in the future please relegate memes to your branch names and not the commit messages.

**Comment by ShadowDeath6** [comment]
time you didn't even fix it

**Comment by ParagonPrime** [comment]
H U G B O X
H U G B O X
H U G B O X

**Pull request merged**
