### PR TITLE
Adds 9 new emoji to OOC

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Adds: :blobderpy: :blobglare: :blobhammer: :blobhyperthink: :blobkissheart: :blobokhand: :blobpolice: :blobthumbsup: and :thinking:
[Here's an album of the emoji](http://imgur.com/a/xBwCt)
[And here's a picture of the emoji in action](http://imgur.com/a/gKU0H)

#### Changelog

:cl:
rscadd: Adds 9 new amazing emoji to OOC 
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Speedmerge tm

:upvote:

:+1:

**Comment by ShadowDeath6** [comment]
use snipping tool on the dmi file so we can see how ass it looks in game

**Comment by Kmc2000** [comment]
https://www.youtube.com/watch?v=r8pJt4dK_s4

**Comment by Amelia0010** [comment]
image

**Comment by LarissaMayrink** [comment]
where is the regular blobthinking? :c

**Comment by Cruix** [comment]
They are not even blobs

**Comment by Amelia0010** [comment]
But they are 
image
They're the android blobs

**Comment by Mrcreepssss** [comment]
:blobhammer: FEAR THE BANHAMMER!

**Pull request merged**
