### PR TITLE
Chasms no longer swallow dim light tiles.

### PR DESCRIPTION
**Pull request by Super3222**
:cl:
fix: Chasms no longer swallow dim light tiles.
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
a hole so deep it swallows the absense of light. feature

**Comment by Super3222** [comment]
Note for Coders: Dim lights are on the TURF layer, not the LIGHT layer, which is why it's interacting with the Entered() proc in the first place.

**Comment by ShadowDeath6** [comment]
Does this fix the chasm slowly opening

**Comment by Super3222** [comment]
I don't believe that this'll fix that, however it might if deleting the light tiles was slowing down the chasm.

**Pull request merged**
