### PR TITLE
LAVALAND ENHANCEMENTS

### PR DESCRIPTION
**Pull request by MacHac**
This patch includes some quality-of-life fixes and improvements for lavaland.
1. Ported TG's 96x96.dmi, meaning that ash drakes now have a swoop icon.  Fighting them should be semi-possible again.

B. Replaced the one toxin kit and one regular kit on the mining station with three burn kits and three brute kits.  Miners may now conceivably be able to heal minor injuries on their own.  Why was there a toxin kit there anyway?

III. Adds an 'elite' version of the mining hardsuit that is fireproof, lavaproof, and ashproof for 6000 points.  Miners may now have some incentive to do their jobs instead of running off and tendril hunting.

:cl:
bugfix: Several missing icons were readded, including the swoop icon for the ash drake.
tweak: The person in charge of packing medical supplies for lavaland has been fired, and a more useful array of medkits has been deployed for miner use.
rscadd: Following study of goliaths, Nanotrasen scientists have created a hardsuit that is completely immune to lava and ash storms.  This piece of technology is now availible in mining vendors, at great cost.
/:cl:

### CODE REVIEW

**Comment by MacHac** [comment]
yogbot pls

I'll post a screenshot in just a minute showing the changes.

**Comment by X-TheDark** [comment]
Convert lavaland map back to TGM format, please.

**Comment by GrayRachnid** [comment]
Picture of "elite" hardsuit please. Better look badass.

**Comment by oisin100** [comment]
TGM format then remake this PR.

**Pull request closed without merging**
